(* Auto-generated file for pretty-printing types *)

type ('a, 'b) sum = [%import: ('a, 'b) FormatTest.sum] 
let sum_to_jer (a_to_jer : 'a -> Yojson.Safe.t)
    (b_to_jer : 'b -> Yojson.Safe.t) (z : ('a, 'b) sum) : Yojson.Safe.t = 
    match z with
    | Inl v -> a_to_jer v
    | Inr v' -> b_to_jer v'
type empty_set = [%import: FormatTest.empty_set] [@@deriving jer]
type comparison = [%import: FormatTest.comparison] [@@deriving jer]

type char_list = [%import: FormatTest.char_list]
let char_list_to_jer (lb : char_list) =
  `String (DebugPrint.string_of_char_list lb)

type byteIdx = [%import: FormatTest.byteIdx] [@@deriving jer]
type bytePos = [%import: FormatTest.bytePos] [@@deriving jer]
type flg = [%import: FormatTest.flg] [@@deriving jer]

type octet_string = [%import: FormatTest.octet_string]
let octet_string_to_jer (lb : octet_string) =
  `String (DebugPrint.hex_of_byte_list lb)


type bit_string = [%import: FormatTest.bit_string] 
let bit_string_to_jer (bs : bit_string) =
  DebugPrint.hex_of_bit_string bs


type bit_string_fixed = [%import: FormatTest.bit_string_fixed] 
let bit_string_fixed_to_jer (bs : bit_string_fixed) =
  DebugPrint.hex_of_bit_string_fixed bs

type stationID__Type = [%import: FormatTest.stationID__Type] [@@deriving jer]
type itsPduHeader__Type = [%import: FormatTest.itsPduHeader__Type] [@@deriving jer]
type generationDeltaTime__Type = [%import: FormatTest.generationDeltaTime__Type] [@@deriving jer]
type stationType__Type = [%import: FormatTest.stationType__Type] [@@deriving jer]
type latitude__Type = [%import: FormatTest.latitude__Type] [@@deriving jer]
type longitude__Type = [%import: FormatTest.longitude__Type] [@@deriving jer]
type semiAxisLength__Type = [%import: FormatTest.semiAxisLength__Type] [@@deriving jer]
type headingValue__Type = [%import: FormatTest.headingValue__Type] [@@deriving jer]
type posConfidenceEllipse__Type = [%import: FormatTest.posConfidenceEllipse__Type] [@@deriving jer]
type altitudeValue__Type = [%import: FormatTest.altitudeValue__Type] [@@deriving jer]
type altitudeConfidence__Type = [%import: FormatTest.altitudeConfidence__Type] [@@deriving jer]
type altitude__Type = [%import: FormatTest.altitude__Type] [@@deriving jer]
type referencePosition__Type = [%import: FormatTest.referencePosition__Type] [@@deriving jer]
type basicContainer__Type = [%import: FormatTest.basicContainer__Type] [@@deriving jer]
type headingConfidence__Type = [%import: FormatTest.headingConfidence__Type] [@@deriving jer]
type heading__Type = [%import: FormatTest.heading__Type] [@@deriving jer]
type speedValue__Type = [%import: FormatTest.speedValue__Type] [@@deriving jer]
type speedConfidence__Type = [%import: FormatTest.speedConfidence__Type] [@@deriving jer]
type speed__Type = [%import: FormatTest.speed__Type] [@@deriving jer]
type driveDirection__Type = [%import: FormatTest.driveDirection__Type] [@@deriving jer]
type vehicleLengthValue__Type = [%import: FormatTest.vehicleLengthValue__Type] [@@deriving jer]
type vehicleLengthConfidenceIndication__Type = [%import: FormatTest.vehicleLengthConfidenceIndication__Type] [@@deriving jer]
type vehicleLength__Type = [%import: FormatTest.vehicleLength__Type] [@@deriving jer]
type vehicleWidth__Type = [%import: FormatTest.vehicleWidth__Type] [@@deriving jer]
type longitudinalAccelerationValue__Type = [%import: FormatTest.longitudinalAccelerationValue__Type] [@@deriving jer]
type accelerationConfidence__Type = [%import: FormatTest.accelerationConfidence__Type] [@@deriving jer]
type longitudinalAcceleration__Type = [%import: FormatTest.longitudinalAcceleration__Type] [@@deriving jer]
type curvatureValue__Type = [%import: FormatTest.curvatureValue__Type] [@@deriving jer]
type curvatureConfidence__Type = [%import: FormatTest.curvatureConfidence__Type] [@@deriving jer]
type curvature__Type = [%import: FormatTest.curvature__Type] [@@deriving jer]
type curvatureCalculationMode__root__Type = [%import: FormatTest.curvatureCalculationMode__root__Type] [@@deriving jer]
type curvatureCalculationMode__ext__Type = [%import: FormatTest.curvatureCalculationMode__ext__Type] [@@deriving jer]
type curvatureCalculationMode__Type = [%import: FormatTest.curvatureCalculationMode__Type] [@@deriving jer]
type yawRateValue__Type = [%import: FormatTest.yawRateValue__Type] [@@deriving jer]
type yawRateConfidence__Type = [%import: FormatTest.yawRateConfidence__Type] [@@deriving jer]
type yawRate__Type = [%import: FormatTest.yawRate__Type] [@@deriving jer]
type accelerationControl__Type = [%import: FormatTest.accelerationControl__Type] [@@deriving jer]
type lanePosition__Type = [%import: FormatTest.lanePosition__Type] [@@deriving jer]
type steeringWheelAngleValue__Type = [%import: FormatTest.steeringWheelAngleValue__Type] [@@deriving jer]
type steeringWheelAngleConfidence__Type = [%import: FormatTest.steeringWheelAngleConfidence__Type] [@@deriving jer]
type steeringWheelAngle__Type = [%import: FormatTest.steeringWheelAngle__Type] [@@deriving jer]
type lateralAccelerationValue__Type = [%import: FormatTest.lateralAccelerationValue__Type] [@@deriving jer]
type lateralAcceleration__Type = [%import: FormatTest.lateralAcceleration__Type] [@@deriving jer]
type verticalAccelerationValue__Type = [%import: FormatTest.verticalAccelerationValue__Type] [@@deriving jer]
type verticalAcceleration__Type = [%import: FormatTest.verticalAcceleration__Type] [@@deriving jer]
type performanceClass__Type = [%import: FormatTest.performanceClass__Type] [@@deriving jer]
type protectedZoneID__Type = [%import: FormatTest.protectedZoneID__Type] [@@deriving jer]
type cenDsrcTollingZoneID__Type = [%import: FormatTest.cenDsrcTollingZoneID__Type] [@@deriving jer]
type cenDsrcTollingZone__Type = [%import: FormatTest.cenDsrcTollingZone__Type] [@@deriving jer]
type basicVehicleContainerHighFrequency__Type = [%import: FormatTest.basicVehicleContainerHighFrequency__Type] [@@deriving jer]
type protectedZoneType__root__Type = [%import: FormatTest.protectedZoneType__root__Type] [@@deriving jer]
type protectedZoneType__ext__Type = [%import: FormatTest.protectedZoneType__ext__Type] [@@deriving jer]
type protectedZoneType__Type = [%import: FormatTest.protectedZoneType__Type] [@@deriving jer]
type timestampIts__Type = [%import: FormatTest.timestampIts__Type] [@@deriving jer]
type protectedZoneRadius__Type = [%import: FormatTest.protectedZoneRadius__Type] [@@deriving jer]
type protectedCommunicationZone__Type = [%import: FormatTest.protectedCommunicationZone__Type] [@@deriving jer]
type protectedCommunicationZonesRSU__Type = [%import: FormatTest.protectedCommunicationZonesRSU__Type] [@@deriving jer]
type rSUContainerHighFrequency__Type = [%import: FormatTest.rSUContainerHighFrequency__Type] [@@deriving jer]
type highFrequencyContainer__root__Type = [%import: FormatTest.highFrequencyContainer__root__Type] [@@deriving jer]
type highFrequencyContainer__ext__Type = [%import: FormatTest.highFrequencyContainer__ext__Type] [@@deriving jer]
type highFrequencyContainer__Type = [%import: FormatTest.highFrequencyContainer__Type] [@@deriving jer]
type vehicleRole__Type = [%import: FormatTest.vehicleRole__Type] [@@deriving jer]
type exteriorLights__Type = [%import: FormatTest.exteriorLights__Type] [@@deriving jer]
type deltaLatitude__Type = [%import: FormatTest.deltaLatitude__Type] [@@deriving jer]
type deltaLongitude__Type = [%import: FormatTest.deltaLongitude__Type] [@@deriving jer]
type deltaAltitude__Type = [%import: FormatTest.deltaAltitude__Type] [@@deriving jer]
type deltaReferencePosition__Type = [%import: FormatTest.deltaReferencePosition__Type] [@@deriving jer]
type pathDeltaTime__Type = [%import: FormatTest.pathDeltaTime__Type] [@@deriving jer]
type pathPoint__Type = [%import: FormatTest.pathPoint__Type] [@@deriving jer]
type pathHistory__Type = [%import: FormatTest.pathHistory__Type] [@@deriving jer]
type basicVehicleContainerLowFrequency__Type = [%import: FormatTest.basicVehicleContainerLowFrequency__Type] [@@deriving jer]
type lowFrequencyContainer__root__Type = [%import: FormatTest.lowFrequencyContainer__root__Type] [@@deriving jer]
type lowFrequencyContainer__ext__Type = [%import: FormatTest.lowFrequencyContainer__ext__Type] [@@deriving jer]
type lowFrequencyContainer__Type = [%import: FormatTest.lowFrequencyContainer__Type] [@@deriving jer]
type embarkationStatus__Type = [%import: FormatTest.embarkationStatus__Type] [@@deriving jer]
type ptActivationType__Type = [%import: FormatTest.ptActivationType__Type] [@@deriving jer]
type ptActivationData__Type = [%import: FormatTest.ptActivationData__Type] [@@deriving jer]
type ptActivation__Type = [%import: FormatTest.ptActivation__Type] [@@deriving jer]
type publicTransportContainer__Type = [%import: FormatTest.publicTransportContainer__Type] [@@deriving jer]
type specialTransportType__Type = [%import: FormatTest.specialTransportType__Type] [@@deriving jer]
type lightBarSirenInUse__Type = [%import: FormatTest.lightBarSirenInUse__Type] [@@deriving jer]
type specialTransportContainer__Type = [%import: FormatTest.specialTransportContainer__Type] [@@deriving jer]
type dangerousGoodsBasic__Type = [%import: FormatTest.dangerousGoodsBasic__Type] [@@deriving jer]
type dangerousGoodsContainer__Type = [%import: FormatTest.dangerousGoodsContainer__Type] [@@deriving jer]
type roadworksSubCauseCode__Type = [%import: FormatTest.roadworksSubCauseCode__Type] [@@deriving jer]
type hardShoulderStatus__Type = [%import: FormatTest.hardShoulderStatus__Type] [@@deriving jer]
type drivingLaneStatus__Type = [%import: FormatTest.drivingLaneStatus__Type] [@@deriving jer]
type closedLanes__Type = [%import: FormatTest.closedLanes__Type] [@@deriving jer]
type roadWorksContainerBasic__Type = [%import: FormatTest.roadWorksContainerBasic__Type] [@@deriving jer]
type rescueContainer__Type = [%import: FormatTest.rescueContainer__Type] [@@deriving jer]
type causeCodeType__Type = [%import: FormatTest.causeCodeType__Type] [@@deriving jer]
type subCauseCodeType__Type = [%import: FormatTest.subCauseCodeType__Type] [@@deriving jer]
type causeCode__Type = [%import: FormatTest.causeCode__Type] [@@deriving jer]
type emergencyPriority__Type = [%import: FormatTest.emergencyPriority__Type] [@@deriving jer]
type emergencyContainer__Type = [%import: FormatTest.emergencyContainer__Type] [@@deriving jer]
type trafficRule__root__Type = [%import: FormatTest.trafficRule__root__Type] [@@deriving jer]
type trafficRule__ext__Type = [%import: FormatTest.trafficRule__ext__Type] [@@deriving jer]
type trafficRule__Type = [%import: FormatTest.trafficRule__Type] [@@deriving jer]
type speedLimit__Type = [%import: FormatTest.speedLimit__Type] [@@deriving jer]
type safetyCarContainer__Type = [%import: FormatTest.safetyCarContainer__Type] [@@deriving jer]
type specialVehicleContainer__root__Type = [%import: FormatTest.specialVehicleContainer__root__Type] [@@deriving jer]
type specialVehicleContainer__ext__Type = [%import: FormatTest.specialVehicleContainer__ext__Type] [@@deriving jer]
type specialVehicleContainer__Type = [%import: FormatTest.specialVehicleContainer__Type] [@@deriving jer]
type camParameters__Type = [%import: FormatTest.camParameters__Type] [@@deriving jer]
type coopAwareness__Type = [%import: FormatTest.coopAwareness__Type] [@@deriving jer]
type cAM__Type = [%import: FormatTest.cAM__Type] [@@deriving jer]
type sequenceNumber__Type = [%import: FormatTest.sequenceNumber__Type] [@@deriving jer]
type actionID__Type = [%import: FormatTest.actionID__Type] [@@deriving jer]
type termination__Type = [%import: FormatTest.termination__Type] [@@deriving jer]
type relevanceDistance__Type = [%import: FormatTest.relevanceDistance__Type] [@@deriving jer]
type relevanceTrafficDirection__Type = [%import: FormatTest.relevanceTrafficDirection__Type] [@@deriving jer]
type validityDuration__Type = [%import: FormatTest.validityDuration__Type] [@@deriving jer]
type transmissionInterval__Type = [%import: FormatTest.transmissionInterval__Type] [@@deriving jer]
type managementContainer__Type = [%import: FormatTest.managementContainer__Type] [@@deriving jer]
type informationQuality__Type = [%import: FormatTest.informationQuality__Type] [@@deriving jer]
type eventPoint__Type = [%import: FormatTest.eventPoint__Type] [@@deriving jer]
type eventHistory__Type = [%import: FormatTest.eventHistory__Type] [@@deriving jer]
type situationContainer__Type = [%import: FormatTest.situationContainer__Type] [@@deriving jer]
type traces__Type = [%import: FormatTest.traces__Type] [@@deriving jer]
type roadType__Type = [%import: FormatTest.roadType__Type] [@@deriving jer]
type locationContainer__Type = [%import: FormatTest.locationContainer__Type] [@@deriving jer]
type heightLonCarr__Type = [%import: FormatTest.heightLonCarr__Type] [@@deriving jer]
type posLonCarr__Type = [%import: FormatTest.posLonCarr__Type] [@@deriving jer]
type posPillar__Type = [%import: FormatTest.posPillar__Type] [@@deriving jer]
type positionOfPillars__Type = [%import: FormatTest.positionOfPillars__Type] [@@deriving jer]
type posCentMass__Type = [%import: FormatTest.posCentMass__Type] [@@deriving jer]
type wheelBaseVehicle__Type = [%import: FormatTest.wheelBaseVehicle__Type] [@@deriving jer]
type turningRadius__Type = [%import: FormatTest.turningRadius__Type] [@@deriving jer]
type posFrontAx__Type = [%import: FormatTest.posFrontAx__Type] [@@deriving jer]
type positionOfOccupants__Type = [%import: FormatTest.positionOfOccupants__Type] [@@deriving jer]
type vehicleMass__Type = [%import: FormatTest.vehicleMass__Type] [@@deriving jer]
type requestResponseIndication__Type = [%import: FormatTest.requestResponseIndication__Type] [@@deriving jer]
type impactReductionContainer__Type = [%import: FormatTest.impactReductionContainer__Type] [@@deriving jer]
type temperature__Type = [%import: FormatTest.temperature__Type] [@@deriving jer]
type restrictedTypes__Type = [%import: FormatTest.restrictedTypes__Type] [@@deriving jer]
type itineraryPath__Type = [%import: FormatTest.itineraryPath__Type] [@@deriving jer]
type referenceDenms__Type = [%import: FormatTest.referenceDenms__Type] [@@deriving jer]
type roadWorksContainerExtended__Type = [%import: FormatTest.roadWorksContainerExtended__Type] [@@deriving jer]
type positioningSolutionType__root__Type = [%import: FormatTest.positioningSolutionType__root__Type] [@@deriving jer]
type positioningSolutionType__ext__Type = [%import: FormatTest.positioningSolutionType__ext__Type] [@@deriving jer]
type positioningSolutionType__Type = [%import: FormatTest.positioningSolutionType__Type] [@@deriving jer]
type stationarySince__Type = [%import: FormatTest.stationarySince__Type] [@@deriving jer]
type phoneNumber__Type = [%import: FormatTest.phoneNumber__Type] [@@deriving jer]
type dangerousGoodsExtended__emergencyActionCode__Type = [%import: FormatTest.dangerousGoodsExtended__emergencyActionCode__Type] [@@deriving jer]
type dangerousGoodsExtended__Type = [%import: FormatTest.dangerousGoodsExtended__Type] [@@deriving jer]
type numberOfOccupants__Type = [%import: FormatTest.numberOfOccupants__Type] [@@deriving jer]
type wMInumber__Type = [%import: FormatTest.wMInumber__Type] [@@deriving jer]
type vDS__Type = [%import: FormatTest.vDS__Type] [@@deriving jer]
type vehicleIdentification__Type = [%import: FormatTest.vehicleIdentification__Type] [@@deriving jer]
type energyStorageType__Type = [%import: FormatTest.energyStorageType__Type] [@@deriving jer]
type stationaryVehicleContainer__Type = [%import: FormatTest.stationaryVehicleContainer__Type] [@@deriving jer]
type alacarteContainer__Type = [%import: FormatTest.alacarteContainer__Type] [@@deriving jer]
type decentralizedEnvironmentalNotificationMessage__Type = [%import: FormatTest.decentralizedEnvironmentalNotificationMessage__Type] [@@deriving jer]
type dENM__Type = [%import: FormatTest.dENM__Type] [@@deriving jer]
