/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PC5-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_AccessStratumReleaseSidelink_r16_H_
#define	_AccessStratumReleaseSidelink_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AccessStratumReleaseSidelink_r16 {
	AccessStratumReleaseSidelink_r16_rel16	= 0,
	AccessStratumReleaseSidelink_r16_rel17	= 1,
	AccessStratumReleaseSidelink_r16_spare6	= 2,
	AccessStratumReleaseSidelink_r16_spare5	= 3,
	AccessStratumReleaseSidelink_r16_spare4	= 4,
	AccessStratumReleaseSidelink_r16_spare3	= 5,
	AccessStratumReleaseSidelink_r16_spare2	= 6,
	AccessStratumReleaseSidelink_r16_spare1	= 7
	/*
	 * Enumeration is extensible
	 */
} e_AccessStratumReleaseSidelink_r16;

/* AccessStratumReleaseSidelink-r16 */
typedef long	 AccessStratumReleaseSidelink_r16_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_AccessStratumReleaseSidelink_r16_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AccessStratumReleaseSidelink_r16;
extern const asn_INTEGER_specifics_t asn_SPC_AccessStratumReleaseSidelink_r16_specs_1;
asn_struct_free_f AccessStratumReleaseSidelink_r16_free;
asn_struct_print_f AccessStratumReleaseSidelink_r16_print;
asn_constr_check_f AccessStratumReleaseSidelink_r16_constraint;
jer_type_encoder_f AccessStratumReleaseSidelink_r16_encode_jer;
per_type_decoder_f AccessStratumReleaseSidelink_r16_decode_uper;
per_type_encoder_f AccessStratumReleaseSidelink_r16_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AccessStratumReleaseSidelink_r16_H_ */
#include <asn_internal.h>
