/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_AreaConfiguration_v1700_H_
#define	_AreaConfiguration_v1700_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AreaConfig_r16;
struct InterFreqTargetInfo_r16;

/* AreaConfiguration-v1700 */
typedef struct AreaConfiguration_v1700 {
	struct AreaConfig_r16	*areaConfig_r17;	/* OPTIONAL */
	struct AreaConfiguration_v1700__interFreqTargetList_r17 {
		A_SEQUENCE_OF(struct InterFreqTargetInfo_r16) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *interFreqTargetList_r17;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AreaConfiguration_v1700_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AreaConfiguration_v1700;
extern asn_SEQUENCE_specifics_t asn_SPC_AreaConfiguration_v1700_specs_1;
extern asn_TYPE_member_t asn_MBR_AreaConfiguration_v1700_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AreaConfig-r16.h"
#include "InterFreqTargetInfo-r16.h"

#endif	/* _AreaConfiguration_v1700_H_ */
#include <asn_internal.h>
