/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-InterNodeDefinitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_BandCombinationIndex_H_
#define	_BandCombinationIndex_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BandCombinationIndex */
typedef long	 BandCombinationIndex_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_BandCombinationIndex_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_BandCombinationIndex;
asn_struct_free_f BandCombinationIndex_free;
asn_struct_print_f BandCombinationIndex_print;
asn_constr_check_f BandCombinationIndex_constraint;
jer_type_encoder_f BandCombinationIndex_encode_jer;
per_type_decoder_f BandCombinationIndex_decode_uper;
per_type_encoder_f BandCombinationIndex_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _BandCombinationIndex_H_ */
#include <asn_internal.h>
