/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_BandCombination_v1640_H_
#define	_BandCombination_v1640_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CA_ParametersNR_v1640;
struct CA_ParametersNRDC_v1640;

/* BandCombination-v1640 */
typedef struct BandCombination_v1640 {
	struct CA_ParametersNR_v1640	*ca_ParametersNR_v1640;	/* OPTIONAL */
	struct CA_ParametersNRDC_v1640	*ca_ParametersNRDC_v1640;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BandCombination_v1640_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BandCombination_v1640;
extern asn_SEQUENCE_specifics_t asn_SPC_BandCombination_v1640_specs_1;
extern asn_TYPE_member_t asn_MBR_BandCombination_v1640_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CA-ParametersNR-v1640.h"
#include "CA-ParametersNRDC-v1640.h"

#endif	/* _BandCombination_v1640_H_ */
#include <asn_internal.h>
