/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_BandParameters_v1730_H_
#define	_BandParameters_v1730_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SRS-SwitchingAffectedBandsNR-r17.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BandParameters-v1730 */
typedef struct BandParameters_v1730 {
	struct BandParameters_v1730__srs_SwitchingAffectedBandsListNR_r17 {
		A_SEQUENCE_OF(SRS_SwitchingAffectedBandsNR_r17_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} srs_SwitchingAffectedBandsListNR_r17;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BandParameters_v1730_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BandParameters_v1730;
extern asn_SEQUENCE_specifics_t asn_SPC_BandParameters_v1730_specs_1;
extern asn_TYPE_member_t asn_MBR_BandParameters_v1730_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _BandParameters_v1730_H_ */
#include <asn_internal.h>
