/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_CA_ParametersNR_v16a0_H_
#define	_CA_ParametersNR_v16a0_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PDCCH_BlindDetectionMixedList_r16;

/* CA-ParametersNR-v16a0 */
typedef struct CA_ParametersNR_v16a0 {
	struct CA_ParametersNR_v16a0__pdcch_BlindDetectionMixedList_r16 {
		A_SEQUENCE_OF(struct PDCCH_BlindDetectionMixedList_r16) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} pdcch_BlindDetectionMixedList_r16;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CA_ParametersNR_v16a0_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CA_ParametersNR_v16a0;
extern asn_SEQUENCE_specifics_t asn_SPC_CA_ParametersNR_v16a0_specs_1;
extern asn_TYPE_member_t asn_MBR_CA_ParametersNR_v16a0_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PDCCH-BlindDetectionMixedList-r16.h"

#endif	/* _CA_ParametersNR_v16a0_H_ */
#include <asn_internal.h>
