/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_CA_ParametersNRDC_v1650_H_
#define	_CA_ParametersNRDC_v1650_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CA-ParametersNRDC-v1650 */
typedef struct CA_ParametersNRDC_v1650 {
	BIT_STRING_t	*supportedCellGrouping_r16;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CA_ParametersNRDC_v1650_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CA_ParametersNRDC_v1650;
extern asn_SEQUENCE_specifics_t asn_SPC_CA_ParametersNRDC_v1650_specs_1;
extern asn_TYPE_member_t asn_MBR_CA_ParametersNRDC_v1650_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _CA_ParametersNRDC_v1650_H_ */
#include <asn_internal.h>
