/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_CellGroupId_H_
#define	_CellGroupId_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CellGroupId */
typedef long	 CellGroupId_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_CellGroupId_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_CellGroupId;
asn_struct_free_f CellGroupId_free;
asn_struct_print_f CellGroupId_print;
asn_constr_check_f CellGroupId_constraint;
jer_type_encoder_f CellGroupId_encode_jer;
per_type_decoder_f CellGroupId_decode_uper;
per_type_encoder_f CellGroupId_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CellGroupId_H_ */
#include <asn_internal.h>
