/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-InterNodeDefinitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_CG_CandidateList_H_
#define	_CG_CandidateList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CG_CandidateList__criticalExtensions_PR {
	CG_CandidateList__criticalExtensions_PR_NOTHING,	/* No components present */
	CG_CandidateList__criticalExtensions_PR_c1,
	CG_CandidateList__criticalExtensions_PR_criticalExtensionsFuture
} CG_CandidateList__criticalExtensions_PR;
typedef enum CG_CandidateList__criticalExtensions__c1_PR {
	CG_CandidateList__criticalExtensions__c1_PR_NOTHING,	/* No components present */
	CG_CandidateList__criticalExtensions__c1_PR_cg_CandidateList_r17,
	CG_CandidateList__criticalExtensions__c1_PR_spare3,
	CG_CandidateList__criticalExtensions__c1_PR_spare2,
	CG_CandidateList__criticalExtensions__c1_PR_spare1
} CG_CandidateList__criticalExtensions__c1_PR;

/* Forward declarations */
struct CG_CandidateList_r17_IEs;

/* CG-CandidateList */
typedef struct CG_CandidateList {
	struct CG_CandidateList__criticalExtensions {
		CG_CandidateList__criticalExtensions_PR present;
		union CG_CandidateList__criticalExtensions_u {
			struct CG_CandidateList__criticalExtensions__c1 {
				CG_CandidateList__criticalExtensions__c1_PR present;
				union CG_CandidateList__criticalExtensions__c1_u {
					struct CG_CandidateList_r17_IEs	*cg_CandidateList_r17;
					NULL_t	 spare3;
					NULL_t	 spare2;
					NULL_t	 spare1;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *c1;
			struct CG_CandidateList__criticalExtensions__criticalExtensionsFuture {
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *criticalExtensionsFuture;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} criticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CG_CandidateList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CG_CandidateList;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CG-CandidateList-r17-IEs.h"

#endif	/* _CG_CandidateList_H_ */
#include <asn_internal.h>
