/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_CO_DurationsPerCell_r16_H_
#define	_CO_DurationsPerCell_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ServCellIndex.h"
#include <NativeInteger.h>
#include "SubcarrierSpacing.h"
#include "CO-Duration-r16.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CO-DurationsPerCell-r16 */
typedef struct CO_DurationsPerCell_r16 {
	ServCellIndex_t	 servingCellId_r16;
	long	 positionInDCI_r16;
	SubcarrierSpacing_t	 subcarrierSpacing_r16;
	struct CO_DurationsPerCell_r16__co_DurationList_r16 {
		A_SEQUENCE_OF(CO_Duration_r16_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} co_DurationList_r16;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CO_DurationsPerCell_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CO_DurationsPerCell_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_CO_DurationsPerCell_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_CO_DurationsPerCell_r16_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _CO_DurationsPerCell_r16_H_ */
#include <asn_internal.h>
