/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-InterNodeDefinitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_FrequencyConfig_NR_r16_H_
#define	_FrequencyConfig_NR_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FreqBandIndicatorNR.h"
#include "ARFCN-ValueNR.h"
#include <NativeInteger.h>
#include "SubcarrierSpacing.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FrequencyConfig-NR-r16 */
typedef struct FrequencyConfig_NR_r16 {
	FreqBandIndicatorNR_t	 freqBandIndicatorNR_r16;
	ARFCN_ValueNR_t	 carrierCenterFreq_NR_r16;
	long	 carrierBandwidth_NR_r16;
	SubcarrierSpacing_t	 subcarrierSpacing_NR_r16;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FrequencyConfig_NR_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FrequencyConfig_NR_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_FrequencyConfig_NR_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_FrequencyConfig_NR_r16_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _FrequencyConfig_NR_r16_H_ */
#include <asn_internal.h>
