/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_HighSpeedParameters_r16_H_
#define	_HighSpeedParameters_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HighSpeedParameters_r16__measurementEnhancement_r16 {
	HighSpeedParameters_r16__measurementEnhancement_r16_supported	= 0
} e_HighSpeedParameters_r16__measurementEnhancement_r16;
typedef enum HighSpeedParameters_r16__demodulationEnhancement_r16 {
	HighSpeedParameters_r16__demodulationEnhancement_r16_supported	= 0
} e_HighSpeedParameters_r16__demodulationEnhancement_r16;

/* HighSpeedParameters-r16 */
typedef struct HighSpeedParameters_r16 {
	long	*measurementEnhancement_r16;	/* OPTIONAL */
	long	*demodulationEnhancement_r16;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HighSpeedParameters_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_measurementEnhancement_r16_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_demodulationEnhancement_r16_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_HighSpeedParameters_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_HighSpeedParameters_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_HighSpeedParameters_r16_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _HighSpeedParameters_r16_H_ */
#include <asn_internal.h>
