/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_IAB_IP_Usage_r16_H_
#define	_IAB_IP_Usage_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IAB_IP_Usage_r16 {
	IAB_IP_Usage_r16_f1_C	= 0,
	IAB_IP_Usage_r16_f1_U	= 1,
	IAB_IP_Usage_r16_non_F1	= 2,
	IAB_IP_Usage_r16_spare	= 3
} e_IAB_IP_Usage_r16;

/* IAB-IP-Usage-r16 */
typedef long	 IAB_IP_Usage_r16_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_IAB_IP_Usage_r16_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_IAB_IP_Usage_r16;
extern const asn_INTEGER_specifics_t asn_SPC_IAB_IP_Usage_r16_specs_1;
asn_struct_free_f IAB_IP_Usage_r16_free;
asn_struct_print_f IAB_IP_Usage_r16_print;
asn_constr_check_f IAB_IP_Usage_r16_constraint;
jer_type_encoder_f IAB_IP_Usage_r16_encode_jer;
per_type_decoder_f IAB_IP_Usage_r16_decode_uper;
per_type_encoder_f IAB_IP_Usage_r16_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _IAB_IP_Usage_r16_H_ */
#include <asn_internal.h>
