/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PC5-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_MAC_ParametersSidelink_r17_H_
#define	_MAC_ParametersSidelink_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MAC_ParametersSidelink_r17__drx_OnSidelink_r17 {
	MAC_ParametersSidelink_r17__drx_OnSidelink_r17_supported	= 0
} e_MAC_ParametersSidelink_r17__drx_OnSidelink_r17;

/* MAC-ParametersSidelink-r17 */
typedef struct MAC_ParametersSidelink_r17 {
	long	*drx_OnSidelink_r17;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MAC_ParametersSidelink_r17_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_drx_OnSidelink_r17_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_MAC_ParametersSidelink_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_MAC_ParametersSidelink_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_MAC_ParametersSidelink_r17_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _MAC_ParametersSidelink_r17_H_ */
#include <asn_internal.h>
