/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PC5-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_MasterInformationBlockSidelink_H_
#define	_MasterInformationBlockSidelink_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MasterInformationBlockSidelink */
typedef struct MasterInformationBlockSidelink {
	BIT_STRING_t	 sl_TDD_Config_r16;
	BOOLEAN_t	 inCoverage_r16;
	BIT_STRING_t	 directFrameNumber_r16;
	BIT_STRING_t	 slotIndex_r16;
	BIT_STRING_t	 reservedBits_r16;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MasterInformationBlockSidelink_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MasterInformationBlockSidelink;
extern asn_SEQUENCE_specifics_t asn_SPC_MasterInformationBlockSidelink_specs_1;
extern asn_TYPE_member_t asn_MBR_MasterInformationBlockSidelink_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _MasterInformationBlockSidelink_H_ */
#include <asn_internal.h>
