/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_MBS_NeighbourCellList_r17_H_
#define	_MBS_NeighbourCellList_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MBS_NeighbourCell_r17;

/* MBS-NeighbourCellList-r17 */
typedef struct MBS_NeighbourCellList_r17 {
	A_SEQUENCE_OF(struct MBS_NeighbourCell_r17) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MBS_NeighbourCellList_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MBS_NeighbourCellList_r17;
extern asn_SET_OF_specifics_t asn_SPC_MBS_NeighbourCellList_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_MBS_NeighbourCellList_r17_1[1];
extern asn_per_constraints_t asn_PER_type_MBS_NeighbourCellList_r17_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MBS-NeighbourCell-r17.h"

#endif	/* _MBS_NeighbourCellList_r17_H_ */
#include <asn_internal.h>
