/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_MCC_MNC_Digit_H_
#define	_MCC_MNC_Digit_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MCC-MNC-Digit */
typedef long	 MCC_MNC_Digit_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_MCC_MNC_Digit_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_MCC_MNC_Digit;
asn_struct_free_f MCC_MNC_Digit_free;
asn_struct_print_f MCC_MNC_Digit_print;
asn_constr_check_f MCC_MNC_Digit_constraint;
jer_type_encoder_f MCC_MNC_Digit_encode_jer;
per_type_decoder_f MCC_MNC_Digit_decode_uper;
per_type_encoder_f MCC_MNC_Digit_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _MCC_MNC_Digit_H_ */
#include <asn_internal.h>
