/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_MeasConfigAppLayer_r17_H_
#define	_MeasConfigAppLayer_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MeasConfigAppLayerId-r17.h"
#include <OCTET_STRING.h>
#include <NativeEnumerated.h>
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MeasConfigAppLayer_r17__serviceType_r17 {
	MeasConfigAppLayer_r17__serviceType_r17_streaming	= 0,
	MeasConfigAppLayer_r17__serviceType_r17_mtsi	= 1,
	MeasConfigAppLayer_r17__serviceType_r17_vr	= 2,
	MeasConfigAppLayer_r17__serviceType_r17_spare5	= 3,
	MeasConfigAppLayer_r17__serviceType_r17_spare4	= 4,
	MeasConfigAppLayer_r17__serviceType_r17_spare3	= 5,
	MeasConfigAppLayer_r17__serviceType_r17_spare2	= 6,
	MeasConfigAppLayer_r17__serviceType_r17_spare1	= 7
} e_MeasConfigAppLayer_r17__serviceType_r17;

/* Forward declarations */
struct SetupRelease_RAN_VisibleParameters_r17;

/* MeasConfigAppLayer-r17 */
typedef struct MeasConfigAppLayer_r17 {
	MeasConfigAppLayerId_r17_t	 measConfigAppLayerId_r17;
	OCTET_STRING_t	*measConfigAppLayerContainer_r17;	/* OPTIONAL */
	long	*serviceType_r17;	/* OPTIONAL */
	BOOLEAN_t	*pauseReporting_r17;	/* OPTIONAL */
	BOOLEAN_t	*transmissionOfSessionStartStop_r17;	/* OPTIONAL */
	struct SetupRelease_RAN_VisibleParameters_r17	*ran_VisibleParameters_r17;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasConfigAppLayer_r17_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_serviceType_r17_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_MeasConfigAppLayer_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasConfigAppLayer_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasConfigAppLayer_r17_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SetupRelease.h"

#endif	/* _MeasConfigAppLayer_r17_H_ */
#include <asn_internal.h>
