/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_MeasResultListCLI_RSSI_r16_H_
#define	_MeasResultListCLI_RSSI_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MeasResultCLI_RSSI_r16;

/* MeasResultListCLI-RSSI-r16 */
typedef struct MeasResultListCLI_RSSI_r16 {
	A_SEQUENCE_OF(struct MeasResultCLI_RSSI_r16) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasResultListCLI_RSSI_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasResultListCLI_RSSI_r16;
extern asn_SET_OF_specifics_t asn_SPC_MeasResultListCLI_RSSI_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasResultListCLI_RSSI_r16_1[1];
extern asn_per_constraints_t asn_PER_type_MeasResultListCLI_RSSI_r16_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MeasResultCLI-RSSI-r16.h"

#endif	/* _MeasResultListCLI_RSSI_r16_H_ */
#include <asn_internal.h>
