/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_MsgA_PUSCH_Config_r16_H_
#define	_MsgA_PUSCH_Config_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MsgA_PUSCH_Config_r16__msgA_TransformPrecoder_r16 {
	MsgA_PUSCH_Config_r16__msgA_TransformPrecoder_r16_enabled	= 0,
	MsgA_PUSCH_Config_r16__msgA_TransformPrecoder_r16_disabled	= 1
} e_MsgA_PUSCH_Config_r16__msgA_TransformPrecoder_r16;

/* Forward declarations */
struct MsgA_PUSCH_Resource_r16;

/* MsgA-PUSCH-Config-r16 */
typedef struct MsgA_PUSCH_Config_r16 {
	struct MsgA_PUSCH_Resource_r16	*msgA_PUSCH_ResourceGroupA_r16;	/* OPTIONAL */
	struct MsgA_PUSCH_Resource_r16	*msgA_PUSCH_ResourceGroupB_r16;	/* OPTIONAL */
	long	*msgA_TransformPrecoder_r16;	/* OPTIONAL */
	long	*msgA_DataScramblingIndex_r16;	/* OPTIONAL */
	long	*msgA_DeltaPreamble_r16;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MsgA_PUSCH_Config_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_msgA_TransformPrecoder_r16_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_MsgA_PUSCH_Config_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_MsgA_PUSCH_Config_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_MsgA_PUSCH_Config_r16_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MsgA-PUSCH-Resource-r16.h"

#endif	/* _MsgA_PUSCH_Config_r16_H_ */
#include <asn_internal.h>
