/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_MultiDCI_MultiTRP_r16_H_
#define	_MultiDCI_MultiTRP_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MultiDCI_MultiTRP_r16__maxNumberCORESET_r16 {
	MultiDCI_MultiTRP_r16__maxNumberCORESET_r16_n2	= 0,
	MultiDCI_MultiTRP_r16__maxNumberCORESET_r16_n3	= 1,
	MultiDCI_MultiTRP_r16__maxNumberCORESET_r16_n4	= 2,
	MultiDCI_MultiTRP_r16__maxNumberCORESET_r16_n5	= 3
} e_MultiDCI_MultiTRP_r16__maxNumberCORESET_r16;
typedef enum MultiDCI_MultiTRP_r16__maxNumberUnicastPDSCH_PerPool_r16 {
	MultiDCI_MultiTRP_r16__maxNumberUnicastPDSCH_PerPool_r16_n1	= 0,
	MultiDCI_MultiTRP_r16__maxNumberUnicastPDSCH_PerPool_r16_n2	= 1,
	MultiDCI_MultiTRP_r16__maxNumberUnicastPDSCH_PerPool_r16_n3	= 2,
	MultiDCI_MultiTRP_r16__maxNumberUnicastPDSCH_PerPool_r16_n4	= 3,
	MultiDCI_MultiTRP_r16__maxNumberUnicastPDSCH_PerPool_r16_n7	= 4
} e_MultiDCI_MultiTRP_r16__maxNumberUnicastPDSCH_PerPool_r16;

/* MultiDCI-MultiTRP-r16 */
typedef struct MultiDCI_MultiTRP_r16 {
	long	 maxNumberCORESET_r16;
	long	 maxNumberCORESETPerPoolIndex_r16;
	long	 maxNumberUnicastPDSCH_PerPool_r16;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MultiDCI_MultiTRP_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_maxNumberCORESET_r16_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_maxNumberUnicastPDSCH_PerPool_r16_8;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_MultiDCI_MultiTRP_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_MultiDCI_MultiTRP_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_MultiDCI_MultiTRP_r16_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _MultiDCI_MultiTRP_r16_H_ */
#include <asn_internal.h>
