/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_NeedForGapsInfoNR_r16_H_
#define	_NeedForGapsInfoNR_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NeedForGapsIntraFreqList-r16.h"
#include "NeedForGapsBandListNR-r16.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NeedForGapsInfoNR-r16 */
typedef struct NeedForGapsInfoNR_r16 {
	NeedForGapsIntraFreqList_r16_t	 intraFreq_needForGap_r16;
	NeedForGapsBandListNR_r16_t	 interFreq_needForGap_r16;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NeedForGapsInfoNR_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NeedForGapsInfoNR_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_NeedForGapsInfoNR_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_NeedForGapsInfoNR_r16_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _NeedForGapsInfoNR_r16_H_ */
#include <asn_internal.h>
