/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_NeighbourCellInfo_r17_H_
#define	_NeighbourCellInfo_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EpochTime-r17.h"
#include "EphemerisInfo-r17.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NeighbourCellInfo-r17 */
typedef struct NeighbourCellInfo_r17 {
	EpochTime_r17_t	 epochTime_r17;
	EphemerisInfo_r17_t	 ephemerisInfo_r17;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NeighbourCellInfo_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NeighbourCellInfo_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_NeighbourCellInfo_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_NeighbourCellInfo_r17_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _NeighbourCellInfo_r17_H_ */
#include <asn_internal.h>
