/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_PathlossReferenceRSs_v1610_H_
#define	_PathlossReferenceRSs_v1610_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PUCCH_PathlossReferenceRS_r16;

/* PathlossReferenceRSs-v1610 */
typedef struct PathlossReferenceRSs_v1610 {
	A_SEQUENCE_OF(struct PUCCH_PathlossReferenceRS_r16) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PathlossReferenceRSs_v1610_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PathlossReferenceRSs_v1610;
extern asn_SET_OF_specifics_t asn_SPC_PathlossReferenceRSs_v1610_specs_1;
extern asn_TYPE_member_t asn_MBR_PathlossReferenceRSs_v1610_1[1];
extern asn_per_constraints_t asn_PER_type_PathlossReferenceRSs_v1610_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PUCCH-PathlossReferenceRS-r16.h"

#endif	/* _PathlossReferenceRSs_v1610_H_ */
#include <asn_internal.h>
