/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_PDCP_ParametersMRDC_v1610_H_
#define	_PDCP_ParametersMRDC_v1610_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PDCP_ParametersMRDC_v1610__scg_DRB_NR_IAB_r16 {
	PDCP_ParametersMRDC_v1610__scg_DRB_NR_IAB_r16_supported	= 0
} e_PDCP_ParametersMRDC_v1610__scg_DRB_NR_IAB_r16;

/* PDCP-ParametersMRDC-v1610 */
typedef struct PDCP_ParametersMRDC_v1610 {
	long	*scg_DRB_NR_IAB_r16;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDCP_ParametersMRDC_v1610_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_scg_DRB_NR_IAB_r16_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_PDCP_ParametersMRDC_v1610;
extern asn_SEQUENCE_specifics_t asn_SPC_PDCP_ParametersMRDC_v1610_specs_1;
extern asn_TYPE_member_t asn_MBR_PDCP_ParametersMRDC_v1610_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _PDCP_ParametersMRDC_v1610_H_ */
#include <asn_internal.h>
