/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_PosSI_SchedulingInfo_r16_H_
#define	_PosSI_SchedulingInfo_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SI_RequestConfig;
struct PosSchedulingInfo_r16;

/* PosSI-SchedulingInfo-r16 */
typedef struct PosSI_SchedulingInfo_r16 {
	struct PosSI_SchedulingInfo_r16__posSchedulingInfoList_r16 {
		A_SEQUENCE_OF(struct PosSchedulingInfo_r16) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} posSchedulingInfoList_r16;
	struct SI_RequestConfig	*posSI_RequestConfig_r16;	/* OPTIONAL */
	struct SI_RequestConfig	*posSI_RequestConfigSUL_r16;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct PosSI_SchedulingInfo_r16__ext1 {
		struct SI_RequestConfig	*posSI_RequestConfigRedCap_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PosSI_SchedulingInfo_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PosSI_SchedulingInfo_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_PosSI_SchedulingInfo_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_PosSI_SchedulingInfo_r16_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SI-RequestConfig.h"
#include "PosSchedulingInfo-r16.h"

#endif	/* _PosSI_SchedulingInfo_r16_H_ */
#include <asn_internal.h>
