/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_PUCCH_SpatialRelationInfoId_H_
#define	_PUCCH_SpatialRelationInfoId_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PUCCH-SpatialRelationInfoId */
typedef long	 PUCCH_SpatialRelationInfoId_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PUCCH_SpatialRelationInfoId_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PUCCH_SpatialRelationInfoId;
asn_struct_free_f PUCCH_SpatialRelationInfoId_free;
asn_struct_print_f PUCCH_SpatialRelationInfoId_print;
asn_constr_check_f PUCCH_SpatialRelationInfoId_constraint;
jer_type_encoder_f PUCCH_SpatialRelationInfoId_encode_jer;
per_type_decoder_f PUCCH_SpatialRelationInfoId_decode_uper;
per_type_encoder_f PUCCH_SpatialRelationInfoId_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PUCCH_SpatialRelationInfoId_H_ */
#include <asn_internal.h>
