/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_RB_SetGroup_r17_H_
#define	_RB_SetGroup_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RB-SetGroup-r17 */
typedef struct RB_SetGroup_r17 {
	struct RB_SetGroup_r17__resourceAvailability_r17 {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *resourceAvailability_r17;
	struct RB_SetGroup_r17__rb_Sets_r17 {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *rb_Sets_r17;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RB_SetGroup_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RB_SetGroup_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_RB_SetGroup_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_RB_SetGroup_r17_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RB_SetGroup_r17_H_ */
#include <asn_internal.h>
