/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_RF_ParametersMRDC_v15g0_H_
#define	_RF_ParametersMRDC_v15g0_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct BandCombinationList_v15g0;

/* RF-ParametersMRDC-v15g0 */
typedef struct RF_ParametersMRDC_v15g0 {
	struct BandCombinationList_v15g0	*supportedBandCombinationList_v15g0;	/* OPTIONAL */
	struct BandCombinationList_v15g0	*supportedBandCombinationListNEDC_Only_v15g0;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RF_ParametersMRDC_v15g0_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RF_ParametersMRDC_v15g0;
extern asn_SEQUENCE_specifics_t asn_SPC_RF_ParametersMRDC_v15g0_specs_1;
extern asn_TYPE_member_t asn_MBR_RF_ParametersMRDC_v15g0_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "BandCombinationList-v15g0.h"

#endif	/* _RF_ParametersMRDC_v15g0_H_ */
#include <asn_internal.h>
