/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PC5-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_RRCReconfigurationFailureSidelink_H_
#define	_RRCReconfigurationFailureSidelink_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RRC-TransactionIdentifier.h"
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRCReconfigurationFailureSidelink__criticalExtensions_PR {
	RRCReconfigurationFailureSidelink__criticalExtensions_PR_NOTHING,	/* No components present */
	RRCReconfigurationFailureSidelink__criticalExtensions_PR_rrcReconfigurationFailureSidelink_r16,
	RRCReconfigurationFailureSidelink__criticalExtensions_PR_criticalExtensionsFuture
} RRCReconfigurationFailureSidelink__criticalExtensions_PR;

/* Forward declarations */
struct RRCReconfigurationFailureSidelink_r16_IEs;

/* RRCReconfigurationFailureSidelink */
typedef struct RRCReconfigurationFailureSidelink {
	RRC_TransactionIdentifier_t	 rrc_TransactionIdentifier_r16;
	struct RRCReconfigurationFailureSidelink__criticalExtensions {
		RRCReconfigurationFailureSidelink__criticalExtensions_PR present;
		union RRCReconfigurationFailureSidelink__criticalExtensions_u {
			struct RRCReconfigurationFailureSidelink_r16_IEs	*rrcReconfigurationFailureSidelink_r16;
			struct RRCReconfigurationFailureSidelink__criticalExtensions__criticalExtensionsFuture {
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *criticalExtensionsFuture;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} criticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCReconfigurationFailureSidelink_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCReconfigurationFailureSidelink;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCReconfigurationFailureSidelink_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCReconfigurationFailureSidelink_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RRCReconfigurationFailureSidelink-r16-IEs.h"

#endif	/* _RRCReconfigurationFailureSidelink_H_ */
#include <asn_internal.h>
