/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PC5-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_RRCReconfigurationCompleteSidelink_H_
#define	_RRCReconfigurationCompleteSidelink_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RRC-TransactionIdentifier.h"
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRCReconfigurationCompleteSidelink__criticalExtensions_PR {
	RRCReconfigurationCompleteSidelink__criticalExtensions_PR_NOTHING,	/* No components present */
	RRCReconfigurationCompleteSidelink__criticalExtensions_PR_rrcReconfigurationCompleteSidelink_r16,
	RRCReconfigurationCompleteSidelink__criticalExtensions_PR_criticalExtensionsFuture
} RRCReconfigurationCompleteSidelink__criticalExtensions_PR;

/* Forward declarations */
struct RRCReconfigurationCompleteSidelink_r16_IEs;

/* RRCReconfigurationCompleteSidelink */
typedef struct RRCReconfigurationCompleteSidelink {
	RRC_TransactionIdentifier_t	 rrc_TransactionIdentifier_r16;
	struct RRCReconfigurationCompleteSidelink__criticalExtensions {
		RRCReconfigurationCompleteSidelink__criticalExtensions_PR present;
		union RRCReconfigurationCompleteSidelink__criticalExtensions_u {
			struct RRCReconfigurationCompleteSidelink_r16_IEs	*rrcReconfigurationCompleteSidelink_r16;
			struct RRCReconfigurationCompleteSidelink__criticalExtensions__criticalExtensionsFuture {
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *criticalExtensionsFuture;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} criticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCReconfigurationCompleteSidelink_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCReconfigurationCompleteSidelink;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCReconfigurationCompleteSidelink_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCReconfigurationCompleteSidelink_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RRCReconfigurationCompleteSidelink-r16-IEs.h"

#endif	/* _RRCReconfigurationCompleteSidelink_H_ */
#include <asn_internal.h>
