/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_RRCRelease_v1610_IEs_H_
#define	_RRCRelease_v1610_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRCRelease_v1610_IEs__voiceFallbackIndication_r16 {
	RRCRelease_v1610_IEs__voiceFallbackIndication_r16_true	= 0
} e_RRCRelease_v1610_IEs__voiceFallbackIndication_r16;

/* Forward declarations */
struct SetupRelease_MeasIdleConfigDedicated_r16;
struct RRCRelease_v1650_IEs;

/* RRCRelease-v1610-IEs */
typedef struct RRCRelease_v1610_IEs {
	long	*voiceFallbackIndication_r16;	/* OPTIONAL */
	struct SetupRelease_MeasIdleConfigDedicated_r16	*measIdleConfig_r16;	/* OPTIONAL */
	struct RRCRelease_v1650_IEs	*nonCriticalExtension;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCRelease_v1610_IEs_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_voiceFallbackIndication_r16_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RRCRelease_v1610_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCRelease_v1610_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCRelease_v1610_IEs_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SetupRelease.h"
#include "RRCRelease-v1650-IEs.h"

#endif	/* _RRCRelease_v1610_IEs_H_ */
#include <asn_internal.h>
