/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_ScalingFactorSidelink_r16_H_
#define	_ScalingFactorSidelink_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ScalingFactorSidelink_r16 {
	ScalingFactorSidelink_r16_f0p4	= 0,
	ScalingFactorSidelink_r16_f0p75	= 1,
	ScalingFactorSidelink_r16_f0p8	= 2,
	ScalingFactorSidelink_r16_f1	= 3
} e_ScalingFactorSidelink_r16;

/* ScalingFactorSidelink-r16 */
typedef long	 ScalingFactorSidelink_r16_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ScalingFactorSidelink_r16_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ScalingFactorSidelink_r16;
extern const asn_INTEGER_specifics_t asn_SPC_ScalingFactorSidelink_r16_specs_1;
asn_struct_free_f ScalingFactorSidelink_r16_free;
asn_struct_print_f ScalingFactorSidelink_r16_print;
asn_constr_check_f ScalingFactorSidelink_r16_constraint;
jer_type_encoder_f ScalingFactorSidelink_r16_encode_jer;
per_type_decoder_f ScalingFactorSidelink_r16_decode_uper;
per_type_encoder_f ScalingFactorSidelink_r16_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ScalingFactorSidelink_r16_H_ */
#include <asn_internal.h>
