/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_SharedSpectrumChAccessParamsPerBand_v1650_H_
#define	_SharedSpectrumChAccessParamsPerBand_v1650_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SharedSpectrumChAccessParamsPerBand_v1650__extendedSearchSpaceSwitchWithDCI_r16 {
	SharedSpectrumChAccessParamsPerBand_v1650__extendedSearchSpaceSwitchWithDCI_r16_supported	= 0
} e_SharedSpectrumChAccessParamsPerBand_v1650__extendedSearchSpaceSwitchWithDCI_r16;

/* SharedSpectrumChAccessParamsPerBand-v1650 */
typedef struct SharedSpectrumChAccessParamsPerBand_v1650 {
	long	*extendedSearchSpaceSwitchWithDCI_r16;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SharedSpectrumChAccessParamsPerBand_v1650_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_extendedSearchSpaceSwitchWithDCI_r16_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SharedSpectrumChAccessParamsPerBand_v1650;
extern asn_SEQUENCE_specifics_t asn_SPC_SharedSpectrumChAccessParamsPerBand_v1650_specs_1;
extern asn_TYPE_member_t asn_MBR_SharedSpectrumChAccessParamsPerBand_v1650_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _SharedSpectrumChAccessParamsPerBand_v1650_H_ */
#include <asn_internal.h>
