/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_SIB14_r16_H_
#define	_SIB14_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SIB14-r16 */
typedef struct SIB14_r16 {
	OCTET_STRING_t	 sl_V2X_ConfigCommonExt_r16;
	OCTET_STRING_t	*lateNonCriticalExtension;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SIB14_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SIB14_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_SIB14_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_SIB14_r16_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _SIB14_r16_H_ */
#include <asn_internal.h>
