/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_SimultaneousRxTxPerBandPair_H_
#define	_SimultaneousRxTxPerBandPair_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SimultaneousRxTxPerBandPair */
typedef BIT_STRING_t	 SimultaneousRxTxPerBandPair_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SimultaneousRxTxPerBandPair_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SimultaneousRxTxPerBandPair;
asn_struct_free_f SimultaneousRxTxPerBandPair_free;
asn_struct_print_f SimultaneousRxTxPerBandPair_print;
asn_constr_check_f SimultaneousRxTxPerBandPair_constraint;
jer_type_encoder_f SimultaneousRxTxPerBandPair_encode_jer;
per_type_decoder_f SimultaneousRxTxPerBandPair_decode_uper;
per_type_encoder_f SimultaneousRxTxPerBandPair_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SimultaneousRxTxPerBandPair_H_ */
#include <asn_internal.h>
