/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PC5-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#include "SL-MeasResultRelay-r17.h"

asn_TYPE_member_t asn_MBR_SL_MeasResultRelay_r17_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SL_MeasResultRelay_r17, cellIdentity_r17),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CellAccessRelatedInfo,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"cellIdentity-r17"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SL_MeasResultRelay_r17, sl_RelayUE_Identity_r17),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SL_SourceIdentity_r17,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"sl-RelayUE-Identity-r17"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SL_MeasResultRelay_r17, sl_MeasResult_r17),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SL_MeasResult_r16,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"sl-MeasResult-r17"
		},
};
static const ber_tlv_tag_t asn_DEF_SL_MeasResultRelay_r17_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SL_MeasResultRelay_r17_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cellIdentity-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sl-RelayUE-Identity-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* sl-MeasResult-r17 */
};
asn_SEQUENCE_specifics_t asn_SPC_SL_MeasResultRelay_r17_specs_1 = {
	sizeof(struct SL_MeasResultRelay_r17),
	offsetof(struct SL_MeasResultRelay_r17, _asn_ctx),
	asn_MAP_SL_MeasResultRelay_r17_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SL_MeasResultRelay_r17 = {
	"SL-MeasResultRelay-r17",
	"SL-MeasResultRelay-r17",
	&asn_OP_SEQUENCE,
	asn_DEF_SL_MeasResultRelay_r17_tags_1,
	sizeof(asn_DEF_SL_MeasResultRelay_r17_tags_1)
		/sizeof(asn_DEF_SL_MeasResultRelay_r17_tags_1[0]), /* 1 */
	asn_DEF_SL_MeasResultRelay_r17_tags_1,	/* Same as above */
	sizeof(asn_DEF_SL_MeasResultRelay_r17_tags_1)
		/sizeof(asn_DEF_SL_MeasResultRelay_r17_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_SL_MeasResultRelay_r17_1,
	3,	/* Elements count */
	&asn_SPC_SL_MeasResultRelay_r17_specs_1	/* Additional specs */
};

