/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-Sidelink-Preconf"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_SL_PreconfigGeneral_r16_H_
#define	_SL_PreconfigGeneral_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TDD_UL_DL_ConfigCommon;

/* SL-PreconfigGeneral-r16 */
typedef struct SL_PreconfigGeneral_r16 {
	struct TDD_UL_DL_ConfigCommon	*sl_TDD_Configuration_r16;	/* OPTIONAL */
	BIT_STRING_t	*reservedBits_r16;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SL_PreconfigGeneral_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SL_PreconfigGeneral_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_SL_PreconfigGeneral_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_SL_PreconfigGeneral_r16_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TDD-UL-DL-ConfigCommon.h"

#endif	/* _SL_PreconfigGeneral_r16_H_ */
#include <asn_internal.h>
