/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#include "SL-RxDRX-Report-v1700.h"

asn_TYPE_member_t asn_MBR_SL_RxDRX_Report_v1700_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SL_RxDRX_Report_v1700, sl_DRX_ConfigFromTx_r17),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SL_DRX_ConfigUC_SemiStatic_r17,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"sl-DRX-ConfigFromTx-r17"
		},
};
static const ber_tlv_tag_t asn_DEF_SL_RxDRX_Report_v1700_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SL_RxDRX_Report_v1700_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* sl-DRX-ConfigFromTx-r17 */
};
asn_SEQUENCE_specifics_t asn_SPC_SL_RxDRX_Report_v1700_specs_1 = {
	sizeof(struct SL_RxDRX_Report_v1700),
	offsetof(struct SL_RxDRX_Report_v1700, _asn_ctx),
	asn_MAP_SL_RxDRX_Report_v1700_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SL_RxDRX_Report_v1700 = {
	"SL-RxDRX-Report-v1700",
	"SL-RxDRX-Report-v1700",
	&asn_OP_SEQUENCE,
	asn_DEF_SL_RxDRX_Report_v1700_tags_1,
	sizeof(asn_DEF_SL_RxDRX_Report_v1700_tags_1)
		/sizeof(asn_DEF_SL_RxDRX_Report_v1700_tags_1[0]), /* 1 */
	asn_DEF_SL_RxDRX_Report_v1700_tags_1,	/* Same as above */
	sizeof(asn_DEF_SL_RxDRX_Report_v1700_tags_1)
		/sizeof(asn_DEF_SL_RxDRX_Report_v1700_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_SL_RxDRX_Report_v1700_1,
	1,	/* Elements count */
	&asn_SPC_SL_RxDRX_Report_v1700_specs_1	/* Additional specs */
};

