/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_TAG_Id_H_
#define	_TAG_Id_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TAG-Id */
typedef long	 TAG_Id_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TAG_Id_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TAG_Id;
asn_struct_free_f TAG_Id_free;
asn_struct_print_f TAG_Id_print;
asn_constr_check_f TAG_Id_constraint;
jer_type_encoder_f TAG_Id_encode_jer;
per_type_decoder_f TAG_Id_decode_uper;
per_type_encoder_f TAG_Id_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TAG_Id_H_ */
#include <asn_internal.h>
