/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_TCI_ActivatedConfig_r17_H_
#define	_TCI_ActivatedConfig_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include "TCI-StateId.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TCI-ActivatedConfig-r17 */
typedef struct TCI_ActivatedConfig_r17 {
	struct TCI_ActivatedConfig_r17__pdcch_TCI_r17 {
		A_SEQUENCE_OF(TCI_StateId_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} pdcch_TCI_r17;
	BIT_STRING_t	 pdsch_TCI_r17;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TCI_ActivatedConfig_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCI_ActivatedConfig_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_TCI_ActivatedConfig_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_TCI_ActivatedConfig_r17_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _TCI_ActivatedConfig_r17_H_ */
#include <asn_internal.h>
