/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_UE_MRDC_Capability_v1700_H_
#define	_UE_MRDC_Capability_v1700_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MeasAndMobParametersMRDC-v1700.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct UE_MRDC_Capability_v1730;

/* UE-MRDC-Capability-v1700 */
typedef struct UE_MRDC_Capability_v1700 {
	MeasAndMobParametersMRDC_v1700_t	 measAndMobParametersMRDC_v1700;
	struct UE_MRDC_Capability_v1730	*nonCriticalExtension;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_MRDC_Capability_v1700_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_MRDC_Capability_v1700;
extern asn_SEQUENCE_specifics_t asn_SPC_UE_MRDC_Capability_v1700_specs_1;
extern asn_TYPE_member_t asn_MBR_UE_MRDC_Capability_v1700_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "UE-MRDC-Capability-v1730.h"

#endif	/* _UE_MRDC_Capability_v1700_H_ */
#include <asn_internal.h>
