/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_UE_NR_Capability_v15c0_H_
#define	_UE_NR_Capability_v15c0_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UE_NR_Capability_v15c0__partialFR2_FallbackRX_Req {
	UE_NR_Capability_v15c0__partialFR2_FallbackRX_Req_true	= 0
} e_UE_NR_Capability_v15c0__partialFR2_FallbackRX_Req;

/* Forward declarations */
struct NRDC_Parameters_v15c0;
struct UE_NR_Capability_v15g0;

/* UE-NR-Capability-v15c0 */
typedef struct UE_NR_Capability_v15c0 {
	struct NRDC_Parameters_v15c0	*nrdc_Parameters_v15c0;	/* OPTIONAL */
	long	*partialFR2_FallbackRX_Req;	/* OPTIONAL */
	struct UE_NR_Capability_v15g0	*nonCriticalExtension;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_NR_Capability_v15c0_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_partialFR2_FallbackRX_Req_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_UE_NR_Capability_v15c0;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NRDC-Parameters-v15c0.h"
#include "UE-NR-Capability-v15g0.h"

#endif	/* _UE_NR_Capability_v15c0_H_ */
#include <asn_internal.h>
