/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_UE_RadioPagingInfo_r17_H_
#define	_UE_RadioPagingInfo_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FreqBandIndicatorNR.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UE-RadioPagingInfo-r17 */
typedef struct UE_RadioPagingInfo_r17 {
	struct UE_RadioPagingInfo_r17__pei_SubgroupingSupportBandList_r17 {
		A_SEQUENCE_OF(FreqBandIndicatorNR_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *pei_SubgroupingSupportBandList_r17;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_RadioPagingInfo_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_RadioPagingInfo_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_UE_RadioPagingInfo_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_UE_RadioPagingInfo_r17_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _UE_RadioPagingInfo_r17_H_ */
#include <asn_internal.h>
