/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_UL_ExcessDelayConfig_r17_H_
#define	_UL_ExcessDelayConfig_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ExcessDelay_DRB_IdentityInfo_r17;

/* UL-ExcessDelayConfig-r17 */
typedef struct UL_ExcessDelayConfig_r17 {
	struct UL_ExcessDelayConfig_r17__excessDelay_DRBlist_r17 {
		A_SEQUENCE_OF(struct ExcessDelay_DRB_IdentityInfo_r17) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} excessDelay_DRBlist_r17;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UL_ExcessDelayConfig_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UL_ExcessDelayConfig_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_UL_ExcessDelayConfig_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_UL_ExcessDelayConfig_r17_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ExcessDelay-DRB-IdentityInfo-r17.h"

#endif	/* _UL_ExcessDelayConfig_r17_H_ */
#include <asn_internal.h>
