/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-UE-Variables"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_VarConditionalReconfig_H_
#define	_VarConditionalReconfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CondReconfigToAddModList_r16;

/* VarConditionalReconfig */
typedef struct VarConditionalReconfig {
	struct CondReconfigToAddModList_r16	*condReconfigList;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VarConditionalReconfig_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VarConditionalReconfig;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CondReconfigToAddModList-r16.h"

#endif	/* _VarConditionalReconfig_H_ */
#include <asn_internal.h>
