/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-UE-Variables"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_VarConnEstFailReport_r16_H_
#define	_VarConnEstFailReport_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ConnEstFailReport-r16.h"
#include "PLMN-Identity.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VarConnEstFailReport-r16 */
typedef struct VarConnEstFailReport_r16 {
	ConnEstFailReport_r16_t	 connEstFailReport_r16;
	PLMN_Identity_t	 plmn_Identity_r16;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VarConnEstFailReport_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VarConnEstFailReport_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_VarConnEstFailReport_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_VarConnEstFailReport_r16_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _VarConnEstFailReport_r16_H_ */
#include <asn_internal.h>
