/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-UE-Variables"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_VarMeasReportListSL_r16_H_
#define	_VarMeasReportListSL_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VarMeasReportSL_r16;

/* VarMeasReportListSL-r16 */
typedef struct VarMeasReportListSL_r16 {
	A_SEQUENCE_OF(struct VarMeasReportSL_r16) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VarMeasReportListSL_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VarMeasReportListSL_r16;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VarMeasReportSL-r16.h"

#endif	/* _VarMeasReportListSL_r16_H_ */
#include <asn_internal.h>
