/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_WLAN_Name_r16_H_
#define	_WLAN_Name_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* WLAN-Name-r16 */
typedef OCTET_STRING_t	 WLAN_Name_r16_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_WLAN_Name_r16_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_WLAN_Name_r16;
asn_struct_free_f WLAN_Name_r16_free;
asn_struct_print_f WLAN_Name_r16_print;
asn_constr_check_f WLAN_Name_r16_constraint;
jer_type_encoder_f WLAN_Name_r16_encode_jer;
per_type_decoder_f WLAN_Name_r16_decode_uper;
per_type_encoder_f WLAN_Name_r16_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _WLAN_Name_r16_H_ */
#include <asn_internal.h>
