/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_ANR_Carrier_NB_r16_H_
#define	_ANR_Carrier_NB_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ANR_BlackCellList_NB_r16;

/* ANR-Carrier-NB-r16 */
typedef struct ANR_Carrier_NB_r16 {
	long	 carrierFreqIndex_r16;
	struct ANR_BlackCellList_NB_r16	*blackCellList_r16;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ANR_Carrier_NB_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ANR_Carrier_NB_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_ANR_Carrier_NB_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_ANR_Carrier_NB_r16_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ANR-BlackCellList-NB-r16.h"

#endif	/* _ANR_Carrier_NB_r16_H_ */
#include <asn_internal.h>
