/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_ANR_MeasResult_NB_r16_H_
#define	_ANR_MeasResult_NB_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CarrierFreq-NB-r13.h"
#include "PhysCellId.h"
#include "MeasResultServCell-NB-r14.h"
#include "NRSRP-Range-NB-r14.h"
#include "CellGlobalIdEUTRA.h"
#include "TrackingAreaCode.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PLMN_IdentityList2;

/* ANR-MeasResult-NB-r16 */
typedef struct ANR_MeasResult_NB_r16 {
	CarrierFreq_NB_r13_t	 carrierFreq_r16;
	PhysCellId_t	*physCellId_r16;	/* OPTIONAL */
	MeasResultServCell_NB_r14_t	 measResultLastServCell_r16;
	NRSRP_Range_NB_r14_t	*measResult_r16;	/* OPTIONAL */
	struct ANR_MeasResult_NB_r16__cgi_Info_r16 {
		CellGlobalIdEUTRA_t	 cellGlobalId_r16;
		TrackingAreaCode_t	 trackingAreaCode_r16;
		struct PLMN_IdentityList2	*plmn_IdentityList_r16;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *cgi_Info_r16;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ANR_MeasResult_NB_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ANR_MeasResult_NB_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_ANR_MeasResult_NB_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_ANR_MeasResult_NB_r16_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PLMN-IdentityList2.h"

#endif	/* _ANR_MeasResult_NB_r16_H_ */
#include <asn_internal.h>
