/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_ANR_MeasReport_NB_r16_H_
#define	_ANR_MeasReport_NB_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MeasResultServCell-NB-r14.h"
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CellGlobalIdEUTRA;
struct ANR_MeasResult_NB_r16;

/* ANR-MeasReport-NB-r16 */
typedef struct ANR_MeasReport_NB_r16 {
	struct CellGlobalIdEUTRA	*servCellIdentity_r16;	/* OPTIONAL */
	MeasResultServCell_NB_r14_t	 measResultServCell_r16;
	long	 relativeTimeStamp_r16;
	struct ANR_MeasReport_NB_r16__measResultList_r16 {
		A_SEQUENCE_OF(struct ANR_MeasResult_NB_r16) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} measResultList_r16;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ANR_MeasReport_NB_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ANR_MeasReport_NB_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_ANR_MeasReport_NB_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_ANR_MeasReport_NB_r16_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CellGlobalIdEUTRA.h"
#include "ANR-MeasResult-NB-r16.h"

#endif	/* _ANR_MeasReport_NB_r16_H_ */
#include <asn_internal.h>
