/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_ARFCN_ValueEUTRA_r9_H_
#define	_ARFCN_ValueEUTRA_r9_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ARFCN-ValueEUTRA-r9 */
typedef long	 ARFCN_ValueEUTRA_r9_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ARFCN_ValueEUTRA_r9_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ARFCN_ValueEUTRA_r9;
asn_struct_free_f ARFCN_ValueEUTRA_r9_free;
asn_struct_print_f ARFCN_ValueEUTRA_r9_print;
asn_constr_check_f ARFCN_ValueEUTRA_r9_constraint;
jer_type_encoder_f ARFCN_ValueEUTRA_r9_encode_jer;
per_type_decoder_f ARFCN_ValueEUTRA_r9_decode_uper;
per_type_encoder_f ARFCN_ValueEUTRA_r9_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ARFCN_ValueEUTRA_r9_H_ */
#include <asn_internal.h>
