/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-InterNodeDefinitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_AS_ConfigNR_v1620_H_
#define	_AS_ConfigNR_v1620_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TDM-PatternConfig-r15.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AS-ConfigNR-v1620 */
typedef struct AS_ConfigNR_v1620 {
	TDM_PatternConfig_r15_t	 tdm_PatternConfig2_r16;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AS_ConfigNR_v1620_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AS_ConfigNR_v1620;
extern asn_SEQUENCE_specifics_t asn_SPC_AS_ConfigNR_v1620_specs_1;
extern asn_TYPE_member_t asn_MBR_AS_ConfigNR_v1620_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _AS_ConfigNR_v1620_H_ */
#include <asn_internal.h>
