/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-InterNodeDefinitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_AS_Context_v1610_H_
#define	_AS_Context_v1610_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ConfigRestrictInfoDAPS_r16;

/* AS-Context-v1610 */
typedef struct AS_Context_v1610 {
	OCTET_STRING_t	*sidelinkUEInformationNR_r16;	/* OPTIONAL */
	OCTET_STRING_t	*ueAssistanceInformationNR_r16;	/* OPTIONAL */
	struct ConfigRestrictInfoDAPS_r16	*configRestrictInfoDAPS_r16;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AS_Context_v1610_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AS_Context_v1610;
extern asn_SEQUENCE_specifics_t asn_SPC_AS_Context_v1610_specs_1;
extern asn_TYPE_member_t asn_MBR_AS_Context_v1610_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ConfigRestrictInfoDAPS-r16.h"

#endif	/* _AS_Context_v1610_H_ */
#include <asn_internal.h>
