/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_BandParametersUL_r13_H_
#define	_BandParametersUL_r13_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CA-MIMO-ParametersUL-r10.h"

#ifdef __cplusplus
extern "C" {
#endif

/* BandParametersUL-r13 */
typedef CA_MIMO_ParametersUL_r10_t	 BandParametersUL_r13_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BandParametersUL_r13;
asn_struct_free_f BandParametersUL_r13_free;
asn_struct_print_f BandParametersUL_r13_print;
asn_constr_check_f BandParametersUL_r13_constraint;
jer_type_encoder_f BandParametersUL_r13_encode_jer;
per_type_decoder_f BandParametersUL_r13_decode_uper;
per_type_encoder_f BandParametersUL_r13_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _BandParametersUL_r13_H_ */
#include <asn_internal.h>
