/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_BeamMeasConfigIdleNR_r16_H_
#define	_BeamMeasConfigIdleNR_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BeamMeasConfigIdleNR_r16__reportQuantityRS_IndexNR_r16 {
	BeamMeasConfigIdleNR_r16__reportQuantityRS_IndexNR_r16_rsrp	= 0,
	BeamMeasConfigIdleNR_r16__reportQuantityRS_IndexNR_r16_rsrq	= 1,
	BeamMeasConfigIdleNR_r16__reportQuantityRS_IndexNR_r16_both	= 2
} e_BeamMeasConfigIdleNR_r16__reportQuantityRS_IndexNR_r16;

/* BeamMeasConfigIdleNR-r16 */
typedef struct BeamMeasConfigIdleNR_r16 {
	long	 reportQuantityRS_IndexNR_r16;
	long	 maxReportRS_Index_r16;
	BOOLEAN_t	 reportRS_IndexResultsNR_r16;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BeamMeasConfigIdleNR_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_reportQuantityRS_IndexNR_r16_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_BeamMeasConfigIdleNR_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_BeamMeasConfigIdleNR_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_BeamMeasConfigIdleNR_r16_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _BeamMeasConfigIdleNR_r16_H_ */
#include <asn_internal.h>
