/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_CarrierFreqsListGERAN_NB_r16_H_
#define	_CarrierFreqsListGERAN_NB_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CarrierFreqsGERAN_NB_r16;

/* CarrierFreqsListGERAN-NB-r16 */
typedef struct CarrierFreqsListGERAN_NB_r16 {
	A_SEQUENCE_OF(struct CarrierFreqsGERAN_NB_r16) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CarrierFreqsListGERAN_NB_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CarrierFreqsListGERAN_NB_r16;
extern asn_SET_OF_specifics_t asn_SPC_CarrierFreqsListGERAN_NB_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_CarrierFreqsListGERAN_NB_r16_1[1];
extern asn_per_constraints_t asn_PER_type_CarrierFreqsListGERAN_NB_r16_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CarrierFreqsGERAN-NB-r16.h"

#endif	/* _CarrierFreqsListGERAN_NB_r16_H_ */
#include <asn_internal.h>
