/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-InterNodeDefinitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_ConfigRestrictInfoDAPS_r16_H_
#define	_ConfigRestrictInfoDAPS_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ConfigRestrictInfoDAPS-r16 */
typedef struct ConfigRestrictInfoDAPS_r16 {
	long	*maxSCH_TB_BitsDL_r16;	/* OPTIONAL */
	long	*maxSCH_TB_BitsUL_r16;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ConfigRestrictInfoDAPS_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConfigRestrictInfoDAPS_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_ConfigRestrictInfoDAPS_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_ConfigRestrictInfoDAPS_r16_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ConfigRestrictInfoDAPS_r16_H_ */
#include <asn_internal.h>
