/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_CSG_Identity_H_
#define	_CSG_Identity_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CSG-Identity */
typedef BIT_STRING_t	 CSG_Identity_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_CSG_Identity_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_CSG_Identity;
asn_struct_free_f CSG_Identity_free;
asn_struct_print_f CSG_Identity_print;
asn_constr_check_f CSG_Identity_constraint;
jer_type_encoder_f CSG_Identity_encode_jer;
per_type_decoder_f CSG_Identity_decode_uper;
per_type_encoder_f CSG_Identity_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CSG_Identity_H_ */
#include <asn_internal.h>
