/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_DL_DCCH_MessageType_NB_H_
#define	_DL_DCCH_MessageType_NB_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DL_DCCH_MessageType_NB_PR {
	DL_DCCH_MessageType_NB_PR_NOTHING,	/* No components present */
	DL_DCCH_MessageType_NB_PR_c1,
	DL_DCCH_MessageType_NB_PR_messageClassExtension
} DL_DCCH_MessageType_NB_PR;
typedef enum DL_DCCH_MessageType_NB__c1_PR {
	DL_DCCH_MessageType_NB__c1_PR_NOTHING,	/* No components present */
	DL_DCCH_MessageType_NB__c1_PR_dlInformationTransfer_r13,
	DL_DCCH_MessageType_NB__c1_PR_rrcConnectionReconfiguration_r13,
	DL_DCCH_MessageType_NB__c1_PR_rrcConnectionRelease_r13,
	DL_DCCH_MessageType_NB__c1_PR_securityModeCommand_r13,
	DL_DCCH_MessageType_NB__c1_PR_ueCapabilityEnquiry_r13,
	DL_DCCH_MessageType_NB__c1_PR_rrcConnectionResume_r13,
	DL_DCCH_MessageType_NB__c1_PR_ueInformationRequest_r16,
	DL_DCCH_MessageType_NB__c1_PR_spare1
} DL_DCCH_MessageType_NB__c1_PR;

/* Forward declarations */
struct DLInformationTransfer_NB;
struct RRCConnectionReconfiguration_NB;
struct RRCConnectionRelease_NB;
struct SecurityModeCommand;
struct UECapabilityEnquiry_NB;
struct RRCConnectionResume_NB;
struct UEInformationRequest_NB_r16;

/* DL-DCCH-MessageType-NB */
typedef struct DL_DCCH_MessageType_NB {
	DL_DCCH_MessageType_NB_PR present;
	union DL_DCCH_MessageType_NB_u {
		struct DL_DCCH_MessageType_NB__c1 {
			DL_DCCH_MessageType_NB__c1_PR present;
			union DL_DCCH_MessageType_NB__c1_u {
				struct DLInformationTransfer_NB	*dlInformationTransfer_r13;
				struct RRCConnectionReconfiguration_NB	*rrcConnectionReconfiguration_r13;
				struct RRCConnectionRelease_NB	*rrcConnectionRelease_r13;
				struct SecurityModeCommand	*securityModeCommand_r13;
				struct UECapabilityEnquiry_NB	*ueCapabilityEnquiry_r13;
				struct RRCConnectionResume_NB	*rrcConnectionResume_r13;
				struct UEInformationRequest_NB_r16	*ueInformationRequest_r16;
				NULL_t	 spare1;
			} choice;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *c1;
		struct DL_DCCH_MessageType_NB__messageClassExtension {
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *messageClassExtension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DL_DCCH_MessageType_NB_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DL_DCCH_MessageType_NB;
extern asn_CHOICE_specifics_t asn_SPC_DL_DCCH_MessageType_NB_specs_1;
extern asn_TYPE_member_t asn_MBR_DL_DCCH_MessageType_NB_1[2];
extern asn_per_constraints_t asn_PER_type_DL_DCCH_MessageType_NB_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DLInformationTransfer-NB.h"
#include "RRCConnectionReconfiguration-NB.h"
#include "RRCConnectionRelease-NB.h"
#include "SecurityModeCommand.h"
#include "UECapabilityEnquiry-NB.h"
#include "RRCConnectionResume-NB.h"
#include "UEInformationRequest-NB-r16.h"

#endif	/* _DL_DCCH_MessageType_NB_H_ */
#include <asn_internal.h>
