/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_DL_DCCH_MessageType_H_
#define	_DL_DCCH_MessageType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DL_DCCH_MessageType_PR {
	DL_DCCH_MessageType_PR_NOTHING,	/* No components present */
	DL_DCCH_MessageType_PR_c1,
	DL_DCCH_MessageType_PR_messageClassExtension
} DL_DCCH_MessageType_PR;
typedef enum DL_DCCH_MessageType__c1_PR {
	DL_DCCH_MessageType__c1_PR_NOTHING,	/* No components present */
	DL_DCCH_MessageType__c1_PR_csfbParametersResponseCDMA2000,
	DL_DCCH_MessageType__c1_PR_dlInformationTransfer,
	DL_DCCH_MessageType__c1_PR_handoverFromEUTRAPreparationRequest,
	DL_DCCH_MessageType__c1_PR_mobilityFromEUTRACommand,
	DL_DCCH_MessageType__c1_PR_rrcConnectionReconfiguration,
	DL_DCCH_MessageType__c1_PR_rrcConnectionRelease,
	DL_DCCH_MessageType__c1_PR_securityModeCommand,
	DL_DCCH_MessageType__c1_PR_ueCapabilityEnquiry,
	DL_DCCH_MessageType__c1_PR_counterCheck,
	DL_DCCH_MessageType__c1_PR_ueInformationRequest_r9,
	DL_DCCH_MessageType__c1_PR_loggedMeasurementConfiguration_r10,
	DL_DCCH_MessageType__c1_PR_rnReconfiguration_r10,
	DL_DCCH_MessageType__c1_PR_rrcConnectionResume_r13,
	DL_DCCH_MessageType__c1_PR_dlDedicatedMessageSegment_r16,
	DL_DCCH_MessageType__c1_PR_spare2,
	DL_DCCH_MessageType__c1_PR_spare1
} DL_DCCH_MessageType__c1_PR;

/* Forward declarations */
struct CSFBParametersResponseCDMA2000;
struct DLInformationTransfer;
struct HandoverFromEUTRAPreparationRequest;
struct MobilityFromEUTRACommand;
struct RRCConnectionReconfiguration;
struct RRCConnectionRelease;
struct SecurityModeCommand;
struct UECapabilityEnquiry;
struct CounterCheck;
struct UEInformationRequest_r9;
struct LoggedMeasurementConfiguration_r10;
struct RNReconfiguration_r10;
struct RRCConnectionResume_r13;
struct DLDedicatedMessageSegment_r16;

/* DL-DCCH-MessageType */
typedef struct DL_DCCH_MessageType {
	DL_DCCH_MessageType_PR present;
	union DL_DCCH_MessageType_u {
		struct DL_DCCH_MessageType__c1 {
			DL_DCCH_MessageType__c1_PR present;
			union DL_DCCH_MessageType__c1_u {
				struct CSFBParametersResponseCDMA2000	*csfbParametersResponseCDMA2000;
				struct DLInformationTransfer	*dlInformationTransfer;
				struct HandoverFromEUTRAPreparationRequest	*handoverFromEUTRAPreparationRequest;
				struct MobilityFromEUTRACommand	*mobilityFromEUTRACommand;
				struct RRCConnectionReconfiguration	*rrcConnectionReconfiguration;
				struct RRCConnectionRelease	*rrcConnectionRelease;
				struct SecurityModeCommand	*securityModeCommand;
				struct UECapabilityEnquiry	*ueCapabilityEnquiry;
				struct CounterCheck	*counterCheck;
				struct UEInformationRequest_r9	*ueInformationRequest_r9;
				struct LoggedMeasurementConfiguration_r10	*loggedMeasurementConfiguration_r10;
				struct RNReconfiguration_r10	*rnReconfiguration_r10;
				struct RRCConnectionResume_r13	*rrcConnectionResume_r13;
				struct DLDedicatedMessageSegment_r16	*dlDedicatedMessageSegment_r16;
				NULL_t	 spare2;
				NULL_t	 spare1;
			} choice;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *c1;
		struct DL_DCCH_MessageType__messageClassExtension {
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *messageClassExtension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DL_DCCH_MessageType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DL_DCCH_MessageType;
extern asn_CHOICE_specifics_t asn_SPC_DL_DCCH_MessageType_specs_1;
extern asn_TYPE_member_t asn_MBR_DL_DCCH_MessageType_1[2];
extern asn_per_constraints_t asn_PER_type_DL_DCCH_MessageType_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CSFBParametersResponseCDMA2000.h"
#include "DLInformationTransfer.h"
#include "HandoverFromEUTRAPreparationRequest.h"
#include "MobilityFromEUTRACommand.h"
#include "RRCConnectionReconfiguration.h"
#include "RRCConnectionRelease.h"
#include "SecurityModeCommand.h"
#include "UECapabilityEnquiry.h"
#include "CounterCheck.h"
#include "UEInformationRequest-r9.h"
#include "LoggedMeasurementConfiguration-r10.h"
#include "RNReconfiguration-r10.h"
#include "RRCConnectionResume-r13.h"
#include "DLDedicatedMessageSegment-r16.h"

#endif	/* _DL_DCCH_MessageType_H_ */
#include <asn_internal.h>
