/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_FailedLogicalChannelIdentity_r16_H_
#define	_FailedLogicalChannelIdentity_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FailedLogicalChannelIdentity_r16__cellGroupIndication_r16 {
	FailedLogicalChannelIdentity_r16__cellGroupIndication_r16_mn	= 0,
	FailedLogicalChannelIdentity_r16__cellGroupIndication_r16_sn	= 1
} e_FailedLogicalChannelIdentity_r16__cellGroupIndication_r16;

/* FailedLogicalChannelIdentity-r16 */
typedef struct FailedLogicalChannelIdentity_r16 {
	long	 cellGroupIndication_r16;
	long	*logicalChannelIdentity_r16;	/* OPTIONAL */
	long	*logicalChannelIdentityExt_r16;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FailedLogicalChannelIdentity_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_cellGroupIndication_r16_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_FailedLogicalChannelIdentity_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_FailedLogicalChannelIdentity_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_FailedLogicalChannelIdentity_r16_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _FailedLogicalChannelIdentity_r16_H_ */
#include <asn_internal.h>
