/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_GWUS_ResourceConfig_NB_r16_H_
#define	_GWUS_ResourceConfig_NB_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GWUS_ResourceConfig_NB_r16__resourcePosition_r16 {
	GWUS_ResourceConfig_NB_r16__resourcePosition_r16_primary	= 0,
	GWUS_ResourceConfig_NB_r16__resourcePosition_r16_secondary	= 1
} e_GWUS_ResourceConfig_NB_r16__resourcePosition_r16;

/* Forward declarations */
struct GWUS_NumGroupsList_NB_r16;
struct GWUS_GroupsForServiceList_NB_r16;

/* GWUS-ResourceConfig-NB-r16 */
typedef struct GWUS_ResourceConfig_NB_r16 {
	long	 resourcePosition_r16;
	struct GWUS_NumGroupsList_NB_r16	*numGroupsList_r16;	/* OPTIONAL */
	struct GWUS_GroupsForServiceList_NB_r16	*groupsForServiceList_r16;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GWUS_ResourceConfig_NB_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_resourcePosition_r16_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_GWUS_ResourceConfig_NB_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_GWUS_ResourceConfig_NB_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_GWUS_ResourceConfig_NB_r16_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "GWUS-NumGroupsList-NB-r16.h"
#include "GWUS-GroupsForServiceList-NB-r16.h"

#endif	/* _GWUS_ResourceConfig_NB_r16_H_ */
#include <asn_internal.h>
