/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_GWUS_Paging_ProbThresh_NB_r16_H_
#define	_GWUS_Paging_ProbThresh_NB_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GWUS_Paging_ProbThresh_NB_r16 {
	GWUS_Paging_ProbThresh_NB_r16_p20	= 0,
	GWUS_Paging_ProbThresh_NB_r16_p30	= 1,
	GWUS_Paging_ProbThresh_NB_r16_p40	= 2,
	GWUS_Paging_ProbThresh_NB_r16_p50	= 3,
	GWUS_Paging_ProbThresh_NB_r16_p60	= 4,
	GWUS_Paging_ProbThresh_NB_r16_p70	= 5,
	GWUS_Paging_ProbThresh_NB_r16_p80	= 6,
	GWUS_Paging_ProbThresh_NB_r16_p90	= 7
} e_GWUS_Paging_ProbThresh_NB_r16;

/* GWUS-Paging-ProbThresh-NB-r16 */
typedef long	 GWUS_Paging_ProbThresh_NB_r16_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_GWUS_Paging_ProbThresh_NB_r16_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_GWUS_Paging_ProbThresh_NB_r16;
extern const asn_INTEGER_specifics_t asn_SPC_GWUS_Paging_ProbThresh_NB_r16_specs_1;
asn_struct_free_f GWUS_Paging_ProbThresh_NB_r16_free;
asn_struct_print_f GWUS_Paging_ProbThresh_NB_r16_print;
asn_constr_check_f GWUS_Paging_ProbThresh_NB_r16_constraint;
jer_type_encoder_f GWUS_Paging_ProbThresh_NB_r16_encode_jer;
per_type_decoder_f GWUS_Paging_ProbThresh_NB_r16_decode_uper;
per_type_encoder_f GWUS_Paging_ProbThresh_NB_r16_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _GWUS_Paging_ProbThresh_NB_r16_H_ */
#include <asn_internal.h>
