/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_MeasResultForRSSI_NR_r16_H_
#define	_MeasResultForRSSI_NR_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RSSI-Range-r13.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MeasResultForRSSI-NR-r16 */
typedef struct MeasResultForRSSI_NR_r16 {
	RSSI_Range_r13_t	 rssi_ResultNR_r16;
	long	 channelOccupancyNR_r16;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasResultForRSSI_NR_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasResultForRSSI_NR_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasResultForRSSI_NR_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasResultForRSSI_NR_r16_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _MeasResultForRSSI_NR_r16_H_ */
#include <asn_internal.h>
