/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_MeasIdleConfigSIB_NR_r16_H_
#define	_MeasIdleConfigSIB_NR_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NR-CarrierList-r16.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MeasIdleConfigSIB-NR-r16 */
typedef struct MeasIdleConfigSIB_NR_r16 {
	NR_CarrierList_r16_t	 measIdleCarrierListNR_r16;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasIdleConfigSIB_NR_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasIdleConfigSIB_NR_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasIdleConfigSIB_NR_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasIdleConfigSIB_NR_r16_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _MeasIdleConfigSIB_NR_r16_H_ */
#include <asn_internal.h>
