/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_MobilityParameters_v1610_H_
#define	_MobilityParameters_v1610_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MobilityParameters_v1610__cho_r16 {
	MobilityParameters_v1610__cho_r16_supported	= 0
} e_MobilityParameters_v1610__cho_r16;
typedef enum MobilityParameters_v1610__cho_FDD_TDD_r16 {
	MobilityParameters_v1610__cho_FDD_TDD_r16_supported	= 0
} e_MobilityParameters_v1610__cho_FDD_TDD_r16;
typedef enum MobilityParameters_v1610__cho_Failure_r16 {
	MobilityParameters_v1610__cho_Failure_r16_supported	= 0
} e_MobilityParameters_v1610__cho_Failure_r16;
typedef enum MobilityParameters_v1610__cho_TwoTriggerEvents_r16 {
	MobilityParameters_v1610__cho_TwoTriggerEvents_r16_supported	= 0
} e_MobilityParameters_v1610__cho_TwoTriggerEvents_r16;

/* MobilityParameters-v1610 */
typedef struct MobilityParameters_v1610 {
	long	*cho_r16;	/* OPTIONAL */
	long	*cho_FDD_TDD_r16;	/* OPTIONAL */
	long	*cho_Failure_r16;	/* OPTIONAL */
	long	*cho_TwoTriggerEvents_r16;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MobilityParameters_v1610_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_cho_r16_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_cho_FDD_TDD_r16_4;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_cho_Failure_r16_6;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_cho_TwoTriggerEvents_r16_8;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_MobilityParameters_v1610;
extern asn_SEQUENCE_specifics_t asn_SPC_MobilityParameters_v1610_specs_1;
extern asn_TYPE_member_t asn_MBR_MobilityParameters_v1610_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _MobilityParameters_v1610_H_ */
#include <asn_internal.h>
