/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_NPDSCH_ConfigDedicated_NB_r16_H_
#define	_NPDSCH_ConfigDedicated_NB_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NPDSCH_MultiTB_Config_NB_r16;

/* NPDSCH-ConfigDedicated-NB-r16 */
typedef struct NPDSCH_ConfigDedicated_NB_r16 {
	struct NPDSCH_MultiTB_Config_NB_r16	*npdsch_MultiTB_Config_r16;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NPDSCH_ConfigDedicated_NB_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NPDSCH_ConfigDedicated_NB_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_NPDSCH_ConfigDedicated_NB_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_NPDSCH_ConfigDedicated_NB_r16_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NPDSCH-MultiTB-Config-NB-r16.h"

#endif	/* _NPDSCH_ConfigDedicated_NB_r16_H_ */
#include <asn_internal.h>
