/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_Other_Parameters_v1650_H_
#define	_Other_Parameters_v1650_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Other_Parameters_v1650__mpsPriorityIndication_r16 {
	Other_Parameters_v1650__mpsPriorityIndication_r16_supported	= 0
} e_Other_Parameters_v1650__mpsPriorityIndication_r16;

/* Other-Parameters-v1650 */
typedef struct Other_Parameters_v1650 {
	long	*mpsPriorityIndication_r16;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Other_Parameters_v1650_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_mpsPriorityIndication_r16_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Other_Parameters_v1650;
extern asn_SEQUENCE_specifics_t asn_SPC_Other_Parameters_v1650_specs_1;
extern asn_TYPE_member_t asn_MBR_Other_Parameters_v1650_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _Other_Parameters_v1650_H_ */
#include <asn_internal.h>
