/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_PagingRecordList_v1610_H_
#define	_PagingRecordList_v1610_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PagingRecord_v1610;

/* PagingRecordList-v1610 */
typedef struct PagingRecordList_v1610 {
	A_SEQUENCE_OF(struct PagingRecord_v1610) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PagingRecordList_v1610_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PagingRecordList_v1610;
extern asn_SET_OF_specifics_t asn_SPC_PagingRecordList_v1610_specs_1;
extern asn_TYPE_member_t asn_MBR_PagingRecordList_v1610_1[1];
extern asn_per_constraints_t asn_PER_type_PagingRecordList_v1610_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PagingRecord-v1610.h"

#endif	/* _PagingRecordList_v1610_H_ */
#include <asn_internal.h>
