/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_Paging_v1610_IEs_H_
#define	_Paging_v1610_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Paging_v1610_IEs__uac_ParamModification_r16 {
	Paging_v1610_IEs__uac_ParamModification_r16_true	= 0
} e_Paging_v1610_IEs__uac_ParamModification_r16;

/* Forward declarations */
struct PagingRecordList_v1610;

/* Paging-v1610-IEs */
typedef struct Paging_v1610_IEs {
	struct PagingRecordList_v1610	*pagingRecordList_v1610;	/* OPTIONAL */
	long	*uac_ParamModification_r16;	/* OPTIONAL */
	struct Paging_v1610_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Paging_v1610_IEs_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_uac_ParamModification_r16_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Paging_v1610_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_Paging_v1610_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_Paging_v1610_IEs_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PagingRecordList-v1610.h"

#endif	/* _Paging_v1610_IEs_H_ */
#include <asn_internal.h>
