/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_PhyLayerParameters_NB_v1610_H_
#define	_PhyLayerParameters_NB_v1610_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PhyLayerParameters_NB_v1610__npdsch_MultiTB_r16 {
	PhyLayerParameters_NB_v1610__npdsch_MultiTB_r16_supported	= 0
} e_PhyLayerParameters_NB_v1610__npdsch_MultiTB_r16;
typedef enum PhyLayerParameters_NB_v1610__npdsch_MultiTB_Interleaving_r16 {
	PhyLayerParameters_NB_v1610__npdsch_MultiTB_Interleaving_r16_supported	= 0
} e_PhyLayerParameters_NB_v1610__npdsch_MultiTB_Interleaving_r16;
typedef enum PhyLayerParameters_NB_v1610__npusch_MultiTB_r16 {
	PhyLayerParameters_NB_v1610__npusch_MultiTB_r16_supported	= 0
} e_PhyLayerParameters_NB_v1610__npusch_MultiTB_r16;
typedef enum PhyLayerParameters_NB_v1610__npusch_MultiTB_Interleaving_r16 {
	PhyLayerParameters_NB_v1610__npusch_MultiTB_Interleaving_r16_supported	= 0
} e_PhyLayerParameters_NB_v1610__npusch_MultiTB_Interleaving_r16;
typedef enum PhyLayerParameters_NB_v1610__multiTB_HARQ_AckBundling_r16 {
	PhyLayerParameters_NB_v1610__multiTB_HARQ_AckBundling_r16_supported	= 0
} e_PhyLayerParameters_NB_v1610__multiTB_HARQ_AckBundling_r16;
typedef enum PhyLayerParameters_NB_v1610__slotSymbolResourceResvDL_r16 {
	PhyLayerParameters_NB_v1610__slotSymbolResourceResvDL_r16_supported	= 0
} e_PhyLayerParameters_NB_v1610__slotSymbolResourceResvDL_r16;
typedef enum PhyLayerParameters_NB_v1610__slotSymbolResourceResvUL_r16 {
	PhyLayerParameters_NB_v1610__slotSymbolResourceResvUL_r16_supported	= 0
} e_PhyLayerParameters_NB_v1610__slotSymbolResourceResvUL_r16;
typedef enum PhyLayerParameters_NB_v1610__subframeResourceResvDL_r16 {
	PhyLayerParameters_NB_v1610__subframeResourceResvDL_r16_supported	= 0
} e_PhyLayerParameters_NB_v1610__subframeResourceResvDL_r16;
typedef enum PhyLayerParameters_NB_v1610__subframeResourceResvUL_r16 {
	PhyLayerParameters_NB_v1610__subframeResourceResvUL_r16_supported	= 0
} e_PhyLayerParameters_NB_v1610__subframeResourceResvUL_r16;

/* PhyLayerParameters-NB-v1610 */
typedef struct PhyLayerParameters_NB_v1610 {
	long	*npdsch_MultiTB_r16;	/* OPTIONAL */
	long	*npdsch_MultiTB_Interleaving_r16;	/* OPTIONAL */
	long	*npusch_MultiTB_r16;	/* OPTIONAL */
	long	*npusch_MultiTB_Interleaving_r16;	/* OPTIONAL */
	long	*multiTB_HARQ_AckBundling_r16;	/* OPTIONAL */
	long	*slotSymbolResourceResvDL_r16;	/* OPTIONAL */
	long	*slotSymbolResourceResvUL_r16;	/* OPTIONAL */
	long	*subframeResourceResvDL_r16;	/* OPTIONAL */
	long	*subframeResourceResvUL_r16;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PhyLayerParameters_NB_v1610_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_npdsch_MultiTB_r16_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_npdsch_MultiTB_Interleaving_r16_4;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_npusch_MultiTB_r16_6;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_npusch_MultiTB_Interleaving_r16_8;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_multiTB_HARQ_AckBundling_r16_10;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_slotSymbolResourceResvDL_r16_12;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_slotSymbolResourceResvUL_r16_14;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_subframeResourceResvDL_r16_16;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_subframeResourceResvUL_r16_18;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_PhyLayerParameters_NB_v1610;
extern asn_SEQUENCE_specifics_t asn_SPC_PhyLayerParameters_NB_v1610_specs_1;
extern asn_TYPE_member_t asn_MBR_PhyLayerParameters_NB_v1610_1[9];

#ifdef __cplusplus
}
#endif

#endif	/* _PhyLayerParameters_NB_v1610_H_ */
#include <asn_internal.h>
