/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_PLMN_IdentityInfo_5GC_NB_r16_H_
#define	_PLMN_IdentityInfo_5GC_NB_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PLMN_IdentityInfo_5GC_NB_r16__plmn_Identity_5GC_r16_PR {
	PLMN_IdentityInfo_5GC_NB_r16__plmn_Identity_5GC_r16_PR_NOTHING,	/* No components present */
	PLMN_IdentityInfo_5GC_NB_r16__plmn_Identity_5GC_r16_PR_plmn_Identity_r16,
	PLMN_IdentityInfo_5GC_NB_r16__plmn_Identity_5GC_r16_PR_plmn_Index_r16
} PLMN_IdentityInfo_5GC_NB_r16__plmn_Identity_5GC_r16_PR;
typedef enum PLMN_IdentityInfo_5GC_NB_r16__cellReservedForOperatorUse_r16 {
	PLMN_IdentityInfo_5GC_NB_r16__cellReservedForOperatorUse_r16_reserved	= 0,
	PLMN_IdentityInfo_5GC_NB_r16__cellReservedForOperatorUse_r16_notReserved	= 1
} e_PLMN_IdentityInfo_5GC_NB_r16__cellReservedForOperatorUse_r16;
typedef enum PLMN_IdentityInfo_5GC_NB_r16__ng_U_DataTransfer_r16 {
	PLMN_IdentityInfo_5GC_NB_r16__ng_U_DataTransfer_r16_true	= 0
} e_PLMN_IdentityInfo_5GC_NB_r16__ng_U_DataTransfer_r16;
typedef enum PLMN_IdentityInfo_5GC_NB_r16__up_CIoT_5GS_Optimisation_r16 {
	PLMN_IdentityInfo_5GC_NB_r16__up_CIoT_5GS_Optimisation_r16_true	= 0
} e_PLMN_IdentityInfo_5GC_NB_r16__up_CIoT_5GS_Optimisation_r16;

/* Forward declarations */
struct PLMN_Identity;

/* PLMN-IdentityInfo-5GC-NB-r16 */
typedef struct PLMN_IdentityInfo_5GC_NB_r16 {
	struct PLMN_IdentityInfo_5GC_NB_r16__plmn_Identity_5GC_r16 {
		PLMN_IdentityInfo_5GC_NB_r16__plmn_Identity_5GC_r16_PR present;
		union PLMN_IdentityInfo_5GC_NB_r16__plmn_Identity_5GC_r16_u {
			struct PLMN_Identity	*plmn_Identity_r16;
			long	 plmn_Index_r16;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} plmn_Identity_5GC_r16;
	long	 cellReservedForOperatorUse_r16;
	long	*ng_U_DataTransfer_r16;	/* OPTIONAL */
	long	*up_CIoT_5GS_Optimisation_r16;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PLMN_IdentityInfo_5GC_NB_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_cellReservedForOperatorUse_r16_5;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ng_U_DataTransfer_r16_8;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_up_CIoT_5GS_Optimisation_r16_10;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_PLMN_IdentityInfo_5GC_NB_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_PLMN_IdentityInfo_5GC_NB_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_PLMN_IdentityInfo_5GC_NB_r16_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PLMN-Identity.h"

#endif	/* _PLMN_IdentityInfo_5GC_NB_r16_H_ */
#include <asn_internal.h>
