/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_PUR_PeriodicityAndOffset_NB_r16_H_
#define	_PUR_PeriodicityAndOffset_NB_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PUR_PeriodicityAndOffset_NB_r16_PR {
	PUR_PeriodicityAndOffset_NB_r16_PR_NOTHING,	/* No components present */
	PUR_PeriodicityAndOffset_NB_r16_PR_periodicity8,
	PUR_PeriodicityAndOffset_NB_r16_PR_periodicity16,
	PUR_PeriodicityAndOffset_NB_r16_PR_periodicity32,
	PUR_PeriodicityAndOffset_NB_r16_PR_periodicity64,
	PUR_PeriodicityAndOffset_NB_r16_PR_periodicity128,
	PUR_PeriodicityAndOffset_NB_r16_PR_periodicity256,
	PUR_PeriodicityAndOffset_NB_r16_PR_periodicity512,
	PUR_PeriodicityAndOffset_NB_r16_PR_periodicity1024,
	PUR_PeriodicityAndOffset_NB_r16_PR_periodicity2048,
	PUR_PeriodicityAndOffset_NB_r16_PR_periodicity4096,
	PUR_PeriodicityAndOffset_NB_r16_PR_periodicity8192
} PUR_PeriodicityAndOffset_NB_r16_PR;

/* PUR-PeriodicityAndOffset-NB-r16 */
typedef struct PUR_PeriodicityAndOffset_NB_r16 {
	PUR_PeriodicityAndOffset_NB_r16_PR present;
	union PUR_PeriodicityAndOffset_NB_r16_u {
		long	 periodicity8;
		long	 periodicity16;
		long	 periodicity32;
		long	 periodicity64;
		long	 periodicity128;
		long	 periodicity256;
		long	 periodicity512;
		long	 periodicity1024;
		long	 periodicity2048;
		long	 periodicity4096;
		long	 periodicity8192;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PUR_PeriodicityAndOffset_NB_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PUR_PeriodicityAndOffset_NB_r16;
extern asn_CHOICE_specifics_t asn_SPC_PUR_PeriodicityAndOffset_NB_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_PUR_PeriodicityAndOffset_NB_r16_1[11];
extern asn_per_constraints_t asn_PER_type_PUR_PeriodicityAndOffset_NB_r16_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _PUR_PeriodicityAndOffset_NB_r16_H_ */
#include <asn_internal.h>
