/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_PUR_NRSRP_ChangeThreshold_NB_r16_H_
#define	_PUR_NRSRP_ChangeThreshold_NB_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRSRP-ChangeThresh-NB-r16.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PUR-NRSRP-ChangeThreshold-NB-r16 */
typedef struct PUR_NRSRP_ChangeThreshold_NB_r16 {
	NRSRP_ChangeThresh_NB_r16_t	 increaseThresh_r16;
	NRSRP_ChangeThresh_NB_r16_t	*decreaseThresh_r16;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PUR_NRSRP_ChangeThreshold_NB_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PUR_NRSRP_ChangeThreshold_NB_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_PUR_NRSRP_ChangeThreshold_NB_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_PUR_NRSRP_ChangeThreshold_NB_r16_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _PUR_NRSRP_ChangeThreshold_NB_r16_H_ */
#include <asn_internal.h>
