/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_PURConfigurationRequest_NB_r16_IEs_H_
#define	_PURConfigurationRequest_NB_r16_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PUR_ConfigRequest_NB_r16;

/* PURConfigurationRequest-NB-r16-IEs */
typedef struct PURConfigurationRequest_NB_r16_IEs {
	struct PUR_ConfigRequest_NB_r16	*pur_ConfigRequest_r16;	/* OPTIONAL */
	OCTET_STRING_t	*lateNonCriticalExtension;	/* OPTIONAL */
	struct PURConfigurationRequest_NB_r16_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PURConfigurationRequest_NB_r16_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PURConfigurationRequest_NB_r16_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_PURConfigurationRequest_NB_r16_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_PURConfigurationRequest_NB_r16_IEs_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PUR-ConfigRequest-NB-r16.h"

#endif	/* _PURConfigurationRequest_NB_r16_IEs_H_ */
#include <asn_internal.h>
