/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_PURConfigurationRequest_r16_H_
#define	_PURConfigurationRequest_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PURConfigurationRequest_r16__criticalExtensions_PR {
	PURConfigurationRequest_r16__criticalExtensions_PR_NOTHING,	/* No components present */
	PURConfigurationRequest_r16__criticalExtensions_PR_purConfigurationRequest,
	PURConfigurationRequest_r16__criticalExtensions_PR_criticalExtensionsFuture
} PURConfigurationRequest_r16__criticalExtensions_PR;

/* Forward declarations */
struct PURConfigurationRequest_r16_IEs;

/* PURConfigurationRequest-r16 */
typedef struct PURConfigurationRequest_r16 {
	struct PURConfigurationRequest_r16__criticalExtensions {
		PURConfigurationRequest_r16__criticalExtensions_PR present;
		union PURConfigurationRequest_r16__criticalExtensions_u {
			struct PURConfigurationRequest_r16_IEs	*purConfigurationRequest;
			struct PURConfigurationRequest_r16__criticalExtensions__criticalExtensionsFuture {
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *criticalExtensionsFuture;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} criticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PURConfigurationRequest_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PURConfigurationRequest_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_PURConfigurationRequest_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_PURConfigurationRequest_r16_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PURConfigurationRequest-r16-IEs.h"

#endif	/* _PURConfigurationRequest_r16_H_ */
#include <asn_internal.h>
