/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_PUSCH_ConfigDedicated_v1610_H_
#define	_PUSCH_ConfigDedicated_v1610_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SetupRelease.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PUSCH-ConfigDedicated-v1610 */
typedef struct PUSCH_ConfigDedicated_v1610 {
	SetupRelease_CE_PUSCH_MultiTB_Config_r16_t	 ce_PUSCH_MultiTB_Config_r16;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PUSCH_ConfigDedicated_v1610_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PUSCH_ConfigDedicated_v1610;
extern asn_SEQUENCE_specifics_t asn_SPC_PUSCH_ConfigDedicated_v1610_specs_1;
extern asn_TYPE_member_t asn_MBR_PUSCH_ConfigDedicated_v1610_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _PUSCH_ConfigDedicated_v1610_H_ */
#include <asn_internal.h>
