/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_RadioResourceConfigDedicated_NB_r13_H_
#define	_RadioResourceConfigDedicated_NB_r13_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>
#include "C-RNTI.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RadioResourceConfigDedicated_NB_r13__mac_MainConfig_r13_PR {
	RadioResourceConfigDedicated_NB_r13__mac_MainConfig_r13_PR_NOTHING,	/* No components present */
	RadioResourceConfigDedicated_NB_r13__mac_MainConfig_r13_PR_explicitValue_r13,
	RadioResourceConfigDedicated_NB_r13__mac_MainConfig_r13_PR_defaultValue_r13
} RadioResourceConfigDedicated_NB_r13__mac_MainConfig_r13_PR;

/* Forward declarations */
struct SRB_ToAddModList_NB_r13;
struct DRB_ToAddModList_NB_r13;
struct DRB_ToReleaseList_NB_r13;
struct PhysicalConfigDedicated_NB_r13;
struct RLF_TimersAndConstants_NB_r13;
struct MAC_MainConfig_NB_r13;
struct SchedulingRequestConfig_NB_r15;

/* RadioResourceConfigDedicated-NB-r13 */
typedef struct RadioResourceConfigDedicated_NB_r13 {
	struct SRB_ToAddModList_NB_r13	*srb_ToAddModList_r13;	/* OPTIONAL */
	struct DRB_ToAddModList_NB_r13	*drb_ToAddModList_r13;	/* OPTIONAL */
	struct DRB_ToReleaseList_NB_r13	*drb_ToReleaseList_r13;	/* OPTIONAL */
	struct RadioResourceConfigDedicated_NB_r13__mac_MainConfig_r13 {
		RadioResourceConfigDedicated_NB_r13__mac_MainConfig_r13_PR present;
		union RadioResourceConfigDedicated_NB_r13__mac_MainConfig_r13_u {
			struct MAC_MainConfig_NB_r13	*explicitValue_r13;
			NULL_t	 defaultValue_r13;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *mac_MainConfig_r13;
	struct PhysicalConfigDedicated_NB_r13	*physicalConfigDedicated_r13;	/* OPTIONAL */
	struct RLF_TimersAndConstants_NB_r13	*rlf_TimersAndConstants_r13;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct RadioResourceConfigDedicated_NB_r13__ext1 {
		struct SchedulingRequestConfig_NB_r15	*schedulingRequestConfig_r15;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct RadioResourceConfigDedicated_NB_r13__ext2 {
		C_RNTI_t	*newUE_Identity_r16;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RadioResourceConfigDedicated_NB_r13_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RadioResourceConfigDedicated_NB_r13;
extern asn_SEQUENCE_specifics_t asn_SPC_RadioResourceConfigDedicated_NB_r13_specs_1;
extern asn_TYPE_member_t asn_MBR_RadioResourceConfigDedicated_NB_r13_1[8];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SRB-ToAddModList-NB-r13.h"
#include "DRB-ToAddModList-NB-r13.h"
#include "DRB-ToReleaseList-NB-r13.h"
#include "PhysicalConfigDedicated-NB-r13.h"
#include "RLF-TimersAndConstants-NB-r13.h"
#include "MAC-MainConfig-NB-r13.h"
#include "SchedulingRequestConfig-NB-r15.h"

#endif	/* _RadioResourceConfigDedicated_NB_r13_H_ */
#include <asn_internal.h>
