/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_ReselectionThreshold_H_
#define	_ReselectionThreshold_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ReselectionThreshold */
typedef long	 ReselectionThreshold_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ReselectionThreshold_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ReselectionThreshold;
asn_struct_free_f ReselectionThreshold_free;
asn_struct_print_f ReselectionThreshold_print;
asn_constr_check_f ReselectionThreshold_constraint;
jer_type_encoder_f ReselectionThreshold_encode_jer;
per_type_decoder_f ReselectionThreshold_decode_uper;
per_type_encoder_f ReselectionThreshold_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ReselectionThreshold_H_ */
#include <asn_internal.h>
