/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_ResourceReservationConfigDedicatedUL_r16_H_
#define	_ResourceReservationConfigDedicatedUL_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ResourceReservationConfigUL_r16;

/* ResourceReservationConfigDedicatedUL-r16 */
typedef struct ResourceReservationConfigDedicatedUL_r16 {
	struct ResourceReservationConfigUL_r16	*resourceReservationDedicatedUL_r16;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ResourceReservationConfigDedicatedUL_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ResourceReservationConfigDedicatedUL_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_ResourceReservationConfigDedicatedUL_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_ResourceReservationConfigDedicatedUL_r16_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ResourceReservationConfigUL-r16.h"

#endif	/* _ResourceReservationConfigDedicatedUL_r16_H_ */
#include <asn_internal.h>
