/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_ResourceReservationConfig_NB_r16_H_
#define	_ResourceReservationConfig_NB_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include <BIT_STRING.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ResourceReservationConfig_NB_r16__periodicity_r16 {
	ResourceReservationConfig_NB_r16__periodicity_r16_ms10	= 0,
	ResourceReservationConfig_NB_r16__periodicity_r16_ms20	= 1,
	ResourceReservationConfig_NB_r16__periodicity_r16_ms40	= 2,
	ResourceReservationConfig_NB_r16__periodicity_r16_ms80	= 3,
	ResourceReservationConfig_NB_r16__periodicity_r16_ms160	= 4,
	ResourceReservationConfig_NB_r16__periodicity_r16_spare3	= 5,
	ResourceReservationConfig_NB_r16__periodicity_r16_spare2	= 6,
	ResourceReservationConfig_NB_r16__periodicity_r16_spare1	= 7
} e_ResourceReservationConfig_NB_r16__periodicity_r16;
typedef enum ResourceReservationConfig_NB_r16__resourceReservation_r16_PR {
	ResourceReservationConfig_NB_r16__resourceReservation_r16_PR_NOTHING,	/* No components present */
	ResourceReservationConfig_NB_r16__resourceReservation_r16_PR_subframeBitmap_r16,
	ResourceReservationConfig_NB_r16__resourceReservation_r16_PR_slotConfig_r16
} ResourceReservationConfig_NB_r16__resourceReservation_r16_PR;
typedef enum ResourceReservationConfig_NB_r16__resourceReservation_r16__subframeBitmap_r16_PR {
	ResourceReservationConfig_NB_r16__resourceReservation_r16__subframeBitmap_r16_PR_NOTHING,	/* No components present */
	ResourceReservationConfig_NB_r16__resourceReservation_r16__subframeBitmap_r16_PR_subframePattern10ms,
	ResourceReservationConfig_NB_r16__resourceReservation_r16__subframeBitmap_r16_PR_subframePattern40ms
} ResourceReservationConfig_NB_r16__resourceReservation_r16__subframeBitmap_r16_PR;
typedef enum ResourceReservationConfig_NB_r16__resourceReservation_r16__slotConfig_r16__slotBitmap_r16_PR {
	ResourceReservationConfig_NB_r16__resourceReservation_r16__slotConfig_r16__slotBitmap_r16_PR_NOTHING,	/* No components present */
	ResourceReservationConfig_NB_r16__resourceReservation_r16__slotConfig_r16__slotBitmap_r16_PR_slotPattern10ms,
	ResourceReservationConfig_NB_r16__resourceReservation_r16__slotConfig_r16__slotBitmap_r16_PR_slotPattern40ms
} ResourceReservationConfig_NB_r16__resourceReservation_r16__slotConfig_r16__slotBitmap_r16_PR;
typedef enum ResourceReservationConfig_NB_r16__resourceReservation_r16__slotConfig_r16__symbolBitmap_r16_PR {
	ResourceReservationConfig_NB_r16__resourceReservation_r16__slotConfig_r16__symbolBitmap_r16_PR_NOTHING,	/* No components present */
	ResourceReservationConfig_NB_r16__resourceReservation_r16__slotConfig_r16__symbolBitmap_r16_PR_symbolBitmapFddDl,
	ResourceReservationConfig_NB_r16__resourceReservation_r16__slotConfig_r16__symbolBitmap_r16_PR_symbolBitmapFddUlOrTdd
} ResourceReservationConfig_NB_r16__resourceReservation_r16__slotConfig_r16__symbolBitmap_r16_PR;

/* ResourceReservationConfig-NB-r16 */
typedef struct ResourceReservationConfig_NB_r16 {
	long	 periodicity_r16;
	long	 startPosition_r16;
	struct ResourceReservationConfig_NB_r16__resourceReservation_r16 {
		ResourceReservationConfig_NB_r16__resourceReservation_r16_PR present;
		union ResourceReservationConfig_NB_r16__resourceReservation_r16_u {
			struct ResourceReservationConfig_NB_r16__resourceReservation_r16__subframeBitmap_r16 {
				ResourceReservationConfig_NB_r16__resourceReservation_r16__subframeBitmap_r16_PR present;
				union ResourceReservationConfig_NB_r16__resourceReservation_r16__subframeBitmap_r16_u {
					BIT_STRING_t	 subframePattern10ms;
					BIT_STRING_t	 subframePattern40ms;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *subframeBitmap_r16;
			struct ResourceReservationConfig_NB_r16__resourceReservation_r16__slotConfig_r16 {
				struct ResourceReservationConfig_NB_r16__resourceReservation_r16__slotConfig_r16__slotBitmap_r16 {
					ResourceReservationConfig_NB_r16__resourceReservation_r16__slotConfig_r16__slotBitmap_r16_PR present;
					union ResourceReservationConfig_NB_r16__resourceReservation_r16__slotConfig_r16__slotBitmap_r16_u {
						BIT_STRING_t	 slotPattern10ms;
						BIT_STRING_t	 slotPattern40ms;
					} choice;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} slotBitmap_r16;
				struct ResourceReservationConfig_NB_r16__resourceReservation_r16__slotConfig_r16__symbolBitmap_r16 {
					ResourceReservationConfig_NB_r16__resourceReservation_r16__slotConfig_r16__symbolBitmap_r16_PR present;
					union ResourceReservationConfig_NB_r16__resourceReservation_r16__slotConfig_r16__symbolBitmap_r16_u {
						struct ResourceReservationConfig_NB_r16__resourceReservation_r16__slotConfig_r16__symbolBitmap_r16__symbolBitmapFddDl {
							BIT_STRING_t	*symbolBitmap1_r16;	/* OPTIONAL */
							BIT_STRING_t	*symbolBitmap2_r16;	/* OPTIONAL */
							
							/* Context for parsing across buffer boundaries */
							asn_struct_ctx_t _asn_ctx;
						} *symbolBitmapFddDl;
						struct ResourceReservationConfig_NB_r16__resourceReservation_r16__slotConfig_r16__symbolBitmap_r16__symbolBitmapFddUlOrTdd {
							BIT_STRING_t	*symbolBitmap1_r16;	/* OPTIONAL */
							BIT_STRING_t	*symbolBitmap2_r16;	/* OPTIONAL */
							
							/* Context for parsing across buffer boundaries */
							asn_struct_ctx_t _asn_ctx;
						} *symbolBitmapFddUlOrTdd;
					} choice;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} symbolBitmap_r16;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *slotConfig_r16;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} resourceReservation_r16;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ResourceReservationConfig_NB_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_periodicity_r16_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ResourceReservationConfig_NB_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_ResourceReservationConfig_NB_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_ResourceReservationConfig_NB_r16_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ResourceReservationConfig_NB_r16_H_ */
#include <asn_internal.h>
