/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_ResumeIdentity_r13_H_
#define	_ResumeIdentity_r13_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ResumeIdentity-r13 */
typedef BIT_STRING_t	 ResumeIdentity_r13_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ResumeIdentity_r13_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ResumeIdentity_r13;
asn_struct_free_f ResumeIdentity_r13_free;
asn_struct_print_f ResumeIdentity_r13_print;
asn_constr_check_f ResumeIdentity_r13_constraint;
jer_type_encoder_f ResumeIdentity_r13_encode_jer;
per_type_decoder_f ResumeIdentity_r13_decode_uper;
per_type_encoder_f ResumeIdentity_r13_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ResumeIdentity_r13_H_ */
#include <asn_internal.h>
