/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_RF_Parameters_v1630_H_
#define	_RF_Parameters_v1630_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SupportedBandCombination_v1630;
struct SupportedBandCombinationAdd_v1630;
struct SupportedBandCombinationReduced_v1630;

/* RF-Parameters-v1630 */
typedef struct RF_Parameters_v1630 {
	struct SupportedBandCombination_v1630	*supportedBandCombination_v1630;	/* OPTIONAL */
	struct SupportedBandCombinationAdd_v1630	*supportedBandCombinationAdd_v1630;	/* OPTIONAL */
	struct SupportedBandCombinationReduced_v1630	*supportedBandCombinationReduced_v1630;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RF_Parameters_v1630_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RF_Parameters_v1630;
extern asn_SEQUENCE_specifics_t asn_SPC_RF_Parameters_v1630_specs_1;
extern asn_TYPE_member_t asn_MBR_RF_Parameters_v1630_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SupportedBandCombination-v1630.h"
#include "SupportedBandCombinationAdd-v1630.h"
#include "SupportedBandCombinationReduced-v1630.h"

#endif	/* _RF_Parameters_v1630_H_ */
#include <asn_internal.h>
