/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_RLF_Report_NB_r16_H_
#define	_RLF_Report_NB_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CellGlobalIdEUTRA.h"
#include "TimeSinceFailure-r11.h"
#include "NRSRP-Range-NB-r14.h"
#include "NRSRQ-Range-NB-r14.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CellGlobalIdEUTRA;
struct LocationInfo_r10;

/* RLF-Report-NB-r16 */
typedef struct RLF_Report_NB_r16 {
	CellGlobalIdEUTRA_t	 failedPCellId_r16;
	struct CellGlobalIdEUTRA	*reestablishmentCellId_r16;	/* OPTIONAL */
	struct LocationInfo_r10	*locationInfo_r16;	/* OPTIONAL */
	struct RLF_Report_NB_r16__measResultLastServCell_r16 {
		NRSRP_Range_NB_r14_t	 nrsrpResult_r16;
		NRSRQ_Range_NB_r14_t	*nrsrqResult_r16;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} measResultLastServCell_r16;
	TimeSinceFailure_r11_t	*timeSinceFailure_r16;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RLF_Report_NB_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RLF_Report_NB_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_RLF_Report_NB_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_RLF_Report_NB_r16_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CellGlobalIdEUTRA.h"
#include "LocationInfo-r10.h"

#endif	/* _RLF_Report_NB_r16_H_ */
#include <asn_internal.h>
