/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_RRCConnectionRelease_NB_v1610_IEs_H_
#define	_RRCConnectionRelease_NB_v1610_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "I-RNTI-r15.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ANR_MeasConfig_NB_r16;
struct SetupRelease_PUR_Config_NB_r16;

/* RRCConnectionRelease-NB-v1610-IEs */
typedef struct RRCConnectionRelease_NB_v1610_IEs {
	I_RNTI_r15_t	*resumeIdentity_r16;	/* OPTIONAL */
	struct ANR_MeasConfig_NB_r16	*anr_MeasConfig_r16;	/* OPTIONAL */
	struct SetupRelease_PUR_Config_NB_r16	*pur_Config_r16;	/* OPTIONAL */
	struct RRCConnectionRelease_NB_v1610_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnectionRelease_NB_v1610_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionRelease_NB_v1610_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCConnectionRelease_NB_v1610_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCConnectionRelease_NB_v1610_IEs_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ANR-MeasConfig-NB-r16.h"
#include "SetupRelease.h"

#endif	/* _RRCConnectionRelease_NB_v1610_IEs_H_ */
#include <asn_internal.h>
