/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_RRCConnectionResume_NB_v1610_IEs_H_
#define	_RRCConnectionResume_NB_v1610_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRCConnectionResume_NB_v1610_IEs__fullConfig_r16 {
	RRCConnectionResume_NB_v1610_IEs__fullConfig_r16_true	= 0
} e_RRCConnectionResume_NB_v1610_IEs__fullConfig_r16;

/* RRCConnectionResume-NB-v1610-IEs */
typedef struct RRCConnectionResume_NB_v1610_IEs {
	long	*fullConfig_r16;	/* OPTIONAL */
	struct RRCConnectionResume_NB_v1610_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnectionResume_NB_v1610_IEs_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_fullConfig_r16_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionResume_NB_v1610_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCConnectionResume_NB_v1610_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCConnectionResume_NB_v1610_IEs_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RRCConnectionResume_NB_v1610_IEs_H_ */
#include <asn_internal.h>
