/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_RRCConnectionRelease_NB_v1550_IEs_H_
#define	_RRCConnectionRelease_NB_v1550_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RedirectedCarrierInfo_NB_v1550;
struct RRCConnectionRelease_NB_v15b0_IEs;

/* RRCConnectionRelease-NB-v1550-IEs */
typedef struct RRCConnectionRelease_NB_v1550_IEs {
	struct RedirectedCarrierInfo_NB_v1550	*redirectedCarrierInfo_v1550;	/* OPTIONAL */
	struct RRCConnectionRelease_NB_v15b0_IEs	*nonCriticalExtension;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnectionRelease_NB_v1550_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionRelease_NB_v1550_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCConnectionRelease_NB_v1550_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCConnectionRelease_NB_v1550_IEs_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RedirectedCarrierInfo-NB-v1550.h"
#include "RRCConnectionRelease-NB-v15b0-IEs.h"

#endif	/* _RRCConnectionRelease_NB_v1550_IEs_H_ */
#include <asn_internal.h>
