/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_RRCConnectionResumeRequest_NB_H_
#define	_RRCConnectionResumeRequest_NB_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRCConnectionResumeRequest_NB__criticalExtensions_PR {
	RRCConnectionResumeRequest_NB__criticalExtensions_PR_NOTHING,	/* No components present */
	RRCConnectionResumeRequest_NB__criticalExtensions_PR_rrcConnectionResumeRequest_r13,
	RRCConnectionResumeRequest_NB__criticalExtensions_PR_later
} RRCConnectionResumeRequest_NB__criticalExtensions_PR;
typedef enum RRCConnectionResumeRequest_NB__criticalExtensions__later_PR {
	RRCConnectionResumeRequest_NB__criticalExtensions__later_PR_NOTHING,	/* No components present */
	RRCConnectionResumeRequest_NB__criticalExtensions__later_PR_rrcConnectionResumeRequest_r16,
	RRCConnectionResumeRequest_NB__criticalExtensions__later_PR_criticalExtensionsFuture
} RRCConnectionResumeRequest_NB__criticalExtensions__later_PR;

/* Forward declarations */
struct RRCConnectionResumeRequest_NB_r13_IEs;
struct RRCConnectionResumeRequest_5GC_NB_r16_IEs;

/* RRCConnectionResumeRequest-NB */
typedef struct RRCConnectionResumeRequest_NB {
	struct RRCConnectionResumeRequest_NB__criticalExtensions {
		RRCConnectionResumeRequest_NB__criticalExtensions_PR present;
		union RRCConnectionResumeRequest_NB__criticalExtensions_u {
			struct RRCConnectionResumeRequest_NB_r13_IEs	*rrcConnectionResumeRequest_r13;
			struct RRCConnectionResumeRequest_NB__criticalExtensions__later {
				RRCConnectionResumeRequest_NB__criticalExtensions__later_PR present;
				union RRCConnectionResumeRequest_NB__criticalExtensions__later_u {
					struct RRCConnectionResumeRequest_5GC_NB_r16_IEs	*rrcConnectionResumeRequest_r16;
					struct RRCConnectionResumeRequest_NB__criticalExtensions__later__criticalExtensionsFuture {
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} *criticalExtensionsFuture;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *later;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} criticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnectionResumeRequest_NB_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionResumeRequest_NB;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCConnectionResumeRequest_NB_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCConnectionResumeRequest_NB_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RRCConnectionResumeRequest-NB-r13-IEs.h"
#include "RRCConnectionResumeRequest-5GC-NB-r16-IEs.h"

#endif	/* _RRCConnectionResumeRequest_NB_H_ */
#include <asn_internal.h>
