/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_RRCConnectionReestablishmentRequest_NB_H_
#define	_RRCConnectionReestablishmentRequest_NB_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRCConnectionReestablishmentRequest_NB__criticalExtensions_PR {
	RRCConnectionReestablishmentRequest_NB__criticalExtensions_PR_NOTHING,	/* No components present */
	RRCConnectionReestablishmentRequest_NB__criticalExtensions_PR_rrcConnectionReestablishmentRequest_r13,
	RRCConnectionReestablishmentRequest_NB__criticalExtensions_PR_later
} RRCConnectionReestablishmentRequest_NB__criticalExtensions_PR;
typedef enum RRCConnectionReestablishmentRequest_NB__criticalExtensions__later_PR {
	RRCConnectionReestablishmentRequest_NB__criticalExtensions__later_PR_NOTHING,	/* No components present */
	RRCConnectionReestablishmentRequest_NB__criticalExtensions__later_PR_rrcConnectionReestablishmentRequest_r14,
	RRCConnectionReestablishmentRequest_NB__criticalExtensions__later_PR_later
} RRCConnectionReestablishmentRequest_NB__criticalExtensions__later_PR;
typedef enum RRCConnectionReestablishmentRequest_NB__criticalExtensions__later__later_PR {
	RRCConnectionReestablishmentRequest_NB__criticalExtensions__later__later_PR_NOTHING,	/* No components present */
	RRCConnectionReestablishmentRequest_NB__criticalExtensions__later__later_PR_rrcConnectionReestablishmentRequest_r16,
	RRCConnectionReestablishmentRequest_NB__criticalExtensions__later__later_PR_criticalExtensionsFuture
} RRCConnectionReestablishmentRequest_NB__criticalExtensions__later__later_PR;

/* Forward declarations */
struct RRCConnectionReestablishmentRequest_NB_r13_IEs;
struct RRCConnectionReestablishmentRequest_NB_r14_IEs;
struct RRCConnectionReestablishmentRequest_5GC_NB_r16_IEs;

/* RRCConnectionReestablishmentRequest-NB */
typedef struct RRCConnectionReestablishmentRequest_NB {
	struct RRCConnectionReestablishmentRequest_NB__criticalExtensions {
		RRCConnectionReestablishmentRequest_NB__criticalExtensions_PR present;
		union RRCConnectionReestablishmentRequest_NB__criticalExtensions_u {
			struct RRCConnectionReestablishmentRequest_NB_r13_IEs	*rrcConnectionReestablishmentRequest_r13;
			struct RRCConnectionReestablishmentRequest_NB__criticalExtensions__later {
				RRCConnectionReestablishmentRequest_NB__criticalExtensions__later_PR present;
				union RRCConnectionReestablishmentRequest_NB__criticalExtensions__later_u {
					struct RRCConnectionReestablishmentRequest_NB_r14_IEs	*rrcConnectionReestablishmentRequest_r14;
					struct RRCConnectionReestablishmentRequest_NB__criticalExtensions__later__later {
						RRCConnectionReestablishmentRequest_NB__criticalExtensions__later__later_PR present;
						union RRCConnectionReestablishmentRequest_NB__criticalExtensions__later__later_u {
							struct RRCConnectionReestablishmentRequest_5GC_NB_r16_IEs	*rrcConnectionReestablishmentRequest_r16;
							struct RRCConnectionReestablishmentRequest_NB__criticalExtensions__later__later__criticalExtensionsFuture {
								
								/* Context for parsing across buffer boundaries */
								asn_struct_ctx_t _asn_ctx;
							} *criticalExtensionsFuture;
						} choice;
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} *later;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *later;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} criticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnectionReestablishmentRequest_NB_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionReestablishmentRequest_NB;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCConnectionReestablishmentRequest_NB_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCConnectionReestablishmentRequest_NB_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RRCConnectionReestablishmentRequest-NB-r13-IEs.h"
#include "RRCConnectionReestablishmentRequest-NB-r14-IEs.h"
#include "RRCConnectionReestablishmentRequest-5GC-NB-r16-IEs.h"

#endif	/* _RRCConnectionReestablishmentRequest_NB_H_ */
#include <asn_internal.h>
