/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_RRCConnectionResumeRequest_5GC_NB_r16_IEs_H_
#define	_RRCConnectionResumeRequest_5GC_NB_r16_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "I-RNTI-r15.h"
#include "ShortMAC-I.h"
#include "EstablishmentCause-NB-r13.h"
#include "CQI-NPDCCH-NB-r14.h"
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RRCConnectionResumeRequest-5GC-NB-r16-IEs */
typedef struct RRCConnectionResumeRequest_5GC_NB_r16_IEs {
	I_RNTI_r15_t	 resumeID_r16;
	ShortMAC_I_t	 shortResumeMAC_I_r16;
	EstablishmentCause_NB_r13_t	 resumeCause_r16;
	CQI_NPDCCH_NB_r14_t	 cqi_NPDCCH_r16;
	BIT_STRING_t	 spare;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnectionResumeRequest_5GC_NB_r16_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionResumeRequest_5GC_NB_r16_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCConnectionResumeRequest_5GC_NB_r16_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCConnectionResumeRequest_5GC_NB_r16_IEs_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _RRCConnectionResumeRequest_5GC_NB_r16_IEs_H_ */
#include <asn_internal.h>
