/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_RRCConnectionRequest_NB_H_
#define	_RRCConnectionRequest_NB_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRCConnectionRequest_NB__criticalExtensions_PR {
	RRCConnectionRequest_NB__criticalExtensions_PR_NOTHING,	/* No components present */
	RRCConnectionRequest_NB__criticalExtensions_PR_rrcConnectionRequest_r13,
	RRCConnectionRequest_NB__criticalExtensions_PR_later
} RRCConnectionRequest_NB__criticalExtensions_PR;
typedef enum RRCConnectionRequest_NB__criticalExtensions__later_PR {
	RRCConnectionRequest_NB__criticalExtensions__later_PR_NOTHING,	/* No components present */
	RRCConnectionRequest_NB__criticalExtensions__later_PR_rrcConnectionRequest_r16,
	RRCConnectionRequest_NB__criticalExtensions__later_PR_criticalExtensionsFuture
} RRCConnectionRequest_NB__criticalExtensions__later_PR;

/* Forward declarations */
struct RRCConnectionRequest_NB_r13_IEs;
struct RRCConnectionRequest_5GC_NB_r16_IEs;

/* RRCConnectionRequest-NB */
typedef struct RRCConnectionRequest_NB {
	struct RRCConnectionRequest_NB__criticalExtensions {
		RRCConnectionRequest_NB__criticalExtensions_PR present;
		union RRCConnectionRequest_NB__criticalExtensions_u {
			struct RRCConnectionRequest_NB_r13_IEs	*rrcConnectionRequest_r13;
			struct RRCConnectionRequest_NB__criticalExtensions__later {
				RRCConnectionRequest_NB__criticalExtensions__later_PR present;
				union RRCConnectionRequest_NB__criticalExtensions__later_u {
					struct RRCConnectionRequest_5GC_NB_r16_IEs	*rrcConnectionRequest_r16;
					struct RRCConnectionRequest_NB__criticalExtensions__later__criticalExtensionsFuture {
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} *criticalExtensionsFuture;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *later;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} criticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnectionRequest_NB_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionRequest_NB;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCConnectionRequest_NB_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCConnectionRequest_NB_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RRCConnectionRequest-NB-r13-IEs.h"
#include "RRCConnectionRequest-5GC-NB-r16-IEs.h"

#endif	/* _RRCConnectionRequest_NB_H_ */
#include <asn_internal.h>
