/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_RRCConnectionResume_v1610_IEs_H_
#define	_RRCConnectionResume_v1610_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <OCTET_STRING.h>
#include "P-Max.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRCConnectionResume_v1610_IEs__idleModeMeasurementReq_r16 {
	RRCConnectionResume_v1610_IEs__idleModeMeasurementReq_r16_true	= 0
} e_RRCConnectionResume_v1610_IEs__idleModeMeasurementReq_r16;
typedef enum RRCConnectionResume_v1610_IEs__restoreMCG_SCells_r16 {
	RRCConnectionResume_v1610_IEs__restoreMCG_SCells_r16_true	= 0
} e_RRCConnectionResume_v1610_IEs__restoreMCG_SCells_r16;
typedef enum RRCConnectionResume_v1610_IEs__restoreSCG_r16 {
	RRCConnectionResume_v1610_IEs__restoreSCG_r16_true	= 0
} e_RRCConnectionResume_v1610_IEs__restoreSCG_r16;

/* Forward declarations */
struct SCellToAddModList_r16;
struct SCellToReleaseListExt_r13;
struct SCellGroupToReleaseList_r15;
struct SCellGroupToAddModList_r15;
struct TDM_PatternConfig_r15;

/* RRCConnectionResume-v1610-IEs */
typedef struct RRCConnectionResume_v1610_IEs {
	long	*idleModeMeasurementReq_r16;	/* OPTIONAL */
	long	*restoreMCG_SCells_r16;	/* OPTIONAL */
	long	*restoreSCG_r16;	/* OPTIONAL */
	struct SCellToAddModList_r16	*sCellToAddModList_r16;	/* OPTIONAL */
	struct SCellToReleaseListExt_r13	*sCellToReleaseList_r16;	/* OPTIONAL */
	struct SCellGroupToReleaseList_r15	*sCellGroupToReleaseList_r16;	/* OPTIONAL */
	struct SCellGroupToAddModList_r15	*sCellGroupToAddModList_r16;	/* OPTIONAL */
	OCTET_STRING_t	*nr_SecondaryCellGroupConfig_r16;	/* OPTIONAL */
	P_Max_t	*p_MaxEUTRA_r16;	/* OPTIONAL */
	P_Max_t	*p_MaxUE_FR1_r16;	/* OPTIONAL */
	struct TDM_PatternConfig_r15	*tdm_PatternConfig_r16;	/* OPTIONAL */
	struct TDM_PatternConfig_r15	*tdm_PatternConfig2_r16;	/* OPTIONAL */
	struct RRCConnectionResume_v1610_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnectionResume_v1610_IEs_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_idleModeMeasurementReq_r16_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_restoreMCG_SCells_r16_4;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_restoreSCG_r16_6;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionResume_v1610_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCConnectionResume_v1610_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCConnectionResume_v1610_IEs_1[13];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SCellToAddModList-r16.h"
#include "SCellToReleaseListExt-r13.h"
#include "SCellGroupToReleaseList-r15.h"
#include "SCellGroupToAddModList-r15.h"
#include "TDM-PatternConfig-r15.h"

#endif	/* _RRCConnectionResume_v1610_IEs_H_ */
#include <asn_internal.h>
