/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_RRCEarlyDataComplete_NB_r15_IEs_H_
#define	_RRCEarlyDataComplete_NB_r15_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DedicatedInfoNAS.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RedirectedCarrierInfo_NB_r13;
struct RedirectedCarrierInfo_NB_v1430;
struct RRCEarlyDataComplete_NB_v1590_IEs;

/* RRCEarlyDataComplete-NB-r15-IEs */
typedef struct RRCEarlyDataComplete_NB_r15_IEs {
	DedicatedInfoNAS_t	*dedicatedInfoNAS_r15;	/* OPTIONAL */
	long	*extendedWaitTime_r15;	/* OPTIONAL */
	struct RedirectedCarrierInfo_NB_r13	*redirectedCarrierInfo_r15;	/* OPTIONAL */
	struct RedirectedCarrierInfo_NB_v1430	*redirectedCarrierInfoExt_r15;	/* OPTIONAL */
	struct RRCEarlyDataComplete_NB_v1590_IEs	*nonCriticalExtension;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCEarlyDataComplete_NB_r15_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCEarlyDataComplete_NB_r15_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCEarlyDataComplete_NB_r15_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCEarlyDataComplete_NB_r15_IEs_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RedirectedCarrierInfo-NB-r13.h"
#include "RedirectedCarrierInfo-NB-v1430.h"
#include "RRCEarlyDataComplete-NB-v1590-IEs.h"

#endif	/* _RRCEarlyDataComplete_NB_r15_IEs_H_ */
#include <asn_internal.h>
