/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_RSRP_Range_v1360_H_
#define	_RSRP_Range_v1360_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RSRP-Range-v1360 */
typedef long	 RSRP_Range_v1360_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RSRP_Range_v1360_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RSRP_Range_v1360;
asn_struct_free_f RSRP_Range_v1360_free;
asn_struct_print_f RSRP_Range_v1360_print;
asn_constr_check_f RSRP_Range_v1360_constraint;
jer_type_encoder_f RSRP_Range_v1360_encode_jer;
per_type_decoder_f RSRP_Range_v1360_decode_uper;
per_type_encoder_f RSRP_Range_v1360_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RSRP_Range_v1360_H_ */
#include <asn_internal.h>
