/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_SC_MCCH_Message_r13_H_
#define	_SC_MCCH_Message_r13_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SC-MCCH-MessageType-r13.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SC-MCCH-Message-r13 */
typedef struct SC_MCCH_Message_r13 {
	SC_MCCH_MessageType_r13_t	 message;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SC_MCCH_Message_r13_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SC_MCCH_Message_r13;

#ifdef __cplusplus
}
#endif

#endif	/* _SC_MCCH_Message_r13_H_ */
#include <asn_internal.h>
