/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_SCellGroupIndex_r15_H_
#define	_SCellGroupIndex_r15_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SCellGroupIndex-r15 */
typedef long	 SCellGroupIndex_r15_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SCellGroupIndex_r15_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SCellGroupIndex_r15;
asn_struct_free_f SCellGroupIndex_r15_free;
asn_struct_print_f SCellGroupIndex_r15_print;
asn_constr_check_f SCellGroupIndex_r15_constraint;
jer_type_encoder_f SCellGroupIndex_r15_encode_jer;
per_type_decoder_f SCellGroupIndex_r15_decode_uper;
per_type_encoder_f SCellGroupIndex_r15_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SCellGroupIndex_r15_H_ */
#include <asn_internal.h>
