/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_SchedulingInfo_H_
#define	_SchedulingInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SI-Periodicity-r12.h"
#include "SIB-MappingInfo.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SchedulingInfo */
typedef struct SchedulingInfo {
	SI_Periodicity_r12_t	 si_Periodicity;
	SIB_MappingInfo_t	 sib_MappingInfo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SchedulingInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SchedulingInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_SchedulingInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_SchedulingInfo_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _SchedulingInfo_H_ */
#include <asn_internal.h>
