/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_SetupRelease_H_
#define	_SetupRelease_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SetupRelease_PUR_Config_r16_PR {
	SetupRelease_PUR_Config_r16_PR_NOTHING,	/* No components present */
	SetupRelease_PUR_Config_r16_PR_release,
	SetupRelease_PUR_Config_r16_PR_setup
} SetupRelease_PUR_Config_r16_PR;
typedef enum SetupRelease_EthernetHeaderCompression_r16_PR {
	SetupRelease_EthernetHeaderCompression_r16_PR_NOTHING,	/* No components present */
	SetupRelease_EthernetHeaderCompression_r16_PR_release,
	SetupRelease_EthernetHeaderCompression_r16_PR_setup
} SetupRelease_EthernetHeaderCompression_r16_PR;
typedef enum SetupRelease_CE_PDSCH_MultiTB_Config_r16_PR {
	SetupRelease_CE_PDSCH_MultiTB_Config_r16_PR_NOTHING,	/* No components present */
	SetupRelease_CE_PDSCH_MultiTB_Config_r16_PR_release,
	SetupRelease_CE_PDSCH_MultiTB_Config_r16_PR_setup
} SetupRelease_CE_PDSCH_MultiTB_Config_r16_PR;
typedef enum SetupRelease_ResourceReservationConfigDedicatedDL_r16_PR {
	SetupRelease_ResourceReservationConfigDedicatedDL_r16_PR_NOTHING,	/* No components present */
	SetupRelease_ResourceReservationConfigDedicatedDL_r16_PR_release,
	SetupRelease_ResourceReservationConfigDedicatedDL_r16_PR_setup
} SetupRelease_ResourceReservationConfigDedicatedDL_r16_PR;
typedef enum SetupRelease_ResourceReservationConfigDedicatedUL_r16_PR {
	SetupRelease_ResourceReservationConfigDedicatedUL_r16_PR_NOTHING,	/* No components present */
	SetupRelease_ResourceReservationConfigDedicatedUL_r16_PR_release,
	SetupRelease_ResourceReservationConfigDedicatedUL_r16_PR_setup
} SetupRelease_ResourceReservationConfigDedicatedUL_r16_PR;
typedef enum SetupRelease_SoundingRS_UL_ConfigDedicatedAdd_r16_PR {
	SetupRelease_SoundingRS_UL_ConfigDedicatedAdd_r16_PR_NOTHING,	/* No components present */
	SetupRelease_SoundingRS_UL_ConfigDedicatedAdd_r16_PR_release,
	SetupRelease_SoundingRS_UL_ConfigDedicatedAdd_r16_PR_setup
} SetupRelease_SoundingRS_UL_ConfigDedicatedAdd_r16_PR;
typedef enum SetupRelease_UplinkPowerControlAddSRS_r16_PR {
	SetupRelease_UplinkPowerControlAddSRS_r16_PR_NOTHING,	/* No components present */
	SetupRelease_UplinkPowerControlAddSRS_r16_PR_release,
	SetupRelease_UplinkPowerControlAddSRS_r16_PR_setup
} SetupRelease_UplinkPowerControlAddSRS_r16_PR;
typedef enum SetupRelease_SoundingRS_VirtualCellID_r16_PR {
	SetupRelease_SoundingRS_VirtualCellID_r16_PR_NOTHING,	/* No components present */
	SetupRelease_SoundingRS_VirtualCellID_r16_PR_release,
	SetupRelease_SoundingRS_VirtualCellID_r16_PR_setup
} SetupRelease_SoundingRS_VirtualCellID_r16_PR;
typedef enum SetupRelease_WidebandPRG_r16_PR {
	SetupRelease_WidebandPRG_r16_PR_NOTHING,	/* No components present */
	SetupRelease_WidebandPRG_r16_PR_release,
	SetupRelease_WidebandPRG_r16_PR_setup
} SetupRelease_WidebandPRG_r16_PR;
typedef enum SetupRelease_PUR_RSRP_ChangeThreshold_r16_PR {
	SetupRelease_PUR_RSRP_ChangeThreshold_r16_PR_NOTHING,	/* No components present */
	SetupRelease_PUR_RSRP_ChangeThreshold_r16_PR_release,
	SetupRelease_PUR_RSRP_ChangeThreshold_r16_PR_setup
} SetupRelease_PUR_RSRP_ChangeThreshold_r16_PR;
typedef enum SetupRelease_CE_PUSCH_MultiTB_Config_r16_PR {
	SetupRelease_CE_PUSCH_MultiTB_Config_r16_PR_NOTHING,	/* No components present */
	SetupRelease_CE_PUSCH_MultiTB_Config_r16_PR_release,
	SetupRelease_CE_PUSCH_MultiTB_Config_r16_PR_setup
} SetupRelease_CE_PUSCH_MultiTB_Config_r16_PR;
typedef enum SetupRelease_CRS_ChEstMPDCCH_ConfigDedicated_r16_PR {
	SetupRelease_CRS_ChEstMPDCCH_ConfigDedicated_r16_PR_NOTHING,	/* No components present */
	SetupRelease_CRS_ChEstMPDCCH_ConfigDedicated_r16_PR_release,
	SetupRelease_CRS_ChEstMPDCCH_ConfigDedicated_r16_PR_setup
} SetupRelease_CRS_ChEstMPDCCH_ConfigDedicated_r16_PR;
typedef enum SetupRelease_MeasRSS_DedicatedConfig_r16_PR {
	SetupRelease_MeasRSS_DedicatedConfig_r16_PR_NOTHING,	/* No components present */
	SetupRelease_MeasRSS_DedicatedConfig_r16_PR_release,
	SetupRelease_MeasRSS_DedicatedConfig_r16_PR_setup
} SetupRelease_MeasRSS_DedicatedConfig_r16_PR;
typedef enum SetupRelease_RMTC_ConfigNR_r16_PR {
	SetupRelease_RMTC_ConfigNR_r16_PR_NOTHING,	/* No components present */
	SetupRelease_RMTC_ConfigNR_r16_PR_release,
	SetupRelease_RMTC_ConfigNR_r16_PR_setup
} SetupRelease_RMTC_ConfigNR_r16_PR;
typedef enum SetupRelease_PUR_Config_NB_r16_PR {
	SetupRelease_PUR_Config_NB_r16_PR_NOTHING,	/* No components present */
	SetupRelease_PUR_Config_NB_r16_PR_release,
	SetupRelease_PUR_Config_NB_r16_PR_setup
} SetupRelease_PUR_Config_NB_r16_PR;
typedef enum SetupRelease_ResourceReservationConfig_NB_r16_PR {
	SetupRelease_ResourceReservationConfig_NB_r16_PR_NOTHING,	/* No components present */
	SetupRelease_ResourceReservationConfig_NB_r16_PR_release,
	SetupRelease_ResourceReservationConfig_NB_r16_PR_setup
} SetupRelease_ResourceReservationConfig_NB_r16_PR;
typedef enum SetupRelease_PUR_NRSRP_ChangeThreshold_NB_r16_PR {
	SetupRelease_PUR_NRSRP_ChangeThreshold_NB_r16_PR_NOTHING,	/* No components present */
	SetupRelease_PUR_NRSRP_ChangeThreshold_NB_r16_PR_release,
	SetupRelease_PUR_NRSRP_ChangeThreshold_NB_r16_PR_setup
} SetupRelease_PUR_NRSRP_ChangeThreshold_NB_r16_PR;

/* Forward declarations */
struct PUR_Config_r16;
struct EthernetHeaderCompression_r16;
struct CE_PDSCH_MultiTB_Config_r16;
struct ResourceReservationConfigDedicatedDL_r16;
struct ResourceReservationConfigDedicatedUL_r16;
struct SoundingRS_UL_ConfigDedicatedAdd_r16;
struct UplinkPowerControlAddSRS_r16;
struct SoundingRS_VirtualCellID_r16;
struct WidebandPRG_r16;
struct PUR_RSRP_ChangeThreshold_r16;
struct CE_PUSCH_MultiTB_Config_r16;
struct CRS_ChEstMPDCCH_ConfigDedicated_r16;
struct MeasRSS_DedicatedConfig_r16;
struct RMTC_ConfigNR_r16;
struct PUR_Config_NB_r16;
struct ResourceReservationConfig_NB_r16;
struct PUR_NRSRP_ChangeThreshold_NB_r16;

/* SetupRelease */
typedef struct SetupRelease_PUR_Config_r16 {
	SetupRelease_PUR_Config_r16_PR present;
	union SetupRelease_PUR_Config_r16_u {
		NULL_t	 release;
		struct PUR_Config_r16	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_PUR_Config_r16_t;
typedef struct SetupRelease_EthernetHeaderCompression_r16 {
	SetupRelease_EthernetHeaderCompression_r16_PR present;
	union SetupRelease_EthernetHeaderCompression_r16_u {
		NULL_t	 release;
		struct EthernetHeaderCompression_r16	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_EthernetHeaderCompression_r16_t;
typedef struct SetupRelease_CE_PDSCH_MultiTB_Config_r16 {
	SetupRelease_CE_PDSCH_MultiTB_Config_r16_PR present;
	union SetupRelease_CE_PDSCH_MultiTB_Config_r16_u {
		NULL_t	 release;
		struct CE_PDSCH_MultiTB_Config_r16	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_CE_PDSCH_MultiTB_Config_r16_t;
typedef struct SetupRelease_ResourceReservationConfigDedicatedDL_r16 {
	SetupRelease_ResourceReservationConfigDedicatedDL_r16_PR present;
	union SetupRelease_ResourceReservationConfigDedicatedDL_r16_u {
		NULL_t	 release;
		struct ResourceReservationConfigDedicatedDL_r16	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_ResourceReservationConfigDedicatedDL_r16_t;
typedef struct SetupRelease_ResourceReservationConfigDedicatedUL_r16 {
	SetupRelease_ResourceReservationConfigDedicatedUL_r16_PR present;
	union SetupRelease_ResourceReservationConfigDedicatedUL_r16_u {
		NULL_t	 release;
		struct ResourceReservationConfigDedicatedUL_r16	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_ResourceReservationConfigDedicatedUL_r16_t;
typedef struct SetupRelease_SoundingRS_UL_ConfigDedicatedAdd_r16 {
	SetupRelease_SoundingRS_UL_ConfigDedicatedAdd_r16_PR present;
	union SetupRelease_SoundingRS_UL_ConfigDedicatedAdd_r16_u {
		NULL_t	 release;
		struct SoundingRS_UL_ConfigDedicatedAdd_r16	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_SoundingRS_UL_ConfigDedicatedAdd_r16_t;
typedef struct SetupRelease_UplinkPowerControlAddSRS_r16 {
	SetupRelease_UplinkPowerControlAddSRS_r16_PR present;
	union SetupRelease_UplinkPowerControlAddSRS_r16_u {
		NULL_t	 release;
		struct UplinkPowerControlAddSRS_r16	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_UplinkPowerControlAddSRS_r16_t;
typedef struct SetupRelease_SoundingRS_VirtualCellID_r16 {
	SetupRelease_SoundingRS_VirtualCellID_r16_PR present;
	union SetupRelease_SoundingRS_VirtualCellID_r16_u {
		NULL_t	 release;
		struct SoundingRS_VirtualCellID_r16	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_SoundingRS_VirtualCellID_r16_t;
typedef struct SetupRelease_WidebandPRG_r16 {
	SetupRelease_WidebandPRG_r16_PR present;
	union SetupRelease_WidebandPRG_r16_u {
		NULL_t	 release;
		struct WidebandPRG_r16	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_WidebandPRG_r16_t;
typedef struct SetupRelease_PUR_RSRP_ChangeThreshold_r16 {
	SetupRelease_PUR_RSRP_ChangeThreshold_r16_PR present;
	union SetupRelease_PUR_RSRP_ChangeThreshold_r16_u {
		NULL_t	 release;
		struct PUR_RSRP_ChangeThreshold_r16	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_PUR_RSRP_ChangeThreshold_r16_t;
typedef struct SetupRelease_CE_PUSCH_MultiTB_Config_r16 {
	SetupRelease_CE_PUSCH_MultiTB_Config_r16_PR present;
	union SetupRelease_CE_PUSCH_MultiTB_Config_r16_u {
		NULL_t	 release;
		struct CE_PUSCH_MultiTB_Config_r16	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_CE_PUSCH_MultiTB_Config_r16_t;
typedef struct SetupRelease_CRS_ChEstMPDCCH_ConfigDedicated_r16 {
	SetupRelease_CRS_ChEstMPDCCH_ConfigDedicated_r16_PR present;
	union SetupRelease_CRS_ChEstMPDCCH_ConfigDedicated_r16_u {
		NULL_t	 release;
		struct CRS_ChEstMPDCCH_ConfigDedicated_r16	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_CRS_ChEstMPDCCH_ConfigDedicated_r16_t;
typedef struct SetupRelease_MeasRSS_DedicatedConfig_r16 {
	SetupRelease_MeasRSS_DedicatedConfig_r16_PR present;
	union SetupRelease_MeasRSS_DedicatedConfig_r16_u {
		NULL_t	 release;
		struct MeasRSS_DedicatedConfig_r16	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_MeasRSS_DedicatedConfig_r16_t;
typedef struct SetupRelease_RMTC_ConfigNR_r16 {
	SetupRelease_RMTC_ConfigNR_r16_PR present;
	union SetupRelease_RMTC_ConfigNR_r16_u {
		NULL_t	 release;
		struct RMTC_ConfigNR_r16	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_RMTC_ConfigNR_r16_t;
typedef struct SetupRelease_PUR_Config_NB_r16 {
	SetupRelease_PUR_Config_NB_r16_PR present;
	union SetupRelease_PUR_Config_NB_r16_u {
		NULL_t	 release;
		struct PUR_Config_NB_r16	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_PUR_Config_NB_r16_t;
typedef struct SetupRelease_ResourceReservationConfig_NB_r16 {
	SetupRelease_ResourceReservationConfig_NB_r16_PR present;
	union SetupRelease_ResourceReservationConfig_NB_r16_u {
		NULL_t	 release;
		struct ResourceReservationConfig_NB_r16	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_ResourceReservationConfig_NB_r16_t;
typedef struct SetupRelease_PUR_NRSRP_ChangeThreshold_NB_r16 {
	SetupRelease_PUR_NRSRP_ChangeThreshold_NB_r16_PR present;
	union SetupRelease_PUR_NRSRP_ChangeThreshold_NB_r16_u {
		NULL_t	 release;
		struct PUR_NRSRP_ChangeThreshold_NB_r16	*setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_PUR_NRSRP_ChangeThreshold_NB_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_PUR_Config_r16;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_PUR_Config_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_SetupRelease_PUR_Config_r16_1[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_PUR_Config_r16_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_EthernetHeaderCompression_r16;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_EthernetHeaderCompression_r16_specs_4;
extern asn_TYPE_member_t asn_MBR_SetupRelease_EthernetHeaderCompression_r16_4[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_EthernetHeaderCompression_r16_constr_4;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_CE_PDSCH_MultiTB_Config_r16;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_CE_PDSCH_MultiTB_Config_r16_specs_7;
extern asn_TYPE_member_t asn_MBR_SetupRelease_CE_PDSCH_MultiTB_Config_r16_7[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_CE_PDSCH_MultiTB_Config_r16_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_ResourceReservationConfigDedicatedDL_r16;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_ResourceReservationConfigDedicatedDL_r16_specs_10;
extern asn_TYPE_member_t asn_MBR_SetupRelease_ResourceReservationConfigDedicatedDL_r16_10[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_ResourceReservationConfigDedicatedDL_r16_constr_10;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_ResourceReservationConfigDedicatedUL_r16;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_ResourceReservationConfigDedicatedUL_r16_specs_13;
extern asn_TYPE_member_t asn_MBR_SetupRelease_ResourceReservationConfigDedicatedUL_r16_13[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_ResourceReservationConfigDedicatedUL_r16_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_SoundingRS_UL_ConfigDedicatedAdd_r16;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_SoundingRS_UL_ConfigDedicatedAdd_r16_specs_16;
extern asn_TYPE_member_t asn_MBR_SetupRelease_SoundingRS_UL_ConfigDedicatedAdd_r16_16[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_SoundingRS_UL_ConfigDedicatedAdd_r16_constr_16;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_UplinkPowerControlAddSRS_r16;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_UplinkPowerControlAddSRS_r16_specs_19;
extern asn_TYPE_member_t asn_MBR_SetupRelease_UplinkPowerControlAddSRS_r16_19[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_UplinkPowerControlAddSRS_r16_constr_19;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_SoundingRS_VirtualCellID_r16;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_SoundingRS_VirtualCellID_r16_specs_22;
extern asn_TYPE_member_t asn_MBR_SetupRelease_SoundingRS_VirtualCellID_r16_22[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_SoundingRS_VirtualCellID_r16_constr_22;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_WidebandPRG_r16;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_WidebandPRG_r16_specs_25;
extern asn_TYPE_member_t asn_MBR_SetupRelease_WidebandPRG_r16_25[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_WidebandPRG_r16_constr_25;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_PUR_RSRP_ChangeThreshold_r16;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_PUR_RSRP_ChangeThreshold_r16_specs_28;
extern asn_TYPE_member_t asn_MBR_SetupRelease_PUR_RSRP_ChangeThreshold_r16_28[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_PUR_RSRP_ChangeThreshold_r16_constr_28;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_CE_PUSCH_MultiTB_Config_r16;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_CE_PUSCH_MultiTB_Config_r16_specs_31;
extern asn_TYPE_member_t asn_MBR_SetupRelease_CE_PUSCH_MultiTB_Config_r16_31[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_CE_PUSCH_MultiTB_Config_r16_constr_31;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_CRS_ChEstMPDCCH_ConfigDedicated_r16;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_CRS_ChEstMPDCCH_ConfigDedicated_r16_specs_34;
extern asn_TYPE_member_t asn_MBR_SetupRelease_CRS_ChEstMPDCCH_ConfigDedicated_r16_34[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_CRS_ChEstMPDCCH_ConfigDedicated_r16_constr_34;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_MeasRSS_DedicatedConfig_r16;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_MeasRSS_DedicatedConfig_r16_specs_37;
extern asn_TYPE_member_t asn_MBR_SetupRelease_MeasRSS_DedicatedConfig_r16_37[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_MeasRSS_DedicatedConfig_r16_constr_37;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_RMTC_ConfigNR_r16;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_RMTC_ConfigNR_r16_specs_40;
extern asn_TYPE_member_t asn_MBR_SetupRelease_RMTC_ConfigNR_r16_40[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_RMTC_ConfigNR_r16_constr_40;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_PUR_Config_NB_r16;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_PUR_Config_NB_r16_specs_43;
extern asn_TYPE_member_t asn_MBR_SetupRelease_PUR_Config_NB_r16_43[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_PUR_Config_NB_r16_constr_43;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_ResourceReservationConfig_NB_r16;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_ResourceReservationConfig_NB_r16_specs_46;
extern asn_TYPE_member_t asn_MBR_SetupRelease_ResourceReservationConfig_NB_r16_46[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_ResourceReservationConfig_NB_r16_constr_46;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_PUR_NRSRP_ChangeThreshold_NB_r16;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_PUR_NRSRP_ChangeThreshold_NB_r16_specs_49;
extern asn_TYPE_member_t asn_MBR_SetupRelease_PUR_NRSRP_ChangeThreshold_NB_r16_49[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_PUR_NRSRP_ChangeThreshold_NB_r16_constr_49;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PUR-Config-r16.h"
#include "EthernetHeaderCompression-r16.h"
#include "CE-PDSCH-MultiTB-Config-r16.h"
#include "ResourceReservationConfigDedicatedDL-r16.h"
#include "ResourceReservationConfigDedicatedUL-r16.h"
#include "SoundingRS-UL-ConfigDedicatedAdd-r16.h"
#include "UplinkPowerControlAddSRS-r16.h"
#include "SoundingRS-VirtualCellID-r16.h"
#include "WidebandPRG-r16.h"
#include "PUR-RSRP-ChangeThreshold-r16.h"
#include "CE-PUSCH-MultiTB-Config-r16.h"
#include "CRS-ChEstMPDCCH-ConfigDedicated-r16.h"
#include "MeasRSS-DedicatedConfig-r16.h"
#include "RMTC-ConfigNR-r16.h"
#include "PUR-Config-NB-r16.h"
#include "ResourceReservationConfig-NB-r16.h"
#include "PUR-NRSRP-ChangeThreshold-NB-r16.h"

#endif	/* _SetupRelease_H_ */
#include <asn_internal.h>
