/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_SI_Periodicity_r12_H_
#define	_SI_Periodicity_r12_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SI_Periodicity_r12 {
	SI_Periodicity_r12_rf8	= 0,
	SI_Periodicity_r12_rf16	= 1,
	SI_Periodicity_r12_rf32	= 2,
	SI_Periodicity_r12_rf64	= 3,
	SI_Periodicity_r12_rf128	= 4,
	SI_Periodicity_r12_rf256	= 5,
	SI_Periodicity_r12_rf512	= 6
} e_SI_Periodicity_r12;

/* SI-Periodicity-r12 */
typedef long	 SI_Periodicity_r12_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SI_Periodicity_r12_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SI_Periodicity_r12;
extern const asn_INTEGER_specifics_t asn_SPC_SI_Periodicity_r12_specs_1;
asn_struct_free_f SI_Periodicity_r12_free;
asn_struct_print_f SI_Periodicity_r12_print;
asn_constr_check_f SI_Periodicity_r12_constraint;
jer_type_encoder_f SI_Periodicity_r12_encode_jer;
per_type_decoder_f SI_Periodicity_r12_decode_uper;
per_type_encoder_f SI_Periodicity_r12_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SI_Periodicity_r12_H_ */
#include <asn_internal.h>
