/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_SL_Parameters_v1630_H_
#define	_SL_Parameters_v1630_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct V2X_SupportedBandCombinationEUTRA_NR_v1630;

/* SL-Parameters-v1630 */
typedef struct SL_Parameters_v1630 {
	struct V2X_SupportedBandCombinationEUTRA_NR_v1630	*v2x_SupportedBandCombinationListEUTRA_NR_r16;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SL_Parameters_v1630_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SL_Parameters_v1630;
extern asn_SEQUENCE_specifics_t asn_SPC_SL_Parameters_v1630_specs_1;
extern asn_TYPE_member_t asn_MBR_SL_Parameters_v1630_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "V2X-SupportedBandCombinationEUTRA-NR-v1630.h"

#endif	/* _SL_Parameters_v1630_H_ */
#include <asn_internal.h>
