/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_SystemInformationBlockType1_NB_v1610_H_
#define	_SystemInformationBlockType1_NB_v1610_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PLMN-IdentityList-5GC-NB-r16.h"
#include "TrackingAreaCode-5GC-r15.h"
#include "CellIdentity.h"
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SystemInformationBlockType1_NB_v1610__cellAccessRelatedInfo_5GC_r16__cellBarred_5GC_r16 {
	SystemInformationBlockType1_NB_v1610__cellAccessRelatedInfo_5GC_r16__cellBarred_5GC_r16_barred	= 0,
	SystemInformationBlockType1_NB_v1610__cellAccessRelatedInfo_5GC_r16__cellBarred_5GC_r16_notBarred	= 1
} e_SystemInformationBlockType1_NB_v1610__cellAccessRelatedInfo_5GC_r16__cellBarred_5GC_r16;

/* SystemInformationBlockType1-NB-v1610 */
typedef struct SystemInformationBlockType1_NB_v1610 {
	struct SystemInformationBlockType1_NB_v1610__cellAccessRelatedInfo_5GC_r16 {
		PLMN_IdentityList_5GC_NB_r16_t	 plmn_IdentityList_r16;
		TrackingAreaCode_5GC_r15_t	 trackingAreaCode_5GC_r16;
		CellIdentity_t	*cellIdentity_r16;	/* OPTIONAL */
		long	 cellBarred_5GC_r16;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *cellAccessRelatedInfo_5GC_r16;
	struct SystemInformationBlockType1_NB_v1610__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SystemInformationBlockType1_NB_v1610_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_cellBarred_5GC_r16_6;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SystemInformationBlockType1_NB_v1610;
extern asn_SEQUENCE_specifics_t asn_SPC_SystemInformationBlockType1_NB_v1610_specs_1;
extern asn_TYPE_member_t asn_MBR_SystemInformationBlockType1_NB_v1610_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _SystemInformationBlockType1_NB_v1610_H_ */
#include <asn_internal.h>
