/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_ThresholdGERAN_H_
#define	_ThresholdGERAN_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ThresholdGERAN */
typedef long	 ThresholdGERAN_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ThresholdGERAN_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ThresholdGERAN;
asn_struct_free_f ThresholdGERAN_free;
asn_struct_print_f ThresholdGERAN_print;
asn_constr_check_f ThresholdGERAN_constraint;
jer_type_encoder_f ThresholdGERAN_encode_jer;
per_type_decoder_f ThresholdGERAN_decode_uper;
per_type_encoder_f ThresholdGERAN_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ThresholdGERAN_H_ */
#include <asn_internal.h>
