/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_UAC_Barring_NB_r16_H_
#define	_UAC_Barring_NB_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UAC-AC1-SelectAssistInfo-r15.h"
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct UAC_BarringPerCatList_NB_r16;

/* UAC-Barring-NB-r16 */
typedef struct UAC_Barring_NB_r16 {
	struct UAC_BarringPerCatList_NB_r16	*uac_BarringPerCatList_r16;	/* OPTIONAL */
	UAC_AC1_SelectAssistInfo_r15_t	*uac_AC1_SelectAssistInfo_r16;	/* OPTIONAL */
	BIT_STRING_t	 uac_BarringForAccessIdentity_r16;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UAC_Barring_NB_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UAC_Barring_NB_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_UAC_Barring_NB_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_UAC_Barring_NB_r16_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "UAC-BarringPerCatList-NB-r16.h"

#endif	/* _UAC_Barring_NB_r16_H_ */
#include <asn_internal.h>
