/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_UE_Capability_NB_v1610_IEs_H_
#define	_UE_Capability_NB_v1610_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include "MAC-Parameters-NB-v1610.h"
#include "MeasParameters-NB-r16.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UE_Capability_NB_v1610_IEs__earlySecurityReactivation_r16 {
	UE_Capability_NB_v1610_IEs__earlySecurityReactivation_r16_supported	= 0
} e_UE_Capability_NB_v1610_IEs__earlySecurityReactivation_r16;
typedef enum UE_Capability_NB_v1610_IEs__earlyData_UP_5GC_r16 {
	UE_Capability_NB_v1610_IEs__earlyData_UP_5GC_r16_supported	= 0
} e_UE_Capability_NB_v1610_IEs__earlyData_UP_5GC_r16;

/* Forward declarations */
struct PUR_Parameters_NB_r16;
struct PhyLayerParameters_NB_v1610;
struct SON_Parameters_NB_r16;
struct TDD_UE_Capability_NB_v1610;

/* UE-Capability-NB-v1610-IEs */
typedef struct UE_Capability_NB_v1610_IEs {
	long	*earlySecurityReactivation_r16;	/* OPTIONAL */
	long	*earlyData_UP_5GC_r16;	/* OPTIONAL */
	struct PUR_Parameters_NB_r16	*pur_Parameters_r16;	/* OPTIONAL */
	MAC_Parameters_NB_v1610_t	 mac_Parameters_v1610;
	struct PhyLayerParameters_NB_v1610	*phyLayerParameters_v1610;	/* OPTIONAL */
	struct SON_Parameters_NB_r16	*son_Parameters_r16;	/* OPTIONAL */
	MeasParameters_NB_r16_t	 measParameters_r16;
	struct TDD_UE_Capability_NB_v1610	*tdd_UE_Capability_v1610;	/* OPTIONAL */
	struct UE_Capability_NB_v1610_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_Capability_NB_v1610_IEs_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_earlySecurityReactivation_r16_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_earlyData_UP_5GC_r16_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_UE_Capability_NB_v1610_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_UE_Capability_NB_v1610_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_UE_Capability_NB_v1610_IEs_1[9];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PUR-Parameters-NB-r16.h"
#include "PhyLayerParameters-NB-v1610.h"
#include "SON-Parameters-NB-r16.h"
#include "TDD-UE-Capability-NB-v1610.h"

#endif	/* _UE_Capability_NB_v1610_IEs_H_ */
#include <asn_internal.h>
