/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_UE_EUTRA_CapabilityAddXDD_Mode_v1610_H_
#define	_UE_EUTRA_CapabilityAddXDD_Mode_v1610_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PhyLayerParameters_v1610;
struct PUR_Parameters_r16;
struct MeasParameters_v1610;
struct EUTRA_5GC_Parameters_v1610;
struct IRAT_ParametersNR_v1610;
struct NeighCellSI_AcquisitionParameters_v1610;
struct MobilityParameters_v1610;

/* UE-EUTRA-CapabilityAddXDD-Mode-v1610 */
typedef struct UE_EUTRA_CapabilityAddXDD_Mode_v1610 {
	struct PhyLayerParameters_v1610	*phyLayerParameters_v1610;	/* OPTIONAL */
	struct PUR_Parameters_r16	*pur_Parameters_r16;	/* OPTIONAL */
	struct MeasParameters_v1610	*measParameters_v1610;	/* OPTIONAL */
	struct EUTRA_5GC_Parameters_v1610	*eutra_5GC_Parameters_v1610;	/* OPTIONAL */
	struct IRAT_ParametersNR_v1610	*irat_ParametersNR_v1610;	/* OPTIONAL */
	struct NeighCellSI_AcquisitionParameters_v1610	*neighCellSI_AcquisitionParameters_v1610;	/* OPTIONAL */
	struct MobilityParameters_v1610	*mobilityParameters_v1610;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_EUTRA_CapabilityAddXDD_Mode_v1610_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_EUTRA_CapabilityAddXDD_Mode_v1610;
extern asn_SEQUENCE_specifics_t asn_SPC_UE_EUTRA_CapabilityAddXDD_Mode_v1610_specs_1;
extern asn_TYPE_member_t asn_MBR_UE_EUTRA_CapabilityAddXDD_Mode_v1610_1[7];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PhyLayerParameters-v1610.h"
#include "PUR-Parameters-r16.h"
#include "MeasParameters-v1610.h"
#include "EUTRA-5GC-Parameters-v1610.h"
#include "IRAT-ParametersNR-v1610.h"
#include "NeighCellSI-AcquisitionParameters-v1610.h"
#include "MobilityParameters-v1610.h"

#endif	/* _UE_EUTRA_CapabilityAddXDD_Mode_v1610_H_ */
#include <asn_internal.h>
