/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_UE_EUTRA_Capability_v1570_IEs_H_
#define	_UE_EUTRA_Capability_v1570_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RF_Parameters_v1570;
struct IRAT_ParametersNR_v1570;
struct UE_EUTRA_Capability_v15a0_IEs;

/* UE-EUTRA-Capability-v1570-IEs */
typedef struct UE_EUTRA_Capability_v1570_IEs {
	struct RF_Parameters_v1570	*rf_Parameters_v1570;	/* OPTIONAL */
	struct IRAT_ParametersNR_v1570	*irat_ParametersNR_v1570;	/* OPTIONAL */
	struct UE_EUTRA_Capability_v15a0_IEs	*nonCriticalExtension;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_EUTRA_Capability_v1570_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_EUTRA_Capability_v1570_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_UE_EUTRA_Capability_v1570_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_UE_EUTRA_Capability_v1570_IEs_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RF-Parameters-v1570.h"
#include "IRAT-ParametersNR-v1570.h"
#include "UE-EUTRA-Capability-v15a0-IEs.h"

#endif	/* _UE_EUTRA_Capability_v1570_IEs_H_ */
#include <asn_internal.h>
