/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_UE_RadioPagingInfo_NB_r13_H_
#define	_UE_RadioPagingInfo_NB_r13_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UE_RadioPagingInfo_NB_r13__ue_Category_NB_r13 {
	UE_RadioPagingInfo_NB_r13__ue_Category_NB_r13_nb1	= 0
} e_UE_RadioPagingInfo_NB_r13__ue_Category_NB_r13;
typedef enum UE_RadioPagingInfo_NB_r13__ext1__multiCarrierPaging_r14 {
	UE_RadioPagingInfo_NB_r13__ext1__multiCarrierPaging_r14_true	= 0
} e_UE_RadioPagingInfo_NB_r13__ext1__multiCarrierPaging_r14;
typedef enum UE_RadioPagingInfo_NB_r13__ext2__mixedOperationMode_r15 {
	UE_RadioPagingInfo_NB_r13__ext2__mixedOperationMode_r15_supported	= 0
} e_UE_RadioPagingInfo_NB_r13__ext2__mixedOperationMode_r15;
typedef enum UE_RadioPagingInfo_NB_r13__ext2__wakeUpSignal_r15 {
	UE_RadioPagingInfo_NB_r13__ext2__wakeUpSignal_r15_true	= 0
} e_UE_RadioPagingInfo_NB_r13__ext2__wakeUpSignal_r15;
typedef enum UE_RadioPagingInfo_NB_r13__ext2__wakeUpSignalMinGap_eDRX_r15 {
	UE_RadioPagingInfo_NB_r13__ext2__wakeUpSignalMinGap_eDRX_r15_ms40	= 0,
	UE_RadioPagingInfo_NB_r13__ext2__wakeUpSignalMinGap_eDRX_r15_ms240	= 1,
	UE_RadioPagingInfo_NB_r13__ext2__wakeUpSignalMinGap_eDRX_r15_ms1000	= 2,
	UE_RadioPagingInfo_NB_r13__ext2__wakeUpSignalMinGap_eDRX_r15_ms2000	= 3
} e_UE_RadioPagingInfo_NB_r13__ext2__wakeUpSignalMinGap_eDRX_r15;
typedef enum UE_RadioPagingInfo_NB_r13__ext2__multiCarrierPagingTDD_r15 {
	UE_RadioPagingInfo_NB_r13__ext2__multiCarrierPagingTDD_r15_true	= 0
} e_UE_RadioPagingInfo_NB_r13__ext2__multiCarrierPagingTDD_r15;
typedef enum UE_RadioPagingInfo_NB_r13__ext3__ue_Category_NB_r16 {
	UE_RadioPagingInfo_NB_r13__ext3__ue_Category_NB_r16_nb2	= 0
} e_UE_RadioPagingInfo_NB_r13__ext3__ue_Category_NB_r16;
typedef enum UE_RadioPagingInfo_NB_r13__ext3__groupWakeUpSignal_r16 {
	UE_RadioPagingInfo_NB_r13__ext3__groupWakeUpSignal_r16_true	= 0
} e_UE_RadioPagingInfo_NB_r13__ext3__groupWakeUpSignal_r16;
typedef enum UE_RadioPagingInfo_NB_r13__ext3__groupWakeUpSignalAlternation_r16 {
	UE_RadioPagingInfo_NB_r13__ext3__groupWakeUpSignalAlternation_r16_true	= 0
} e_UE_RadioPagingInfo_NB_r13__ext3__groupWakeUpSignalAlternation_r16;

/* UE-RadioPagingInfo-NB-r13 */
typedef struct UE_RadioPagingInfo_NB_r13 {
	long	*ue_Category_NB_r13;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct UE_RadioPagingInfo_NB_r13__ext1 {
		long	*multiCarrierPaging_r14;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct UE_RadioPagingInfo_NB_r13__ext2 {
		long	*mixedOperationMode_r15;	/* OPTIONAL */
		long	*wakeUpSignal_r15;	/* OPTIONAL */
		long	*wakeUpSignalMinGap_eDRX_r15;	/* OPTIONAL */
		long	*multiCarrierPagingTDD_r15;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	struct UE_RadioPagingInfo_NB_r13__ext3 {
		long	*ue_Category_NB_r16;	/* OPTIONAL */
		long	*groupWakeUpSignal_r16;	/* OPTIONAL */
		long	*groupWakeUpSignalAlternation_r16;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext3;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_RadioPagingInfo_NB_r13_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ue_Category_NB_r13_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_multiCarrierPaging_r14_6;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_mixedOperationMode_r15_9;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_wakeUpSignal_r15_11;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_wakeUpSignalMinGap_eDRX_r15_13;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_multiCarrierPagingTDD_r15_18;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ue_Category_NB_r16_21;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_groupWakeUpSignal_r16_23;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_groupWakeUpSignalAlternation_r16_25;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_UE_RadioPagingInfo_NB_r13;
extern asn_SEQUENCE_specifics_t asn_SPC_UE_RadioPagingInfo_NB_r13_specs_1;
extern asn_TYPE_member_t asn_MBR_UE_RadioPagingInfo_NB_r13_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _UE_RadioPagingInfo_NB_r13_H_ */
#include <asn_internal.h>
