/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_UEInformationResponse_v1610_IEs_H_
#define	_UEInformationResponse_v1610_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RACH_Report_v1610;
struct MeasResultListExtIdle_r16;
struct MeasResultListIdleNR_r16;

/* UEInformationResponse-v1610-IEs */
typedef struct UEInformationResponse_v1610_IEs {
	struct RACH_Report_v1610	*rach_Report_v1610;	/* OPTIONAL */
	struct MeasResultListExtIdle_r16	*measResultListExtIdle_r16;	/* OPTIONAL */
	struct MeasResultListIdleNR_r16	*measResultListIdleNR_r16;	/* OPTIONAL */
	struct UEInformationResponse_v1610_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UEInformationResponse_v1610_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UEInformationResponse_v1610_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_UEInformationResponse_v1610_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_UEInformationResponse_v1610_IEs_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RACH-Report-v1610.h"
#include "MeasResultListExtIdle-r16.h"
#include "MeasResultListIdleNR-r16.h"

#endif	/* _UEInformationResponse_v1610_IEs_H_ */
#include <asn_internal.h>
