/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_UEInformationRequest_NB_r16_IEs_H_
#define	_UEInformationRequest_NB_r16_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UEInformationRequest-NB-r16-IEs */
typedef struct UEInformationRequest_NB_r16_IEs {
	BOOLEAN_t	 rach_ReportReq_r16;
	BOOLEAN_t	 rlf_ReportReq_r16;
	BOOLEAN_t	 anr_ReportReq_r16;
	OCTET_STRING_t	*lateNonCriticalExtension;	/* OPTIONAL */
	struct UEInformationRequest_NB_r16_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UEInformationRequest_NB_r16_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UEInformationRequest_NB_r16_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_UEInformationRequest_NB_r16_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_UEInformationRequest_NB_r16_IEs_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _UEInformationRequest_NB_r16_IEs_H_ */
#include <asn_internal.h>
