/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_UL_ConfigCommon_NB_r14_H_
#define	_UL_ConfigCommon_NB_r14_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CarrierFreq-NB-r13.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NPRACH_ParametersList_NB_r14;
struct RSRP_ThresholdsNPRACH_InfoList_NB_r13;

/* UL-ConfigCommon-NB-r14 */
typedef struct UL_ConfigCommon_NB_r14 {
	CarrierFreq_NB_r13_t	 ul_CarrierFreq_r14;
	struct NPRACH_ParametersList_NB_r14	*nprach_ParametersList_r14;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct UL_ConfigCommon_NB_r14__ext1 {
		struct NPRACH_ParametersList_NB_r14	*nprach_ParametersListEDT_r15;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct UL_ConfigCommon_NB_r14__ext2 {
		struct RSRP_ThresholdsNPRACH_InfoList_NB_r13	*rsrp_ThresholdsPrachInfoList_r16;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UL_ConfigCommon_NB_r14_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UL_ConfigCommon_NB_r14;
extern asn_SEQUENCE_specifics_t asn_SPC_UL_ConfigCommon_NB_r14_specs_1;
extern asn_TYPE_member_t asn_MBR_UL_ConfigCommon_NB_r14_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NPRACH-ParametersList-NB-r14.h"
#include "RSRP-ThresholdsNPRACH-InfoList-NB-r13.h"

#endif	/* _UL_ConfigCommon_NB_r14_H_ */
#include <asn_internal.h>
