/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_UL_DCCH_MessageType_NB_H_
#define	_UL_DCCH_MessageType_NB_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UL_DCCH_MessageType_NB_PR {
	UL_DCCH_MessageType_NB_PR_NOTHING,	/* No components present */
	UL_DCCH_MessageType_NB_PR_c1,
	UL_DCCH_MessageType_NB_PR_messageClassExtension
} UL_DCCH_MessageType_NB_PR;
typedef enum UL_DCCH_MessageType_NB__c1_PR {
	UL_DCCH_MessageType_NB__c1_PR_NOTHING,	/* No components present */
	UL_DCCH_MessageType_NB__c1_PR_rrcConnectionReconfigurationComplete_r13,
	UL_DCCH_MessageType_NB__c1_PR_rrcConnectionReestablishmentComplete_r13,
	UL_DCCH_MessageType_NB__c1_PR_rrcConnectionSetupComplete_r13,
	UL_DCCH_MessageType_NB__c1_PR_securityModeComplete_r13,
	UL_DCCH_MessageType_NB__c1_PR_securityModeFailure_r13,
	UL_DCCH_MessageType_NB__c1_PR_ueCapabilityInformation_r13,
	UL_DCCH_MessageType_NB__c1_PR_ulInformationTransfer_r13,
	UL_DCCH_MessageType_NB__c1_PR_rrcConnectionResumeComplete_r13,
	UL_DCCH_MessageType_NB__c1_PR_ueInformationResponse_r16,
	UL_DCCH_MessageType_NB__c1_PR_purConfigurationRequest_r16,
	UL_DCCH_MessageType_NB__c1_PR_spare6,
	UL_DCCH_MessageType_NB__c1_PR_spare5,
	UL_DCCH_MessageType_NB__c1_PR_spare4,
	UL_DCCH_MessageType_NB__c1_PR_spare3,
	UL_DCCH_MessageType_NB__c1_PR_spare2,
	UL_DCCH_MessageType_NB__c1_PR_spare1
} UL_DCCH_MessageType_NB__c1_PR;

/* Forward declarations */
struct RRCConnectionReconfigurationComplete_NB;
struct RRCConnectionReestablishmentComplete_NB;
struct RRCConnectionSetupComplete_NB;
struct SecurityModeComplete;
struct SecurityModeFailure;
struct UECapabilityInformation_NB;
struct ULInformationTransfer_NB;
struct RRCConnectionResumeComplete_NB;
struct UEInformationResponse_NB_r16;
struct PURConfigurationRequest_NB_r16;

/* UL-DCCH-MessageType-NB */
typedef struct UL_DCCH_MessageType_NB {
	UL_DCCH_MessageType_NB_PR present;
	union UL_DCCH_MessageType_NB_u {
		struct UL_DCCH_MessageType_NB__c1 {
			UL_DCCH_MessageType_NB__c1_PR present;
			union UL_DCCH_MessageType_NB__c1_u {
				struct RRCConnectionReconfigurationComplete_NB	*rrcConnectionReconfigurationComplete_r13;
				struct RRCConnectionReestablishmentComplete_NB	*rrcConnectionReestablishmentComplete_r13;
				struct RRCConnectionSetupComplete_NB	*rrcConnectionSetupComplete_r13;
				struct SecurityModeComplete	*securityModeComplete_r13;
				struct SecurityModeFailure	*securityModeFailure_r13;
				struct UECapabilityInformation_NB	*ueCapabilityInformation_r13;
				struct ULInformationTransfer_NB	*ulInformationTransfer_r13;
				struct RRCConnectionResumeComplete_NB	*rrcConnectionResumeComplete_r13;
				struct UEInformationResponse_NB_r16	*ueInformationResponse_r16;
				struct PURConfigurationRequest_NB_r16	*purConfigurationRequest_r16;
				NULL_t	 spare6;
				NULL_t	 spare5;
				NULL_t	 spare4;
				NULL_t	 spare3;
				NULL_t	 spare2;
				NULL_t	 spare1;
			} choice;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *c1;
		struct UL_DCCH_MessageType_NB__messageClassExtension {
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *messageClassExtension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UL_DCCH_MessageType_NB_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UL_DCCH_MessageType_NB;
extern asn_CHOICE_specifics_t asn_SPC_UL_DCCH_MessageType_NB_specs_1;
extern asn_TYPE_member_t asn_MBR_UL_DCCH_MessageType_NB_1[2];
extern asn_per_constraints_t asn_PER_type_UL_DCCH_MessageType_NB_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RRCConnectionReconfigurationComplete-NB.h"
#include "RRCConnectionReestablishmentComplete-NB.h"
#include "RRCConnectionSetupComplete-NB.h"
#include "SecurityModeComplete.h"
#include "SecurityModeFailure.h"
#include "UECapabilityInformation-NB.h"
#include "ULInformationTransfer-NB.h"
#include "RRCConnectionResumeComplete-NB.h"
#include "UEInformationResponse-NB-r16.h"
#include "PURConfigurationRequest-NB-r16.h"

#endif	/* _UL_DCCH_MessageType_NB_H_ */
#include <asn_internal.h>
