/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_ValidityArea_r16_H_
#define	_ValidityArea_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ARFCN-ValueEUTRA-r9.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ValidityCellList_r16;

/* ValidityArea-r16 */
typedef struct ValidityArea_r16 {
	ARFCN_ValueEUTRA_r9_t	 carrierFreq_r16;
	struct ValidityCellList_r16	*validityCellList_r16;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ValidityArea_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ValidityArea_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_ValidityArea_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_ValidityArea_r16_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ValidityCellList-r16.h"

#endif	/* _ValidityArea_r16_H_ */
#include <asn_internal.h>
