/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-UE-Variables"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#include "VarANR-MeasConfig-NB-r16.h"

static asn_TYPE_member_t asn_MBR_VarANR_MeasConfig_NB_r16_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct VarANR_MeasConfig_NB_r16, anr_QualityThreshold_r16),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NRSRP_Range_NB_r14,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"anr-QualityThreshold-r16"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct VarANR_MeasConfig_NB_r16, anr_CarrierList_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ANR_CarrierList_NB_r16,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"anr-CarrierList-r16"
		},
};
static const ber_tlv_tag_t asn_DEF_VarANR_MeasConfig_NB_r16_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_VarANR_MeasConfig_NB_r16_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* anr-QualityThreshold-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* anr-CarrierList-r16 */
};
static asn_SEQUENCE_specifics_t asn_SPC_VarANR_MeasConfig_NB_r16_specs_1 = {
	sizeof(struct VarANR_MeasConfig_NB_r16),
	offsetof(struct VarANR_MeasConfig_NB_r16, _asn_ctx),
	asn_MAP_VarANR_MeasConfig_NB_r16_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_VarANR_MeasConfig_NB_r16 = {
	"VarANR-MeasConfig-NB-r16",
	"VarANR-MeasConfig-NB-r16",
	&asn_OP_SEQUENCE,
	asn_DEF_VarANR_MeasConfig_NB_r16_tags_1,
	sizeof(asn_DEF_VarANR_MeasConfig_NB_r16_tags_1)
		/sizeof(asn_DEF_VarANR_MeasConfig_NB_r16_tags_1[0]), /* 1 */
	asn_DEF_VarANR_MeasConfig_NB_r16_tags_1,	/* Same as above */
	sizeof(asn_DEF_VarANR_MeasConfig_NB_r16_tags_1)
		/sizeof(asn_DEF_VarANR_MeasConfig_NB_r16_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_VarANR_MeasConfig_NB_r16_1,
	2,	/* Elements count */
	&asn_SPC_VarANR_MeasConfig_NB_r16_specs_1	/* Additional specs */
};

