/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-UE-Variables"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_VarANR_MeasConfig_NB_r16_H_
#define	_VarANR_MeasConfig_NB_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRSRP-Range-NB-r14.h"
#include "ANR-CarrierList-NB-r16.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VarANR-MeasConfig-NB-r16 */
typedef struct VarANR_MeasConfig_NB_r16 {
	NRSRP_Range_NB_r14_t	 anr_QualityThreshold_r16;
	ANR_CarrierList_NB_r16_t	 anr_CarrierList_r16;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VarANR_MeasConfig_NB_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VarANR_MeasConfig_NB_r16;

#ifdef __cplusplus
}
#endif

#endif	/* _VarANR_MeasConfig_NB_r16_H_ */
#include <asn_internal.h>
