/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-UE-Variables"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_VarMeasIdleReport_r16_H_
#define	_VarMeasIdleReport_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MeasResultListExtIdle_r16;
struct MeasResultListIdleNR_r16;

/* VarMeasIdleReport-r16 */
typedef struct VarMeasIdleReport_r16 {
	struct MeasResultListExtIdle_r16	*measReportIdle_r16;	/* OPTIONAL */
	struct MeasResultListIdleNR_r16	*measReportIdleNR_r16;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VarMeasIdleReport_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VarMeasIdleReport_r16;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MeasResultListExtIdle-r16.h"
#include "MeasResultListIdleNR-r16.h"

#endif	/* _VarMeasIdleReport_r16_H_ */
#include <asn_internal.h>
