/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-UE-Variables"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_VarMeasIdleConfig_r16_H_
#define	_VarMeasIdleConfig_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NR_CarrierList_r16;
struct ValidityAreaList_r16;

/* VarMeasIdleConfig-r16 */
typedef struct VarMeasIdleConfig_r16 {
	struct NR_CarrierList_r16	*measIdleCarrierListNR_r16;	/* OPTIONAL */
	struct ValidityAreaList_r16	*validityAreaList_r16;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VarMeasIdleConfig_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VarMeasIdleConfig_r16;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NR-CarrierList-r16.h"
#include "ValidityAreaList-r16.h"

#endif	/* _VarMeasIdleConfig_r16_H_ */
#include <asn_internal.h>
