/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-UE-Variables"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_VarShortINACTIVE_MAC_Input_r15_H_
#define	_VarShortINACTIVE_MAC_Input_r15_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CellIdentity.h"
#include "PhysCellId.h"
#include "C-RNTI.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VarShortINACTIVE-MAC-Input-r15 */
typedef struct VarShortINACTIVE_MAC_Input_r15 {
	CellIdentity_t	 cellIdentity_r15;
	PhysCellId_t	 physCellId_r15;
	C_RNTI_t	 c_RNTI_r15;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VarShortINACTIVE_MAC_Input_r15_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VarShortINACTIVE_MAC_Input_r15;

#ifdef __cplusplus
}
#endif

#endif	/* _VarShortINACTIVE_MAC_Input_r15_H_ */
#include <asn_internal.h>
