/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-UE-Variables"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_VarShortResumeMAC_Input_NB_r13_H_
#define	_VarShortResumeMAC_Input_NB_r13_H_


#include <asn_application.h>

/* Including external dependencies */
#include "VarShortResumeMAC-Input-r13.h"

#ifdef __cplusplus
extern "C" {
#endif

/* VarShortResumeMAC-Input-NB-r13 */
typedef VarShortResumeMAC_Input_r13_t	 VarShortResumeMAC_Input_NB_r13_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VarShortResumeMAC_Input_NB_r13;
asn_struct_free_f VarShortResumeMAC_Input_NB_r13_free;
asn_struct_print_f VarShortResumeMAC_Input_NB_r13_print;
asn_constr_check_f VarShortResumeMAC_Input_NB_r13_constraint;
jer_type_encoder_f VarShortResumeMAC_Input_NB_r13_encode_jer;
per_type_decoder_f VarShortResumeMAC_Input_NB_r13_decode_uper;
per_type_encoder_f VarShortResumeMAC_Input_NB_r13_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _VarShortResumeMAC_Input_NB_r13_H_ */
#include <asn_internal.h>
