/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-UE-Variables"
 * 	found in "lte.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#include "VarShortResumeMAC-Input-NB-r13.h"

/*
 * This type is implemented using VarShortResumeMAC_Input_r13,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_VarShortResumeMAC_Input_NB_r13_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_VarShortResumeMAC_Input_NB_r13 = {
	"VarShortResumeMAC-Input-NB-r13",
	"VarShortResumeMAC-Input-NB-r13",
	&asn_OP_SEQUENCE,
	asn_DEF_VarShortResumeMAC_Input_NB_r13_tags_1,
	sizeof(asn_DEF_VarShortResumeMAC_Input_NB_r13_tags_1)
		/sizeof(asn_DEF_VarShortResumeMAC_Input_NB_r13_tags_1[0]), /* 1 */
	asn_DEF_VarShortResumeMAC_Input_NB_r13_tags_1,	/* Same as above */
	sizeof(asn_DEF_VarShortResumeMAC_Input_NB_r13_tags_1)
		/sizeof(asn_DEF_VarShortResumeMAC_Input_NB_r13_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_VarShortResumeMAC_Input_r13_1,
	4,	/* Elements count */
	&asn_SPC_VarShortResumeMAC_Input_r13_specs_1	/* Additional specs */
};

