Require Import ASN1Parser.ExtrOCaml.ExtractHelper.

Require Import NR.NR_RRC_Definitions.
Require Import NR.FreqBandIndicatorEUTRA.

Opaque FreqBandIndicatorEUTRA__cond FreqBandIndicatorEUTRA__Format.

Inductive BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__Type : Set :=
 | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms0
 | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms0dot25
 | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms0dot5
 | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms0dot625
 | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms0dot75
 | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms1
 | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms1dot25
 | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms1dot5
 | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms1dot75
 | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms2
 | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms2dot5
 | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms3
 | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms4
 | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms5
 | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms6
 | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms8
 | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms10
 | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms20
.
Definition BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__cond := (fun (_ : BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__Type) => True).
Lemma BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__nat__helper : to_bit_sz 17 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__nat__Format : T_Format nat (fun z => (z <= 17)) :=
  nat_enum_format 17 BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__nat__helper.

Definition BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__F1 t :=
  match t with
  | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms0 => 0
  | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms0dot25 => 1
  | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms0dot5 => 2
  | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms0dot625 => 3
  | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms0dot75 => 4
  | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms1 => 5
  | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms1dot25 => 6
  | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms1dot5 => 7
  | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms1dot75 => 8
  | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms2 => 9
  | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms2dot5 => 10
  | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms3 => 11
  | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms4 => 12
  | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms5 => 13
  | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms6 => 14
  | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms8 => 15
  | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms10 => 16
  | BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms20 => 17
  end.
Definition BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__F2 n :=
  match n with
  | 0 => BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms0
  | 1 => BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms0dot25
  | 2 => BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms0dot5
  | 3 => BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms0dot625
  | 4 => BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms0dot75
  | 5 => BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms1
  | 6 => BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms1dot25
  | 7 => BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms1dot5
  | 8 => BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms1dot75
  | 9 => BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms2
  | 10 => BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms2dot5
  | 11 => BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms3
  | 12 => BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms4
  | 13 => BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms5
  | 14 => BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms6
  | 15 => BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms8
  | 16 => BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms10
  | 17 => BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms20
  | _ => BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__ms0
  end.
Lemma BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__F1F2 : forall x : BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__Type, (BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__F1 x <= 17) /\ BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__F2 (BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__F1 x) = x. imp_solve. Qed.
Lemma BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__F2F1 : forall (y : nat) (H : y <= 17), BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__F1 (BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__F2 y) = y. enum_solve H y. Qed.

Record BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__Type : Set :=
  make__BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__Type {
    BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16 : BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__Type ;
}.
Definition BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__list := (
 Nor BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__Type BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__cond ::
 nil).
Definition BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__cond z := 
  BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__cond (BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16 z) /\
  True.

Inductive BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__Type : Set :=
 | BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__supported
.
Definition BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__cond := (fun (_ : BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__Type) => True).
Lemma BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__nat__helper.

Definition BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__F1 t :=
  match t with
  | BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__supported => 0
  end.
Definition BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__F2 n :=
  match n with
  | 0 => BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__supported
  | _ => BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__supported
  end.
Lemma BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__F1F2 : forall x : BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__Type, (BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__F1 x <= 0) /\ BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__F2 (BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__F1 x) = x. imp_solve. Qed.
Lemma BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__F2F1 : forall (y : nat) (H : y <= 0), BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__F1 (BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__F2 y) = y. enum_solve H y. Qed.

Record BandSidelinkEUTRA_r16__Type : Set :=
  make__BandSidelinkEUTRA_r16__Type {
    BandSidelinkEUTRA_r16__freqBandSidelinkEUTRA_r16 : FreqBandIndicatorEUTRA__Type ;
    BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16 : option BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__Type ;
    BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16 : option BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__Type ;
}.
Definition BandSidelinkEUTRA_r16__list := (
 Nor FreqBandIndicatorEUTRA__Type FreqBandIndicatorEUTRA__cond ::
 Opt BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__Type BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__cond ::
 Opt BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__Type BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__cond ::
 nil).
Definition BandSidelinkEUTRA_r16__cond z := 
  FreqBandIndicatorEUTRA__cond (BandSidelinkEUTRA_r16__freqBandSidelinkEUTRA_r16 z) /\
  opt_cond BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__cond (BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16 z) /\
  opt_cond BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__cond (BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16 z) /\
  True.


Opaque Byte.to_nat Byte.of_nat.
Opaque bind_parse restrict_parse proj_parse return_parse.
Opaque restrict_serialize proj_serialize sigma_serialize append_serialize proj2_serialize.

Opaque read_n_nat read_unit.
Opaque put_n_nat put_unit. 

Opaque opt_bind opt_serialize dft_serialize prepend_serialize list_serial.
Opaque opt_parse list_parse dft_parse fail_parse append_parse
  bind_parse return_parse.

Opaque Z.to_nat Z.of_nat Z.sub Z.add Z.le Z.lt Z.pow Z.opp Z.ltb.
Opaque Nat.mul Nat.shiftr Nat.shiftl Nat.div Nat.modulo Nat.leb Nat.ltb Nat.add
  Nat.sub Nat.land Nat.lor Nat.eqb  Nat.log2 Nat.pow Nat.even PeanoNat.Nat.lnot.
Opaque Compare_dec.le_dec Compare_dec.le_lt_dec ZArith_dec.Z_le_dec lt_eq_lt_dec_new. 
Opaque sumbool_and1 list_and list_and_cons list_cons_S flg_add. 

Opaque list_to_len.
   Opaque length Compare_dec.le_dec Compare_dec.lt_dec PeanoNat.Nat.eq_dec.
   Opaque bool__Format int__Format octet_string_nc__Format bit_string_nc__Format.

   Opaque ByteIdx_to_nat nat_to_ByteIdx add_opt list_bool_format normally_small_len_det_format
  get_byte_len to_parse_skip  open_typ_serialize open_typ_parse open_type_to_len.
  

Opaque seq_cond seq_ext_cond choice_cond.
Definition BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__Format : T_Format BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__Type (fun _ => True) :=
(* Eval compute in *) proj3_format BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__nat__Format BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__F1 BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__F2 BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__F1F2 BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__F2F1.

Opaque BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__cond BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__Format.


Definition BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__Format_Type := Eval cbn in seq_format_prod BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__list.
Definition BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__Format_list : BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__Format_Type :=
  (BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16__Format, unit_format).
Definition BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__list__Format := (*Eval compute in *) seq_format BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__list BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__Format_list.
Definition BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__F1 z :=
  (BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__gnb_ScheduledMode3DelaySidelinkEUTRA_r16 z, tt).
Definition BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__F2 (y : seq_type BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__list) :=
  match y with
  | (i0, _)=>
    make__BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__Type i0
  end.
Lemma BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__F1F2_cond (z : BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__Type)
  : BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__cond z ->
  (seq_cond BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__list (BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__F1 z)).
intro H. unfold BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__cond in H. simpl. auto. Qed.
Lemma BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__F1F2_cond2 (z : BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__Type)
 : BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__F2 (BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__F2F1_cond (y : seq_type BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__list)
  : seq_cond BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__list y ->
 (BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__cond (BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__F2 y)) /\  BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__F1 (BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__cond. simpl in *. auto.
 - simpl. unfold BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__F1. simpl. destruct_all_unit. auto.   Qed.
Definition BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__Format : T_Format BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__Type BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__cond :=
        proj2_format  BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__cond BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__list__Format
    BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__F1 BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__F2 BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__F1F2_cond  BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__F1F2_cond2 BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__F2F1_cond.
Opaque BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__cond BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__Format.

Definition BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__Format : T_Format BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__Type (fun _ => True) :=
(* Eval compute in *) proj3_format BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__nat__Format BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__F1 BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__F2 BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__F1F2 BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__F2F1.

Opaque BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__cond BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__Format.


Definition BandSidelinkEUTRA_r16__Format_Type := Eval cbn in seq_format_prod BandSidelinkEUTRA_r16__list.
Definition BandSidelinkEUTRA_r16__Format_list : BandSidelinkEUTRA_r16__Format_Type :=
  (FreqBandIndicatorEUTRA__Format, (BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16__Format, (BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16__Format, unit_format))).
Definition BandSidelinkEUTRA_r16__list__Format := (*Eval compute in *) seq_format BandSidelinkEUTRA_r16__list BandSidelinkEUTRA_r16__Format_list.
Definition BandSidelinkEUTRA_r16__F1 z :=
  (BandSidelinkEUTRA_r16__freqBandSidelinkEUTRA_r16 z, (BandSidelinkEUTRA_r16__gnb_ScheduledMode3SidelinkEUTRA_r16 z, (BandSidelinkEUTRA_r16__gnb_ScheduledMode4SidelinkEUTRA_r16 z, tt))).
Definition BandSidelinkEUTRA_r16__F2 (y : seq_type BandSidelinkEUTRA_r16__list) :=
  match y with
  | (i0, (i1, (i2, _)))=>
    make__BandSidelinkEUTRA_r16__Type i0 i1 i2
  end.
Lemma BandSidelinkEUTRA_r16__F1F2_cond (z : BandSidelinkEUTRA_r16__Type)
  : BandSidelinkEUTRA_r16__cond z ->
  (seq_cond BandSidelinkEUTRA_r16__list (BandSidelinkEUTRA_r16__F1 z)).
intro H. unfold BandSidelinkEUTRA_r16__cond in H. simpl. auto. Qed.
Lemma BandSidelinkEUTRA_r16__F1F2_cond2 (z : BandSidelinkEUTRA_r16__Type)
 : BandSidelinkEUTRA_r16__F2 (BandSidelinkEUTRA_r16__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma BandSidelinkEUTRA_r16__F2F1_cond (y : seq_type BandSidelinkEUTRA_r16__list)
  : seq_cond BandSidelinkEUTRA_r16__list y ->
 (BandSidelinkEUTRA_r16__cond (BandSidelinkEUTRA_r16__F2 y)) /\  BandSidelinkEUTRA_r16__F1 (BandSidelinkEUTRA_r16__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold BandSidelinkEUTRA_r16__cond. simpl in *. auto.
 - simpl. unfold BandSidelinkEUTRA_r16__F1. simpl. destruct_all_unit. auto.   Qed.
Definition BandSidelinkEUTRA_r16__Format : T_Format BandSidelinkEUTRA_r16__Type BandSidelinkEUTRA_r16__cond :=
        proj2_format  BandSidelinkEUTRA_r16__cond BandSidelinkEUTRA_r16__list__Format
    BandSidelinkEUTRA_r16__F1 BandSidelinkEUTRA_r16__F2 BandSidelinkEUTRA_r16__F1F2_cond  BandSidelinkEUTRA_r16__F1F2_cond2 BandSidelinkEUTRA_r16__F2F1_cond.
Opaque BandSidelinkEUTRA_r16__cond BandSidelinkEUTRA_r16__Format.

