Require Import ASN1Parser.ExtrOCaml.ExtractHelper.

Require Import NR.NR_RRC_Definitions.
Inductive BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__Type : Set :=
 | BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__supported
.
Definition BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__cond := (fun (_ : BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__Type) => True).
Lemma BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__nat__helper.

Definition BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__F1 t :=
  match t with
  | BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__supported => 0
  end.
Definition BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__F2 n :=
  match n with
  | 0 => BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__supported
  | _ => BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__supported
  end.
Lemma BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__F1F2 : forall x : BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__Type, (BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__F1 x <= 0) /\ BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__F2 (BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__F1 x) = x. imp_solve. Qed.
Lemma BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__F2F1 : forall (y : nat) (H : y <= 0), BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__F1 (BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__F2 y) = y. enum_solve H y. Qed.

Inductive BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__Type : Set :=
 | BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__n8
 | BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__n16
.
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__cond := (fun (_ : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__Type) => True).
Lemma BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__nat__helper : to_bit_sz 1 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__nat__Format : T_Format nat (fun z => (z <= 1)) :=
  nat_enum_format 1 BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__nat__helper.

Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__F1 t :=
  match t with
  | BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__n8 => 0
  | BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__n16 => 1
  end.
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__F2 n :=
  match n with
  | 0 => BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__n8
  | 1 => BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__n16
  | _ => BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__n8
  end.
Lemma BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__F1F2 : forall x : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__Type, (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__F1 x <= 1) /\ BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__F2 (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__F1 x) = x. imp_solve. Qed.
Lemma BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__F2F1 : forall (y : nat) (H : y <= 1), BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__F1 (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__F2 y) = y. enum_solve H y. Qed.

Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_15kHz_r17__Type := bit_string_fixed.
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_15kHz_r17__cond := (fun z : bit_string_fixed => (fst z) = Z.to_nat 16 /\ bit_string_len_prop (fst z) (snd z)).
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_30kHz_r17__Type := bit_string_fixed.
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_30kHz_r17__cond := (fun z : bit_string_fixed => (fst z) = Z.to_nat 16 /\ bit_string_len_prop (fst z) (snd z)).
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_60kHz_r17__Type := bit_string_fixed.
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_60kHz_r17__cond := (fun z : bit_string_fixed => (fst z) = Z.to_nat 16 /\ bit_string_len_prop (fst z) (snd z)).
Record BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__Type : Set :=
  make__BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__Type {
    BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_15kHz_r17 : option BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_15kHz_r17__Type ;
    BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_30kHz_r17 : option BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_30kHz_r17__Type ;
    BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_60kHz_r17 : option BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_60kHz_r17__Type ;
}.
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__list := (
 Opt BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_15kHz_r17__Type BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_15kHz_r17__cond ::
 Opt BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_30kHz_r17__Type BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_30kHz_r17__cond ::
 Opt BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_60kHz_r17__Type BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_60kHz_r17__cond ::
 nil).
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__cond z := 
  opt_cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_15kHz_r17__cond (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_15kHz_r17 z) /\
  opt_cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_30kHz_r17__cond (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_30kHz_r17 z) /\
  opt_cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_60kHz_r17__cond (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_60kHz_r17 z) /\
  True.

Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__scs_60kHz_r17__Type := bit_string_fixed.
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__scs_60kHz_r17__cond := (fun z : bit_string_fixed => (fst z) = Z.to_nat 16 /\ bit_string_len_prop (fst z) (snd z)).
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__scs_120kHz_r17__Type := bit_string_fixed.
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__scs_120kHz_r17__cond := (fun z : bit_string_fixed => (fst z) = Z.to_nat 16 /\ bit_string_len_prop (fst z) (snd z)).
Record BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__Type : Set :=
  make__BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__Type {
    BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__scs_60kHz_r17 : option BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__scs_60kHz_r17__Type ;
    BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__scs_120kHz_r17 : option BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__scs_120kHz_r17__Type ;
}.
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__list := (
 Opt BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__scs_60kHz_r17__Type BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__scs_60kHz_r17__cond ::
 Opt BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__scs_120kHz_r17__Type BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__scs_120kHz_r17__cond ::
 nil).
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__cond z := 
  opt_cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__scs_60kHz_r17__cond (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__scs_60kHz_r17 z) /\
  opt_cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__scs_120kHz_r17__cond (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__scs_120kHz_r17 z) /\
  True.


Inductive BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__Type : Set :=
  | BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17 : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__Type -> BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__Type
  | BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17 : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__Type -> BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__Type
.
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__list : list typ := (
typ_cons BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__Type BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__cond ::
typ_cons BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__Type BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__cond ::
 nil).
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__cond (c : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__Type) := 
  match c with
  | BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17 t => BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__cond t 
  | BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17 t => BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__cond t 
  end.

Lemma BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__len_helper1 : to_bit_sz (length BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__list - 1) <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia. Qed.
Lemma BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__len_helper2 : 2 <= length2 BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__list.
 simpl. lia. Qed.
Inductive BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__Type : Set :=
 | BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__supported
.
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__cond := (fun (_ : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__Type) => True).
Lemma BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__nat__helper.

Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__F1 t :=
  match t with
  | BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__supported => 0
  end.
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__F2 n :=
  match n with
  | 0 => BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__supported
  | _ => BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__supported
  end.
Lemma BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__F1F2 : forall x : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__Type, (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__F1 x <= 0) /\ BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__F2 (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__F1 x) = x. imp_solve. Qed.
Lemma BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__F2F1 : forall (y : nat) (H : y <= 0), BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__F1 (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__F2 y) = y. enum_solve H y. Qed.

Inductive BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__Type : Set :=
 | BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__supported
.
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__cond := (fun (_ : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__Type) => True).
Lemma BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__nat__helper.

Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__F1 t :=
  match t with
  | BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__supported => 0
  end.
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__F2 n :=
  match n with
  | 0 => BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__supported
  | _ => BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__supported
  end.
Lemma BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__F1F2 : forall x : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__Type, (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__F1 x <= 0) /\ BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__F2 (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__F1 x) = x. imp_solve. Qed.
Lemma BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__F2F1 : forall (y : nat) (H : y <= 0), BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__F1 (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__F2 y) = y. enum_solve H y. Qed.

Record BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__Type : Set :=
  make__BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__Type {
    BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17 : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__Type ;
    BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17 : option BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__Type ;
    BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17 : option BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__Type ;
    BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17 : option BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__Type ;
}.
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__list := (
 Nor BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__Type BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__cond ::
 Opt BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__Type BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__cond ::
 Opt BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__Type BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__cond ::
 Opt BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__Type BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__cond ::
 nil).
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__cond z := 
  BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__cond (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17 z) /\
  opt_cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__cond (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17 z) /\
  opt_cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__cond (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17 z) /\
  opt_cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__cond (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17 z) /\
  True.

Inductive BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__Type : Set :=
 | BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__supported
.
Definition BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__cond := (fun (_ : BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__Type) => True).
Lemma BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__nat__helper.

Definition BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__F1 t :=
  match t with
  | BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__supported => 0
  end.
Definition BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__F2 n :=
  match n with
  | 0 => BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__supported
  | _ => BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__supported
  end.
Lemma BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__F1F2 : forall x : BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__Type, (BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__F1 x <= 0) /\ BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__F2 (BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__F1 x) = x. imp_solve. Qed.
Lemma BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__F2F1 : forall (y : nat) (H : y <= 0), BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__F1 (BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__F2 y) = y. enum_solve H y. Qed.

Record BandParametersSidelinkDiscovery_r17__Type : Set :=
  make__BandParametersSidelinkDiscovery_r17__Type {
    BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17 : option BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__Type ;
    BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17 : option BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__Type ;
    BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17 : option BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__Type ;
}.
Definition BandParametersSidelinkDiscovery_r17__list := (
 Opt BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__Type BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__cond ::
 Opt BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__Type BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__cond ::
 Opt BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__Type BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__cond ::
 nil).
Definition BandParametersSidelinkDiscovery_r17__cond z := 
  opt_cond BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__cond (BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17 z) /\
  opt_cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__cond (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17 z) /\
  opt_cond BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__cond (BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17 z) /\
  True.


Opaque Byte.to_nat Byte.of_nat.
Opaque bind_parse restrict_parse proj_parse return_parse.
Opaque restrict_serialize proj_serialize sigma_serialize append_serialize proj2_serialize.

Opaque read_n_nat read_unit.
Opaque put_n_nat put_unit. 

Opaque opt_bind opt_serialize dft_serialize prepend_serialize list_serial.
Opaque opt_parse list_parse dft_parse fail_parse append_parse
  bind_parse return_parse.

Opaque Z.to_nat Z.of_nat Z.sub Z.add Z.le Z.lt Z.pow Z.opp Z.ltb.
Opaque Nat.mul Nat.shiftr Nat.shiftl Nat.div Nat.modulo Nat.leb Nat.ltb Nat.add
  Nat.sub Nat.land Nat.lor Nat.eqb  Nat.log2 Nat.pow Nat.even PeanoNat.Nat.lnot.
Opaque Compare_dec.le_dec Compare_dec.le_lt_dec ZArith_dec.Z_le_dec lt_eq_lt_dec_new. 
Opaque sumbool_and1 list_and list_and_cons list_cons_S flg_add. 

Opaque list_to_len.
   Opaque length Compare_dec.le_dec Compare_dec.lt_dec PeanoNat.Nat.eq_dec.
   Opaque bool__Format int__Format octet_string_nc__Format bit_string_nc__Format.

   Opaque ByteIdx_to_nat nat_to_ByteIdx add_opt list_bool_format normally_small_len_det_format
  get_byte_len to_parse_skip  open_typ_serialize open_typ_parse open_type_to_len.
  

Opaque seq_cond seq_ext_cond choice_cond.
Definition BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__Format : T_Format BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__nat__Format BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__F1 BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__F2 BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__F1F2 BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__F2F1.

Opaque BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__cond BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__Format.

Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__Format : T_Format BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__nat__Format BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__F1 BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__F2 BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__F1F2 BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__F2F1.

Opaque BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__Format.

Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_15kHz_r17__Format : T_Format BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_15kHz_r17__Type BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_15kHz_r17__cond := (* Eval compute in *) bit_string_fixed_format 16.
Opaque BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_15kHz_r17__cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_15kHz_r17__Format.

Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_30kHz_r17__Format : T_Format BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_30kHz_r17__Type BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_30kHz_r17__cond := (* Eval compute in *) bit_string_fixed_format 16.
Opaque BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_30kHz_r17__cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_30kHz_r17__Format.

Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_60kHz_r17__Format : T_Format BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_60kHz_r17__Type BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_60kHz_r17__cond := (* Eval compute in *) bit_string_fixed_format 16.
Opaque BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_60kHz_r17__cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_60kHz_r17__Format.


Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__Format_Type := Eval cbn in seq_format_prod BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__list.
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__Format_list : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__Format_Type :=
  (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_15kHz_r17__Format, (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_30kHz_r17__Format, (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_60kHz_r17__Format, unit_format))).
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__list__Format := (*Eval compute in *) seq_format BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__list BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__Format_list.
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__F1 z :=
  (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_15kHz_r17 z, (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_30kHz_r17 z, (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__scs_60kHz_r17 z, tt))).
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__F2 (y : seq_type BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__list) :=
  match y with
  | (i0, (i1, (i2, _)))=>
    make__BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__Type i0 i1 i2
  end.
Lemma BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__F1F2_cond (z : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__Type)
  : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__cond z ->
  (seq_cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__list (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__F1 z)).
intro H. unfold BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__cond in H. simpl. auto. Qed.
Lemma BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__F1F2_cond2 (z : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__Type)
 : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__F2 (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__F2F1_cond (y : seq_type BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__list)
  : seq_cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__list y ->
 (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__cond (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__F2 y)) /\  BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__F1 (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__cond. simpl in *. auto.
 - simpl. unfold BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__F1. simpl. destruct_all_unit. auto.   Qed.
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__Format : T_Format BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__Type BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__cond :=
        proj2_format  BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__list__Format
    BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__F1 BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__F2 BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__F1F2_cond  BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__F1F2_cond2 BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__F2F1_cond.
Opaque BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__Format.

Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__scs_60kHz_r17__Format : T_Format BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__scs_60kHz_r17__Type BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__scs_60kHz_r17__cond := (* Eval compute in *) bit_string_fixed_format 16.
Opaque BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__scs_60kHz_r17__cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__scs_60kHz_r17__Format.

Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__scs_120kHz_r17__Format : T_Format BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__scs_120kHz_r17__Type BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__scs_120kHz_r17__cond := (* Eval compute in *) bit_string_fixed_format 16.
Opaque BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__scs_120kHz_r17__cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__scs_120kHz_r17__Format.


Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__Format_Type := Eval cbn in seq_format_prod BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__list.
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__Format_list : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__Format_Type :=
  (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__scs_60kHz_r17__Format, (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__scs_120kHz_r17__Format, unit_format)).
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__list__Format := (*Eval compute in *) seq_format BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__list BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__Format_list.
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__F1 z :=
  (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__scs_60kHz_r17 z, (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__scs_120kHz_r17 z, tt)).
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__F2 (y : seq_type BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__list) :=
  match y with
  | (i0, (i1, _))=>
    make__BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__Type i0 i1
  end.
Lemma BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__F1F2_cond (z : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__Type)
  : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__cond z ->
  (seq_cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__list (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__F1 z)).
intro H. unfold BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__cond in H. simpl. auto. Qed.
Lemma BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__F1F2_cond2 (z : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__Type)
 : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__F2 (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__F2F1_cond (y : seq_type BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__list)
  : seq_cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__list y ->
 (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__cond (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__F2 y)) /\  BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__F1 (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__cond. simpl in *. auto.
 - simpl. unfold BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__F1. simpl. destruct_all_unit. auto.   Qed.
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__Format : T_Format BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__Type BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__cond :=
        proj2_format  BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__list__Format
    BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__F1 BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__F2 BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__F1F2_cond  BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__F1F2_cond2 BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__F2F1_cond.
Opaque BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__Format.


Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__Format_Type := Eval cbn in get_formats BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__list.
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__Format_list : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__Format_Type :=
  (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__Format, (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__Format, unit__Format)).
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__list__Format := Eval compute in choice_format BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__list BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__len_helper1 BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__len_helper2  BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__Format_list.
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__F1 (z : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__Type) : (choice BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__list) :=
  match z with
   | BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17 t => existT _ 0 t
  | BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17 t => existT _ 1 t
  end.
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__g := (fun n => typ_set (get_nth_typ BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__list n)).
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__F2 (y : choice BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__list) : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__Type :=
  let (x0, t0) := y in
    (match x0 as n return  (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__g n -> BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__Type) with
    | 0 => fun (t : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17__Type) => BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr1_r17 t 
    | 1 => fun (t : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17__Type) => BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__fr2_r17 t 
 | (S (S n0)) => (fun (x' : nat) (t'' : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__g (S (S x'))) =>let t' :=
           eq_rect (get_nth_typ BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__list (S (S x')))
           (fun t' : typ => typ_set t') t'' empty_typ
           (get_nth_typ_ge_len BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__list (S (S x'))
           (le_n_S _ _ (le_n_S _ _ (le_0_n x')))) in match t' return BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__Type with end) n0
           end t0).

Lemma BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__helper2 :  forall (y : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__Type), BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__cond y -> choice_cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__list (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__F1 y).
  choice_helper_tact_dec y. Qed.

Lemma BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__helper3 :  forall (y : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__Type), BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__F2 (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__F1 y) = y.
  choice_helper_tact_dec y. Qed.

Transparent length.
Lemma BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__helper4 : (forall b : choice BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__list, choice_cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__list b -> BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__cond (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__F2 b) /\ BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__F1 (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__F2 b) = b).
Proof. intros. destruct b as [x t]; split; choice_helper_tact0 H x t. Qed.
Opaque length BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__F1 BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__F2.
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__Format : T_Format BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__Type BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__cond :=
  (* Eval compute in *) proj2_format BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__list__Format BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__F1 BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__F2 BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__helper2 BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__helper3 BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__helper4.
Opaque BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__Format.

Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__Format : T_Format BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__nat__Format BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__F1 BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__F2 BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__F1F2 BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__F2F1.

Opaque BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__Format.

Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__Format : T_Format BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__nat__Format BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__F1 BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__F2 BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__F1F2 BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__F2F1.

Opaque BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__Format.


Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__Format_Type := Eval cbn in seq_format_prod BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__list.
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__Format_list : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__Format_Type :=
  (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17__Format, (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17__Format, (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17__Format, (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17__Format, unit_format)))).
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__list__Format := (*Eval compute in *) seq_format BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__list BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__Format_list.
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__F1 z :=
  (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__harq_TxProcessModeTwoSidelink_r17 z, (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__scs_CP_PatternTxSidelinkModeTwo_r17 z, (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__extendedCP_Mode2PartialSensing_r17 z, (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__dl_openLoopPC_Sidelink_r17 z, tt)))).
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__F2 (y : seq_type BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__list) :=
  match y with
  | (i0, (i1, (i2, (i3, _))))=>
    make__BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__Type i0 i1 i2 i3
  end.
Lemma BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__F1F2_cond (z : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__Type)
  : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__cond z ->
  (seq_cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__list (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__F1 z)).
intro H. unfold BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__cond in H. simpl. auto. Qed.
Lemma BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__F1F2_cond2 (z : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__Type)
 : BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__F2 (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__F2F1_cond (y : seq_type BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__list)
  : seq_cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__list y ->
 (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__cond (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__F2 y)) /\  BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__F1 (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__cond. simpl in *. auto.
 - simpl. unfold BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__F1. simpl. destruct_all_unit. auto.   Qed.
Definition BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__Format : T_Format BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__Type BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__cond :=
        proj2_format  BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__list__Format
    BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__F1 BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__F2 BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__F1F2_cond  BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__F1F2_cond2 BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__F2F1_cond.
Opaque BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__cond BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__Format.

Definition BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__Format : T_Format BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__nat__Format BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__F1 BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__F2 BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__F1F2 BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__F2F1.

Opaque BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__cond BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__Format.


Definition BandParametersSidelinkDiscovery_r17__Format_Type := Eval cbn in seq_format_prod BandParametersSidelinkDiscovery_r17__list.
Definition BandParametersSidelinkDiscovery_r17__Format_list : BandParametersSidelinkDiscovery_r17__Format_Type :=
  (BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17__Format, (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17__Format, (BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17__Format, unit_format))).
Definition BandParametersSidelinkDiscovery_r17__list__Format := (*Eval compute in *) seq_format BandParametersSidelinkDiscovery_r17__list BandParametersSidelinkDiscovery_r17__Format_list.
Definition BandParametersSidelinkDiscovery_r17__F1 z :=
  (BandParametersSidelinkDiscovery_r17__sl_CrossCarrierScheduling_r17 z, (BandParametersSidelinkDiscovery_r17__sl_TransmissionMode2_PartialSensing_r17 z, (BandParametersSidelinkDiscovery_r17__tx_IUC_Scheme1_Mode2Sidelink_r17 z, tt))).
Definition BandParametersSidelinkDiscovery_r17__F2 (y : seq_type BandParametersSidelinkDiscovery_r17__list) :=
  match y with
  | (i0, (i1, (i2, _)))=>
    make__BandParametersSidelinkDiscovery_r17__Type i0 i1 i2
  end.
Lemma BandParametersSidelinkDiscovery_r17__F1F2_cond (z : BandParametersSidelinkDiscovery_r17__Type)
  : BandParametersSidelinkDiscovery_r17__cond z ->
  (seq_cond BandParametersSidelinkDiscovery_r17__list (BandParametersSidelinkDiscovery_r17__F1 z)).
intro H. unfold BandParametersSidelinkDiscovery_r17__cond in H. simpl. auto. Qed.
Lemma BandParametersSidelinkDiscovery_r17__F1F2_cond2 (z : BandParametersSidelinkDiscovery_r17__Type)
 : BandParametersSidelinkDiscovery_r17__F2 (BandParametersSidelinkDiscovery_r17__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma BandParametersSidelinkDiscovery_r17__F2F1_cond (y : seq_type BandParametersSidelinkDiscovery_r17__list)
  : seq_cond BandParametersSidelinkDiscovery_r17__list y ->
 (BandParametersSidelinkDiscovery_r17__cond (BandParametersSidelinkDiscovery_r17__F2 y)) /\  BandParametersSidelinkDiscovery_r17__F1 (BandParametersSidelinkDiscovery_r17__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold BandParametersSidelinkDiscovery_r17__cond. simpl in *. auto.
 - simpl. unfold BandParametersSidelinkDiscovery_r17__F1. simpl. destruct_all_unit. auto.   Qed.
Definition BandParametersSidelinkDiscovery_r17__Format : T_Format BandParametersSidelinkDiscovery_r17__Type BandParametersSidelinkDiscovery_r17__cond :=
        proj2_format  BandParametersSidelinkDiscovery_r17__cond BandParametersSidelinkDiscovery_r17__list__Format
    BandParametersSidelinkDiscovery_r17__F1 BandParametersSidelinkDiscovery_r17__F2 BandParametersSidelinkDiscovery_r17__F1F2_cond  BandParametersSidelinkDiscovery_r17__F1F2_cond2 BandParametersSidelinkDiscovery_r17__F2F1_cond.
Opaque BandParametersSidelinkDiscovery_r17__cond BandParametersSidelinkDiscovery_r17__Format.

