Require Import ASN1Parser.ExtrOCaml.ExtractHelper.

Require Import NR.NR_RRC_Definitions.
Inductive CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__Type : Set :=
 | CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__supported
.
Definition CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__cond := (fun (_ : CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__Type) => True).
Lemma CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__nat__helper.

Definition CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__F1 t :=
  match t with
  | CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__supported => 0
  end.
Definition CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__F2 n :=
  match n with
  | 0 => CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__supported
  | _ => CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__supported
  end.
Lemma CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__F1F2 : forall x : CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__Type, (CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__F1 x <= 0) /\ CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__F2 (CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__F1 x) = x. imp_solve. Qed.
Lemma CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__F2F1 : forall (y : nat) (H : y <= 0), CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__F1 (CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__F2 y) = y. enum_solve H y. Qed.

Require Import NR.PUCCH_Grp_CarrierTypes_r16.

Opaque PUCCH_Grp_CarrierTypes_r16__cond PUCCH_Grp_CarrierTypes_r16__Format.

Require Import NR.PUCCH_Grp_CarrierTypes_r16.

Opaque PUCCH_Grp_CarrierTypes_r16__cond PUCCH_Grp_CarrierTypes_r16__Format.

Require Import NR.TwoPUCCH_Grp_Configurations_r16.

Opaque TwoPUCCH_Grp_Configurations_r16__cond TwoPUCCH_Grp_Configurations_r16__Format.

Definition CA_ParametersNR_v1640__twoPUCCH_Grp_ConfigurationsList_r16__Type := list TwoPUCCH_Grp_Configurations_r16__Type.

Lemma CA_ParametersNR_v1640__twoPUCCH_Grp_ConfigurationsList_r16__helper1 : (0 <= 1 <= maxTwoPUCCH_Grp_ConfigList_r16)%Z. unfold maxTwoPUCCH_Grp_ConfigList_r16.
 lia. Qed.
Lemma CA_ParametersNR_v1640__twoPUCCH_Grp_ConfigurationsList_r16__helper2 : to_bit_sz (Z.to_nat (maxTwoPUCCH_Grp_ConfigList_r16 - 1)) <= INT_MAX_LEN.
unfold to_bit_sz, INT_MAX_LEN. 
        assert (H : (0 <= (maxTwoPUCCH_Grp_ConfigList_r16 - 1))%Z). { apply Zorder.Zle_minus_le_0. apply CA_ParametersNR_v1640__twoPUCCH_Grp_ConfigurationsList_r16__helper1. }
        assert (G := log2_same _ H). rewrite <- G.
        simpl. lia. Qed.
Definition CA_ParametersNR_v1640__twoPUCCH_Grp_ConfigurationsList_r16__cond (z : CA_ParametersNR_v1640__twoPUCCH_Grp_ConfigurationsList_r16__Type) :=  (1 <= Z.of_nat (length z) <= maxTwoPUCCH_Grp_ConfigList_r16)%Z /\ (list_and TwoPUCCH_Grp_Configurations_r16__cond z) .

Inductive CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__Type : Set :=
 | CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__supported
.
Definition CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__cond := (fun (_ : CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__Type) => True).
Lemma CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__nat__helper.

Definition CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__F1 t :=
  match t with
  | CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__supported => 0
  end.
Definition CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__F2 n :=
  match n with
  | 0 => CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__supported
  | _ => CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__supported
  end.
Lemma CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__F1F2 : forall x : CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__Type, (CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__F1 x <= 0) /\ CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__F2 (CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__F1 x) = x. imp_solve. Qed.
Lemma CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__F2F1 : forall (y : nat) (H : y <= 0), CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__F1 (CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__F2 y) = y. enum_solve H y. Qed.

Inductive CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__Type : Set :=
 | CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__supported
.
Definition CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__cond := (fun (_ : CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__Type) => True).
Lemma CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__nat__helper.

Definition CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__F1 t :=
  match t with
  | CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__supported => 0
  end.
Definition CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__F2 n :=
  match n with
  | 0 => CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__supported
  | _ => CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__supported
  end.
Lemma CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__F1F2 : forall x : CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__Type, (CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__F1 x <= 0) /\ CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__F2 (CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__F1 x) = x. imp_solve. Qed.
Lemma CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__F2F1 : forall (y : nat) (H : y <= 0), CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__F1 (CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__F2 y) = y. enum_solve H y. Qed.

Inductive CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__Type : Set :=
 | CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__supported
.
Definition CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__cond := (fun (_ : CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__Type) => True).
Lemma CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__nat__helper.

Definition CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__F1 t :=
  match t with
  | CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__supported => 0
  end.
Definition CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__F2 n :=
  match n with
  | 0 => CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__supported
  | _ => CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__supported
  end.
Lemma CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__F1F2 : forall x : CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__Type, (CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__F1 x <= 0) /\ CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__F2 (CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__F1 x) = x. imp_solve. Qed.
Lemma CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__F2F1 : forall (y : nat) (H : y <= 0), CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__F1 (CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__F2 y) = y. enum_solve H y. Qed.

Lemma CA_ParametersNR_v1640__pdcch_MonitoringCA_NonAlignedSpan_r16__helper1 : (2 <= 16)%Z.  lia. Qed.
Lemma CA_ParametersNR_v1640__pdcch_MonitoringCA_NonAlignedSpan_r16__helper2 : to_bit_sz (Z.to_nat (16 - 2)) <= INT_MAX_LEN.
unfold to_bit_sz, INT_MAX_LEN. 
        assert (H : (0 <= (16 - 2))%Z). { apply Zorder.Zle_minus_le_0. apply CA_ParametersNR_v1640__pdcch_MonitoringCA_NonAlignedSpan_r16__helper1. }
        assert (G := log2_same _ H). rewrite <- G.
        simpl. lia. Qed.
Definition CA_ParametersNR_v1640__pdcch_MonitoringCA_NonAlignedSpan_r16__Type := Z.
Definition CA_ParametersNR_v1640__pdcch_MonitoringCA_NonAlignedSpan_r16__cond := (fun z => (2 <= z <= 16)%Z).
Lemma CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA1_r16__helper1 : (1 <= 15)%Z.  lia. Qed.
Lemma CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA1_r16__helper2 : to_bit_sz (Z.to_nat (15 - 1)) <= INT_MAX_LEN.
unfold to_bit_sz, INT_MAX_LEN. 
        assert (H : (0 <= (15 - 1))%Z). { apply Zorder.Zle_minus_le_0. apply CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA1_r16__helper1. }
        assert (G := log2_same _ H). rewrite <- G.
        simpl. lia. Qed.
Definition CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA1_r16__Type := Z.
Definition CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA1_r16__cond := (fun z => (1 <= z <= 15)%Z).
Lemma CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA2_r16__helper1 : (1 <= 15)%Z.  lia. Qed.
Lemma CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA2_r16__helper2 : to_bit_sz (Z.to_nat (15 - 1)) <= INT_MAX_LEN.
unfold to_bit_sz, INT_MAX_LEN. 
        assert (H : (0 <= (15 - 1))%Z). { apply Zorder.Zle_minus_le_0. apply CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA2_r16__helper1. }
        assert (G := log2_same _ H). rewrite <- G.
        simpl. lia. Qed.
Definition CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA2_r16__Type := Z.
Definition CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA2_r16__cond := (fun z => (1 <= z <= 15)%Z).
Record CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__Type : Set :=
  make__CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__Type {
    CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA1_r16 : Z ;
    CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA2_r16 : Z ;
}.
Definition CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__list := (
 Nor Z CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA1_r16__cond ::
 Nor Z CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA2_r16__cond ::
 nil).
Definition CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__cond z := 
  CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA1_r16__cond (CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA1_r16 z) /\
  CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA2_r16__cond (CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA2_r16 z) /\
  True.

Record CA_ParametersNR_v1640__Type : Set :=
  make__CA_ParametersNR_v1640__Type {
    CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16 : option CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__Type ;
    CA_ParametersNR_v1640__maxUpTo3Diff_NumerologiesConfigSinglePUCCH_grp_r16 : option PUCCH_Grp_CarrierTypes_r16__Type ;
    CA_ParametersNR_v1640__maxUpTo4Diff_NumerologiesConfigSinglePUCCH_grp_r16 : option PUCCH_Grp_CarrierTypes_r16__Type ;
    CA_ParametersNR_v1640__twoPUCCH_Grp_ConfigurationsList_r16 : option CA_ParametersNR_v1640__twoPUCCH_Grp_ConfigurationsList_r16__Type ;
    CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16 : option CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__Type ;
    CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16 : option CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__Type ;
    CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16 : option CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__Type ;
    CA_ParametersNR_v1640__pdcch_MonitoringCA_NonAlignedSpan_r16 : option Z ;
    CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16 : option CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__Type ;
}.
Definition CA_ParametersNR_v1640__list := (
 Opt CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__Type CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__cond ::
 Opt PUCCH_Grp_CarrierTypes_r16__Type PUCCH_Grp_CarrierTypes_r16__cond ::
 Opt PUCCH_Grp_CarrierTypes_r16__Type PUCCH_Grp_CarrierTypes_r16__cond ::
 Opt CA_ParametersNR_v1640__twoPUCCH_Grp_ConfigurationsList_r16__Type CA_ParametersNR_v1640__twoPUCCH_Grp_ConfigurationsList_r16__cond ::
 Opt CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__Type CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__cond ::
 Opt CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__Type CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__cond ::
 Opt CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__Type CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__cond ::
 Opt Z CA_ParametersNR_v1640__pdcch_MonitoringCA_NonAlignedSpan_r16__cond ::
 Opt CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__Type CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__cond ::
 nil).
Definition CA_ParametersNR_v1640__cond z := 
  opt_cond CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__cond (CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16 z) /\
  opt_cond PUCCH_Grp_CarrierTypes_r16__cond (CA_ParametersNR_v1640__maxUpTo3Diff_NumerologiesConfigSinglePUCCH_grp_r16 z) /\
  opt_cond PUCCH_Grp_CarrierTypes_r16__cond (CA_ParametersNR_v1640__maxUpTo4Diff_NumerologiesConfigSinglePUCCH_grp_r16 z) /\
  opt_cond CA_ParametersNR_v1640__twoPUCCH_Grp_ConfigurationsList_r16__cond (CA_ParametersNR_v1640__twoPUCCH_Grp_ConfigurationsList_r16 z) /\
  opt_cond CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__cond (CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16 z) /\
  opt_cond CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__cond (CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16 z) /\
  opt_cond CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__cond (CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16 z) /\
  opt_cond CA_ParametersNR_v1640__pdcch_MonitoringCA_NonAlignedSpan_r16__cond (CA_ParametersNR_v1640__pdcch_MonitoringCA_NonAlignedSpan_r16 z) /\
  opt_cond CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__cond (CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16 z) /\
  True.


Opaque Byte.to_nat Byte.of_nat.
Opaque bind_parse restrict_parse proj_parse return_parse.
Opaque restrict_serialize proj_serialize sigma_serialize append_serialize proj2_serialize.

Opaque read_n_nat read_unit.
Opaque put_n_nat put_unit. 

Opaque opt_bind opt_serialize dft_serialize prepend_serialize list_serial.
Opaque opt_parse list_parse dft_parse fail_parse append_parse
  bind_parse return_parse.

Opaque Z.to_nat Z.of_nat Z.sub Z.add Z.le Z.lt Z.pow Z.opp Z.ltb.
Opaque Nat.mul Nat.shiftr Nat.shiftl Nat.div Nat.modulo Nat.leb Nat.ltb Nat.add
  Nat.sub Nat.land Nat.lor Nat.eqb  Nat.log2 Nat.pow Nat.even PeanoNat.Nat.lnot.
Opaque Compare_dec.le_dec Compare_dec.le_lt_dec ZArith_dec.Z_le_dec lt_eq_lt_dec_new. 
Opaque sumbool_and1 list_and list_and_cons list_cons_S flg_add. 

Opaque list_to_len.
   Opaque length Compare_dec.le_dec Compare_dec.lt_dec PeanoNat.Nat.eq_dec.
   Opaque bool__Format int__Format octet_string_nc__Format bit_string_nc__Format.

   Opaque ByteIdx_to_nat nat_to_ByteIdx add_opt list_bool_format normally_small_len_det_format
  get_byte_len to_parse_skip  open_typ_serialize open_typ_parse open_type_to_len.
  

Opaque seq_cond seq_ext_cond choice_cond.
Definition CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__Format : T_Format CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__Type (fun _ => True) :=
(* Eval compute in *) proj3_format CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__nat__Format CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__F1 CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__F2 CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__F1F2 CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__F2F1.

Opaque CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__cond CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__Format.

Definition CA_ParametersNR_v1640__twoPUCCH_Grp_ConfigurationsList_r16__Format : T_Format CA_ParametersNR_v1640__twoPUCCH_Grp_ConfigurationsList_r16__Type CA_ParametersNR_v1640__twoPUCCH_Grp_ConfigurationsList_r16__cond := seq_of_format TwoPUCCH_Grp_Configurations_r16__Format 1 maxTwoPUCCH_Grp_ConfigList_r16 CA_ParametersNR_v1640__twoPUCCH_Grp_ConfigurationsList_r16__helper1 CA_ParametersNR_v1640__twoPUCCH_Grp_ConfigurationsList_r16__helper2.

Opaque CA_ParametersNR_v1640__twoPUCCH_Grp_ConfigurationsList_r16__cond CA_ParametersNR_v1640__twoPUCCH_Grp_ConfigurationsList_r16__Format.

Definition CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__Format : T_Format CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__Type (fun _ => True) :=
(* Eval compute in *) proj3_format CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__nat__Format CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__F1 CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__F2 CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__F1F2 CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__F2F1.

Opaque CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__cond CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__Format.

Definition CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__Format : T_Format CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__Type (fun _ => True) :=
(* Eval compute in *) proj3_format CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__nat__Format CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__F1 CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__F2 CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__F1F2 CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__F2F1.

Opaque CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__cond CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__Format.

Definition CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__Format : T_Format CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__Type (fun _ => True) :=
(* Eval compute in *) proj3_format CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__nat__Format CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__F1 CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__F2 CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__F1F2 CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__F2F1.

Opaque CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__cond CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__Format.

Definition CA_ParametersNR_v1640__pdcch_MonitoringCA_NonAlignedSpan_r16__Format : T_Format Z CA_ParametersNR_v1640__pdcch_MonitoringCA_NonAlignedSpan_r16__cond :=
 ranged_int_format (2) (16) CA_ParametersNR_v1640__pdcch_MonitoringCA_NonAlignedSpan_r16__helper1 CA_ParametersNR_v1640__pdcch_MonitoringCA_NonAlignedSpan_r16__helper2.

Opaque CA_ParametersNR_v1640__pdcch_MonitoringCA_NonAlignedSpan_r16__cond CA_ParametersNR_v1640__pdcch_MonitoringCA_NonAlignedSpan_r16__Format.

Definition CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA1_r16__Format : T_Format Z CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA1_r16__cond :=
 ranged_int_format (1) (15) CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA1_r16__helper1 CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA1_r16__helper2.

Opaque CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA1_r16__cond CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA1_r16__Format.

Definition CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA2_r16__Format : T_Format Z CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA2_r16__cond :=
 ranged_int_format (1) (15) CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA2_r16__helper1 CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA2_r16__helper2.

Opaque CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA2_r16__cond CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA2_r16__Format.


Definition CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__Format_Type := Eval cbn in seq_format_prod CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__list.
Definition CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__Format_list : CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__Format_Type :=
  (CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA1_r16__Format, (CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA2_r16__Format, unit_format)).
Definition CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__list__Format := (*Eval compute in *) seq_format CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__list CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__Format_list.
Definition CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__F1 z :=
  (CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA1_r16 z, (CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__pdcch_BlindDetectionCA2_r16 z, tt)).
Definition CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__F2 (y : seq_type CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__list) :=
  match y with
  | (i0, (i1, _))=>
    make__CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__Type i0 i1
  end.
Lemma CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__F1F2_cond (z : CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__Type)
  : CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__cond z ->
  (seq_cond CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__list (CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__F1 z)).
intro H. unfold CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__cond in H. simpl. auto. Qed.
Lemma CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__F1F2_cond2 (z : CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__Type)
 : CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__F2 (CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__F2F1_cond (y : seq_type CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__list)
  : seq_cond CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__list y ->
 (CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__cond (CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__F2 y)) /\  CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__F1 (CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__cond. simpl in *. auto.
 - simpl. unfold CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__F1. simpl. destruct_all_unit. auto.   Qed.
Definition CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__Format : T_Format CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__Type CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__cond :=
        proj2_format  CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__cond CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__list__Format
    CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__F1 CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__F2 CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__F1F2_cond  CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__F1F2_cond2 CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__F2F1_cond.
Opaque CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__cond CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__Format.


Definition CA_ParametersNR_v1640__Format_Type := Eval cbn in seq_format_prod CA_ParametersNR_v1640__list.
Definition CA_ParametersNR_v1640__Format_list : CA_ParametersNR_v1640__Format_Type :=
  (CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16__Format, (PUCCH_Grp_CarrierTypes_r16__Format, (PUCCH_Grp_CarrierTypes_r16__Format, (CA_ParametersNR_v1640__twoPUCCH_Grp_ConfigurationsList_r16__Format, (CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16__Format, (CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16__Format, (CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16__Format, (CA_ParametersNR_v1640__pdcch_MonitoringCA_NonAlignedSpan_r16__Format, (CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16__Format, unit_format))))))))).
Definition CA_ParametersNR_v1640__list__Format := (*Eval compute in *) seq_format CA_ParametersNR_v1640__list CA_ParametersNR_v1640__Format_list.
Definition CA_ParametersNR_v1640__F1 z :=
  (CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16 z, (CA_ParametersNR_v1640__maxUpTo3Diff_NumerologiesConfigSinglePUCCH_grp_r16 z, (CA_ParametersNR_v1640__maxUpTo4Diff_NumerologiesConfigSinglePUCCH_grp_r16 z, (CA_ParametersNR_v1640__twoPUCCH_Grp_ConfigurationsList_r16 z, (CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16 z, (CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16 z, (CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16 z, (CA_ParametersNR_v1640__pdcch_MonitoringCA_NonAlignedSpan_r16 z, (CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16 z, tt))))))))).
Definition CA_ParametersNR_v1640__F2 (y : seq_type CA_ParametersNR_v1640__list) :=
  match y with
  | (i0, (i1, (i2, (i3, (i4, (i5, (i6, (i7, (i8, _)))))))))=>
    make__CA_ParametersNR_v1640__Type i0 i1 i2 i3 i4 i5 i6 i7 i8
  end.
Lemma CA_ParametersNR_v1640__F1F2_cond (z : CA_ParametersNR_v1640__Type)
  : CA_ParametersNR_v1640__cond z ->
  (seq_cond CA_ParametersNR_v1640__list (CA_ParametersNR_v1640__F1 z)).
intro H. unfold CA_ParametersNR_v1640__cond in H. simpl. auto. Qed.
Lemma CA_ParametersNR_v1640__F1F2_cond2 (z : CA_ParametersNR_v1640__Type)
 : CA_ParametersNR_v1640__F2 (CA_ParametersNR_v1640__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma CA_ParametersNR_v1640__F2F1_cond (y : seq_type CA_ParametersNR_v1640__list)
  : seq_cond CA_ParametersNR_v1640__list y ->
 (CA_ParametersNR_v1640__cond (CA_ParametersNR_v1640__F2 y)) /\  CA_ParametersNR_v1640__F1 (CA_ParametersNR_v1640__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold CA_ParametersNR_v1640__cond. simpl in *. auto.
 - simpl. unfold CA_ParametersNR_v1640__F1. simpl. destruct_all_unit. auto.   Qed.
Definition CA_ParametersNR_v1640__Format : T_Format CA_ParametersNR_v1640__Type CA_ParametersNR_v1640__cond :=
        proj2_format  CA_ParametersNR_v1640__cond CA_ParametersNR_v1640__list__Format
    CA_ParametersNR_v1640__F1 CA_ParametersNR_v1640__F2 CA_ParametersNR_v1640__F1F2_cond  CA_ParametersNR_v1640__F1F2_cond2 CA_ParametersNR_v1640__F2F1_cond.
Opaque CA_ParametersNR_v1640__cond CA_ParametersNR_v1640__Format.

