Require Import ASN1Parser.ExtrOCaml.ExtractHelper.

Require Import NR.NR_RRC_Definitions.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_one__Type := bit_string_fixed.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_one__cond := (fun z : bit_string_fixed => (fst z) = Z.to_nat 16 /\ bit_string_len_prop (fst z) (snd z)).
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_two__Type := bit_string_fixed.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_two__cond := (fun z : bit_string_fixed => (fst z) = Z.to_nat 43 /\ bit_string_len_prop (fst z) (snd z)).
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_one__Type := bit_string_fixed.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_one__cond := (fun z : bit_string_fixed => (fst z) = Z.to_nat 32 /\ bit_string_len_prop (fst z) (snd z)).
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__three_two__Type := bit_string_fixed.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__three_two__cond := (fun z : bit_string_fixed => (fst z) = Z.to_nat 59 /\ bit_string_len_prop (fst z) (snd z)).
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_one__Type := bit_string_fixed.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_one__cond := (fun z : bit_string_fixed => (fst z) = Z.to_nat 48 /\ bit_string_len_prop (fst z) (snd z)).
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_two__Type := bit_string_fixed.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_two__cond := (fun z : bit_string_fixed => (fst z) = Z.to_nat 75 /\ bit_string_len_prop (fst z) (snd z)).
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_one__Type := bit_string_fixed.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_one__cond := (fun z : bit_string_fixed => (fst z) = Z.to_nat 64 /\ bit_string_len_prop (fst z) (snd z)).
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_three__Type := bit_string_fixed.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_three__cond := (fun z : bit_string_fixed => (fst z) = Z.to_nat 107 /\ bit_string_len_prop (fst z) (snd z)).
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_two__Type := bit_string_fixed.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_two__cond := (fun z : bit_string_fixed => (fst z) = Z.to_nat 107 /\ bit_string_len_prop (fst z) (snd z)).
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__twelve_one__Type := bit_string_fixed.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__twelve_one__cond := (fun z : bit_string_fixed => (fst z) = Z.to_nat 96 /\ bit_string_len_prop (fst z) (snd z)).
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_four__Type := bit_string_fixed.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_four__cond := (fun z : bit_string_fixed => (fst z) = Z.to_nat 139 /\ bit_string_len_prop (fst z) (snd z)).
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_two__Type := bit_string_fixed.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_two__cond := (fun z : bit_string_fixed => (fst z) = Z.to_nat 139 /\ bit_string_len_prop (fst z) (snd z)).
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__sixteen_one__Type := bit_string_fixed.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__sixteen_one__cond := (fun z : bit_string_fixed => (fst z) = Z.to_nat 128 /\ bit_string_len_prop (fst z) (snd z)).

Inductive CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__Type : Set :=
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_one : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_one__Type -> CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__Type
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_two : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_two__Type -> CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__Type
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_one : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_one__Type -> CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__Type
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__three_two : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__three_two__Type -> CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__Type
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_one : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_one__Type -> CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__Type
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_two : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_two__Type -> CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__Type
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_one : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_one__Type -> CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__Type
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_three : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_three__Type -> CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__Type
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_two : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_two__Type -> CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__Type
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__twelve_one : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__twelve_one__Type -> CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__Type
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_four : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_four__Type -> CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__Type
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_two : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_two__Type -> CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__Type
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__sixteen_one : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__sixteen_one__Type -> CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__Type
.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__list : list typ := (
typ_cons CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_one__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_one__cond ::
typ_cons CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_two__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_two__cond ::
typ_cons CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_one__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_one__cond ::
typ_cons CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__three_two__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__three_two__cond ::
typ_cons CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_one__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_one__cond ::
typ_cons CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_two__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_two__cond ::
typ_cons CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_one__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_one__cond ::
typ_cons CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_three__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_three__cond ::
typ_cons CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_two__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_two__cond ::
typ_cons CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__twelve_one__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__twelve_one__cond ::
typ_cons CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_four__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_four__cond ::
typ_cons CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_two__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_two__cond ::
typ_cons CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__sixteen_one__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__sixteen_one__cond ::
 nil).
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__cond (c : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__Type) := 
  match c with
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_one t => CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_one__cond t 
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_two t => CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_two__cond t 
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_one t => CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_one__cond t 
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__three_two t => CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__three_two__cond t 
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_one t => CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_one__cond t 
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_two t => CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_two__cond t 
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_one t => CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_one__cond t 
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_three t => CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_three__cond t 
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_two t => CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_two__cond t 
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__twelve_one t => CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__twelve_one__cond t 
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_four t => CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_four__cond t 
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_two t => CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_two__cond t 
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__sixteen_one t => CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__sixteen_one__cond t 
  end.

Lemma CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__len_helper1 : to_bit_sz (length CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__list - 1) <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia. Qed.
Lemma CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__len_helper2 : 2 <= length2 CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__list.
 simpl. lia. Qed.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__typeII_RI_Restriction_r16__Type := bit_string_fixed.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__typeII_RI_Restriction_r16__cond := (fun z : bit_string_fixed => (fst z) = Z.to_nat 4 /\ bit_string_len_prop (fst z) (snd z)).
Record CodebookConfig_r16__codebookType__type2__subType__typeII_r16__Type : Set :=
  make__CodebookConfig_r16__codebookType__type2__subType__typeII_r16__Type {
    CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16 : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__Type ;
    CodebookConfig_r16__codebookType__type2__subType__typeII_r16__typeII_RI_Restriction_r16 : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__typeII_RI_Restriction_r16__Type ;
}.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__list := (
 Nor CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__cond ::
 Nor CodebookConfig_r16__codebookType__type2__subType__typeII_r16__typeII_RI_Restriction_r16__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__typeII_RI_Restriction_r16__cond ::
 nil).
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__cond z := 
  CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__cond (CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16 z) /\
  CodebookConfig_r16__codebookType__type2__subType__typeII_r16__typeII_RI_Restriction_r16__cond (CodebookConfig_r16__codebookType__type2__subType__typeII_r16__typeII_RI_Restriction_r16 z) /\
  True.

Inductive CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__Type : Set :=
 | CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__n1
 | CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__n2
 | CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__n3
 | CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__n4
.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__cond := (fun (_ : CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__Type) => True).
Lemma CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__nat__helper : to_bit_sz 3 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__nat__Format : T_Format nat (fun z => (z <= 3)) :=
  nat_enum_format 3 CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__nat__helper.

Definition CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__F1 t :=
  match t with
  | CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__n1 => 0
  | CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__n2 => 1
  | CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__n3 => 2
  | CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__n4 => 3
  end.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__F2 n :=
  match n with
  | 0 => CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__n1
  | 1 => CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__n2
  | 2 => CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__n3
  | 3 => CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__n4
  | _ => CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__n1
  end.
Lemma CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__F1F2 : forall x : CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__Type, (CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__F1 x <= 3) /\ CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__F2 (CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__F1 x) = x. imp_solve. Qed.
Lemma CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__F2F1 : forall (y : nat) (H : y <= 3), CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__F1 (CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__F2 y) = y. enum_solve H y. Qed.

Definition CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__typeII_PortSelectionRI_Restriction_r16__Type := bit_string_fixed.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__typeII_PortSelectionRI_Restriction_r16__cond := (fun z : bit_string_fixed => (fst z) = Z.to_nat 4 /\ bit_string_len_prop (fst z) (snd z)).
Record CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__Type : Set :=
  make__CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__Type {
    CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16 : CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__Type ;
    CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__typeII_PortSelectionRI_Restriction_r16 : CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__typeII_PortSelectionRI_Restriction_r16__Type ;
}.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__list := (
 Nor CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__Type CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__cond ::
 Nor CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__typeII_PortSelectionRI_Restriction_r16__Type CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__typeII_PortSelectionRI_Restriction_r16__cond ::
 nil).
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__cond z := 
  CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__cond (CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16 z) /\
  CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__typeII_PortSelectionRI_Restriction_r16__cond (CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__typeII_PortSelectionRI_Restriction_r16 z) /\
  True.


Inductive CodebookConfig_r16__codebookType__type2__subType__Type : Set :=
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16 : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__Type -> CodebookConfig_r16__codebookType__type2__subType__Type
  | CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16 : CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__Type -> CodebookConfig_r16__codebookType__type2__subType__Type
.
Definition CodebookConfig_r16__codebookType__type2__subType__list : list typ := (
typ_cons CodebookConfig_r16__codebookType__type2__subType__typeII_r16__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__cond ::
typ_cons CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__Type CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__cond ::
 nil).
Definition CodebookConfig_r16__codebookType__type2__subType__cond (c : CodebookConfig_r16__codebookType__type2__subType__Type) := 
  match c with
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16 t => CodebookConfig_r16__codebookType__type2__subType__typeII_r16__cond t 
  | CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16 t => CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__cond t 
  end.

Lemma CodebookConfig_r16__codebookType__type2__subType__len_helper1 : to_bit_sz (length CodebookConfig_r16__codebookType__type2__subType__list - 1) <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia. Qed.
Lemma CodebookConfig_r16__codebookType__type2__subType__len_helper2 : 2 <= length2 CodebookConfig_r16__codebookType__type2__subType__list.
 simpl. lia. Qed.
Lemma CodebookConfig_r16__codebookType__type2__numberOfPMI_SubbandsPerCQI_Subband_r16__helper1 : (1 <= 2)%Z.  lia. Qed.
Lemma CodebookConfig_r16__codebookType__type2__numberOfPMI_SubbandsPerCQI_Subband_r16__helper2 : to_bit_sz (Z.to_nat (2 - 1)) <= INT_MAX_LEN.
unfold to_bit_sz, INT_MAX_LEN. 
        assert (H : (0 <= (2 - 1))%Z). { apply Zorder.Zle_minus_le_0. apply CodebookConfig_r16__codebookType__type2__numberOfPMI_SubbandsPerCQI_Subband_r16__helper1. }
        assert (G := log2_same _ H). rewrite <- G.
        simpl. lia. Qed.
Definition CodebookConfig_r16__codebookType__type2__numberOfPMI_SubbandsPerCQI_Subband_r16__Type := Z.
Definition CodebookConfig_r16__codebookType__type2__numberOfPMI_SubbandsPerCQI_Subband_r16__cond := (fun z => (1 <= z <= 2)%Z).
Lemma CodebookConfig_r16__codebookType__type2__paramCombination_r16__helper1 : (1 <= 8)%Z.  lia. Qed.
Lemma CodebookConfig_r16__codebookType__type2__paramCombination_r16__helper2 : to_bit_sz (Z.to_nat (8 - 1)) <= INT_MAX_LEN.
unfold to_bit_sz, INT_MAX_LEN. 
        assert (H : (0 <= (8 - 1))%Z). { apply Zorder.Zle_minus_le_0. apply CodebookConfig_r16__codebookType__type2__paramCombination_r16__helper1. }
        assert (G := log2_same _ H). rewrite <- G.
        simpl. lia. Qed.
Definition CodebookConfig_r16__codebookType__type2__paramCombination_r16__Type := Z.
Definition CodebookConfig_r16__codebookType__type2__paramCombination_r16__cond := (fun z => (1 <= z <= 8)%Z).
Record CodebookConfig_r16__codebookType__type2__Type : Set :=
  make__CodebookConfig_r16__codebookType__type2__Type {
    CodebookConfig_r16__codebookType__type2__subType : CodebookConfig_r16__codebookType__type2__subType__Type ;
    CodebookConfig_r16__codebookType__type2__numberOfPMI_SubbandsPerCQI_Subband_r16 : Z ;
    CodebookConfig_r16__codebookType__type2__paramCombination_r16 : Z ;
}.
Definition CodebookConfig_r16__codebookType__type2__list := (
 Nor CodebookConfig_r16__codebookType__type2__subType__Type CodebookConfig_r16__codebookType__type2__subType__cond ::
 Nor Z CodebookConfig_r16__codebookType__type2__numberOfPMI_SubbandsPerCQI_Subband_r16__cond ::
 Nor Z CodebookConfig_r16__codebookType__type2__paramCombination_r16__cond ::
 nil).
Definition CodebookConfig_r16__codebookType__type2__cond z := 
  CodebookConfig_r16__codebookType__type2__subType__cond (CodebookConfig_r16__codebookType__type2__subType z) /\
  CodebookConfig_r16__codebookType__type2__numberOfPMI_SubbandsPerCQI_Subband_r16__cond (CodebookConfig_r16__codebookType__type2__numberOfPMI_SubbandsPerCQI_Subband_r16 z) /\
  CodebookConfig_r16__codebookType__type2__paramCombination_r16__cond (CodebookConfig_r16__codebookType__type2__paramCombination_r16 z) /\
  True.


Inductive CodebookConfig_r16__codebookType__Type : Set := | CodebookConfig_r16__codebookType__type2 : CodebookConfig_r16__codebookType__type2__Type -> CodebookConfig_r16__codebookType__Type.
Definition CodebookConfig_r16__codebookType__cond (c : CodebookConfig_r16__codebookType__Type) := 
  match c with
  | CodebookConfig_r16__codebookType__type2 t => CodebookConfig_r16__codebookType__type2__cond t 
  end.

Record CodebookConfig_r16__Type : Set :=
  make__CodebookConfig_r16__Type {
    CodebookConfig_r16__codebookType : CodebookConfig_r16__codebookType__Type ;
}.
Definition CodebookConfig_r16__list := (
 Nor CodebookConfig_r16__codebookType__Type CodebookConfig_r16__codebookType__cond ::
 nil).
Definition CodebookConfig_r16__cond z := 
  CodebookConfig_r16__codebookType__cond (CodebookConfig_r16__codebookType z) /\
  True.


Opaque Byte.to_nat Byte.of_nat.
Opaque bind_parse restrict_parse proj_parse return_parse.
Opaque restrict_serialize proj_serialize sigma_serialize append_serialize proj2_serialize.

Opaque read_n_nat read_unit.
Opaque put_n_nat put_unit. 

Opaque opt_bind opt_serialize dft_serialize prepend_serialize list_serial.
Opaque opt_parse list_parse dft_parse fail_parse append_parse
  bind_parse return_parse.

Opaque Z.to_nat Z.of_nat Z.sub Z.add Z.le Z.lt Z.pow Z.opp Z.ltb.
Opaque Nat.mul Nat.shiftr Nat.shiftl Nat.div Nat.modulo Nat.leb Nat.ltb Nat.add
  Nat.sub Nat.land Nat.lor Nat.eqb  Nat.log2 Nat.pow Nat.even PeanoNat.Nat.lnot.
Opaque Compare_dec.le_dec Compare_dec.le_lt_dec ZArith_dec.Z_le_dec lt_eq_lt_dec_new. 
Opaque sumbool_and1 list_and list_and_cons list_cons_S flg_add. 

Opaque list_to_len.
   Opaque length Compare_dec.le_dec Compare_dec.lt_dec PeanoNat.Nat.eq_dec.
   Opaque bool__Format int__Format octet_string_nc__Format bit_string_nc__Format.

   Opaque ByteIdx_to_nat nat_to_ByteIdx add_opt list_bool_format normally_small_len_det_format
  get_byte_len to_parse_skip  open_typ_serialize open_typ_parse open_type_to_len.
  

Opaque seq_cond seq_ext_cond choice_cond.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_one__Format : T_Format CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_one__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_one__cond := (* Eval compute in *) bit_string_fixed_format 16.
Opaque CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_one__cond CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_one__Format.

Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_two__Format : T_Format CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_two__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_two__cond := (* Eval compute in *) bit_string_fixed_format 43.
Opaque CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_two__cond CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_two__Format.

Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_one__Format : T_Format CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_one__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_one__cond := (* Eval compute in *) bit_string_fixed_format 32.
Opaque CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_one__cond CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_one__Format.

Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__three_two__Format : T_Format CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__three_two__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__three_two__cond := (* Eval compute in *) bit_string_fixed_format 59.
Opaque CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__three_two__cond CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__three_two__Format.

Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_one__Format : T_Format CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_one__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_one__cond := (* Eval compute in *) bit_string_fixed_format 48.
Opaque CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_one__cond CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_one__Format.

Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_two__Format : T_Format CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_two__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_two__cond := (* Eval compute in *) bit_string_fixed_format 75.
Opaque CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_two__cond CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_two__Format.

Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_one__Format : T_Format CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_one__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_one__cond := (* Eval compute in *) bit_string_fixed_format 64.
Opaque CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_one__cond CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_one__Format.

Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_three__Format : T_Format CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_three__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_three__cond := (* Eval compute in *) bit_string_fixed_format 107.
Opaque CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_three__cond CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_three__Format.

Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_two__Format : T_Format CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_two__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_two__cond := (* Eval compute in *) bit_string_fixed_format 107.
Opaque CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_two__cond CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_two__Format.

Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__twelve_one__Format : T_Format CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__twelve_one__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__twelve_one__cond := (* Eval compute in *) bit_string_fixed_format 96.
Opaque CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__twelve_one__cond CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__twelve_one__Format.

Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_four__Format : T_Format CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_four__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_four__cond := (* Eval compute in *) bit_string_fixed_format 139.
Opaque CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_four__cond CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_four__Format.

Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_two__Format : T_Format CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_two__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_two__cond := (* Eval compute in *) bit_string_fixed_format 139.
Opaque CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_two__cond CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_two__Format.

Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__sixteen_one__Format : T_Format CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__sixteen_one__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__sixteen_one__cond := (* Eval compute in *) bit_string_fixed_format 128.
Opaque CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__sixteen_one__cond CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__sixteen_one__Format.


Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__Format_Type := Eval cbn in get_formats CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__list.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__Format_list : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__Format_Type :=
  (CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_one__Format, (CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_two__Format, (CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_one__Format, (CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__three_two__Format, (CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_one__Format, (CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_two__Format, (CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_one__Format, (CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_three__Format, (CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_two__Format, (CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__twelve_one__Format, (CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_four__Format, (CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_two__Format, (CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__sixteen_one__Format, unit__Format))))))))))))).
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__list__Format := Eval compute in choice_format CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__list CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__len_helper1 CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__len_helper2  CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__Format_list.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__F1 (z : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__Type) : (choice CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__list) :=
  match z with
   | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_one t => existT _ 0 t
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_two t => existT _ 1 t
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_one t => existT _ 2 t
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__three_two t => existT _ 3 t
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_one t => existT _ 4 t
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_two t => existT _ 5 t
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_one t => existT _ 6 t
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_three t => existT _ 7 t
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_two t => existT _ 8 t
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__twelve_one t => existT _ 9 t
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_four t => existT _ 10 t
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_two t => existT _ 11 t
  | CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__sixteen_one t => existT _ 12 t
  end.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__g := (fun n => typ_set (get_nth_typ CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__list n)).
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__F2 (y : choice CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__list) : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__Type :=
  let (x0, t0) := y in
    (match x0 as n return  (CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__g n -> CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__Type) with
    | 0 => fun (t : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_one__Type) => CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_one t 
    | 1 => fun (t : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_two__Type) => CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__two_two t 
    | 2 => fun (t : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_one__Type) => CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_one t 
    | 3 => fun (t : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__three_two__Type) => CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__three_two t 
    | 4 => fun (t : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_one__Type) => CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_one t 
    | 5 => fun (t : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_two__Type) => CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_two t 
    | 6 => fun (t : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_one__Type) => CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_one t 
    | 7 => fun (t : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_three__Type) => CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_three t 
    | 8 => fun (t : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_two__Type) => CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__six_two t 
    | 9 => fun (t : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__twelve_one__Type) => CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__twelve_one t 
    | 10 => fun (t : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_four__Type) => CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__four_four t 
    | 11 => fun (t : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_two__Type) => CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__eight_two t 
    | 12 => fun (t : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__sixteen_one__Type) => CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__sixteen_one t 
 | (S (S (S (S (S (S (S (S (S (S (S (S (S n0))))))))))))) => (fun (x' : nat) (t'' : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__g (S (S (S (S (S (S (S (S (S (S (S (S (S x')))))))))))))) =>let t' :=
           eq_rect (get_nth_typ CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__list (S (S (S (S (S (S (S (S (S (S (S (S (S x'))))))))))))))
           (fun t' : typ => typ_set t') t'' empty_typ
           (get_nth_typ_ge_len CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__list (S (S (S (S (S (S (S (S (S (S (S (S (S x')))))))))))))
           (le_n_S _ _ (le_n_S _ _ (le_n_S _ _ (le_n_S _ _ (le_n_S _ _ (le_n_S _ _ (le_n_S _ _ (le_n_S _ _ (le_n_S _ _ (le_n_S _ _ (le_n_S _ _ (le_n_S _ _ (le_n_S _ _ (le_0_n x'))))))))))))))) in match t' return CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__Type with end) n0
           end t0).

Lemma CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__helper2 :  forall (y : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__Type), CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__cond y -> choice_cond CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__list (CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__F1 y).
  choice_helper_tact_dec y. Qed.

Lemma CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__helper3 :  forall (y : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__Type), CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__F2 (CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__F1 y) = y.
  choice_helper_tact_dec y. Qed.

Transparent length.
Lemma CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__helper4 : (forall b : choice CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__list, choice_cond CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__list b -> CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__cond (CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__F2 b) /\ CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__F1 (CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__F2 b) = b).
Proof. intros. destruct b as [x t]; split; choice_helper_tact0 H x t. Qed.
Opaque length CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__F1 CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__F2.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__Format : T_Format CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__cond :=
  (* Eval compute in *) proj2_format CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__cond CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__list__Format CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__F1 CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__F2 CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__helper2 CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__helper3 CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__helper4.
Opaque CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__cond CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__Format.

Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__typeII_RI_Restriction_r16__Format : T_Format CodebookConfig_r16__codebookType__type2__subType__typeII_r16__typeII_RI_Restriction_r16__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__typeII_RI_Restriction_r16__cond := (* Eval compute in *) bit_string_fixed_format 4.
Opaque CodebookConfig_r16__codebookType__type2__subType__typeII_r16__typeII_RI_Restriction_r16__cond CodebookConfig_r16__codebookType__type2__subType__typeII_r16__typeII_RI_Restriction_r16__Format.


Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__Format_Type := Eval cbn in seq_format_prod CodebookConfig_r16__codebookType__type2__subType__typeII_r16__list.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__Format_list : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__Format_Type :=
  (CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16__Format, (CodebookConfig_r16__codebookType__type2__subType__typeII_r16__typeII_RI_Restriction_r16__Format, unit_format)).
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__list__Format := (*Eval compute in *) seq_format CodebookConfig_r16__codebookType__type2__subType__typeII_r16__list CodebookConfig_r16__codebookType__type2__subType__typeII_r16__Format_list.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__F1 z :=
  (CodebookConfig_r16__codebookType__type2__subType__typeII_r16__n1_n2_codebookSubsetRestriction_r16 z, (CodebookConfig_r16__codebookType__type2__subType__typeII_r16__typeII_RI_Restriction_r16 z, tt)).
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__F2 (y : seq_type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__list) :=
  match y with
  | (i0, (i1, _))=>
    make__CodebookConfig_r16__codebookType__type2__subType__typeII_r16__Type i0 i1
  end.
Lemma CodebookConfig_r16__codebookType__type2__subType__typeII_r16__F1F2_cond (z : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__Type)
  : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__cond z ->
  (seq_cond CodebookConfig_r16__codebookType__type2__subType__typeII_r16__list (CodebookConfig_r16__codebookType__type2__subType__typeII_r16__F1 z)).
intro H. unfold CodebookConfig_r16__codebookType__type2__subType__typeII_r16__cond in H. simpl. auto. Qed.
Lemma CodebookConfig_r16__codebookType__type2__subType__typeII_r16__F1F2_cond2 (z : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__Type)
 : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__F2 (CodebookConfig_r16__codebookType__type2__subType__typeII_r16__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma CodebookConfig_r16__codebookType__type2__subType__typeII_r16__F2F1_cond (y : seq_type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__list)
  : seq_cond CodebookConfig_r16__codebookType__type2__subType__typeII_r16__list y ->
 (CodebookConfig_r16__codebookType__type2__subType__typeII_r16__cond (CodebookConfig_r16__codebookType__type2__subType__typeII_r16__F2 y)) /\  CodebookConfig_r16__codebookType__type2__subType__typeII_r16__F1 (CodebookConfig_r16__codebookType__type2__subType__typeII_r16__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold CodebookConfig_r16__codebookType__type2__subType__typeII_r16__cond. simpl in *. auto.
 - simpl. unfold CodebookConfig_r16__codebookType__type2__subType__typeII_r16__F1. simpl. destruct_all_unit. auto.   Qed.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_r16__Format : T_Format CodebookConfig_r16__codebookType__type2__subType__typeII_r16__Type CodebookConfig_r16__codebookType__type2__subType__typeII_r16__cond :=
        proj2_format  CodebookConfig_r16__codebookType__type2__subType__typeII_r16__cond CodebookConfig_r16__codebookType__type2__subType__typeII_r16__list__Format
    CodebookConfig_r16__codebookType__type2__subType__typeII_r16__F1 CodebookConfig_r16__codebookType__type2__subType__typeII_r16__F2 CodebookConfig_r16__codebookType__type2__subType__typeII_r16__F1F2_cond  CodebookConfig_r16__codebookType__type2__subType__typeII_r16__F1F2_cond2 CodebookConfig_r16__codebookType__type2__subType__typeII_r16__F2F1_cond.
Opaque CodebookConfig_r16__codebookType__type2__subType__typeII_r16__cond CodebookConfig_r16__codebookType__type2__subType__typeII_r16__Format.

Definition CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__Format : T_Format CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__Type (fun _ => True) :=
(* Eval compute in *) proj3_format CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__nat__Format CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__F1 CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__F2 CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__F1F2 CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__F2F1.

Opaque CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__cond CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__Format.

Definition CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__typeII_PortSelectionRI_Restriction_r16__Format : T_Format CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__typeII_PortSelectionRI_Restriction_r16__Type CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__typeII_PortSelectionRI_Restriction_r16__cond := (* Eval compute in *) bit_string_fixed_format 4.
Opaque CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__typeII_PortSelectionRI_Restriction_r16__cond CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__typeII_PortSelectionRI_Restriction_r16__Format.


Definition CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__Format_Type := Eval cbn in seq_format_prod CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__list.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__Format_list : CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__Format_Type :=
  (CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16__Format, (CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__typeII_PortSelectionRI_Restriction_r16__Format, unit_format)).
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__list__Format := (*Eval compute in *) seq_format CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__list CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__Format_list.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__F1 z :=
  (CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__portSelectionSamplingSize_r16 z, (CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__typeII_PortSelectionRI_Restriction_r16 z, tt)).
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__F2 (y : seq_type CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__list) :=
  match y with
  | (i0, (i1, _))=>
    make__CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__Type i0 i1
  end.
Lemma CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__F1F2_cond (z : CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__Type)
  : CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__cond z ->
  (seq_cond CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__list (CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__F1 z)).
intro H. unfold CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__cond in H. simpl. auto. Qed.
Lemma CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__F1F2_cond2 (z : CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__Type)
 : CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__F2 (CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__F2F1_cond (y : seq_type CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__list)
  : seq_cond CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__list y ->
 (CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__cond (CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__F2 y)) /\  CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__F1 (CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__cond. simpl in *. auto.
 - simpl. unfold CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__F1. simpl. destruct_all_unit. auto.   Qed.
Definition CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__Format : T_Format CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__Type CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__cond :=
        proj2_format  CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__cond CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__list__Format
    CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__F1 CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__F2 CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__F1F2_cond  CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__F1F2_cond2 CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__F2F1_cond.
Opaque CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__cond CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__Format.


Definition CodebookConfig_r16__codebookType__type2__subType__Format_Type := Eval cbn in get_formats CodebookConfig_r16__codebookType__type2__subType__list.
Definition CodebookConfig_r16__codebookType__type2__subType__Format_list : CodebookConfig_r16__codebookType__type2__subType__Format_Type :=
  (CodebookConfig_r16__codebookType__type2__subType__typeII_r16__Format, (CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__Format, unit__Format)).
Definition CodebookConfig_r16__codebookType__type2__subType__list__Format := Eval compute in choice_format CodebookConfig_r16__codebookType__type2__subType__list CodebookConfig_r16__codebookType__type2__subType__len_helper1 CodebookConfig_r16__codebookType__type2__subType__len_helper2  CodebookConfig_r16__codebookType__type2__subType__Format_list.
Definition CodebookConfig_r16__codebookType__type2__subType__F1 (z : CodebookConfig_r16__codebookType__type2__subType__Type) : (choice CodebookConfig_r16__codebookType__type2__subType__list) :=
  match z with
   | CodebookConfig_r16__codebookType__type2__subType__typeII_r16 t => existT _ 0 t
  | CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16 t => existT _ 1 t
  end.
Definition CodebookConfig_r16__codebookType__type2__subType__g := (fun n => typ_set (get_nth_typ CodebookConfig_r16__codebookType__type2__subType__list n)).
Definition CodebookConfig_r16__codebookType__type2__subType__F2 (y : choice CodebookConfig_r16__codebookType__type2__subType__list) : CodebookConfig_r16__codebookType__type2__subType__Type :=
  let (x0, t0) := y in
    (match x0 as n return  (CodebookConfig_r16__codebookType__type2__subType__g n -> CodebookConfig_r16__codebookType__type2__subType__Type) with
    | 0 => fun (t : CodebookConfig_r16__codebookType__type2__subType__typeII_r16__Type) => CodebookConfig_r16__codebookType__type2__subType__typeII_r16 t 
    | 1 => fun (t : CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16__Type) => CodebookConfig_r16__codebookType__type2__subType__typeII_PortSelection_r16 t 
 | (S (S n0)) => (fun (x' : nat) (t'' : CodebookConfig_r16__codebookType__type2__subType__g (S (S x'))) =>let t' :=
           eq_rect (get_nth_typ CodebookConfig_r16__codebookType__type2__subType__list (S (S x')))
           (fun t' : typ => typ_set t') t'' empty_typ
           (get_nth_typ_ge_len CodebookConfig_r16__codebookType__type2__subType__list (S (S x'))
           (le_n_S _ _ (le_n_S _ _ (le_0_n x')))) in match t' return CodebookConfig_r16__codebookType__type2__subType__Type with end) n0
           end t0).

Lemma CodebookConfig_r16__codebookType__type2__subType__helper2 :  forall (y : CodebookConfig_r16__codebookType__type2__subType__Type), CodebookConfig_r16__codebookType__type2__subType__cond y -> choice_cond CodebookConfig_r16__codebookType__type2__subType__list (CodebookConfig_r16__codebookType__type2__subType__F1 y).
  choice_helper_tact_dec y. Qed.

Lemma CodebookConfig_r16__codebookType__type2__subType__helper3 :  forall (y : CodebookConfig_r16__codebookType__type2__subType__Type), CodebookConfig_r16__codebookType__type2__subType__F2 (CodebookConfig_r16__codebookType__type2__subType__F1 y) = y.
  choice_helper_tact_dec y. Qed.

Transparent length.
Lemma CodebookConfig_r16__codebookType__type2__subType__helper4 : (forall b : choice CodebookConfig_r16__codebookType__type2__subType__list, choice_cond CodebookConfig_r16__codebookType__type2__subType__list b -> CodebookConfig_r16__codebookType__type2__subType__cond (CodebookConfig_r16__codebookType__type2__subType__F2 b) /\ CodebookConfig_r16__codebookType__type2__subType__F1 (CodebookConfig_r16__codebookType__type2__subType__F2 b) = b).
Proof. intros. destruct b as [x t]; split; choice_helper_tact0 H x t. Qed.
Opaque length CodebookConfig_r16__codebookType__type2__subType__F1 CodebookConfig_r16__codebookType__type2__subType__F2.
Definition CodebookConfig_r16__codebookType__type2__subType__Format : T_Format CodebookConfig_r16__codebookType__type2__subType__Type CodebookConfig_r16__codebookType__type2__subType__cond :=
  (* Eval compute in *) proj2_format CodebookConfig_r16__codebookType__type2__subType__cond CodebookConfig_r16__codebookType__type2__subType__list__Format CodebookConfig_r16__codebookType__type2__subType__F1 CodebookConfig_r16__codebookType__type2__subType__F2 CodebookConfig_r16__codebookType__type2__subType__helper2 CodebookConfig_r16__codebookType__type2__subType__helper3 CodebookConfig_r16__codebookType__type2__subType__helper4.
Opaque CodebookConfig_r16__codebookType__type2__subType__cond CodebookConfig_r16__codebookType__type2__subType__Format.

Definition CodebookConfig_r16__codebookType__type2__numberOfPMI_SubbandsPerCQI_Subband_r16__Format : T_Format Z CodebookConfig_r16__codebookType__type2__numberOfPMI_SubbandsPerCQI_Subband_r16__cond :=
 ranged_int_format (1) (2) CodebookConfig_r16__codebookType__type2__numberOfPMI_SubbandsPerCQI_Subband_r16__helper1 CodebookConfig_r16__codebookType__type2__numberOfPMI_SubbandsPerCQI_Subband_r16__helper2.

Opaque CodebookConfig_r16__codebookType__type2__numberOfPMI_SubbandsPerCQI_Subband_r16__cond CodebookConfig_r16__codebookType__type2__numberOfPMI_SubbandsPerCQI_Subband_r16__Format.

Definition CodebookConfig_r16__codebookType__type2__paramCombination_r16__Format : T_Format Z CodebookConfig_r16__codebookType__type2__paramCombination_r16__cond :=
 ranged_int_format (1) (8) CodebookConfig_r16__codebookType__type2__paramCombination_r16__helper1 CodebookConfig_r16__codebookType__type2__paramCombination_r16__helper2.

Opaque CodebookConfig_r16__codebookType__type2__paramCombination_r16__cond CodebookConfig_r16__codebookType__type2__paramCombination_r16__Format.


Definition CodebookConfig_r16__codebookType__type2__Format_Type := Eval cbn in seq_format_prod CodebookConfig_r16__codebookType__type2__list.
Definition CodebookConfig_r16__codebookType__type2__Format_list : CodebookConfig_r16__codebookType__type2__Format_Type :=
  (CodebookConfig_r16__codebookType__type2__subType__Format, (CodebookConfig_r16__codebookType__type2__numberOfPMI_SubbandsPerCQI_Subband_r16__Format, (CodebookConfig_r16__codebookType__type2__paramCombination_r16__Format, unit_format))).
Definition CodebookConfig_r16__codebookType__type2__list__Format := (*Eval compute in *) seq_format CodebookConfig_r16__codebookType__type2__list CodebookConfig_r16__codebookType__type2__Format_list.
Definition CodebookConfig_r16__codebookType__type2__F1 z :=
  (CodebookConfig_r16__codebookType__type2__subType z, (CodebookConfig_r16__codebookType__type2__numberOfPMI_SubbandsPerCQI_Subband_r16 z, (CodebookConfig_r16__codebookType__type2__paramCombination_r16 z, tt))).
Definition CodebookConfig_r16__codebookType__type2__F2 (y : seq_type CodebookConfig_r16__codebookType__type2__list) :=
  match y with
  | (i0, (i1, (i2, _)))=>
    make__CodebookConfig_r16__codebookType__type2__Type i0 i1 i2
  end.
Lemma CodebookConfig_r16__codebookType__type2__F1F2_cond (z : CodebookConfig_r16__codebookType__type2__Type)
  : CodebookConfig_r16__codebookType__type2__cond z ->
  (seq_cond CodebookConfig_r16__codebookType__type2__list (CodebookConfig_r16__codebookType__type2__F1 z)).
intro H. unfold CodebookConfig_r16__codebookType__type2__cond in H. simpl. auto. Qed.
Lemma CodebookConfig_r16__codebookType__type2__F1F2_cond2 (z : CodebookConfig_r16__codebookType__type2__Type)
 : CodebookConfig_r16__codebookType__type2__F2 (CodebookConfig_r16__codebookType__type2__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma CodebookConfig_r16__codebookType__type2__F2F1_cond (y : seq_type CodebookConfig_r16__codebookType__type2__list)
  : seq_cond CodebookConfig_r16__codebookType__type2__list y ->
 (CodebookConfig_r16__codebookType__type2__cond (CodebookConfig_r16__codebookType__type2__F2 y)) /\  CodebookConfig_r16__codebookType__type2__F1 (CodebookConfig_r16__codebookType__type2__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold CodebookConfig_r16__codebookType__type2__cond. simpl in *. auto.
 - simpl. unfold CodebookConfig_r16__codebookType__type2__F1. simpl. destruct_all_unit. auto.   Qed.
Definition CodebookConfig_r16__codebookType__type2__Format : T_Format CodebookConfig_r16__codebookType__type2__Type CodebookConfig_r16__codebookType__type2__cond :=
        proj2_format  CodebookConfig_r16__codebookType__type2__cond CodebookConfig_r16__codebookType__type2__list__Format
    CodebookConfig_r16__codebookType__type2__F1 CodebookConfig_r16__codebookType__type2__F2 CodebookConfig_r16__codebookType__type2__F1F2_cond  CodebookConfig_r16__codebookType__type2__F1F2_cond2 CodebookConfig_r16__codebookType__type2__F2F1_cond.
Opaque CodebookConfig_r16__codebookType__type2__cond CodebookConfig_r16__codebookType__type2__Format.

Definition CodebookConfig_r16__codebookType__F1 (z : CodebookConfig_r16__codebookType__Type) : CodebookConfig_r16__codebookType__type2__Type := 
  match z with
  | CodebookConfig_r16__codebookType__type2 t => t
  end.
Definition CodebookConfig_r16__codebookType__F2 (y : CodebookConfig_r16__codebookType__type2__Type) : CodebookConfig_r16__codebookType__Type := CodebookConfig_r16__codebookType__type2 y.

Definition CodebookConfig_r16__codebookType__helper2 : (forall z : CodebookConfig_r16__codebookType__Type, CodebookConfig_r16__codebookType__cond z -> CodebookConfig_r16__codebookType__type2__cond (CodebookConfig_r16__codebookType__F1 z)).
Proof. intros. destruct z; auto. Qed.
Definition CodebookConfig_r16__codebookType__helper3 : (forall z : CodebookConfig_r16__codebookType__Type, CodebookConfig_r16__codebookType__F2 (CodebookConfig_r16__codebookType__F1 z) = z).
Proof. intros. destruct z; auto. Qed.
Definition CodebookConfig_r16__codebookType__helper4 : (forall y : CodebookConfig_r16__codebookType__type2__Type, CodebookConfig_r16__codebookType__type2__cond y -> CodebookConfig_r16__codebookType__cond (CodebookConfig_r16__codebookType__F2 y) /\  CodebookConfig_r16__codebookType__F1 (CodebookConfig_r16__codebookType__F2 y) = y).
Proof. intros. destruct y; auto. Qed.
Definition CodebookConfig_r16__codebookType__Format : T_Format CodebookConfig_r16__codebookType__Type CodebookConfig_r16__codebookType__cond :=
  proj2_format CodebookConfig_r16__codebookType__cond CodebookConfig_r16__codebookType__type2__Format CodebookConfig_r16__codebookType__F1 CodebookConfig_r16__codebookType__F2 CodebookConfig_r16__codebookType__helper2 CodebookConfig_r16__codebookType__helper3 CodebookConfig_r16__codebookType__helper4.
Opaque CodebookConfig_r16__codebookType__cond CodebookConfig_r16__codebookType__Format.


Definition CodebookConfig_r16__Format_Type := Eval cbn in seq_format_prod CodebookConfig_r16__list.
Definition CodebookConfig_r16__Format_list : CodebookConfig_r16__Format_Type :=
  (CodebookConfig_r16__codebookType__Format, unit_format).
Definition CodebookConfig_r16__list__Format := (*Eval compute in *) seq_format CodebookConfig_r16__list CodebookConfig_r16__Format_list.
Definition CodebookConfig_r16__F1 z :=
  (CodebookConfig_r16__codebookType z, tt).
Definition CodebookConfig_r16__F2 (y : seq_type CodebookConfig_r16__list) :=
  match y with
  | (i0, _)=>
    make__CodebookConfig_r16__Type i0
  end.
Lemma CodebookConfig_r16__F1F2_cond (z : CodebookConfig_r16__Type)
  : CodebookConfig_r16__cond z ->
  (seq_cond CodebookConfig_r16__list (CodebookConfig_r16__F1 z)).
intro H. unfold CodebookConfig_r16__cond in H. simpl. auto. Qed.
Lemma CodebookConfig_r16__F1F2_cond2 (z : CodebookConfig_r16__Type)
 : CodebookConfig_r16__F2 (CodebookConfig_r16__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma CodebookConfig_r16__F2F1_cond (y : seq_type CodebookConfig_r16__list)
  : seq_cond CodebookConfig_r16__list y ->
 (CodebookConfig_r16__cond (CodebookConfig_r16__F2 y)) /\  CodebookConfig_r16__F1 (CodebookConfig_r16__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold CodebookConfig_r16__cond. simpl in *. auto.
 - simpl. unfold CodebookConfig_r16__F1. simpl. destruct_all_unit. auto.   Qed.
Definition CodebookConfig_r16__Format : T_Format CodebookConfig_r16__Type CodebookConfig_r16__cond :=
        proj2_format  CodebookConfig_r16__cond CodebookConfig_r16__list__Format
    CodebookConfig_r16__F1 CodebookConfig_r16__F2 CodebookConfig_r16__F1F2_cond  CodebookConfig_r16__F1F2_cond2 CodebookConfig_r16__F2F1_cond.
Opaque CodebookConfig_r16__cond CodebookConfig_r16__Format.

