Require Import ASN1Parser.ExtrOCaml.ExtractHelper.

Require Import NR.NR_RRC_Definitions.
Inductive CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__Type : Set :=
 | CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__supported
.
Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__cond := (fun (_ : CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__Type) => True).
Lemma CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__nat__helper.

Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__F1 t :=
  match t with
  | CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__supported => 0
  end.
Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__F2 n :=
  match n with
  | 0 => CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__supported
  | _ => CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__supported
  end.
Lemma CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__F1F2 : forall x : CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__Type, (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__F1 x <= 0) /\ CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__F2 (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__F1 x) = x. imp_solve. Qed.
Lemma CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__F2F1 : forall (y : nat) (H : y <= 0), CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__F1 (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__F2 y) = y. enum_solve H y. Qed.

Inductive CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__Type : Set :=
 | CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__supported
.
Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__cond := (fun (_ : CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__Type) => True).
Lemma CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__nat__helper.

Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__F1 t :=
  match t with
  | CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__supported => 0
  end.
Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__F2 n :=
  match n with
  | 0 => CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__supported
  | _ => CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__supported
  end.
Lemma CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__F1F2 : forall x : CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__Type, (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__F1 x <= 0) /\ CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__F2 (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__F1 x) = x. imp_solve. Qed.
Lemma CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__F2F1 : forall (y : nat) (H : y <= 0), CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__F1 (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__F2 y) = y. enum_solve H y. Qed.

Inductive CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__Type : Set :=
 | CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__supported
.
Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__cond := (fun (_ : CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__Type) => True).
Lemma CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__nat__helper.

Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__F1 t :=
  match t with
  | CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__supported => 0
  end.
Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__F2 n :=
  match n with
  | 0 => CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__supported
  | _ => CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__supported
  end.
Lemma CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__F1F2 : forall x : CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__Type, (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__F1 x <= 0) /\ CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__F2 (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__F1 x) = x. imp_solve. Qed.
Lemma CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__F2F1 : forall (y : nat) (H : y <= 0), CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__F1 (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__F2 y) = y. enum_solve H y. Qed.

Lemma CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_30kHz_r17__helper1 : (0 <= 1 <= 496)%Z.  lia. Qed.
Lemma CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_30kHz_r17__helper2 : to_bit_sz (Z.to_nat (496 - 1)) <= INT_MAX_LEN.
unfold to_bit_sz, INT_MAX_LEN. 
        assert (H : (0 <= (496 - 1))%Z). { apply Zorder.Zle_minus_le_0. apply CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_30kHz_r17__helper1. }
        assert (G := log2_same _ H). rewrite <- G.
        simpl. lia. Qed.
Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_30kHz_r17__Type := bit_string.
Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_30kHz_r17__cond := (fun z : bit_string => (1 <= Z.of_nat (fst z) <= 496)%Z /\ bit_string_len_prop (fst z) (snd z)).
Lemma CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_60kHz_r17__helper1 : (0 <= 1 <= 496)%Z.  lia. Qed.
Lemma CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_60kHz_r17__helper2 : to_bit_sz (Z.to_nat (496 - 1)) <= INT_MAX_LEN.
unfold to_bit_sz, INT_MAX_LEN. 
        assert (H : (0 <= (496 - 1))%Z). { apply Zorder.Zle_minus_le_0. apply CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_60kHz_r17__helper1. }
        assert (G := log2_same _ H). rewrite <- G.
        simpl. lia. Qed.
Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_60kHz_r17__Type := bit_string.
Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_60kHz_r17__cond := (fun z : bit_string => (1 <= Z.of_nat (fst z) <= 496)%Z /\ bit_string_len_prop (fst z) (snd z)).
Lemma CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs60kHz_60kHz_r17__helper1 : (0 <= 1 <= 496)%Z.  lia. Qed.
Lemma CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs60kHz_60kHz_r17__helper2 : to_bit_sz (Z.to_nat (496 - 1)) <= INT_MAX_LEN.
unfold to_bit_sz, INT_MAX_LEN. 
        assert (H : (0 <= (496 - 1))%Z). { apply Zorder.Zle_minus_le_0. apply CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs60kHz_60kHz_r17__helper1. }
        assert (G := log2_same _ H). rewrite <- G.
        simpl. lia. Qed.
Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs60kHz_60kHz_r17__Type := bit_string.
Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs60kHz_60kHz_r17__cond := (fun z : bit_string => (1 <= Z.of_nat (fst z) <= 496)%Z /\ bit_string_len_prop (fst z) (snd z)).
Record CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__Type : Set :=
  make__CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__Type {
    CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17 : option CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__Type ;
    CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17 : option CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__Type ;
    CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17 : option CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__Type ;
    CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_30kHz_r17 : option CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_30kHz_r17__Type ;
    CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_60kHz_r17 : option CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_60kHz_r17__Type ;
    CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs60kHz_60kHz_r17 : option CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs60kHz_60kHz_r17__Type ;
}.
Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__list := (
 Opt CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__Type CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__cond ::
 Opt CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__Type CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__cond ::
 Opt CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__Type CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__cond ::
 Opt CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_30kHz_r17__Type CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_30kHz_r17__cond ::
 Opt CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_60kHz_r17__Type CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_60kHz_r17__cond ::
 Opt CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs60kHz_60kHz_r17__Type CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs60kHz_60kHz_r17__cond ::
 nil).
Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__cond z := 
  opt_cond CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__cond (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17 z) /\
  opt_cond CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__cond (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17 z) /\
  opt_cond CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__cond (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17 z) /\
  opt_cond CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_30kHz_r17__cond (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_30kHz_r17 z) /\
  opt_cond CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_60kHz_r17__cond (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_60kHz_r17 z) /\
  opt_cond CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs60kHz_60kHz_r17__cond (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs60kHz_60kHz_r17 z) /\
  True.

Inductive CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__Type : Set :=
 | CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__val1
 | CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__val2
.
Definition CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__cond := (fun (_ : CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__Type) => True).
Lemma CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__nat__helper : to_bit_sz 1 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__nat__Format : T_Format nat (fun z => (z <= 1)) :=
  nat_enum_format 1 CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__nat__helper.

Definition CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__F1 t :=
  match t with
  | CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__val1 => 0
  | CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__val2 => 1
  end.
Definition CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__F2 n :=
  match n with
  | 0 => CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__val1
  | 1 => CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__val2
  | _ => CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__val1
  end.
Lemma CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__F1F2 : forall x : CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__Type, (CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__F1 x <= 1) /\ CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__F2 (CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__F1 x) = x. imp_solve. Qed.
Lemma CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__F2F1 : forall (y : nat) (H : y <= 1), CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__F1 (CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__F2 y) = y. enum_solve H y. Qed.

Record CrossCarrierSchedulingSCell_SpCell_r17__Type : Set :=
  make__CrossCarrierSchedulingSCell_SpCell_r17__Type {
    CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17 : CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__Type ;
    CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17 : CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__Type ;
}.
Definition CrossCarrierSchedulingSCell_SpCell_r17__list := (
 Nor CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__Type CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__cond ::
 Nor CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__Type CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__cond ::
 nil).
Definition CrossCarrierSchedulingSCell_SpCell_r17__cond z := 
  CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__cond (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17 z) /\
  CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__cond (CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17 z) /\
  True.


Opaque Byte.to_nat Byte.of_nat.
Opaque bind_parse restrict_parse proj_parse return_parse.
Opaque restrict_serialize proj_serialize sigma_serialize append_serialize proj2_serialize.

Opaque read_n_nat read_unit.
Opaque put_n_nat put_unit. 

Opaque opt_bind opt_serialize dft_serialize prepend_serialize list_serial.
Opaque opt_parse list_parse dft_parse fail_parse append_parse
  bind_parse return_parse.

Opaque Z.to_nat Z.of_nat Z.sub Z.add Z.le Z.lt Z.pow Z.opp Z.ltb.
Opaque Nat.mul Nat.shiftr Nat.shiftl Nat.div Nat.modulo Nat.leb Nat.ltb Nat.add
  Nat.sub Nat.land Nat.lor Nat.eqb  Nat.log2 Nat.pow Nat.even PeanoNat.Nat.lnot.
Opaque Compare_dec.le_dec Compare_dec.le_lt_dec ZArith_dec.Z_le_dec lt_eq_lt_dec_new. 
Opaque sumbool_and1 list_and list_and_cons list_cons_S flg_add. 

Opaque list_to_len.
   Opaque length Compare_dec.le_dec Compare_dec.lt_dec PeanoNat.Nat.eq_dec.
   Opaque bool__Format int__Format octet_string_nc__Format bit_string_nc__Format.

   Opaque ByteIdx_to_nat nat_to_ByteIdx add_opt list_bool_format normally_small_len_det_format
  get_byte_len to_parse_skip  open_typ_serialize open_typ_parse open_type_to_len.
  

Opaque seq_cond seq_ext_cond choice_cond.
Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__Format : T_Format CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__nat__Format CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__F1 CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__F2 CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__F1F2 CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__F2F1.

Opaque CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__cond CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__Format.

Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__Format : T_Format CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__nat__Format CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__F1 CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__F2 CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__F1F2 CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__F2F1.

Opaque CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__cond CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__Format.

Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__Format : T_Format CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__nat__Format CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__F1 CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__F2 CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__F1F2 CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__F2F1.

Opaque CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__cond CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__Format.

Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_30kHz_r17__Format : T_Format CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_30kHz_r17__Type CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_30kHz_r17__cond := (* Eval compute in *) bit_string_ranged_format 1 496 CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_30kHz_r17__helper1 CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_30kHz_r17__helper2.
Opaque CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_30kHz_r17__cond CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_30kHz_r17__Format.

Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_60kHz_r17__Format : T_Format CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_60kHz_r17__Type CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_60kHz_r17__cond := (* Eval compute in *) bit_string_ranged_format 1 496 CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_60kHz_r17__helper1 CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_60kHz_r17__helper2.
Opaque CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_60kHz_r17__cond CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_60kHz_r17__Format.

Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs60kHz_60kHz_r17__Format : T_Format CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs60kHz_60kHz_r17__Type CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs60kHz_60kHz_r17__cond := (* Eval compute in *) bit_string_ranged_format 1 496 CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs60kHz_60kHz_r17__helper1 CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs60kHz_60kHz_r17__helper2.
Opaque CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs60kHz_60kHz_r17__cond CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs60kHz_60kHz_r17__Format.


Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__Format_Type := Eval cbn in seq_format_prod CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__list.
Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__Format_list : CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__Format_Type :=
  (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17__Format, (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17__Format, (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17__Format, (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_30kHz_r17__Format, (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_60kHz_r17__Format, (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs60kHz_60kHz_r17__Format, unit_format)))))).
Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__list__Format := (*Eval compute in *) seq_format CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__list CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__Format_list.
Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__F1 z :=
  (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_15kHz_r17 z, (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_30kHz_r17 z, (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs15kHz_60kHz_r17 z, (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_30kHz_r17 z, (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs30kHz_60kHz_r17 z, (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__scs60kHz_60kHz_r17 z, tt)))))).
Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__F2 (y : seq_type CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__list) :=
  match y with
  | (i0, (i1, (i2, (i3, (i4, (i5, _))))))=>
    make__CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__Type i0 i1 i2 i3 i4 i5
  end.
Lemma CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__F1F2_cond (z : CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__Type)
  : CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__cond z ->
  (seq_cond CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__list (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__F1 z)).
intro H. unfold CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__cond in H. simpl. auto. Qed.
Lemma CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__F1F2_cond2 (z : CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__Type)
 : CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__F2 (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__F2F1_cond (y : seq_type CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__list)
  : seq_cond CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__list y ->
 (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__cond (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__F2 y)) /\  CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__F1 (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__cond. simpl in *. auto.
 - simpl. unfold CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__F1. simpl. destruct_all_unit. auto.   Qed.
Definition CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__Format : T_Format CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__Type CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__cond :=
        proj2_format  CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__cond CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__list__Format
    CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__F1 CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__F2 CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__F1F2_cond  CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__F1F2_cond2 CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__F2F1_cond.
Opaque CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__cond CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__Format.

Definition CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__Format : T_Format CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__nat__Format CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__F1 CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__F2 CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__F1F2 CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__F2F1.

Opaque CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__cond CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__Format.


Definition CrossCarrierSchedulingSCell_SpCell_r17__Format_Type := Eval cbn in seq_format_prod CrossCarrierSchedulingSCell_SpCell_r17__list.
Definition CrossCarrierSchedulingSCell_SpCell_r17__Format_list : CrossCarrierSchedulingSCell_SpCell_r17__Format_Type :=
  (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17__Format, (CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17__Format, unit_format)).
Definition CrossCarrierSchedulingSCell_SpCell_r17__list__Format := (*Eval compute in *) seq_format CrossCarrierSchedulingSCell_SpCell_r17__list CrossCarrierSchedulingSCell_SpCell_r17__Format_list.
Definition CrossCarrierSchedulingSCell_SpCell_r17__F1 z :=
  (CrossCarrierSchedulingSCell_SpCell_r17__supportedSCS_Combinations_r17 z, (CrossCarrierSchedulingSCell_SpCell_r17__pdcch_MonitoringOccasion_r17 z, tt)).
Definition CrossCarrierSchedulingSCell_SpCell_r17__F2 (y : seq_type CrossCarrierSchedulingSCell_SpCell_r17__list) :=
  match y with
  | (i0, (i1, _))=>
    make__CrossCarrierSchedulingSCell_SpCell_r17__Type i0 i1
  end.
Lemma CrossCarrierSchedulingSCell_SpCell_r17__F1F2_cond (z : CrossCarrierSchedulingSCell_SpCell_r17__Type)
  : CrossCarrierSchedulingSCell_SpCell_r17__cond z ->
  (seq_cond CrossCarrierSchedulingSCell_SpCell_r17__list (CrossCarrierSchedulingSCell_SpCell_r17__F1 z)).
intro H. unfold CrossCarrierSchedulingSCell_SpCell_r17__cond in H. simpl. auto. Qed.
Lemma CrossCarrierSchedulingSCell_SpCell_r17__F1F2_cond2 (z : CrossCarrierSchedulingSCell_SpCell_r17__Type)
 : CrossCarrierSchedulingSCell_SpCell_r17__F2 (CrossCarrierSchedulingSCell_SpCell_r17__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma CrossCarrierSchedulingSCell_SpCell_r17__F2F1_cond (y : seq_type CrossCarrierSchedulingSCell_SpCell_r17__list)
  : seq_cond CrossCarrierSchedulingSCell_SpCell_r17__list y ->
 (CrossCarrierSchedulingSCell_SpCell_r17__cond (CrossCarrierSchedulingSCell_SpCell_r17__F2 y)) /\  CrossCarrierSchedulingSCell_SpCell_r17__F1 (CrossCarrierSchedulingSCell_SpCell_r17__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold CrossCarrierSchedulingSCell_SpCell_r17__cond. simpl in *. auto.
 - simpl. unfold CrossCarrierSchedulingSCell_SpCell_r17__F1. simpl. destruct_all_unit. auto.   Qed.
Definition CrossCarrierSchedulingSCell_SpCell_r17__Format : T_Format CrossCarrierSchedulingSCell_SpCell_r17__Type CrossCarrierSchedulingSCell_SpCell_r17__cond :=
        proj2_format  CrossCarrierSchedulingSCell_SpCell_r17__cond CrossCarrierSchedulingSCell_SpCell_r17__list__Format
    CrossCarrierSchedulingSCell_SpCell_r17__F1 CrossCarrierSchedulingSCell_SpCell_r17__F2 CrossCarrierSchedulingSCell_SpCell_r17__F1F2_cond  CrossCarrierSchedulingSCell_SpCell_r17__F1F2_cond2 CrossCarrierSchedulingSCell_SpCell_r17__F2F1_cond.
Opaque CrossCarrierSchedulingSCell_SpCell_r17__cond CrossCarrierSchedulingSCell_SpCell_r17__Format.

