Require Import ASN1Parser.ExtrOCaml.ExtractHelper.

Require Import NR.NR_RRC_Definitions.
Inductive FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__Type : Set :=
 | FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__supported
.
Definition FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__cond := (fun (_ : FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__Type) => True).
Lemma FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__nat__helper.

Definition FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__F1 t :=
  match t with
  | FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__supported => 0
  end.
Definition FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__F2 n :=
  match n with
  | 0 => FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__supported
  | _ => FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__supported
  end.
Lemma FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__F1F2 : forall x : FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__Type, (FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__F1 x <= 0) /\ FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__F2 (FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__F1 x) = x. imp_solve. Qed.
Lemma FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__F2F1 : forall (y : nat) (H : y <= 0), FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__F1 (FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__F2 y) = y. enum_solve H y. Qed.

Inductive FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__Type : Set :=
 | FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__supported
.
Definition FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__cond := (fun (_ : FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__Type) => True).
Lemma FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__nat__helper.

Definition FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__F1 t :=
  match t with
  | FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__supported => 0
  end.
Definition FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__F2 n :=
  match n with
  | 0 => FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__supported
  | _ => FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__supported
  end.
Lemma FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__F1F2 : forall x : FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__Type, (FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__F1 x <= 0) /\ FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__F2 (FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__F1 x) = x. imp_solve. Qed.
Lemma FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__F2F1 : forall (y : nat) (H : y <= 0), FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__F1 (FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__F2 y) = y. enum_solve H y. Qed.

Inductive FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__Type : Set :=
 | FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__supported
.
Definition FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__cond := (fun (_ : FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__Type) => True).
Lemma FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__nat__helper.

Definition FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__F1 t :=
  match t with
  | FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__supported => 0
  end.
Definition FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__F2 n :=
  match n with
  | 0 => FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__supported
  | _ => FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__supported
  end.
Lemma FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__F1F2 : forall x : FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__Type, (FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__F1 x <= 0) /\ FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__F2 (FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__F1 x) = x. imp_solve. Qed.
Lemma FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__F2F1 : forall (y : nat) (H : y <= 0), FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__F1 (FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__F2 y) = y. enum_solve H y. Qed.

Inductive FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__Type : Set :=
 | FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__supported
.
Definition FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__cond := (fun (_ : FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__Type) => True).
Lemma FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__nat__helper.

Definition FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__F1 t :=
  match t with
  | FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__supported => 0
  end.
Definition FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__F2 n :=
  match n with
  | 0 => FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__supported
  | _ => FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__supported
  end.
Lemma FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__F1F2 : forall x : FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__Type, (FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__F1 x <= 0) /\ FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__F2 (FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__F1 x) = x. imp_solve. Qed.
Lemma FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__F2F1 : forall (y : nat) (H : y <= 0), FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__F1 (FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__F2 y) = y. enum_solve H y. Qed.

Lemma FeatureSetUplink_v1720__phy_PrioritizationLowPriorityDG_HighPriorityCG_r17__helper1 : (1 <= 16)%Z.  lia. Qed.
Lemma FeatureSetUplink_v1720__phy_PrioritizationLowPriorityDG_HighPriorityCG_r17__helper2 : to_bit_sz (Z.to_nat (16 - 1)) <= INT_MAX_LEN.
unfold to_bit_sz, INT_MAX_LEN. 
        assert (H : (0 <= (16 - 1))%Z). { apply Zorder.Zle_minus_le_0. apply FeatureSetUplink_v1720__phy_PrioritizationLowPriorityDG_HighPriorityCG_r17__helper1. }
        assert (G := log2_same _ H). rewrite <- G.
        simpl. lia. Qed.
Definition FeatureSetUplink_v1720__phy_PrioritizationLowPriorityDG_HighPriorityCG_r17__Type := Z.
Definition FeatureSetUplink_v1720__phy_PrioritizationLowPriorityDG_HighPriorityCG_r17__cond := (fun z => (1 <= z <= 16)%Z).
Inductive FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__Type : Set :=
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__sym0
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__sym1
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__sym2
.
Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__cond := (fun (_ : FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__Type) => True).
Lemma FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__nat__helper : to_bit_sz 2 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__nat__Format : T_Format nat (fun z => (z <= 2)) :=
  nat_enum_format 2 FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__nat__helper.

Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__F1 t :=
  match t with
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__sym0 => 0
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__sym1 => 1
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__sym2 => 2
  end.
Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__F2 n :=
  match n with
  | 0 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__sym0
  | 1 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__sym1
  | 2 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__sym2
  | _ => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__sym0
  end.
Lemma FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__F1F2 : forall x : FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__Type, (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__F1 x <= 2) /\ FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__F2 (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__F1 x) = x. imp_solve. Qed.
Lemma FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__F2F1 : forall (y : nat) (H : y <= 2), FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__F1 (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__F2 y) = y. enum_solve H y. Qed.

Inductive FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__Type : Set :=
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__sym0
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__sym1
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__sym2
.
Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__cond := (fun (_ : FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__Type) => True).
Lemma FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__nat__helper : to_bit_sz 2 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__nat__Format : T_Format nat (fun z => (z <= 2)) :=
  nat_enum_format 2 FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__nat__helper.

Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__F1 t :=
  match t with
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__sym0 => 0
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__sym1 => 1
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__sym2 => 2
  end.
Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__F2 n :=
  match n with
  | 0 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__sym0
  | 1 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__sym1
  | 2 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__sym2
  | _ => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__sym0
  end.
Lemma FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__F1F2 : forall x : FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__Type, (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__F1 x <= 2) /\ FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__F2 (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__F1 x) = x. imp_solve. Qed.
Lemma FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__F2F1 : forall (y : nat) (H : y <= 2), FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__F1 (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__F2 y) = y. enum_solve H y. Qed.

Inductive FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__Type : Set :=
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__sym0
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__sym1
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__sym2
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__sym3
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__sym4
.
Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__cond := (fun (_ : FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__Type) => True).
Lemma FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__nat__helper : to_bit_sz 4 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__nat__Format : T_Format nat (fun z => (z <= 4)) :=
  nat_enum_format 4 FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__nat__helper.

Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__F1 t :=
  match t with
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__sym0 => 0
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__sym1 => 1
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__sym2 => 2
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__sym3 => 3
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__sym4 => 4
  end.
Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__F2 n :=
  match n with
  | 0 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__sym0
  | 1 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__sym1
  | 2 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__sym2
  | 3 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__sym3
  | 4 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__sym4
  | _ => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__sym0
  end.
Lemma FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__F1F2 : forall x : FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__Type, (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__F1 x <= 4) /\ FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__F2 (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__F1 x) = x. imp_solve. Qed.
Lemma FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__F2F1 : forall (y : nat) (H : y <= 4), FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__F1 (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__F2 y) = y. enum_solve H y. Qed.

Inductive FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__Type : Set :=
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__sym0
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__sym1
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__sym2
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__sym3
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__sym4
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__sym5
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__sym6
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__sym7
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__sym8
.
Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__cond := (fun (_ : FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__Type) => True).
Lemma FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__nat__helper : to_bit_sz 8 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__nat__Format : T_Format nat (fun z => (z <= 8)) :=
  nat_enum_format 8 FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__nat__helper.

Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__F1 t :=
  match t with
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__sym0 => 0
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__sym1 => 1
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__sym2 => 2
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__sym3 => 3
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__sym4 => 4
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__sym5 => 5
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__sym6 => 6
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__sym7 => 7
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__sym8 => 8
  end.
Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__F2 n :=
  match n with
  | 0 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__sym0
  | 1 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__sym1
  | 2 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__sym2
  | 3 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__sym3
  | 4 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__sym4
  | 5 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__sym5
  | 6 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__sym6
  | 7 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__sym7
  | 8 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__sym8
  | _ => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__sym0
  end.
Lemma FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__F1F2 : forall x : FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__Type, (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__F1 x <= 8) /\ FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__F2 (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__F1 x) = x. imp_solve. Qed.
Lemma FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__F2F1 : forall (y : nat) (H : y <= 8), FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__F1 (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__F2 y) = y. enum_solve H y. Qed.

Inductive FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__Type : Set :=
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym0
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym1
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym2
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym3
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym4
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym5
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym6
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym7
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym8
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym9
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym10
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym11
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym12
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym13
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym14
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym15
 | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym16
.
Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__cond := (fun (_ : FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__Type) => True).
Lemma FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__nat__helper : to_bit_sz 16 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__nat__Format : T_Format nat (fun z => (z <= 16)) :=
  nat_enum_format 16 FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__nat__helper.

Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__F1 t :=
  match t with
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym0 => 0
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym1 => 1
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym2 => 2
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym3 => 3
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym4 => 4
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym5 => 5
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym6 => 6
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym7 => 7
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym8 => 8
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym9 => 9
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym10 => 10
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym11 => 11
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym12 => 12
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym13 => 13
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym14 => 14
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym15 => 15
  | FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym16 => 16
  end.
Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__F2 n :=
  match n with
  | 0 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym0
  | 1 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym1
  | 2 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym2
  | 3 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym3
  | 4 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym4
  | 5 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym5
  | 6 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym6
  | 7 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym7
  | 8 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym8
  | 9 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym9
  | 10 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym10
  | 11 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym11
  | 12 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym12
  | 13 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym13
  | 14 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym14
  | 15 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym15
  | 16 => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym16
  | _ => FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__sym0
  end.
Lemma FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__F1F2 : forall x : FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__Type, (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__F1 x <= 16) /\ FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__F2 (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__F1 x) = x. imp_solve. Qed.
Lemma FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__F2F1 : forall (y : nat) (H : y <= 16), FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__F1 (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__F2 y) = y. enum_solve H y. Qed.

Record FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__Type : Set :=
  make__FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__Type {
    FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17 : option FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__Type ;
    FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17 : option FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__Type ;
    FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17 : option FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__Type ;
    FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17 : option FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__Type ;
}.
Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__list := (
 Opt FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__Type FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__cond ::
 Opt FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__Type FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__cond ::
 Opt FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__Type FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__cond ::
 Opt FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__Type FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__cond ::
 nil).
Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__cond z := 
  opt_cond FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__cond (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17 z) /\
  opt_cond FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__cond (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17 z) /\
  opt_cond FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__cond (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17 z) /\
  opt_cond FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__cond (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17 z) /\
  True.

Lemma FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__maxNumberCarriers_r17__helper1 : (1 <= 16)%Z.  lia. Qed.
Lemma FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__maxNumberCarriers_r17__helper2 : to_bit_sz (Z.to_nat (16 - 1)) <= INT_MAX_LEN.
unfold to_bit_sz, INT_MAX_LEN. 
        assert (H : (0 <= (16 - 1))%Z). { apply Zorder.Zle_minus_le_0. apply FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__maxNumberCarriers_r17__helper1. }
        assert (G := log2_same _ H). rewrite <- G.
        simpl. lia. Qed.
Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__maxNumberCarriers_r17__Type := Z.
Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__maxNumberCarriers_r17__cond := (fun z => (1 <= z <= 16)%Z).
Record FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__Type : Set :=
  make__FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__Type {
    FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17 : FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__Type ;
    FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17 : FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__Type ;
    FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__maxNumberCarriers_r17 : Z ;
}.
Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__list := (
 Nor FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__Type FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__cond ::
 Nor FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__Type FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__cond ::
 Nor Z FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__maxNumberCarriers_r17__cond ::
 nil).
Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__cond z := 
  FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__cond (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17 z) /\
  FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__cond (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17 z) /\
  FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__maxNumberCarriers_r17__cond (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__maxNumberCarriers_r17 z) /\
  True.

Inductive FeatureSetUplink_v1720__extendedDC_LocationReport_r17__Type : Set :=
 | FeatureSetUplink_v1720__extendedDC_LocationReport_r17__supported
.
Definition FeatureSetUplink_v1720__extendedDC_LocationReport_r17__cond := (fun (_ : FeatureSetUplink_v1720__extendedDC_LocationReport_r17__Type) => True).
Lemma FeatureSetUplink_v1720__extendedDC_LocationReport_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition FeatureSetUplink_v1720__extendedDC_LocationReport_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 FeatureSetUplink_v1720__extendedDC_LocationReport_r17__nat__helper.

Definition FeatureSetUplink_v1720__extendedDC_LocationReport_r17__F1 t :=
  match t with
  | FeatureSetUplink_v1720__extendedDC_LocationReport_r17__supported => 0
  end.
Definition FeatureSetUplink_v1720__extendedDC_LocationReport_r17__F2 n :=
  match n with
  | 0 => FeatureSetUplink_v1720__extendedDC_LocationReport_r17__supported
  | _ => FeatureSetUplink_v1720__extendedDC_LocationReport_r17__supported
  end.
Lemma FeatureSetUplink_v1720__extendedDC_LocationReport_r17__F1F2 : forall x : FeatureSetUplink_v1720__extendedDC_LocationReport_r17__Type, (FeatureSetUplink_v1720__extendedDC_LocationReport_r17__F1 x <= 0) /\ FeatureSetUplink_v1720__extendedDC_LocationReport_r17__F2 (FeatureSetUplink_v1720__extendedDC_LocationReport_r17__F1 x) = x. imp_solve. Qed.
Lemma FeatureSetUplink_v1720__extendedDC_LocationReport_r17__F2F1 : forall (y : nat) (H : y <= 0), FeatureSetUplink_v1720__extendedDC_LocationReport_r17__F1 (FeatureSetUplink_v1720__extendedDC_LocationReport_r17__F2 y) = y. enum_solve H y. Qed.

Record FeatureSetUplink_v1720__Type : Set :=
  make__FeatureSetUplink_v1720__Type {
    FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17 : option FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__Type ;
    FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17 : option FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__Type ;
    FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17 : option FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__Type ;
    FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17 : option FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__Type ;
    FeatureSetUplink_v1720__phy_PrioritizationLowPriorityDG_HighPriorityCG_r17 : option Z ;
    FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17 : option FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__Type ;
    FeatureSetUplink_v1720__extendedDC_LocationReport_r17 : option FeatureSetUplink_v1720__extendedDC_LocationReport_r17__Type ;
}.
Definition FeatureSetUplink_v1720__list := (
 Opt FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__Type FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__cond ::
 Opt FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__Type FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__cond ::
 Opt FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__Type FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__cond ::
 Opt FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__Type FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__cond ::
 Opt Z FeatureSetUplink_v1720__phy_PrioritizationLowPriorityDG_HighPriorityCG_r17__cond ::
 Opt FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__Type FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__cond ::
 Opt FeatureSetUplink_v1720__extendedDC_LocationReport_r17__Type FeatureSetUplink_v1720__extendedDC_LocationReport_r17__cond ::
 nil).
Definition FeatureSetUplink_v1720__cond z := 
  opt_cond FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__cond (FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17 z) /\
  opt_cond FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__cond (FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17 z) /\
  opt_cond FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__cond (FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17 z) /\
  opt_cond FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__cond (FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17 z) /\
  opt_cond FeatureSetUplink_v1720__phy_PrioritizationLowPriorityDG_HighPriorityCG_r17__cond (FeatureSetUplink_v1720__phy_PrioritizationLowPriorityDG_HighPriorityCG_r17 z) /\
  opt_cond FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__cond (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17 z) /\
  opt_cond FeatureSetUplink_v1720__extendedDC_LocationReport_r17__cond (FeatureSetUplink_v1720__extendedDC_LocationReport_r17 z) /\
  True.


Opaque Byte.to_nat Byte.of_nat.
Opaque bind_parse restrict_parse proj_parse return_parse.
Opaque restrict_serialize proj_serialize sigma_serialize append_serialize proj2_serialize.

Opaque read_n_nat read_unit.
Opaque put_n_nat put_unit. 

Opaque opt_bind opt_serialize dft_serialize prepend_serialize list_serial.
Opaque opt_parse list_parse dft_parse fail_parse append_parse
  bind_parse return_parse.

Opaque Z.to_nat Z.of_nat Z.sub Z.add Z.le Z.lt Z.pow Z.opp Z.ltb.
Opaque Nat.mul Nat.shiftr Nat.shiftl Nat.div Nat.modulo Nat.leb Nat.ltb Nat.add
  Nat.sub Nat.land Nat.lor Nat.eqb  Nat.log2 Nat.pow Nat.even PeanoNat.Nat.lnot.
Opaque Compare_dec.le_dec Compare_dec.le_lt_dec ZArith_dec.Z_le_dec lt_eq_lt_dec_new. 
Opaque sumbool_and1 list_and list_and_cons list_cons_S flg_add. 

Opaque list_to_len.
   Opaque length Compare_dec.le_dec Compare_dec.lt_dec PeanoNat.Nat.eq_dec.
   Opaque bool__Format int__Format octet_string_nc__Format bit_string_nc__Format.

   Opaque ByteIdx_to_nat nat_to_ByteIdx add_opt list_bool_format normally_small_len_det_format
  get_byte_len to_parse_skip  open_typ_serialize open_typ_parse open_type_to_len.
  

Opaque seq_cond seq_ext_cond choice_cond.
Definition FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__Format : T_Format FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__nat__Format FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__F1 FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__F2 FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__F1F2 FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__F2F1.

Opaque FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__cond FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__Format.

Definition FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__Format : T_Format FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__nat__Format FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__F1 FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__F2 FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__F1F2 FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__F2F1.

Opaque FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__cond FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__Format.

Definition FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__Format : T_Format FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__nat__Format FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__F1 FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__F2 FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__F1F2 FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__F2F1.

Opaque FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__cond FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__Format.

Definition FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__Format : T_Format FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__nat__Format FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__F1 FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__F2 FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__F1F2 FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__F2F1.

Opaque FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__cond FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__Format.

Definition FeatureSetUplink_v1720__phy_PrioritizationLowPriorityDG_HighPriorityCG_r17__Format : T_Format Z FeatureSetUplink_v1720__phy_PrioritizationLowPriorityDG_HighPriorityCG_r17__cond :=
 ranged_int_format (1) (16) FeatureSetUplink_v1720__phy_PrioritizationLowPriorityDG_HighPriorityCG_r17__helper1 FeatureSetUplink_v1720__phy_PrioritizationLowPriorityDG_HighPriorityCG_r17__helper2.

Opaque FeatureSetUplink_v1720__phy_PrioritizationLowPriorityDG_HighPriorityCG_r17__cond FeatureSetUplink_v1720__phy_PrioritizationLowPriorityDG_HighPriorityCG_r17__Format.

Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__Format : T_Format FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__nat__Format FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__F1 FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__F2 FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__F1F2 FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__F2F1.

Opaque FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__cond FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__Format.

Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__Format : T_Format FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__nat__Format FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__F1 FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__F2 FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__F1F2 FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__F2F1.

Opaque FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__cond FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__Format.

Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__Format : T_Format FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__nat__Format FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__F1 FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__F2 FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__F1F2 FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__F2F1.

Opaque FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__cond FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__Format.

Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__Format : T_Format FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__nat__Format FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__F1 FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__F2 FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__F1F2 FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__F2F1.

Opaque FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__cond FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__Format.

Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__Format : T_Format FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__nat__Format FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__F1 FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__F2 FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__F1F2 FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__F2F1.

Opaque FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__cond FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__Format.


Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__Format_Type := Eval cbn in seq_format_prod FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__list.
Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__Format_list : FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__Format_Type :=
  (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17__Format, (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17__Format, (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17__Format, (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17__Format, unit_format)))).
Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__list__Format := (*Eval compute in *) seq_format FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__list FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__Format_list.
Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__F1 z :=
  (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_15kHz_r17 z, (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_30kHz_r17 z, (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_60kHz_r17 z, (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__scs_120kHz_r17 z, tt)))).
Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__F2 (y : seq_type FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__list) :=
  match y with
  | (i0, (i1, (i2, (i3, _))))=>
    make__FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__Type i0 i1 i2 i3
  end.
Lemma FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__F1F2_cond (z : FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__Type)
  : FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__cond z ->
  (seq_cond FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__list (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__F1 z)).
intro H. unfold FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__cond in H. simpl. auto. Qed.
Lemma FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__F1F2_cond2 (z : FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__Type)
 : FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__F2 (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__F2F1_cond (y : seq_type FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__list)
  : seq_cond FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__list y ->
 (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__cond (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__F2 y)) /\  FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__F1 (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__cond. simpl in *. auto.
 - simpl. unfold FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__F1. simpl. destruct_all_unit. auto.   Qed.
Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__Format : T_Format FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__Type FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__cond :=
        proj2_format  FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__cond FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__list__Format
    FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__F1 FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__F2 FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__F1F2_cond  FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__F1F2_cond2 FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__F2F1_cond.
Opaque FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__cond FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__Format.

Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__maxNumberCarriers_r17__Format : T_Format Z FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__maxNumberCarriers_r17__cond :=
 ranged_int_format (1) (16) FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__maxNumberCarriers_r17__helper1 FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__maxNumberCarriers_r17__helper2.

Opaque FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__maxNumberCarriers_r17__cond FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__maxNumberCarriers_r17__Format.


Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__Format_Type := Eval cbn in seq_format_prod FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__list.
Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__Format_list : FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__Format_Type :=
  (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17__Format, (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17__Format, (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__maxNumberCarriers_r17__Format, unit_format))).
Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__list__Format := (*Eval compute in *) seq_format FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__list FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__Format_list.
Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__F1 z :=
  (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__pusch_PreparationLowPriority_r17 z, (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__additionalCancellationTime_r17 z, (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__maxNumberCarriers_r17 z, tt))).
Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__F2 (y : seq_type FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__list) :=
  match y with
  | (i0, (i1, (i2, _)))=>
    make__FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__Type i0 i1 i2
  end.
Lemma FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__F1F2_cond (z : FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__Type)
  : FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__cond z ->
  (seq_cond FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__list (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__F1 z)).
intro H. unfold FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__cond in H. simpl. auto. Qed.
Lemma FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__F1F2_cond2 (z : FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__Type)
 : FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__F2 (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__F2F1_cond (y : seq_type FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__list)
  : seq_cond FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__list y ->
 (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__cond (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__F2 y)) /\  FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__F1 (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__cond. simpl in *. auto.
 - simpl. unfold FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__F1. simpl. destruct_all_unit. auto.   Qed.
Definition FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__Format : T_Format FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__Type FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__cond :=
        proj2_format  FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__cond FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__list__Format
    FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__F1 FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__F2 FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__F1F2_cond  FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__F1F2_cond2 FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__F2F1_cond.
Opaque FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__cond FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__Format.

Definition FeatureSetUplink_v1720__extendedDC_LocationReport_r17__Format : T_Format FeatureSetUplink_v1720__extendedDC_LocationReport_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format FeatureSetUplink_v1720__extendedDC_LocationReport_r17__nat__Format FeatureSetUplink_v1720__extendedDC_LocationReport_r17__F1 FeatureSetUplink_v1720__extendedDC_LocationReport_r17__F2 FeatureSetUplink_v1720__extendedDC_LocationReport_r17__F1F2 FeatureSetUplink_v1720__extendedDC_LocationReport_r17__F2F1.

Opaque FeatureSetUplink_v1720__extendedDC_LocationReport_r17__cond FeatureSetUplink_v1720__extendedDC_LocationReport_r17__Format.


Definition FeatureSetUplink_v1720__Format_Type := Eval cbn in seq_format_prod FeatureSetUplink_v1720__list.
Definition FeatureSetUplink_v1720__Format_list : FeatureSetUplink_v1720__Format_Type :=
  (FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17__Format, (FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17__Format, (FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17__Format, (FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17__Format, (FeatureSetUplink_v1720__phy_PrioritizationLowPriorityDG_HighPriorityCG_r17__Format, (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17__Format, (FeatureSetUplink_v1720__extendedDC_LocationReport_r17__Format, unit_format))))))).
Definition FeatureSetUplink_v1720__list__Format := (*Eval compute in *) seq_format FeatureSetUplink_v1720__list FeatureSetUplink_v1720__Format_list.
Definition FeatureSetUplink_v1720__F1 z :=
  (FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_RRC_Config_r17 z, (FeatureSetUplink_v1720__pucch_Repetition_F0_1_2_3_4_DynamicIndication_r17 z, (FeatureSetUplink_v1720__interSubslotFreqHopping_PUCCH_r17 z, (FeatureSetUplink_v1720__semiStaticHARQ_ACK_CodebookSub_SlotPUCCH_r17 z, (FeatureSetUplink_v1720__phy_PrioritizationLowPriorityDG_HighPriorityCG_r17 z, (FeatureSetUplink_v1720__phy_PrioritizationHighPriorityDG_LowPriorityCG_r17 z, (FeatureSetUplink_v1720__extendedDC_LocationReport_r17 z, tt))))))).
Definition FeatureSetUplink_v1720__F2 (y : seq_type FeatureSetUplink_v1720__list) :=
  match y with
  | (i0, (i1, (i2, (i3, (i4, (i5, (i6, _)))))))=>
    make__FeatureSetUplink_v1720__Type i0 i1 i2 i3 i4 i5 i6
  end.
Lemma FeatureSetUplink_v1720__F1F2_cond (z : FeatureSetUplink_v1720__Type)
  : FeatureSetUplink_v1720__cond z ->
  (seq_cond FeatureSetUplink_v1720__list (FeatureSetUplink_v1720__F1 z)).
intro H. unfold FeatureSetUplink_v1720__cond in H. simpl. auto. Qed.
Lemma FeatureSetUplink_v1720__F1F2_cond2 (z : FeatureSetUplink_v1720__Type)
 : FeatureSetUplink_v1720__F2 (FeatureSetUplink_v1720__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma FeatureSetUplink_v1720__F2F1_cond (y : seq_type FeatureSetUplink_v1720__list)
  : seq_cond FeatureSetUplink_v1720__list y ->
 (FeatureSetUplink_v1720__cond (FeatureSetUplink_v1720__F2 y)) /\  FeatureSetUplink_v1720__F1 (FeatureSetUplink_v1720__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold FeatureSetUplink_v1720__cond. simpl in *. auto.
 - simpl. unfold FeatureSetUplink_v1720__F1. simpl. destruct_all_unit. auto.   Qed.
Definition FeatureSetUplink_v1720__Format : T_Format FeatureSetUplink_v1720__Type FeatureSetUplink_v1720__cond :=
        proj2_format  FeatureSetUplink_v1720__cond FeatureSetUplink_v1720__list__Format
    FeatureSetUplink_v1720__F1 FeatureSetUplink_v1720__F2 FeatureSetUplink_v1720__F1F2_cond  FeatureSetUplink_v1720__F1F2_cond2 FeatureSetUplink_v1720__F2F1_cond.
Opaque FeatureSetUplink_v1720__cond FeatureSetUplink_v1720__Format.

