Require Import ASN1Parser.ExtrOCaml.ExtractHelper.

Require Import NR.NR_RRC_Definitions.
Inductive MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__Type : Set :=
 | MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__supported
.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__cond := (fun (_ : MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__Type) => True).
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__nat__helper.

Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__F1 t :=
  match t with
  | MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__supported => 0
  end.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__F2 n :=
  match n with
  | 0 => MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__supported
  | _ => MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__supported
  end.
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__F1F2 : forall x : MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__Type, (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__F1 x <= 0) /\ MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__F2 (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__F1 x) = x. imp_solve. Qed.
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__F2F1 : forall (y : nat) (H : y <= 0), MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__F1 (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__F2 y) = y. enum_solve H y. Qed.

Inductive MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__Type : Set :=
 | MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__supported
.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__cond := (fun (_ : MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__Type) => True).
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__nat__helper.

Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__F1 t :=
  match t with
  | MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__supported => 0
  end.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__F2 n :=
  match n with
  | 0 => MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__supported
  | _ => MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__supported
  end.
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__F1F2 : forall x : MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__Type, (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__F1 x <= 0) /\ MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__F2 (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__F1 x) = x. imp_solve. Qed.
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__F2F1 : forall (y : nat) (H : y <= 0), MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__F1 (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__F2 y) = y. enum_solve H y. Qed.

Inductive MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__Type : Set :=
 | MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__supported
.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__cond := (fun (_ : MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__Type) => True).
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__nat__helper.

Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__F1 t :=
  match t with
  | MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__supported => 0
  end.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__F2 n :=
  match n with
  | 0 => MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__supported
  | _ => MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__supported
  end.
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__F1F2 : forall x : MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__Type, (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__F1 x <= 0) /\ MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__F2 (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__F1 x) = x. imp_solve. Qed.
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__F2F1 : forall (y : nat) (H : y <= 0), MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__F1 (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__F2 y) = y. enum_solve H y. Qed.

Inductive MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__Type : Set :=
 | MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__supported
.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__cond := (fun (_ : MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__Type) => True).
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__nat__helper.

Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__F1 t :=
  match t with
  | MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__supported => 0
  end.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__F2 n :=
  match n with
  | 0 => MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__supported
  | _ => MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__supported
  end.
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__F1F2 : forall x : MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__Type, (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__F1 x <= 0) /\ MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__F2 (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__F1 x) = x. imp_solve. Qed.
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__F2F1 : forall (y : nat) (H : y <= 0), MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__F1 (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__F2 y) = y. enum_solve H y. Qed.

Inductive MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__Type : Set :=
 | MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__supported
.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__cond := (fun (_ : MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__Type) => True).
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__nat__helper.

Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__F1 t :=
  match t with
  | MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__supported => 0
  end.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__F2 n :=
  match n with
  | 0 => MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__supported
  | _ => MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__supported
  end.
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__F1F2 : forall x : MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__Type, (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__F1 x <= 0) /\ MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__F2 (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__F1 x) = x. imp_solve. Qed.
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__F2F1 : forall (y : nat) (H : y <= 0), MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__F1 (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__F2 y) = y. enum_solve H y. Qed.

Inductive MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__Type : Set :=
 | MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__supported
.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__cond := (fun (_ : MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__Type) => True).
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__nat__helper.

Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__F1 t :=
  match t with
  | MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__supported => 0
  end.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__F2 n :=
  match n with
  | 0 => MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__supported
  | _ => MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__supported
  end.
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__F1F2 : forall x : MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__Type, (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__F1 x <= 0) /\ MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__F2 (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__F1 x) = x. imp_solve. Qed.
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__F2F1 : forall (y : nat) (H : y <= 0), MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__F1 (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__F2 y) = y. enum_solve H y. Qed.

Inductive MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__Type : Set :=
 | MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__supported
.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__cond := (fun (_ : MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__Type) => True).
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__nat__helper.

Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__F1 t :=
  match t with
  | MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__supported => 0
  end.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__F2 n :=
  match n with
  | 0 => MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__supported
  | _ => MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__supported
  end.
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__F1F2 : forall x : MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__Type, (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__F1 x <= 0) /\ MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__F2 (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__F1 x) = x. imp_solve. Qed.
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__F2F1 : forall (y : nat) (H : y <= 0), MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__F1 (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__F2 y) = y. enum_solve H y. Qed.

Inductive MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__Type : Set :=
 | MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__supported
.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__cond := (fun (_ : MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__Type) => True).
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__nat__helper.

Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__F1 t :=
  match t with
  | MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__supported => 0
  end.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__F2 n :=
  match n with
  | 0 => MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__supported
  | _ => MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__supported
  end.
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__F1F2 : forall x : MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__Type, (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__F1 x <= 0) /\ MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__F2 (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__F1 x) = x. imp_solve. Qed.
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__F2F1 : forall (y : nat) (H : y <= 0), MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__F1 (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__F2 y) = y. enum_solve H y. Qed.

Inductive MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__Type : Set :=
 | MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__supported
.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__cond := (fun (_ : MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__Type) => True).
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__nat__helper.

Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__F1 t :=
  match t with
  | MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__supported => 0
  end.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__F2 n :=
  match n with
  | 0 => MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__supported
  | _ => MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__supported
  end.
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__F1F2 : forall x : MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__Type, (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__F1 x <= 0) /\ MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__F2 (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__F1 x) = x. imp_solve. Qed.
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__F2F1 : forall (y : nat) (H : y <= 0), MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__F1 (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__F2 y) = y. enum_solve H y. Qed.

Inductive MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__Type : Set :=
 | MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__supported
.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__cond := (fun (_ : MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__Type) => True).
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__nat__helper.

Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__F1 t :=
  match t with
  | MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__supported => 0
  end.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__F2 n :=
  match n with
  | 0 => MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__supported
  | _ => MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__supported
  end.
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__F1F2 : forall x : MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__Type, (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__F1 x <= 0) /\ MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__F2 (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__F1 x) = x. imp_solve. Qed.
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__F2F1 : forall (y : nat) (H : y <= 0), MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__F1 (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__F2 y) = y. enum_solve H y. Qed.

Record MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__Type : Set :=
  make__MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__Type {
    MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17 : option MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__Type ;
    MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17 : option MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__Type ;
    MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17 : option MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__Type ;
    MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17 : option MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__Type ;
    MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17 : option MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__Type ;
    MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17 : option MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__Type ;
    MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17 : option MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__Type ;
    MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17 : option MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__Type ;
    MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17 : option MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__Type ;
    MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17 : option MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__Type ;
}.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__list := (
 Opt MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__Type MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__cond ::
 Opt MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__Type MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__cond ::
 Opt MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__Type MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__cond ::
 Opt MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__Type MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__cond ::
 Opt MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__Type MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__cond ::
 Opt MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__Type MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__cond ::
 Opt MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__Type MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__cond ::
 Opt MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__Type MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__cond ::
 Opt MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__Type MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__cond ::
 Opt MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__Type MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__cond ::
 nil).
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__cond z := 
  opt_cond MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__cond (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17 z) /\
  opt_cond MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__cond (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17 z) /\
  opt_cond MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__cond (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17 z) /\
  opt_cond MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__cond (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17 z) /\
  opt_cond MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__cond (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17 z) /\
  opt_cond MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__cond (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17 z) /\
  opt_cond MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__cond (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17 z) /\
  opt_cond MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__cond (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17 z) /\
  opt_cond MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__cond (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17 z) /\
  opt_cond MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__cond (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17 z) /\
  True.

Inductive MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__Type : Set :=
 | MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__supported
.
Definition MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__cond := (fun (_ : MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__Type) => True).
Lemma MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__nat__helper.

Definition MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__F1 t :=
  match t with
  | MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__supported => 0
  end.
Definition MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__F2 n :=
  match n with
  | 0 => MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__supported
  | _ => MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__supported
  end.
Lemma MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__F1F2 : forall x : MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__Type, (MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__F1 x <= 0) /\ MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__F2 (MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__F1 x) = x. imp_solve. Qed.
Lemma MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__F2F1 : forall (y : nat) (H : y <= 0), MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__F1 (MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__F2 y) = y. enum_solve H y. Qed.

Inductive MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__Type : Set :=
 | MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__supported
.
Definition MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__cond := (fun (_ : MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__Type) => True).
Lemma MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__nat__helper.

Definition MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__F1 t :=
  match t with
  | MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__supported => 0
  end.
Definition MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__F2 n :=
  match n with
  | 0 => MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__supported
  | _ => MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__supported
  end.
Lemma MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__F1F2 : forall x : MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__Type, (MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__F1 x <= 0) /\ MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__F2 (MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__F1 x) = x. imp_solve. Qed.
Lemma MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__F2F1 : forall (y : nat) (H : y <= 0), MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__F1 (MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__F2 y) = y. enum_solve H y. Qed.

Record MeasAndMobParametersMRDC_Common_v1700__Type : Set :=
  make__MeasAndMobParametersMRDC_Common_v1700__Type {
    MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17 : option MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__Type ;
    MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17 : option MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__Type ;
    MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17 : option MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__Type ;
}.
Definition MeasAndMobParametersMRDC_Common_v1700__list := (
 Opt MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__Type MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__cond ::
 Opt MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__Type MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__cond ::
 Opt MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__Type MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__cond ::
 nil).
Definition MeasAndMobParametersMRDC_Common_v1700__cond z := 
  opt_cond MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__cond (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17 z) /\
  opt_cond MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__cond (MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17 z) /\
  opt_cond MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__cond (MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17 z) /\
  True.


Opaque Byte.to_nat Byte.of_nat.
Opaque bind_parse restrict_parse proj_parse return_parse.
Opaque restrict_serialize proj_serialize sigma_serialize append_serialize proj2_serialize.

Opaque read_n_nat read_unit.
Opaque put_n_nat put_unit. 

Opaque opt_bind opt_serialize dft_serialize prepend_serialize list_serial.
Opaque opt_parse list_parse dft_parse fail_parse append_parse
  bind_parse return_parse.

Opaque Z.to_nat Z.of_nat Z.sub Z.add Z.le Z.lt Z.pow Z.opp Z.ltb.
Opaque Nat.mul Nat.shiftr Nat.shiftl Nat.div Nat.modulo Nat.leb Nat.ltb Nat.add
  Nat.sub Nat.land Nat.lor Nat.eqb  Nat.log2 Nat.pow Nat.even PeanoNat.Nat.lnot.
Opaque Compare_dec.le_dec Compare_dec.le_lt_dec ZArith_dec.Z_le_dec lt_eq_lt_dec_new. 
Opaque sumbool_and1 list_and list_and_cons list_cons_S flg_add. 

Opaque list_to_len.
   Opaque length Compare_dec.le_dec Compare_dec.lt_dec PeanoNat.Nat.eq_dec.
   Opaque bool__Format int__Format octet_string_nc__Format bit_string_nc__Format.

   Opaque ByteIdx_to_nat nat_to_ByteIdx add_opt list_bool_format normally_small_len_det_format
  get_byte_len to_parse_skip  open_typ_serialize open_typ_parse open_type_to_len.
  

Opaque seq_cond seq_ext_cond choice_cond.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__Format : T_Format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__nat__Format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__F1 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__F2 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__F1F2 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__F2F1.

Opaque MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__cond MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__Format.

Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__Format : T_Format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__nat__Format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__F1 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__F2 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__F1F2 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__F2F1.

Opaque MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__cond MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__Format.

Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__Format : T_Format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__nat__Format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__F1 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__F2 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__F1F2 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__F2F1.

Opaque MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__cond MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__Format.

Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__Format : T_Format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__nat__Format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__F1 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__F2 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__F1F2 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__F2F1.

Opaque MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__cond MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__Format.

Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__Format : T_Format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__nat__Format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__F1 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__F2 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__F1F2 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__F2F1.

Opaque MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__cond MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__Format.

Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__Format : T_Format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__nat__Format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__F1 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__F2 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__F1F2 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__F2F1.

Opaque MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__cond MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__Format.

Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__Format : T_Format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__nat__Format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__F1 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__F2 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__F1F2 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__F2F1.

Opaque MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__cond MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__Format.

Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__Format : T_Format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__nat__Format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__F1 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__F2 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__F1F2 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__F2F1.

Opaque MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__cond MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__Format.

Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__Format : T_Format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__nat__Format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__F1 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__F2 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__F1F2 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__F2F1.

Opaque MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__cond MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__Format.

Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__Format : T_Format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__nat__Format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__F1 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__F2 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__F1F2 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__F2F1.

Opaque MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__cond MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__Format.


Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__Format_Type := Eval cbn in seq_format_prod MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__list.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__Format_list : MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__Format_Type :=
  (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17__Format, (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17__Format, (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17__Format, (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17__Format, (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__Format, (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__Format, (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__Format, (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17__Format, (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17__Format, (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17__Format, unit_format)))))))))).
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__list__Format := (*Eval compute in *) seq_format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__list MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__Format_list.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__F1 z :=
  (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_NRDC_r17 z, (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_NRDC_r17 z, (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFDD_TDD_ENDC_r17 z, (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__inter_SN_condPSCellChangeFR1_FR2_ENDC_r17 z, (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17 z, (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17 z, (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__mn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17 z, (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1FDD_ENDC_r17 z, (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR1TDD_ENDC_r17 z, (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__sn_InitiatedCondPSCellChange_FR2TDD_ENDC_r17 z, tt)))))))))).
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__F2 (y : seq_type MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__list) :=
  match y with
  | (i0, (i1, (i2, (i3, (i4, (i5, (i6, (i7, (i8, (i9, _))))))))))=>
    make__MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__Type i0 i1 i2 i3 i4 i5 i6 i7 i8 i9
  end.
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__F1F2_cond (z : MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__Type)
  : MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__cond z ->
  (seq_cond MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__list (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__F1 z)).
intro H. unfold MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__cond in H. simpl. auto. Qed.
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__F1F2_cond2 (z : MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__Type)
 : MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__F2 (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__F2F1_cond (y : seq_type MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__list)
  : seq_cond MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__list y ->
 (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__cond (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__F2 y)) /\  MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__F1 (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__cond. simpl in *. auto.
 - simpl. unfold MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__F1. simpl. destruct_all_unit. auto.   Qed.
Definition MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__Format : T_Format MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__Type MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__cond :=
        proj2_format  MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__cond MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__list__Format
    MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__F1 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__F2 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__F1F2_cond  MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__F1F2_cond2 MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__F2F1_cond.
Opaque MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__cond MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__Format.

Definition MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__Format : T_Format MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__nat__Format MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__F1 MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__F2 MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__F1F2 MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__F2F1.

Opaque MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__cond MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__Format.

Definition MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__Format : T_Format MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__nat__Format MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__F1 MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__F2 MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__F1F2 MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__F2F1.

Opaque MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__cond MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__Format.


Definition MeasAndMobParametersMRDC_Common_v1700__Format_Type := Eval cbn in seq_format_prod MeasAndMobParametersMRDC_Common_v1700__list.
Definition MeasAndMobParametersMRDC_Common_v1700__Format_list : MeasAndMobParametersMRDC_Common_v1700__Format_Type :=
  (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17__Format, (MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17__Format, (MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17__Format, unit_format))).
Definition MeasAndMobParametersMRDC_Common_v1700__list__Format := (*Eval compute in *) seq_format MeasAndMobParametersMRDC_Common_v1700__list MeasAndMobParametersMRDC_Common_v1700__Format_list.
Definition MeasAndMobParametersMRDC_Common_v1700__F1 z :=
  (MeasAndMobParametersMRDC_Common_v1700__condPSCellChangeParameters_r17 z, (MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_ENDC_r17 z, (MeasAndMobParametersMRDC_Common_v1700__condHandoverWithSCG_NEDC_r17 z, tt))).
Definition MeasAndMobParametersMRDC_Common_v1700__F2 (y : seq_type MeasAndMobParametersMRDC_Common_v1700__list) :=
  match y with
  | (i0, (i1, (i2, _)))=>
    make__MeasAndMobParametersMRDC_Common_v1700__Type i0 i1 i2
  end.
Lemma MeasAndMobParametersMRDC_Common_v1700__F1F2_cond (z : MeasAndMobParametersMRDC_Common_v1700__Type)
  : MeasAndMobParametersMRDC_Common_v1700__cond z ->
  (seq_cond MeasAndMobParametersMRDC_Common_v1700__list (MeasAndMobParametersMRDC_Common_v1700__F1 z)).
intro H. unfold MeasAndMobParametersMRDC_Common_v1700__cond in H. simpl. auto. Qed.
Lemma MeasAndMobParametersMRDC_Common_v1700__F1F2_cond2 (z : MeasAndMobParametersMRDC_Common_v1700__Type)
 : MeasAndMobParametersMRDC_Common_v1700__F2 (MeasAndMobParametersMRDC_Common_v1700__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma MeasAndMobParametersMRDC_Common_v1700__F2F1_cond (y : seq_type MeasAndMobParametersMRDC_Common_v1700__list)
  : seq_cond MeasAndMobParametersMRDC_Common_v1700__list y ->
 (MeasAndMobParametersMRDC_Common_v1700__cond (MeasAndMobParametersMRDC_Common_v1700__F2 y)) /\  MeasAndMobParametersMRDC_Common_v1700__F1 (MeasAndMobParametersMRDC_Common_v1700__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold MeasAndMobParametersMRDC_Common_v1700__cond. simpl in *. auto.
 - simpl. unfold MeasAndMobParametersMRDC_Common_v1700__F1. simpl. destruct_all_unit. auto.   Qed.
Definition MeasAndMobParametersMRDC_Common_v1700__Format : T_Format MeasAndMobParametersMRDC_Common_v1700__Type MeasAndMobParametersMRDC_Common_v1700__cond :=
        proj2_format  MeasAndMobParametersMRDC_Common_v1700__cond MeasAndMobParametersMRDC_Common_v1700__list__Format
    MeasAndMobParametersMRDC_Common_v1700__F1 MeasAndMobParametersMRDC_Common_v1700__F2 MeasAndMobParametersMRDC_Common_v1700__F1F2_cond  MeasAndMobParametersMRDC_Common_v1700__F1F2_cond2 MeasAndMobParametersMRDC_Common_v1700__F2F1_cond.
Opaque MeasAndMobParametersMRDC_Common_v1700__cond MeasAndMobParametersMRDC_Common_v1700__Format.

