Require Import ASN1Parser.ExtrOCaml.ExtractHelper.

Require Import NR.NR_RRC_Definitions.
Inductive MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__Type : Set :=
 | MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__sl8
 | MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__sl16
 | MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__sl32
 | MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__sl48
.
Definition MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__cond := (fun (_ : MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__Type) => True).
Lemma MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__nat__helper : to_bit_sz 3 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__nat__Format : T_Format nat (fun z => (z <= 3)) :=
  nat_enum_format 3 MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__nat__helper.

Definition MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__F1 t :=
  match t with
  | MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__sl8 => 0
  | MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__sl16 => 1
  | MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__sl32 => 2
  | MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__sl48 => 3
  end.
Definition MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__F2 n :=
  match n with
  | 0 => MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__sl8
  | 1 => MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__sl16
  | 2 => MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__sl32
  | 3 => MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__sl48
  | _ => MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__sl8
  end.
Lemma MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__F1F2 : forall x : MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__Type, (MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__F1 x <= 3) /\ MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__F2 (MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__F1 x) = x. imp_solve. Qed.
Lemma MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__F2F1 : forall (y : nat) (H : y <= 3), MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__F1 (MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__F2 y) = y. enum_solve H y. Qed.

Inductive MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__Type : Set :=
 | MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__sl8
 | MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__sl16
 | MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__sl32
 | MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__sl48
.
Definition MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__cond := (fun (_ : MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__Type) => True).
Lemma MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__nat__helper : to_bit_sz 3 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__nat__Format : T_Format nat (fun z => (z <= 3)) :=
  nat_enum_format 3 MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__nat__helper.

Definition MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__F1 t :=
  match t with
  | MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__sl8 => 0
  | MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__sl16 => 1
  | MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__sl32 => 2
  | MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__sl48 => 3
  end.
Definition MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__F2 n :=
  match n with
  | 0 => MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__sl8
  | 1 => MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__sl16
  | 2 => MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__sl32
  | 3 => MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__sl48
  | _ => MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__sl8
  end.
Lemma MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__F1F2 : forall x : MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__Type, (MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__F1 x <= 3) /\ MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__F2 (MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__F1 x) = x. imp_solve. Qed.
Lemma MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__F2F1 : forall (y : nat) (H : y <= 3), MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__F1 (MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__F2 y) = y. enum_solve H y. Qed.

Record MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__Type : Set :=
  make__MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__Type {
    MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17 : option MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__Type ;
    MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17 : option MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__Type ;
}.
Definition MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__list := (
 Opt MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__Type MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__cond ::
 Opt MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__Type MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__cond ::
 nil).
Definition MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__cond z := 
  opt_cond MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__cond (MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17 z) /\
  opt_cond MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__cond (MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17 z) /\
  True.

Inductive MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__Type : Set :=
 | MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__sl8
 | MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__sl16
 | MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__sl32
 | MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__sl48
.
Definition MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__cond := (fun (_ : MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__Type) => True).
Lemma MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__nat__helper : to_bit_sz 3 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__nat__Format : T_Format nat (fun z => (z <= 3)) :=
  nat_enum_format 3 MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__nat__helper.

Definition MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__F1 t :=
  match t with
  | MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__sl8 => 0
  | MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__sl16 => 1
  | MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__sl32 => 2
  | MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__sl48 => 3
  end.
Definition MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__F2 n :=
  match n with
  | 0 => MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__sl8
  | 1 => MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__sl16
  | 2 => MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__sl32
  | 3 => MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__sl48
  | _ => MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__sl8
  end.
Lemma MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__F1F2 : forall x : MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__Type, (MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__F1 x <= 3) /\ MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__F2 (MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__F1 x) = x. imp_solve. Qed.
Lemma MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__F2F1 : forall (y : nat) (H : y <= 3), MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__F1 (MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__F2 y) = y. enum_solve H y. Qed.

Inductive MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__Type : Set :=
 | MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__sl8
 | MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__sl16
 | MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__sl32
 | MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__sl48
.
Definition MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__cond := (fun (_ : MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__Type) => True).
Lemma MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__nat__helper : to_bit_sz 3 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__nat__Format : T_Format nat (fun z => (z <= 3)) :=
  nat_enum_format 3 MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__nat__helper.

Definition MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__F1 t :=
  match t with
  | MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__sl8 => 0
  | MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__sl16 => 1
  | MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__sl32 => 2
  | MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__sl48 => 3
  end.
Definition MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__F2 n :=
  match n with
  | 0 => MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__sl8
  | 1 => MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__sl16
  | 2 => MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__sl32
  | 3 => MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__sl48
  | _ => MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__sl8
  end.
Lemma MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__F1F2 : forall x : MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__Type, (MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__F1 x <= 3) /\ MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__F2 (MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__F1 x) = x. imp_solve. Qed.
Lemma MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__F2F1 : forall (y : nat) (H : y <= 3), MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__F1 (MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__F2 y) = y. enum_solve H y. Qed.

Record MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__Type : Set :=
  make__MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__Type {
    MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17 : option MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__Type ;
    MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17 : option MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__Type ;
}.
Definition MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__list := (
 Opt MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__Type MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__cond ::
 Opt MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__Type MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__cond ::
 nil).
Definition MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__cond z := 
  opt_cond MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__cond (MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17 z) /\
  opt_cond MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__cond (MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17 z) /\
  True.

Record MinSchedulingOffsetPreferenceExt_r17__Type : Set :=
  make__MinSchedulingOffsetPreferenceExt_r17__Type {
    MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17 : option MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__Type ;
    MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17 : option MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__Type ;
}.
Definition MinSchedulingOffsetPreferenceExt_r17__list := (
 Opt MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__Type MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__cond ::
 Opt MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__Type MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__cond ::
 nil).
Definition MinSchedulingOffsetPreferenceExt_r17__cond z := 
  opt_cond MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__cond (MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17 z) /\
  opt_cond MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__cond (MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17 z) /\
  True.


Opaque Byte.to_nat Byte.of_nat.
Opaque bind_parse restrict_parse proj_parse return_parse.
Opaque restrict_serialize proj_serialize sigma_serialize append_serialize proj2_serialize.

Opaque read_n_nat read_unit.
Opaque put_n_nat put_unit. 

Opaque opt_bind opt_serialize dft_serialize prepend_serialize list_serial.
Opaque opt_parse list_parse dft_parse fail_parse append_parse
  bind_parse return_parse.

Opaque Z.to_nat Z.of_nat Z.sub Z.add Z.le Z.lt Z.pow Z.opp Z.ltb.
Opaque Nat.mul Nat.shiftr Nat.shiftl Nat.div Nat.modulo Nat.leb Nat.ltb Nat.add
  Nat.sub Nat.land Nat.lor Nat.eqb  Nat.log2 Nat.pow Nat.even PeanoNat.Nat.lnot.
Opaque Compare_dec.le_dec Compare_dec.le_lt_dec ZArith_dec.Z_le_dec lt_eq_lt_dec_new. 
Opaque sumbool_and1 list_and list_and_cons list_cons_S flg_add. 

Opaque list_to_len.
   Opaque length Compare_dec.le_dec Compare_dec.lt_dec PeanoNat.Nat.eq_dec.
   Opaque bool__Format int__Format octet_string_nc__Format bit_string_nc__Format.

   Opaque ByteIdx_to_nat nat_to_ByteIdx add_opt list_bool_format normally_small_len_det_format
  get_byte_len to_parse_skip  open_typ_serialize open_typ_parse open_type_to_len.
  

Opaque seq_cond seq_ext_cond choice_cond.
Definition MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__Format : T_Format MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__nat__Format MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__F1 MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__F2 MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__F1F2 MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__F2F1.

Opaque MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__cond MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__Format.

Definition MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__Format : T_Format MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__nat__Format MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__F1 MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__F2 MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__F1F2 MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__F2F1.

Opaque MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__cond MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__Format.


Definition MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__Format_Type := Eval cbn in seq_format_prod MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__list.
Definition MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__Format_list : MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__Format_Type :=
  (MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17__Format, (MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17__Format, unit_format)).
Definition MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__list__Format := (*Eval compute in *) seq_format MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__list MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__Format_list.
Definition MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__F1 z :=
  (MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_480kHz_r17 z, (MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__preferredK0_SCS_960kHz_r17 z, tt)).
Definition MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__F2 (y : seq_type MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__list) :=
  match y with
  | (i0, (i1, _))=>
    make__MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__Type i0 i1
  end.
Lemma MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__F1F2_cond (z : MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__Type)
  : MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__cond z ->
  (seq_cond MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__list (MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__F1 z)).
intro H. unfold MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__cond in H. simpl. auto. Qed.
Lemma MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__F1F2_cond2 (z : MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__Type)
 : MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__F2 (MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__F2F1_cond (y : seq_type MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__list)
  : seq_cond MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__list y ->
 (MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__cond (MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__F2 y)) /\  MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__F1 (MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__cond. simpl in *. auto.
 - simpl. unfold MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__F1. simpl. destruct_all_unit. auto.   Qed.
Definition MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__Format : T_Format MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__Type MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__cond :=
        proj2_format  MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__cond MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__list__Format
    MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__F1 MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__F2 MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__F1F2_cond  MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__F1F2_cond2 MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__F2F1_cond.
Opaque MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__cond MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__Format.

Definition MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__Format : T_Format MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__nat__Format MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__F1 MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__F2 MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__F1F2 MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__F2F1.

Opaque MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__cond MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__Format.

Definition MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__Format : T_Format MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__nat__Format MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__F1 MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__F2 MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__F1F2 MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__F2F1.

Opaque MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__cond MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__Format.


Definition MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__Format_Type := Eval cbn in seq_format_prod MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__list.
Definition MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__Format_list : MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__Format_Type :=
  (MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17__Format, (MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17__Format, unit_format)).
Definition MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__list__Format := (*Eval compute in *) seq_format MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__list MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__Format_list.
Definition MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__F1 z :=
  (MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_480kHz_r17 z, (MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__preferredK2_SCS_960kHz_r17 z, tt)).
Definition MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__F2 (y : seq_type MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__list) :=
  match y with
  | (i0, (i1, _))=>
    make__MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__Type i0 i1
  end.
Lemma MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__F1F2_cond (z : MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__Type)
  : MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__cond z ->
  (seq_cond MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__list (MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__F1 z)).
intro H. unfold MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__cond in H. simpl. auto. Qed.
Lemma MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__F1F2_cond2 (z : MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__Type)
 : MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__F2 (MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__F2F1_cond (y : seq_type MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__list)
  : seq_cond MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__list y ->
 (MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__cond (MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__F2 y)) /\  MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__F1 (MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__cond. simpl in *. auto.
 - simpl. unfold MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__F1. simpl. destruct_all_unit. auto.   Qed.
Definition MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__Format : T_Format MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__Type MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__cond :=
        proj2_format  MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__cond MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__list__Format
    MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__F1 MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__F2 MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__F1F2_cond  MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__F1F2_cond2 MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__F2F1_cond.
Opaque MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__cond MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__Format.


Definition MinSchedulingOffsetPreferenceExt_r17__Format_Type := Eval cbn in seq_format_prod MinSchedulingOffsetPreferenceExt_r17__list.
Definition MinSchedulingOffsetPreferenceExt_r17__Format_list : MinSchedulingOffsetPreferenceExt_r17__Format_Type :=
  (MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17__Format, (MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17__Format, unit_format)).
Definition MinSchedulingOffsetPreferenceExt_r17__list__Format := (*Eval compute in *) seq_format MinSchedulingOffsetPreferenceExt_r17__list MinSchedulingOffsetPreferenceExt_r17__Format_list.
Definition MinSchedulingOffsetPreferenceExt_r17__F1 z :=
  (MinSchedulingOffsetPreferenceExt_r17__preferredK0_r17 z, (MinSchedulingOffsetPreferenceExt_r17__preferredK2_r17 z, tt)).
Definition MinSchedulingOffsetPreferenceExt_r17__F2 (y : seq_type MinSchedulingOffsetPreferenceExt_r17__list) :=
  match y with
  | (i0, (i1, _))=>
    make__MinSchedulingOffsetPreferenceExt_r17__Type i0 i1
  end.
Lemma MinSchedulingOffsetPreferenceExt_r17__F1F2_cond (z : MinSchedulingOffsetPreferenceExt_r17__Type)
  : MinSchedulingOffsetPreferenceExt_r17__cond z ->
  (seq_cond MinSchedulingOffsetPreferenceExt_r17__list (MinSchedulingOffsetPreferenceExt_r17__F1 z)).
intro H. unfold MinSchedulingOffsetPreferenceExt_r17__cond in H. simpl. auto. Qed.
Lemma MinSchedulingOffsetPreferenceExt_r17__F1F2_cond2 (z : MinSchedulingOffsetPreferenceExt_r17__Type)
 : MinSchedulingOffsetPreferenceExt_r17__F2 (MinSchedulingOffsetPreferenceExt_r17__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma MinSchedulingOffsetPreferenceExt_r17__F2F1_cond (y : seq_type MinSchedulingOffsetPreferenceExt_r17__list)
  : seq_cond MinSchedulingOffsetPreferenceExt_r17__list y ->
 (MinSchedulingOffsetPreferenceExt_r17__cond (MinSchedulingOffsetPreferenceExt_r17__F2 y)) /\  MinSchedulingOffsetPreferenceExt_r17__F1 (MinSchedulingOffsetPreferenceExt_r17__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold MinSchedulingOffsetPreferenceExt_r17__cond. simpl in *. auto.
 - simpl. unfold MinSchedulingOffsetPreferenceExt_r17__F1. simpl. destruct_all_unit. auto.   Qed.
Definition MinSchedulingOffsetPreferenceExt_r17__Format : T_Format MinSchedulingOffsetPreferenceExt_r17__Type MinSchedulingOffsetPreferenceExt_r17__cond :=
        proj2_format  MinSchedulingOffsetPreferenceExt_r17__cond MinSchedulingOffsetPreferenceExt_r17__list__Format
    MinSchedulingOffsetPreferenceExt_r17__F1 MinSchedulingOffsetPreferenceExt_r17__F2 MinSchedulingOffsetPreferenceExt_r17__F1F2_cond  MinSchedulingOffsetPreferenceExt_r17__F1F2_cond2 MinSchedulingOffsetPreferenceExt_r17__F2F1_cond.
Opaque MinSchedulingOffsetPreferenceExt_r17__cond MinSchedulingOffsetPreferenceExt_r17__Format.

