Require Import ASN1Parser.ExtrOCaml.ExtractHelper.

Require Import NR.NR_RRC_Definitions.
Inductive MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__Type : Set :=
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__n20
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__n40
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__n50
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__n60
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__n70
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__n80
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__n90
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__n100
.
Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__cond := (fun (_ : MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__Type) => True).
Lemma MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__nat__helper : to_bit_sz 7 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__nat__Format : T_Format nat (fun z => (z <= 7)) :=
  nat_enum_format 7 MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__nat__helper.

Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__F1 t :=
  match t with
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__n20 => 0
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__n40 => 1
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__n50 => 2
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__n60 => 3
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__n70 => 4
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__n80 => 5
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__n90 => 6
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__n100 => 7
  end.
Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__F2 n :=
  match n with
  | 0 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__n20
  | 1 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__n40
  | 2 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__n50
  | 3 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__n60
  | 4 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__n70
  | 5 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__n80
  | 6 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__n90
  | 7 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__n100
  | _ => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__n20
  end.
Lemma MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__F1F2 : forall x : MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__Type, (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__F1 x <= 7) /\ MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__F2 (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__F1 x) = x. imp_solve. Qed.
Lemma MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__F2F1 : forall (y : nat) (H : y <= 7), MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__F1 (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__F2 y) = y. enum_solve H y. Qed.

Inductive MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__Type : Set :=
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__n20
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__n40
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__n50
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__n60
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__n70
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__n80
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__n90
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__n100
.
Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__cond := (fun (_ : MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__Type) => True).
Lemma MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__nat__helper : to_bit_sz 7 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__nat__Format : T_Format nat (fun z => (z <= 7)) :=
  nat_enum_format 7 MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__nat__helper.

Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__F1 t :=
  match t with
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__n20 => 0
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__n40 => 1
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__n50 => 2
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__n60 => 3
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__n70 => 4
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__n80 => 5
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__n90 => 6
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__n100 => 7
  end.
Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__F2 n :=
  match n with
  | 0 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__n20
  | 1 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__n40
  | 2 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__n50
  | 3 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__n60
  | 4 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__n70
  | 5 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__n80
  | 6 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__n90
  | 7 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__n100
  | _ => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__n20
  end.
Lemma MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__F1F2 : forall x : MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__Type, (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__F1 x <= 7) /\ MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__F2 (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__F1 x) = x. imp_solve. Qed.
Lemma MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__F2F1 : forall (y : nat) (H : y <= 7), MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__F1 (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__F2 y) = y. enum_solve H y. Qed.

Inductive MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__Type : Set :=
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__n20
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__n40
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__n50
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__n60
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__n70
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__n80
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__n90
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__n100
.
Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__cond := (fun (_ : MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__Type) => True).
Lemma MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__nat__helper : to_bit_sz 7 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__nat__Format : T_Format nat (fun z => (z <= 7)) :=
  nat_enum_format 7 MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__nat__helper.

Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__F1 t :=
  match t with
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__n20 => 0
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__n40 => 1
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__n50 => 2
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__n60 => 3
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__n70 => 4
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__n80 => 5
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__n90 => 6
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__n100 => 7
  end.
Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__F2 n :=
  match n with
  | 0 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__n20
  | 1 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__n40
  | 2 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__n50
  | 3 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__n60
  | 4 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__n70
  | 5 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__n80
  | 6 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__n90
  | 7 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__n100
  | _ => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__n20
  end.
Lemma MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__F1F2 : forall x : MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__Type, (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__F1 x <= 7) /\ MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__F2 (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__F1 x) = x. imp_solve. Qed.
Lemma MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__F2F1 : forall (y : nat) (H : y <= 7), MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__F1 (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__F2 y) = y. enum_solve H y. Qed.

Inductive MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__Type : Set :=
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__n20
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__n40
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__n50
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__n60
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__n70
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__n80
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__n90
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__n100
.
Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__cond := (fun (_ : MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__Type) => True).
Lemma MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__nat__helper : to_bit_sz 7 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__nat__Format : T_Format nat (fun z => (z <= 7)) :=
  nat_enum_format 7 MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__nat__helper.

Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__F1 t :=
  match t with
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__n20 => 0
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__n40 => 1
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__n50 => 2
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__n60 => 3
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__n70 => 4
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__n80 => 5
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__n90 => 6
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__n100 => 7
  end.
Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__F2 n :=
  match n with
  | 0 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__n20
  | 1 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__n40
  | 2 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__n50
  | 3 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__n60
  | 4 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__n70
  | 5 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__n80
  | 6 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__n90
  | 7 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__n100
  | _ => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__n20
  end.
Lemma MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__F1F2 : forall x : MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__Type, (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__F1 x <= 7) /\ MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__F2 (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__F1 x) = x. imp_solve. Qed.
Lemma MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__F2F1 : forall (y : nat) (H : y <= 7), MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__F1 (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__F2 y) = y. enum_solve H y. Qed.

Inductive MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__Type : Set :=
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__n20
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__n40
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__n50
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__n60
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__n70
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__n80
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__n90
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__n100
.
Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__cond := (fun (_ : MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__Type) => True).
Lemma MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__nat__helper : to_bit_sz 7 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__nat__Format : T_Format nat (fun z => (z <= 7)) :=
  nat_enum_format 7 MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__nat__helper.

Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__F1 t :=
  match t with
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__n20 => 0
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__n40 => 1
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__n50 => 2
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__n60 => 3
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__n70 => 4
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__n80 => 5
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__n90 => 6
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__n100 => 7
  end.
Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__F2 n :=
  match n with
  | 0 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__n20
  | 1 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__n40
  | 2 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__n50
  | 3 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__n60
  | 4 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__n70
  | 5 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__n80
  | 6 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__n90
  | 7 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__n100
  | _ => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__n20
  end.
Lemma MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__F1F2 : forall x : MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__Type, (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__F1 x <= 7) /\ MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__F2 (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__F1 x) = x. imp_solve. Qed.
Lemma MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__F2F1 : forall (y : nat) (H : y <= 7), MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__F1 (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__F2 y) = y. enum_solve H y. Qed.

Inductive MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__Type : Set :=
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__n20
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__n40
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__n50
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__n60
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__n70
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__n80
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__n90
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__n100
.
Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__cond := (fun (_ : MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__Type) => True).
Lemma MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__nat__helper : to_bit_sz 7 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__nat__Format : T_Format nat (fun z => (z <= 7)) :=
  nat_enum_format 7 MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__nat__helper.

Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__F1 t :=
  match t with
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__n20 => 0
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__n40 => 1
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__n50 => 2
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__n60 => 3
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__n70 => 4
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__n80 => 5
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__n90 => 6
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__n100 => 7
  end.
Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__F2 n :=
  match n with
  | 0 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__n20
  | 1 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__n40
  | 2 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__n50
  | 3 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__n60
  | 4 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__n70
  | 5 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__n80
  | 6 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__n90
  | 7 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__n100
  | _ => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__n20
  end.
Lemma MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__F1F2 : forall x : MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__Type, (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__F1 x <= 7) /\ MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__F2 (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__F1 x) = x. imp_solve. Qed.
Lemma MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__F2F1 : forall (y : nat) (H : y <= 7), MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__F1 (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__F2 y) = y. enum_solve H y. Qed.

Inductive MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__Type : Set :=
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__n20
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__n40
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__n50
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__n60
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__n70
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__n80
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__n90
 | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__n100
.
Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__cond := (fun (_ : MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__Type) => True).
Lemma MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__nat__helper : to_bit_sz 7 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__nat__Format : T_Format nat (fun z => (z <= 7)) :=
  nat_enum_format 7 MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__nat__helper.

Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__F1 t :=
  match t with
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__n20 => 0
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__n40 => 1
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__n50 => 2
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__n60 => 3
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__n70 => 4
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__n80 => 5
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__n90 => 6
  | MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__n100 => 7
  end.
Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__F2 n :=
  match n with
  | 0 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__n20
  | 1 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__n40
  | 2 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__n50
  | 3 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__n60
  | 4 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__n70
  | 5 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__n80
  | 6 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__n90
  | 7 => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__n100
  | _ => MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__n20
  end.
Lemma MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__F1F2 : forall x : MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__Type, (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__F1 x <= 7) /\ MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__F2 (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__F1 x) = x. imp_solve. Qed.
Lemma MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__F2F1 : forall (y : nat) (H : y <= 7), MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__F1 (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__F2 y) = y. enum_solve H y. Qed.

Record MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__Type : Set :=
  make__MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__Type {
    MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16 : option MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__Type ;
    MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16 : option MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__Type ;
    MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16 : option MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__Type ;
    MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16 : option MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__Type ;
    MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16 : option MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__Type ;
    MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16 : option MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__Type ;
    MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16 : option MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__Type ;
}.
Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__list := (
 Opt MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__Type MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__cond ::
 Opt MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__Type MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__cond ::
 Opt MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__Type MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__cond ::
 Opt MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__Type MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__cond ::
 Opt MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__Type MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__cond ::
 Opt MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__Type MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__cond ::
 Opt MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__Type MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__cond ::
 nil).
Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__cond z := 
  opt_cond MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__cond (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16 z) /\
  opt_cond MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__cond (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16 z) /\
  opt_cond MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__cond (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16 z) /\
  opt_cond MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__cond (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16 z) /\
  opt_cond MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__cond (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16 z) /\
  opt_cond MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__cond (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16 z) /\
  opt_cond MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__cond (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16 z) /\
  True.

Inductive MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__Type : Set :=
 | MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__supported
.
Definition MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__cond := (fun (_ : MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__Type) => True).
Lemma MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__nat__helper.

Definition MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__F1 t :=
  match t with
  | MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__supported => 0
  end.
Definition MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__F2 n :=
  match n with
  | 0 => MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__supported
  | _ => MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__supported
  end.
Lemma MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__F1F2 : forall x : MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__Type, (MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__F1 x <= 0) /\ MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__F2 (MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__F1 x) = x. imp_solve. Qed.
Lemma MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__F2F1 : forall (y : nat) (H : y <= 0), MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__F1 (MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__F2 y) = y. enum_solve H y. Qed.

Inductive MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__Type : Set :=
 | MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__supported
.
Definition MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__cond := (fun (_ : MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__Type) => True).
Lemma MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__nat__helper.

Definition MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__F1 t :=
  match t with
  | MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__supported => 0
  end.
Definition MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__F2 n :=
  match n with
  | 0 => MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__supported
  | _ => MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__supported
  end.
Lemma MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__F1F2 : forall x : MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__Type, (MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__F1 x <= 0) /\ MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__F2 (MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__F1 x) = x. imp_solve. Qed.
Lemma MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__F2F1 : forall (y : nat) (H : y <= 0), MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__F1 (MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__F2 y) = y. enum_solve H y. Qed.

Inductive MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__Type : Set :=
 | MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__supported
.
Definition MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__cond := (fun (_ : MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__Type) => True).
Lemma MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__nat__helper.

Definition MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__F1 t :=
  match t with
  | MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__supported => 0
  end.
Definition MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__F2 n :=
  match n with
  | 0 => MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__supported
  | _ => MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__supported
  end.
Lemma MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__F1F2 : forall x : MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__Type, (MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__F1 x <= 0) /\ MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__F2 (MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__F1 x) = x. imp_solve. Qed.
Lemma MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__F2F1 : forall (y : nat) (H : y <= 0), MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__F1 (MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__F2 y) = y. enum_solve H y. Qed.

Inductive MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__Type : Set :=
 | MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__supported
.
Definition MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__cond := (fun (_ : MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__Type) => True).
Lemma MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__nat__helper.

Definition MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__F1 t :=
  match t with
  | MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__supported => 0
  end.
Definition MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__F2 n :=
  match n with
  | 0 => MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__supported
  | _ => MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__supported
  end.
Lemma MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__F1F2 : forall x : MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__Type, (MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__F1 x <= 0) /\ MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__F2 (MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__F1 x) = x. imp_solve. Qed.
Lemma MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__F2F1 : forall (y : nat) (H : y <= 0), MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__F1 (MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__F2 y) = y. enum_solve H y. Qed.

Record MRDC_Parameters_v1620__Type : Set :=
  make__MRDC_Parameters_v1620__Type {
    MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16 : option MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__Type ;
    MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16 : option MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__Type ;
    MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16 : option MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__Type ;
    MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16 : option MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__Type ;
    MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16 : option MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__Type ;
}.
Definition MRDC_Parameters_v1620__list := (
 Opt MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__Type MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__cond ::
 Opt MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__Type MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__cond ::
 Opt MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__Type MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__cond ::
 Opt MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__Type MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__cond ::
 Opt MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__Type MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__cond ::
 nil).
Definition MRDC_Parameters_v1620__cond z := 
  opt_cond MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__cond (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16 z) /\
  opt_cond MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__cond (MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16 z) /\
  opt_cond MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__cond (MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16 z) /\
  opt_cond MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__cond (MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16 z) /\
  opt_cond MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__cond (MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16 z) /\
  True.


Opaque Byte.to_nat Byte.of_nat.
Opaque bind_parse restrict_parse proj_parse return_parse.
Opaque restrict_serialize proj_serialize sigma_serialize append_serialize proj2_serialize.

Opaque read_n_nat read_unit.
Opaque put_n_nat put_unit. 

Opaque opt_bind opt_serialize dft_serialize prepend_serialize list_serial.
Opaque opt_parse list_parse dft_parse fail_parse append_parse
  bind_parse return_parse.

Opaque Z.to_nat Z.of_nat Z.sub Z.add Z.le Z.lt Z.pow Z.opp Z.ltb.
Opaque Nat.mul Nat.shiftr Nat.shiftl Nat.div Nat.modulo Nat.leb Nat.ltb Nat.add
  Nat.sub Nat.land Nat.lor Nat.eqb  Nat.log2 Nat.pow Nat.even PeanoNat.Nat.lnot.
Opaque Compare_dec.le_dec Compare_dec.le_lt_dec ZArith_dec.Z_le_dec lt_eq_lt_dec_new. 
Opaque sumbool_and1 list_and list_and_cons list_cons_S flg_add. 

Opaque list_to_len.
   Opaque length Compare_dec.le_dec Compare_dec.lt_dec PeanoNat.Nat.eq_dec.
   Opaque bool__Format int__Format octet_string_nc__Format bit_string_nc__Format.

   Opaque ByteIdx_to_nat nat_to_ByteIdx add_opt list_bool_format normally_small_len_det_format
  get_byte_len to_parse_skip  open_typ_serialize open_typ_parse open_type_to_len.
  

Opaque seq_cond seq_ext_cond choice_cond.
Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__Format : T_Format MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__Type (fun _ => True) :=
(* Eval compute in *) proj3_format MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__nat__Format MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__F1 MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__F2 MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__F1F2 MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__F2F1.

Opaque MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__cond MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__Format.

Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__Format : T_Format MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__Type (fun _ => True) :=
(* Eval compute in *) proj3_format MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__nat__Format MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__F1 MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__F2 MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__F1F2 MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__F2F1.

Opaque MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__cond MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__Format.

Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__Format : T_Format MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__Type (fun _ => True) :=
(* Eval compute in *) proj3_format MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__nat__Format MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__F1 MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__F2 MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__F1F2 MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__F2F1.

Opaque MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__cond MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__Format.

Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__Format : T_Format MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__Type (fun _ => True) :=
(* Eval compute in *) proj3_format MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__nat__Format MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__F1 MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__F2 MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__F1F2 MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__F2F1.

Opaque MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__cond MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__Format.

Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__Format : T_Format MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__Type (fun _ => True) :=
(* Eval compute in *) proj3_format MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__nat__Format MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__F1 MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__F2 MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__F1F2 MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__F2F1.

Opaque MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__cond MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__Format.

Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__Format : T_Format MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__Type (fun _ => True) :=
(* Eval compute in *) proj3_format MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__nat__Format MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__F1 MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__F2 MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__F1F2 MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__F2F1.

Opaque MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__cond MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__Format.

Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__Format : T_Format MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__Type (fun _ => True) :=
(* Eval compute in *) proj3_format MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__nat__Format MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__F1 MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__F2 MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__F1F2 MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__F2F1.

Opaque MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__cond MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__Format.


Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__Format_Type := Eval cbn in seq_format_prod MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__list.
Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__Format_list : MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__Format_Type :=
  (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16__Format, (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16__Format, (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16__Format, (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16__Format, (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16__Format, (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16__Format, (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16__Format, unit_format))))))).
Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__list__Format := (*Eval compute in *) seq_format MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__list MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__Format_list.
Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__F1 z :=
  (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config0_r16 z, (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config1_r16 z, (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config2_r16 z, (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config3_r16 z, (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config4_r16 z, (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config5_r16 z, (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__eutra_TDD_Config6_r16 z, tt))))))).
Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__F2 (y : seq_type MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__list) :=
  match y with
  | (i0, (i1, (i2, (i3, (i4, (i5, (i6, _)))))))=>
    make__MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__Type i0 i1 i2 i3 i4 i5 i6
  end.
Lemma MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__F1F2_cond (z : MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__Type)
  : MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__cond z ->
  (seq_cond MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__list (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__F1 z)).
intro H. unfold MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__cond in H. simpl. auto. Qed.
Lemma MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__F1F2_cond2 (z : MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__Type)
 : MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__F2 (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__F2F1_cond (y : seq_type MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__list)
  : seq_cond MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__list y ->
 (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__cond (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__F2 y)) /\  MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__F1 (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__cond. simpl in *. auto.
 - simpl. unfold MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__F1. simpl. destruct_all_unit. auto.   Qed.
Definition MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__Format : T_Format MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__Type MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__cond :=
        proj2_format  MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__cond MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__list__Format
    MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__F1 MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__F2 MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__F1F2_cond  MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__F1F2_cond2 MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__F2F1_cond.
Opaque MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__cond MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__Format.

Definition MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__Format : T_Format MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__Type (fun _ => True) :=
(* Eval compute in *) proj3_format MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__nat__Format MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__F1 MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__F2 MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__F1F2 MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__F2F1.

Opaque MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__cond MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__Format.

Definition MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__Format : T_Format MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__Type (fun _ => True) :=
(* Eval compute in *) proj3_format MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__nat__Format MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__F1 MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__F2 MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__F1F2 MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__F2F1.

Opaque MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__cond MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__Format.

Definition MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__Format : T_Format MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__Type (fun _ => True) :=
(* Eval compute in *) proj3_format MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__nat__Format MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__F1 MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__F2 MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__F1F2 MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__F2F1.

Opaque MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__cond MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__Format.

Definition MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__Format : T_Format MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__Type (fun _ => True) :=
(* Eval compute in *) proj3_format MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__nat__Format MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__F1 MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__F2 MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__F1F2 MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__F2F1.

Opaque MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__cond MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__Format.


Definition MRDC_Parameters_v1620__Format_Type := Eval cbn in seq_format_prod MRDC_Parameters_v1620__list.
Definition MRDC_Parameters_v1620__Format_list : MRDC_Parameters_v1620__Format_Type :=
  (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16__Format, (MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16__Format, (MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16__Format, (MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16__Format, (MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16__Format, unit_format))))).
Definition MRDC_Parameters_v1620__list__Format := (*Eval compute in *) seq_format MRDC_Parameters_v1620__list MRDC_Parameters_v1620__Format_list.
Definition MRDC_Parameters_v1620__F1 z :=
  (MRDC_Parameters_v1620__maxUplinkDutyCycle_interBandENDC_TDD_PC2_r16 z, (MRDC_Parameters_v1620__tdm_restrictionTDD_endc_r16 z, (MRDC_Parameters_v1620__tdm_restrictionFDD_endc_r16 z, (MRDC_Parameters_v1620__singleUL_HARQ_offsetTDD_PCell_r16 z, (MRDC_Parameters_v1620__tdm_restrictionDualTX_FDD_endc_r16 z, tt))))).
Definition MRDC_Parameters_v1620__F2 (y : seq_type MRDC_Parameters_v1620__list) :=
  match y with
  | (i0, (i1, (i2, (i3, (i4, _)))))=>
    make__MRDC_Parameters_v1620__Type i0 i1 i2 i3 i4
  end.
Lemma MRDC_Parameters_v1620__F1F2_cond (z : MRDC_Parameters_v1620__Type)
  : MRDC_Parameters_v1620__cond z ->
  (seq_cond MRDC_Parameters_v1620__list (MRDC_Parameters_v1620__F1 z)).
intro H. unfold MRDC_Parameters_v1620__cond in H. simpl. auto. Qed.
Lemma MRDC_Parameters_v1620__F1F2_cond2 (z : MRDC_Parameters_v1620__Type)
 : MRDC_Parameters_v1620__F2 (MRDC_Parameters_v1620__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma MRDC_Parameters_v1620__F2F1_cond (y : seq_type MRDC_Parameters_v1620__list)
  : seq_cond MRDC_Parameters_v1620__list y ->
 (MRDC_Parameters_v1620__cond (MRDC_Parameters_v1620__F2 y)) /\  MRDC_Parameters_v1620__F1 (MRDC_Parameters_v1620__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold MRDC_Parameters_v1620__cond. simpl in *. auto.
 - simpl. unfold MRDC_Parameters_v1620__F1. simpl. destruct_all_unit. auto.   Qed.
Definition MRDC_Parameters_v1620__Format : T_Format MRDC_Parameters_v1620__Type MRDC_Parameters_v1620__cond :=
        proj2_format  MRDC_Parameters_v1620__cond MRDC_Parameters_v1620__list__Format
    MRDC_Parameters_v1620__F1 MRDC_Parameters_v1620__F2 MRDC_Parameters_v1620__F1F2_cond  MRDC_Parameters_v1620__F1F2_cond2 MRDC_Parameters_v1620__F2F1_cond.
Opaque MRDC_Parameters_v1620__cond MRDC_Parameters_v1620__Format.

