Require Import ASN1Parser.ExtrOCaml.ExtractHelper.

Require Import NR.NR_RRC_Definitions.
Inductive OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__Type : Set :=
 | OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__true
.
Definition OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__cond := (fun (_ : OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__Type) => True).
Lemma OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__nat__helper.

Definition OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__F1 t :=
  match t with
  | OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__true => 0
  end.
Definition OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__F2 n :=
  match n with
  | 0 => OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__true
  | _ => OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__true
  end.
Lemma OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__F1F2 : forall x : OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__Type, (OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__F1 x <= 0) /\ OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__F2 (OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__F1 x) = x. imp_solve. Qed.
Lemma OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__F2F1 : forall (y : nat) (H : y <= 0), OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__F1 (OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__F2 y) = y. enum_solve H y. Qed.

Require Import NR.SetupRelease.
Require Import NR.MUSIM_GapAssistanceConfig_r17.
Definition OtherConfig_v1700__musim_GapAssistanceConfig_r17__Type := SetupRelease__Type MUSIM_GapAssistanceConfig_r17__Type.
Definition OtherConfig_v1700__musim_GapAssistanceConfig_r17__cond := SetupRelease__cond _ MUSIM_GapAssistanceConfig_r17__cond.
Definition OtherConfig_v1700__musim_GapAssistanceConfig_r17__Format : T_Format OtherConfig_v1700__musim_GapAssistanceConfig_r17__Type OtherConfig_v1700__musim_GapAssistanceConfig_r17__cond := SetupRelease__Format _ _ MUSIM_GapAssistanceConfig_r17__Format.
Opaque OtherConfig_v1700__musim_GapAssistanceConfig_r17__cond OtherConfig_v1700__musim_GapAssistanceConfig_r17__Format.

Require Import NR.SetupRelease.
Require Import NR.MUSIM_LeaveAssistanceConfig_r17.
Definition OtherConfig_v1700__musim_LeaveAssistanceConfig_r17__Type := SetupRelease__Type MUSIM_LeaveAssistanceConfig_r17__Type.
Definition OtherConfig_v1700__musim_LeaveAssistanceConfig_r17__cond := SetupRelease__cond _ MUSIM_LeaveAssistanceConfig_r17__cond.
Definition OtherConfig_v1700__musim_LeaveAssistanceConfig_r17__Format : T_Format OtherConfig_v1700__musim_LeaveAssistanceConfig_r17__Type OtherConfig_v1700__musim_LeaveAssistanceConfig_r17__cond := SetupRelease__Format _ _ MUSIM_LeaveAssistanceConfig_r17__Format.
Opaque OtherConfig_v1700__musim_LeaveAssistanceConfig_r17__cond OtherConfig_v1700__musim_LeaveAssistanceConfig_r17__Format.

Require Import NR.SetupRelease.
Require Import NR.SuccessHO_Config_r17.
Definition OtherConfig_v1700__successHO_Config_r17__Type := SetupRelease__Type SuccessHO_Config_r17__Type.
Definition OtherConfig_v1700__successHO_Config_r17__cond := SetupRelease__cond _ SuccessHO_Config_r17__cond.
Definition OtherConfig_v1700__successHO_Config_r17__Format : T_Format OtherConfig_v1700__successHO_Config_r17__Type OtherConfig_v1700__successHO_Config_r17__cond := SetupRelease__Format _ _ SuccessHO_Config_r17__Format.
Opaque OtherConfig_v1700__successHO_Config_r17__cond OtherConfig_v1700__successHO_Config_r17__Format.

Inductive OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__Type : Set :=
 | OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__true
.
Definition OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__cond := (fun (_ : OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__Type) => True).
Lemma OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__nat__helper.

Definition OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__F1 t :=
  match t with
  | OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__true => 0
  end.
Definition OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__F2 n :=
  match n with
  | 0 => OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__true
  | _ => OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__true
  end.
Lemma OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__F1F2 : forall x : OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__Type, (OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__F1 x <= 0) /\ OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__F2 (OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__F1 x) = x. imp_solve. Qed.
Lemma OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__F2F1 : forall (y : nat) (H : y <= 0), OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__F1 (OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__F2 y) = y. enum_solve H y. Qed.

Inductive OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__Type : Set :=
 | OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__true
.
Definition OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__cond := (fun (_ : OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__Type) => True).
Lemma OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__nat__helper.

Definition OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__F1 t :=
  match t with
  | OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__true => 0
  end.
Definition OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__F2 n :=
  match n with
  | 0 => OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__true
  | _ => OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__true
  end.
Lemma OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__F1F2 : forall x : OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__Type, (OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__F1 x <= 0) /\ OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__F2 (OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__F1 x) = x. imp_solve. Qed.
Lemma OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__F2F1 : forall (y : nat) (H : y <= 0), OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__F1 (OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__F2 y) = y. enum_solve H y. Qed.

Inductive OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__Type : Set :=
 | OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__true
.
Definition OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__cond := (fun (_ : OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__Type) => True).
Lemma OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__nat__helper.

Definition OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__F1 t :=
  match t with
  | OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__true => 0
  end.
Definition OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__F2 n :=
  match n with
  | 0 => OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__true
  | _ => OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__true
  end.
Lemma OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__F1F2 : forall x : OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__Type, (OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__F1 x <= 0) /\ OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__F2 (OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__F1 x) = x. imp_solve. Qed.
Lemma OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__F2F1 : forall (y : nat) (H : y <= 0), OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__F1 (OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__F2 y) = y. enum_solve H y. Qed.

Require Import NR.SetupRelease.
Require Import NR.RLM_RelaxationReportingConfig_r17.
Definition OtherConfig_v1700__rlm_RelaxationReportingConfig_r17__Type := SetupRelease__Type RLM_RelaxationReportingConfig_r17__Type.
Definition OtherConfig_v1700__rlm_RelaxationReportingConfig_r17__cond := SetupRelease__cond _ RLM_RelaxationReportingConfig_r17__cond.
Definition OtherConfig_v1700__rlm_RelaxationReportingConfig_r17__Format : T_Format OtherConfig_v1700__rlm_RelaxationReportingConfig_r17__Type OtherConfig_v1700__rlm_RelaxationReportingConfig_r17__cond := SetupRelease__Format _ _ RLM_RelaxationReportingConfig_r17__Format.
Opaque OtherConfig_v1700__rlm_RelaxationReportingConfig_r17__cond OtherConfig_v1700__rlm_RelaxationReportingConfig_r17__Format.

Require Import NR.SetupRelease.
Require Import NR.BFD_RelaxationReportingConfig_r17.
Definition OtherConfig_v1700__bfd_RelaxationReportingConfig_r17__Type := SetupRelease__Type BFD_RelaxationReportingConfig_r17__Type.
Definition OtherConfig_v1700__bfd_RelaxationReportingConfig_r17__cond := SetupRelease__cond _ BFD_RelaxationReportingConfig_r17__cond.
Definition OtherConfig_v1700__bfd_RelaxationReportingConfig_r17__Format : T_Format OtherConfig_v1700__bfd_RelaxationReportingConfig_r17__Type OtherConfig_v1700__bfd_RelaxationReportingConfig_r17__cond := SetupRelease__Format _ _ BFD_RelaxationReportingConfig_r17__Format.
Opaque OtherConfig_v1700__bfd_RelaxationReportingConfig_r17__cond OtherConfig_v1700__bfd_RelaxationReportingConfig_r17__Format.

Require Import NR.SetupRelease.
Require Import NR.SCG_DeactivationPreferenceConfig_r17.
Definition OtherConfig_v1700__scg_DeactivationPreferenceConfig_r17__Type := SetupRelease__Type SCG_DeactivationPreferenceConfig_r17__Type.
Definition OtherConfig_v1700__scg_DeactivationPreferenceConfig_r17__cond := SetupRelease__cond _ SCG_DeactivationPreferenceConfig_r17__cond.
Definition OtherConfig_v1700__scg_DeactivationPreferenceConfig_r17__Format : T_Format OtherConfig_v1700__scg_DeactivationPreferenceConfig_r17__Type OtherConfig_v1700__scg_DeactivationPreferenceConfig_r17__cond := SetupRelease__Format _ _ SCG_DeactivationPreferenceConfig_r17__Format.
Opaque OtherConfig_v1700__scg_DeactivationPreferenceConfig_r17__cond OtherConfig_v1700__scg_DeactivationPreferenceConfig_r17__Format.

Require Import NR.SetupRelease.
Require Import NR.RRM_MeasRelaxationReportingConfig_r17.
Definition OtherConfig_v1700__rrm_MeasRelaxationReportingConfig_r17__Type := SetupRelease__Type RRM_MeasRelaxationReportingConfig_r17__Type.
Definition OtherConfig_v1700__rrm_MeasRelaxationReportingConfig_r17__cond := SetupRelease__cond _ RRM_MeasRelaxationReportingConfig_r17__cond.
Definition OtherConfig_v1700__rrm_MeasRelaxationReportingConfig_r17__Format : T_Format OtherConfig_v1700__rrm_MeasRelaxationReportingConfig_r17__Type OtherConfig_v1700__rrm_MeasRelaxationReportingConfig_r17__cond := SetupRelease__Format _ _ RRM_MeasRelaxationReportingConfig_r17__Format.
Opaque OtherConfig_v1700__rrm_MeasRelaxationReportingConfig_r17__cond OtherConfig_v1700__rrm_MeasRelaxationReportingConfig_r17__Format.

Require Import NR.SetupRelease.
Require Import NR.PropDelayDiffReportConfig_r17.
Definition OtherConfig_v1700__propDelayDiffReportConfig_r17__Type := SetupRelease__Type PropDelayDiffReportConfig_r17__Type.
Definition OtherConfig_v1700__propDelayDiffReportConfig_r17__cond := SetupRelease__cond _ PropDelayDiffReportConfig_r17__cond.
Definition OtherConfig_v1700__propDelayDiffReportConfig_r17__Format : T_Format OtherConfig_v1700__propDelayDiffReportConfig_r17__Type OtherConfig_v1700__propDelayDiffReportConfig_r17__cond := SetupRelease__Format _ _ PropDelayDiffReportConfig_r17__Format.
Opaque OtherConfig_v1700__propDelayDiffReportConfig_r17__cond OtherConfig_v1700__propDelayDiffReportConfig_r17__Format.

Record OtherConfig_v1700__Type : Set :=
  make__OtherConfig_v1700__Type {
    OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17 : option OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__Type ;
    OtherConfig_v1700__musim_GapAssistanceConfig_r17 : option OtherConfig_v1700__musim_GapAssistanceConfig_r17__Type ;
    OtherConfig_v1700__musim_LeaveAssistanceConfig_r17 : option OtherConfig_v1700__musim_LeaveAssistanceConfig_r17__Type ;
    OtherConfig_v1700__successHO_Config_r17 : option OtherConfig_v1700__successHO_Config_r17__Type ;
    OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17 : option OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__Type ;
    OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17 : option OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__Type ;
    OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17 : option OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__Type ;
    OtherConfig_v1700__rlm_RelaxationReportingConfig_r17 : option OtherConfig_v1700__rlm_RelaxationReportingConfig_r17__Type ;
    OtherConfig_v1700__bfd_RelaxationReportingConfig_r17 : option OtherConfig_v1700__bfd_RelaxationReportingConfig_r17__Type ;
    OtherConfig_v1700__scg_DeactivationPreferenceConfig_r17 : option OtherConfig_v1700__scg_DeactivationPreferenceConfig_r17__Type ;
    OtherConfig_v1700__rrm_MeasRelaxationReportingConfig_r17 : option OtherConfig_v1700__rrm_MeasRelaxationReportingConfig_r17__Type ;
    OtherConfig_v1700__propDelayDiffReportConfig_r17 : option OtherConfig_v1700__propDelayDiffReportConfig_r17__Type ;
}.
Definition OtherConfig_v1700__list := (
 Opt OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__Type OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__cond ::
 Opt OtherConfig_v1700__musim_GapAssistanceConfig_r17__Type OtherConfig_v1700__musim_GapAssistanceConfig_r17__cond ::
 Opt OtherConfig_v1700__musim_LeaveAssistanceConfig_r17__Type OtherConfig_v1700__musim_LeaveAssistanceConfig_r17__cond ::
 Opt OtherConfig_v1700__successHO_Config_r17__Type OtherConfig_v1700__successHO_Config_r17__cond ::
 Opt OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__Type OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__cond ::
 Opt OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__Type OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__cond ::
 Opt OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__Type OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__cond ::
 Opt OtherConfig_v1700__rlm_RelaxationReportingConfig_r17__Type OtherConfig_v1700__rlm_RelaxationReportingConfig_r17__cond ::
 Opt OtherConfig_v1700__bfd_RelaxationReportingConfig_r17__Type OtherConfig_v1700__bfd_RelaxationReportingConfig_r17__cond ::
 Opt OtherConfig_v1700__scg_DeactivationPreferenceConfig_r17__Type OtherConfig_v1700__scg_DeactivationPreferenceConfig_r17__cond ::
 Opt OtherConfig_v1700__rrm_MeasRelaxationReportingConfig_r17__Type OtherConfig_v1700__rrm_MeasRelaxationReportingConfig_r17__cond ::
 Opt OtherConfig_v1700__propDelayDiffReportConfig_r17__Type OtherConfig_v1700__propDelayDiffReportConfig_r17__cond ::
 nil).
Definition OtherConfig_v1700__cond z := 
  opt_cond OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__cond (OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17 z) /\
  opt_cond OtherConfig_v1700__musim_GapAssistanceConfig_r17__cond (OtherConfig_v1700__musim_GapAssistanceConfig_r17 z) /\
  opt_cond OtherConfig_v1700__musim_LeaveAssistanceConfig_r17__cond (OtherConfig_v1700__musim_LeaveAssistanceConfig_r17 z) /\
  opt_cond OtherConfig_v1700__successHO_Config_r17__cond (OtherConfig_v1700__successHO_Config_r17 z) /\
  opt_cond OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__cond (OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17 z) /\
  opt_cond OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__cond (OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17 z) /\
  opt_cond OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__cond (OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17 z) /\
  opt_cond OtherConfig_v1700__rlm_RelaxationReportingConfig_r17__cond (OtherConfig_v1700__rlm_RelaxationReportingConfig_r17 z) /\
  opt_cond OtherConfig_v1700__bfd_RelaxationReportingConfig_r17__cond (OtherConfig_v1700__bfd_RelaxationReportingConfig_r17 z) /\
  opt_cond OtherConfig_v1700__scg_DeactivationPreferenceConfig_r17__cond (OtherConfig_v1700__scg_DeactivationPreferenceConfig_r17 z) /\
  opt_cond OtherConfig_v1700__rrm_MeasRelaxationReportingConfig_r17__cond (OtherConfig_v1700__rrm_MeasRelaxationReportingConfig_r17 z) /\
  opt_cond OtherConfig_v1700__propDelayDiffReportConfig_r17__cond (OtherConfig_v1700__propDelayDiffReportConfig_r17 z) /\
  True.


Opaque Byte.to_nat Byte.of_nat.
Opaque bind_parse restrict_parse proj_parse return_parse.
Opaque restrict_serialize proj_serialize sigma_serialize append_serialize proj2_serialize.

Opaque read_n_nat read_unit.
Opaque put_n_nat put_unit. 

Opaque opt_bind opt_serialize dft_serialize prepend_serialize list_serial.
Opaque opt_parse list_parse dft_parse fail_parse append_parse
  bind_parse return_parse.

Opaque Z.to_nat Z.of_nat Z.sub Z.add Z.le Z.lt Z.pow Z.opp Z.ltb.
Opaque Nat.mul Nat.shiftr Nat.shiftl Nat.div Nat.modulo Nat.leb Nat.ltb Nat.add
  Nat.sub Nat.land Nat.lor Nat.eqb  Nat.log2 Nat.pow Nat.even PeanoNat.Nat.lnot.
Opaque Compare_dec.le_dec Compare_dec.le_lt_dec ZArith_dec.Z_le_dec lt_eq_lt_dec_new. 
Opaque sumbool_and1 list_and list_and_cons list_cons_S flg_add. 

Opaque list_to_len.
   Opaque length Compare_dec.le_dec Compare_dec.lt_dec PeanoNat.Nat.eq_dec.
   Opaque bool__Format int__Format octet_string_nc__Format bit_string_nc__Format.

   Opaque ByteIdx_to_nat nat_to_ByteIdx add_opt list_bool_format normally_small_len_det_format
  get_byte_len to_parse_skip  open_typ_serialize open_typ_parse open_type_to_len.
  

Opaque seq_cond seq_ext_cond choice_cond.
Definition OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__Format : T_Format OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__nat__Format OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__F1 OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__F2 OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__F1F2 OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__F2F1.

Opaque OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__cond OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__Format.

Opaque OtherConfig_v1700__musim_GapAssistanceConfig_r17__cond OtherConfig_v1700__musim_GapAssistanceConfig_r17__Format.

Opaque OtherConfig_v1700__musim_LeaveAssistanceConfig_r17__cond OtherConfig_v1700__musim_LeaveAssistanceConfig_r17__Format.

Opaque OtherConfig_v1700__successHO_Config_r17__cond OtherConfig_v1700__successHO_Config_r17__Format.

Definition OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__Format : T_Format OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__nat__Format OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__F1 OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__F2 OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__F1F2 OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__F2F1.

Opaque OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__cond OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__Format.

Definition OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__Format : T_Format OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__nat__Format OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__F1 OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__F2 OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__F1F2 OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__F2F1.

Opaque OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__cond OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__Format.

Definition OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__Format : T_Format OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__nat__Format OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__F1 OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__F2 OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__F1F2 OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__F2F1.

Opaque OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__cond OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__Format.

Opaque OtherConfig_v1700__rlm_RelaxationReportingConfig_r17__cond OtherConfig_v1700__rlm_RelaxationReportingConfig_r17__Format.

Opaque OtherConfig_v1700__bfd_RelaxationReportingConfig_r17__cond OtherConfig_v1700__bfd_RelaxationReportingConfig_r17__Format.

Opaque OtherConfig_v1700__scg_DeactivationPreferenceConfig_r17__cond OtherConfig_v1700__scg_DeactivationPreferenceConfig_r17__Format.

Opaque OtherConfig_v1700__rrm_MeasRelaxationReportingConfig_r17__cond OtherConfig_v1700__rrm_MeasRelaxationReportingConfig_r17__Format.

Opaque OtherConfig_v1700__propDelayDiffReportConfig_r17__cond OtherConfig_v1700__propDelayDiffReportConfig_r17__Format.


Definition OtherConfig_v1700__Format_Type := Eval cbn in seq_format_prod OtherConfig_v1700__list.
Definition OtherConfig_v1700__Format_list : OtherConfig_v1700__Format_Type :=
  (OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17__Format, (OtherConfig_v1700__musim_GapAssistanceConfig_r17__Format, (OtherConfig_v1700__musim_LeaveAssistanceConfig_r17__Format, (OtherConfig_v1700__successHO_Config_r17__Format, (OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17__Format, (OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17__Format, (OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17__Format, (OtherConfig_v1700__rlm_RelaxationReportingConfig_r17__Format, (OtherConfig_v1700__bfd_RelaxationReportingConfig_r17__Format, (OtherConfig_v1700__scg_DeactivationPreferenceConfig_r17__Format, (OtherConfig_v1700__rrm_MeasRelaxationReportingConfig_r17__Format, (OtherConfig_v1700__propDelayDiffReportConfig_r17__Format, unit_format)))))))))))).
Definition OtherConfig_v1700__list__Format := (*Eval compute in *) seq_format OtherConfig_v1700__list OtherConfig_v1700__Format_list.
Definition OtherConfig_v1700__F1 z :=
  (OtherConfig_v1700__ul_GapFR2_PreferenceConfig_r17 z, (OtherConfig_v1700__musim_GapAssistanceConfig_r17 z, (OtherConfig_v1700__musim_LeaveAssistanceConfig_r17 z, (OtherConfig_v1700__successHO_Config_r17 z, (OtherConfig_v1700__maxBW_PreferenceConfigFR2_2_r17 z, (OtherConfig_v1700__maxMIMO_LayerPreferenceConfigFR2_2_r17 z, (OtherConfig_v1700__minSchedulingOffsetPreferenceConfigExt_r17 z, (OtherConfig_v1700__rlm_RelaxationReportingConfig_r17 z, (OtherConfig_v1700__bfd_RelaxationReportingConfig_r17 z, (OtherConfig_v1700__scg_DeactivationPreferenceConfig_r17 z, (OtherConfig_v1700__rrm_MeasRelaxationReportingConfig_r17 z, (OtherConfig_v1700__propDelayDiffReportConfig_r17 z, tt)))))))))))).
Definition OtherConfig_v1700__F2 (y : seq_type OtherConfig_v1700__list) :=
  match y with
  | (i0, (i1, (i2, (i3, (i4, (i5, (i6, (i7, (i8, (i9, (i10, (i11, _))))))))))))=>
    make__OtherConfig_v1700__Type i0 i1 i2 i3 i4 i5 i6 i7 i8 i9 i10 i11
  end.
Lemma OtherConfig_v1700__F1F2_cond (z : OtherConfig_v1700__Type)
  : OtherConfig_v1700__cond z ->
  (seq_cond OtherConfig_v1700__list (OtherConfig_v1700__F1 z)).
intro H. unfold OtherConfig_v1700__cond in H. simpl. auto. Qed.
Lemma OtherConfig_v1700__F1F2_cond2 (z : OtherConfig_v1700__Type)
 : OtherConfig_v1700__F2 (OtherConfig_v1700__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma OtherConfig_v1700__F2F1_cond (y : seq_type OtherConfig_v1700__list)
  : seq_cond OtherConfig_v1700__list y ->
 (OtherConfig_v1700__cond (OtherConfig_v1700__F2 y)) /\  OtherConfig_v1700__F1 (OtherConfig_v1700__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold OtherConfig_v1700__cond. simpl in *. auto.
 - simpl. unfold OtherConfig_v1700__F1. simpl. destruct_all_unit. auto.   Qed.
Definition OtherConfig_v1700__Format : T_Format OtherConfig_v1700__Type OtherConfig_v1700__cond :=
        proj2_format  OtherConfig_v1700__cond OtherConfig_v1700__list__Format
    OtherConfig_v1700__F1 OtherConfig_v1700__F2 OtherConfig_v1700__F1F2_cond  OtherConfig_v1700__F1F2_cond2 OtherConfig_v1700__F2F1_cond.
Opaque OtherConfig_v1700__cond OtherConfig_v1700__Format.

