Require Import ASN1Parser.ExtrOCaml.ExtractHelper.

Require Import NR.NR_RRC_Definitions.
Require Import NR.PDCCH_BlindDetectionCA_MixedExt_r16.

Opaque PDCCH_BlindDetectionCA_MixedExt_r16__cond PDCCH_BlindDetectionCA_MixedExt_r16__Format.

Require Import NR.PDCCH_BlindDetectionCA_MixedExt_r16.

Opaque PDCCH_BlindDetectionCA_MixedExt_r16__cond PDCCH_BlindDetectionCA_MixedExt_r16__Format.


Inductive PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__Type : Set :=
  | PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__pdcch_BlindDetectionCA_Mixed_v16a0 : PDCCH_BlindDetectionCA_MixedExt_r16__Type -> PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__Type
  | PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_v16a0 : PDCCH_BlindDetectionCA_MixedExt_r16__Type -> PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__Type
.
Definition PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__list : list typ := (
typ_cons PDCCH_BlindDetectionCA_MixedExt_r16__Type PDCCH_BlindDetectionCA_MixedExt_r16__cond ::
typ_cons PDCCH_BlindDetectionCA_MixedExt_r16__Type PDCCH_BlindDetectionCA_MixedExt_r16__cond ::
 nil).
Definition PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__cond (c : PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__Type) := 
  match c with
  | PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__pdcch_BlindDetectionCA_Mixed_v16a0 t => PDCCH_BlindDetectionCA_MixedExt_r16__cond t 
  | PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_v16a0 t => PDCCH_BlindDetectionCA_MixedExt_r16__cond t 
  end.

Lemma PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__len_helper1 : to_bit_sz (length PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__list - 1) <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia. Qed.
Lemma PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__len_helper2 : 2 <= length2 PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__list.
 simpl. lia. Qed.
Require Import NR.PDCCH_BlindDetectionCG_UE_MixedExt_r16.

Opaque PDCCH_BlindDetectionCG_UE_MixedExt_r16__cond PDCCH_BlindDetectionCG_UE_MixedExt_r16__Format.

Require Import NR.PDCCH_BlindDetectionCG_UE_MixedExt_r16.

Opaque PDCCH_BlindDetectionCG_UE_MixedExt_r16__cond PDCCH_BlindDetectionCG_UE_MixedExt_r16__Format.

Record PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__Type : Set :=
  make__PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__Type {
    PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__pdcch_BlindDetectionMCG_UE_Mixed_v16a0 : PDCCH_BlindDetectionCG_UE_MixedExt_r16__Type ;
    PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__pdcch_BlindDetectionSCG_UE_Mixed_v16a0 : PDCCH_BlindDetectionCG_UE_MixedExt_r16__Type ;
}.
Definition PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__list := (
 Nor PDCCH_BlindDetectionCG_UE_MixedExt_r16__Type PDCCH_BlindDetectionCG_UE_MixedExt_r16__cond ::
 Nor PDCCH_BlindDetectionCG_UE_MixedExt_r16__Type PDCCH_BlindDetectionCG_UE_MixedExt_r16__cond ::
 nil).
Definition PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__cond z := 
  PDCCH_BlindDetectionCG_UE_MixedExt_r16__cond (PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__pdcch_BlindDetectionMCG_UE_Mixed_v16a0 z) /\
  PDCCH_BlindDetectionCG_UE_MixedExt_r16__cond (PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__pdcch_BlindDetectionSCG_UE_Mixed_v16a0 z) /\
  True.

Record PDCCH_BlindDetectionMixedList_r16__Type : Set :=
  make__PDCCH_BlindDetectionMixedList_r16__Type {
    PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16 : option PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__Type ;
    PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16 : option PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__Type ;
}.
Definition PDCCH_BlindDetectionMixedList_r16__list := (
 Opt PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__Type PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__cond ::
 Opt PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__Type PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__cond ::
 nil).
Definition PDCCH_BlindDetectionMixedList_r16__cond z := 
  opt_cond PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__cond (PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16 z) /\
  opt_cond PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__cond (PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16 z) /\
  True.


Opaque Byte.to_nat Byte.of_nat.
Opaque bind_parse restrict_parse proj_parse return_parse.
Opaque restrict_serialize proj_serialize sigma_serialize append_serialize proj2_serialize.

Opaque read_n_nat read_unit.
Opaque put_n_nat put_unit. 

Opaque opt_bind opt_serialize dft_serialize prepend_serialize list_serial.
Opaque opt_parse list_parse dft_parse fail_parse append_parse
  bind_parse return_parse.

Opaque Z.to_nat Z.of_nat Z.sub Z.add Z.le Z.lt Z.pow Z.opp Z.ltb.
Opaque Nat.mul Nat.shiftr Nat.shiftl Nat.div Nat.modulo Nat.leb Nat.ltb Nat.add
  Nat.sub Nat.land Nat.lor Nat.eqb  Nat.log2 Nat.pow Nat.even PeanoNat.Nat.lnot.
Opaque Compare_dec.le_dec Compare_dec.le_lt_dec ZArith_dec.Z_le_dec lt_eq_lt_dec_new. 
Opaque sumbool_and1 list_and list_and_cons list_cons_S flg_add. 

Opaque list_to_len.
   Opaque length Compare_dec.le_dec Compare_dec.lt_dec PeanoNat.Nat.eq_dec.
   Opaque bool__Format int__Format octet_string_nc__Format bit_string_nc__Format.

   Opaque ByteIdx_to_nat nat_to_ByteIdx add_opt list_bool_format normally_small_len_det_format
  get_byte_len to_parse_skip  open_typ_serialize open_typ_parse open_type_to_len.
  

Opaque seq_cond seq_ext_cond choice_cond.

Definition PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__Format_Type := Eval cbn in get_formats PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__list.
Definition PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__Format_list : PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__Format_Type :=
  (PDCCH_BlindDetectionCA_MixedExt_r16__Format, (PDCCH_BlindDetectionCA_MixedExt_r16__Format, unit__Format)).
Definition PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__list__Format := Eval compute in choice_format PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__list PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__len_helper1 PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__len_helper2  PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__Format_list.
Definition PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__F1 (z : PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__Type) : (choice PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__list) :=
  match z with
   | PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__pdcch_BlindDetectionCA_Mixed_v16a0 t => existT _ 0 t
  | PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_v16a0 t => existT _ 1 t
  end.
Definition PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__g := (fun n => typ_set (get_nth_typ PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__list n)).
Definition PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__F2 (y : choice PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__list) : PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__Type :=
  let (x0, t0) := y in
    (match x0 as n return  (PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__g n -> PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__Type) with
    | 0 => fun (t : PDCCH_BlindDetectionCA_MixedExt_r16__Type) => PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__pdcch_BlindDetectionCA_Mixed_v16a0 t 
    | 1 => fun (t : PDCCH_BlindDetectionCA_MixedExt_r16__Type) => PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_v16a0 t 
 | (S (S n0)) => (fun (x' : nat) (t'' : PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__g (S (S x'))) =>let t' :=
           eq_rect (get_nth_typ PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__list (S (S x')))
           (fun t' : typ => typ_set t') t'' empty_typ
           (get_nth_typ_ge_len PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__list (S (S x'))
           (le_n_S _ _ (le_n_S _ _ (le_0_n x')))) in match t' return PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__Type with end) n0
           end t0).

Lemma PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__helper2 :  forall (y : PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__Type), PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__cond y -> choice_cond PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__list (PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__F1 y).
  choice_helper_tact_dec y. Qed.

Lemma PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__helper3 :  forall (y : PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__Type), PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__F2 (PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__F1 y) = y.
  choice_helper_tact_dec y. Qed.

Transparent length.
Lemma PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__helper4 : (forall b : choice PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__list, choice_cond PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__list b -> PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__cond (PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__F2 b) /\ PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__F1 (PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__F2 b) = b).
Proof. intros. destruct b as [x t]; split; choice_helper_tact0 H x t. Qed.
Opaque length PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__F1 PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__F2.
Definition PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__Format : T_Format PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__Type PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__cond :=
  (* Eval compute in *) proj2_format PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__cond PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__list__Format PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__F1 PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__F2 PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__helper2 PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__helper3 PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__helper4.
Opaque PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__cond PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__Format.


Definition PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__Format_Type := Eval cbn in seq_format_prod PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__list.
Definition PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__Format_list : PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__Format_Type :=
  (PDCCH_BlindDetectionCG_UE_MixedExt_r16__Format, (PDCCH_BlindDetectionCG_UE_MixedExt_r16__Format, unit_format)).
Definition PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__list__Format := (*Eval compute in *) seq_format PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__list PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__Format_list.
Definition PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__F1 z :=
  (PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__pdcch_BlindDetectionMCG_UE_Mixed_v16a0 z, (PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__pdcch_BlindDetectionSCG_UE_Mixed_v16a0 z, tt)).
Definition PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__F2 (y : seq_type PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__list) :=
  match y with
  | (i0, (i1, _))=>
    make__PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__Type i0 i1
  end.
Lemma PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__F1F2_cond (z : PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__Type)
  : PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__cond z ->
  (seq_cond PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__list (PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__F1 z)).
intro H. unfold PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__cond in H. simpl. auto. Qed.
Lemma PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__F1F2_cond2 (z : PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__Type)
 : PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__F2 (PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__F2F1_cond (y : seq_type PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__list)
  : seq_cond PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__list y ->
 (PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__cond (PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__F2 y)) /\  PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__F1 (PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__cond. simpl in *. auto.
 - simpl. unfold PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__F1. simpl. destruct_all_unit. auto.   Qed.
Definition PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__Format : T_Format PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__Type PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__cond :=
        proj2_format  PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__cond PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__list__Format
    PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__F1 PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__F2 PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__F1F2_cond  PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__F1F2_cond2 PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__F2F1_cond.
Opaque PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__cond PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__Format.


Definition PDCCH_BlindDetectionMixedList_r16__Format_Type := Eval cbn in seq_format_prod PDCCH_BlindDetectionMixedList_r16__list.
Definition PDCCH_BlindDetectionMixedList_r16__Format_list : PDCCH_BlindDetectionMixedList_r16__Format_Type :=
  (PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16__Format, (PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16__Format, unit_format)).
Definition PDCCH_BlindDetectionMixedList_r16__list__Format := (*Eval compute in *) seq_format PDCCH_BlindDetectionMixedList_r16__list PDCCH_BlindDetectionMixedList_r16__Format_list.
Definition PDCCH_BlindDetectionMixedList_r16__F1 z :=
  (PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCA_MixedExt_r16 z, (PDCCH_BlindDetectionMixedList_r16__pdcch_BlindDetectionCG_UE_MixedExt_r16 z, tt)).
Definition PDCCH_BlindDetectionMixedList_r16__F2 (y : seq_type PDCCH_BlindDetectionMixedList_r16__list) :=
  match y with
  | (i0, (i1, _))=>
    make__PDCCH_BlindDetectionMixedList_r16__Type i0 i1
  end.
Lemma PDCCH_BlindDetectionMixedList_r16__F1F2_cond (z : PDCCH_BlindDetectionMixedList_r16__Type)
  : PDCCH_BlindDetectionMixedList_r16__cond z ->
  (seq_cond PDCCH_BlindDetectionMixedList_r16__list (PDCCH_BlindDetectionMixedList_r16__F1 z)).
intro H. unfold PDCCH_BlindDetectionMixedList_r16__cond in H. simpl. auto. Qed.
Lemma PDCCH_BlindDetectionMixedList_r16__F1F2_cond2 (z : PDCCH_BlindDetectionMixedList_r16__Type)
 : PDCCH_BlindDetectionMixedList_r16__F2 (PDCCH_BlindDetectionMixedList_r16__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma PDCCH_BlindDetectionMixedList_r16__F2F1_cond (y : seq_type PDCCH_BlindDetectionMixedList_r16__list)
  : seq_cond PDCCH_BlindDetectionMixedList_r16__list y ->
 (PDCCH_BlindDetectionMixedList_r16__cond (PDCCH_BlindDetectionMixedList_r16__F2 y)) /\  PDCCH_BlindDetectionMixedList_r16__F1 (PDCCH_BlindDetectionMixedList_r16__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold PDCCH_BlindDetectionMixedList_r16__cond. simpl in *. auto.
 - simpl. unfold PDCCH_BlindDetectionMixedList_r16__F1. simpl. destruct_all_unit. auto.   Qed.
Definition PDCCH_BlindDetectionMixedList_r16__Format : T_Format PDCCH_BlindDetectionMixedList_r16__Type PDCCH_BlindDetectionMixedList_r16__cond :=
        proj2_format  PDCCH_BlindDetectionMixedList_r16__cond PDCCH_BlindDetectionMixedList_r16__list__Format
    PDCCH_BlindDetectionMixedList_r16__F1 PDCCH_BlindDetectionMixedList_r16__F2 PDCCH_BlindDetectionMixedList_r16__F1F2_cond  PDCCH_BlindDetectionMixedList_r16__F1F2_cond2 PDCCH_BlindDetectionMixedList_r16__F2F1_cond.
Opaque PDCCH_BlindDetectionMixedList_r16__cond PDCCH_BlindDetectionMixedList_r16__Format.

