Require Import ASN1Parser.ExtrOCaml.ExtractHelper.

Require Import NR.NR_RRC_Definitions.
Inductive PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__Type : Set :=
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw5
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw10
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw15
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw20
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw25
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw30
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw35
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw40
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw45
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw50
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw60
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw70
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw80
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw90
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw100
.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__cond := (fun (_ : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__Type) => True).
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__nat__helper : to_bit_sz 14 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__nat__Format : T_Format nat (fun z => (z <= 14)) :=
  nat_enum_format 14 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__nat__helper.

Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__F1 t :=
  match t with
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw5 => 0
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw10 => 1
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw15 => 2
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw20 => 3
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw25 => 4
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw30 => 5
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw35 => 6
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw40 => 7
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw45 => 8
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw50 => 9
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw60 => 10
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw70 => 11
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw80 => 12
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw90 => 13
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw100 => 14
  end.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__F2 n :=
  match n with
  | 0 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw5
  | 1 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw10
  | 2 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw15
  | 3 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw20
  | 4 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw25
  | 5 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw30
  | 6 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw35
  | 7 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw40
  | 8 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw45
  | 9 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw50
  | 10 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw60
  | 11 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw70
  | 12 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw80
  | 13 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw90
  | 14 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw100
  | _ => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__bw5
  end.
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__F1F2 : forall x : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__Type, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__F1 x <= 14) /\ PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__F2 (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__F1 x) = x. imp_solve. Qed.
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__F2F1 : forall (y : nat) (H : y <= 14), PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__F1 (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__F2 y) = y. enum_solve H y. Qed.

Inductive PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__Type : Set :=
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__bw50
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__bw100
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__bw200
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__bw400
.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__cond := (fun (_ : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__Type) => True).
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__nat__helper : to_bit_sz 3 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__nat__Format : T_Format nat (fun z => (z <= 3)) :=
  nat_enum_format 3 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__nat__helper.

Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__F1 t :=
  match t with
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__bw50 => 0
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__bw100 => 1
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__bw200 => 2
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__bw400 => 3
  end.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__F2 n :=
  match n with
  | 0 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__bw50
  | 1 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__bw100
  | 2 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__bw200
  | 3 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__bw400
  | _ => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__bw50
  end.
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__F1F2 : forall x : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__Type, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__F1 x <= 3) /\ PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__F2 (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__F1 x) = x. imp_solve. Qed.
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__F2F1 : forall (y : nat) (H : y <= 3), PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__F1 (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__F2 y) = y. enum_solve H y. Qed.

Inductive PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__Type : Set :=
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__n1
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__n2
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__n4
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__n8
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__n12
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__n16
.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__cond := (fun (_ : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__Type) => True).
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__nat__helper : to_bit_sz 5 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__nat__Format : T_Format nat (fun z => (z <= 5)) :=
  nat_enum_format 5 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__nat__helper.

Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__F1 t :=
  match t with
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__n1 => 0
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__n2 => 1
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__n4 => 2
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__n8 => 3
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__n12 => 4
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__n16 => 5
  end.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__F2 n :=
  match n with
  | 0 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__n1
  | 1 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__n2
  | 2 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__n4
  | 3 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__n8
  | 4 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__n12
  | 5 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__n16
  | _ => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__n1
  end.
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__F1F2 : forall x : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__Type, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__F1 x <= 5) /\ PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__F2 (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__F1 x) = x. imp_solve. Qed.
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__F2F1 : forall (y : nat) (H : y <= 5), PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__F1 (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__F2 y) = y. enum_solve H y. Qed.

Inductive PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__Type : Set :=
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__n1
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__n2
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__n4
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__n8
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__n16
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__n32
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__n64
.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__cond := (fun (_ : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__Type) => True).
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__nat__helper : to_bit_sz 6 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__nat__Format : T_Format nat (fun z => (z <= 6)) :=
  nat_enum_format 6 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__nat__helper.

Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__F1 t :=
  match t with
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__n1 => 0
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__n2 => 1
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__n4 => 2
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__n8 => 3
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__n16 => 4
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__n32 => 5
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__n64 => 6
  end.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__F2 n :=
  match n with
  | 0 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__n1
  | 1 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__n2
  | 2 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__n4
  | 3 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__n8
  | 4 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__n16
  | 5 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__n32
  | 6 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__n64
  | _ => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__n1
  end.
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__F1F2 : forall x : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__Type, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__F1 x <= 6) /\ PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__F2 (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__F1 x) = x. imp_solve. Qed.
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__F2F1 : forall (y : nat) (H : y <= 6), PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__F1 (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__F2 y) = y. enum_solve H y. Qed.

Inductive PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__Type : Set :=
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__n1
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__n2
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__n3
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__n4
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__n5
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__n6
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__n8
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__n10
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__n12
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__n14
.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__cond := (fun (_ : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__Type) => True).
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__nat__helper : to_bit_sz 9 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__nat__Format : T_Format nat (fun z => (z <= 9)) :=
  nat_enum_format 9 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__nat__helper.

Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__F1 t :=
  match t with
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__n1 => 0
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__n2 => 1
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__n3 => 2
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__n4 => 3
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__n5 => 4
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__n6 => 5
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__n8 => 6
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__n10 => 7
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__n12 => 8
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__n14 => 9
  end.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__F2 n :=
  match n with
  | 0 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__n1
  | 1 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__n2
  | 2 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__n3
  | 3 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__n4
  | 4 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__n5
  | 5 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__n6
  | 6 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__n8
  | 7 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__n10
  | 8 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__n12
  | 9 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__n14
  | _ => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__n1
  end.
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__F1F2 : forall x : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__Type, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__F1 x <= 9) /\ PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__F2 (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__F1 x) = x. imp_solve. Qed.
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__F2F1 : forall (y : nat) (H : y <= 9), PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__F1 (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__F2 y) = y. enum_solve H y. Qed.

Inductive PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__Type : Set :=
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__supported
.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__cond := (fun (_ : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__Type) => True).
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__nat__helper.

Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__F1 t :=
  match t with
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__supported => 0
  end.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__F2 n :=
  match n with
  | 0 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__supported
  | _ => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__supported
  end.
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__F1F2 : forall x : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__Type, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__F1 x <= 0) /\ PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__F2 (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__F1 x) = x. imp_solve. Qed.
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__F2F1 : forall (y : nat) (H : y <= 0), PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__F1 (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__F2 y) = y. enum_solve H y. Qed.

Inductive PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__Type : Set :=
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__supported
.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__cond := (fun (_ : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__Type) => True).
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__nat__helper.

Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__F1 t :=
  match t with
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__supported => 0
  end.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__F2 n :=
  match n with
  | 0 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__supported
  | _ => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__supported
  end.
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__F1F2 : forall x : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__Type, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__F1 x <= 0) /\ PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__F2 (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__F1 x) = x. imp_solve. Qed.
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__F2F1 : forall (y : nat) (H : y <= 0), PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__F1 (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__F2 y) = y. enum_solve H y. Qed.

Inductive PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__Type : Set :=
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__n1
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__n2
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__n4
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__n8
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__n16
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__n32
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__n64
.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__cond := (fun (_ : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__Type) => True).
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__nat__helper : to_bit_sz 6 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__nat__Format : T_Format nat (fun z => (z <= 6)) :=
  nat_enum_format 6 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__nat__helper.

Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__F1 t :=
  match t with
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__n1 => 0
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__n2 => 1
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__n4 => 2
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__n8 => 3
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__n16 => 4
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__n32 => 5
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__n64 => 6
  end.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__F2 n :=
  match n with
  | 0 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__n1
  | 1 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__n2
  | 2 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__n4
  | 3 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__n8
  | 4 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__n16
  | 5 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__n32
  | 6 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__n64
  | _ => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__n1
  end.
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__F1F2 : forall x : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__Type, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__F1 x <= 6) /\ PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__F2 (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__F1 x) = x. imp_solve. Qed.
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__F2F1 : forall (y : nat) (H : y <= 6), PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__F1 (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__F2 y) = y. enum_solve H y. Qed.

Inductive PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__Type : Set :=
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__n1
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__n2
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__n3
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__n4
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__n5
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__n6
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__n8
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__n10
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__n12
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__n14
.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__cond := (fun (_ : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__Type) => True).
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__nat__helper : to_bit_sz 9 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__nat__Format : T_Format nat (fun z => (z <= 9)) :=
  nat_enum_format 9 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__nat__helper.

Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__F1 t :=
  match t with
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__n1 => 0
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__n2 => 1
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__n3 => 2
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__n4 => 3
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__n5 => 4
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__n6 => 5
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__n8 => 6
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__n10 => 7
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__n12 => 8
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__n14 => 9
  end.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__F2 n :=
  match n with
  | 0 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__n1
  | 1 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__n2
  | 2 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__n3
  | 3 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__n4
  | 4 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__n5
  | 5 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__n6
  | 6 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__n8
  | 7 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__n10
  | 8 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__n12
  | 9 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__n14
  | _ => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__n1
  end.
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__F1F2 : forall x : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__Type, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__F1 x <= 9) /\ PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__F2 (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__F1 x) = x. imp_solve. Qed.
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__F2F1 : forall (y : nat) (H : y <= 9), PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__F1 (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__F2 y) = y. enum_solve H y. Qed.

Inductive PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__Type : Set :=
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__supported
.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__cond := (fun (_ : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__Type) => True).
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__nat__helper.

Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__F1 t :=
  match t with
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__supported => 0
  end.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__F2 n :=
  match n with
  | 0 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__supported
  | _ => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__supported
  end.
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__F1F2 : forall x : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__Type, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__F1 x <= 0) /\ PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__F2 (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__F1 x) = x. imp_solve. Qed.
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__F2F1 : forall (y : nat) (H : y <= 0), PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__F1 (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__F2 y) = y. enum_solve H y. Qed.

Inductive PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__Type : Set :=
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__us100
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__us140
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__us200
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__us300
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__us500
.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__cond := (fun (_ : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__Type) => True).
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__nat__helper : to_bit_sz 4 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__nat__Format : T_Format nat (fun z => (z <= 4)) :=
  nat_enum_format 4 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__nat__helper.

Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__F1 t :=
  match t with
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__us100 => 0
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__us140 => 1
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__us200 => 2
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__us300 => 3
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__us500 => 4
  end.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__F2 n :=
  match n with
  | 0 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__us100
  | 1 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__us140
  | 2 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__us200
  | 3 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__us300
  | 4 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__us500
  | _ => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__us100
  end.
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__F1F2 : forall x : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__Type, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__F1 x <= 4) /\ PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__F2 (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__F1 x) = x. imp_solve. Qed.
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__F2F1 : forall (y : nat) (H : y <= 4), PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__F1 (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__F2 y) = y. enum_solve H y. Qed.

Inductive PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__Type : Set :=
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__n1
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__n2
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__n4
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__n8
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__n16
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__n32
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__n64
.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__cond := (fun (_ : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__Type) => True).
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__nat__helper : to_bit_sz 6 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__nat__Format : T_Format nat (fun z => (z <= 6)) :=
  nat_enum_format 6 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__nat__helper.

Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__F1 t :=
  match t with
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__n1 => 0
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__n2 => 1
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__n4 => 2
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__n8 => 3
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__n16 => 4
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__n32 => 5
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__n64 => 6
  end.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__F2 n :=
  match n with
  | 0 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__n1
  | 1 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__n2
  | 2 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__n4
  | 3 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__n8
  | 4 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__n16
  | 5 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__n32
  | 6 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__n64
  | _ => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__n1
  end.
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__F1F2 : forall x : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__Type, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__F1 x <= 6) /\ PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__F2 (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__F1 x) = x. imp_solve. Qed.
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__F2F1 : forall (y : nat) (H : y <= 6), PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__F1 (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__F2 y) = y. enum_solve H y. Qed.

Inductive PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__Type : Set :=
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__n1
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__n2
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__n3
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__n4
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__n5
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__n6
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__n8
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__n10
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__n12
 | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__n14
.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__cond := (fun (_ : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__Type) => True).
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__nat__helper : to_bit_sz 9 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__nat__Format : T_Format nat (fun z => (z <= 9)) :=
  nat_enum_format 9 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__nat__helper.

Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__F1 t :=
  match t with
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__n1 => 0
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__n2 => 1
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__n3 => 2
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__n4 => 3
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__n5 => 4
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__n6 => 5
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__n8 => 6
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__n10 => 7
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__n12 => 8
  | PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__n14 => 9
  end.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__F2 n :=
  match n with
  | 0 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__n1
  | 1 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__n2
  | 2 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__n3
  | 3 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__n4
  | 4 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__n5
  | 5 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__n6
  | 6 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__n8
  | 7 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__n10
  | 8 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__n12
  | 9 => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__n14
  | _ => PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__n1
  end.
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__F1F2 : forall x : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__Type, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__F1 x <= 9) /\ PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__F2 (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__F1 x) = x. imp_solve. Qed.
Lemma PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__F2F1 : forall (y : nat) (H : y <= 9), PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__F1 (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__F2 y) = y. enum_solve H y. Qed.

Record PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__Type : Set :=
  make__PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__Type {
    PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17 : option PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__Type ;
    PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17 : option PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__Type ;
    PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17 : option PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__Type ;
    PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17 : option PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__Type ;
    PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17 : option PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__Type ;
    PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17 : option PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__Type ;
    PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17 : option PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__Type ;
    PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17 : option PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__Type ;
    PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17 : option PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__Type ;
    PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17 : option PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__Type ;
    PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17 : option PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__Type ;
    PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17 : option PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__Type ;
    PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17 : option PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__Type ;
}.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__root_list : list seq_elem := (
 Opt PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__Type PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__cond ::
 Opt PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__Type PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__cond ::
 Opt PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__Type PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__cond ::
 Opt PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__Type PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__cond ::
 Opt PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__Type PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__cond ::
 Opt PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__Type PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__cond ::
 Opt PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__Type PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__cond ::
 Opt PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__Type PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__cond ::
 Opt PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__Type PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__cond ::
 Opt PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__Type PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__cond ::
 Opt PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__Type PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__cond ::
 Opt PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__Type PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__cond ::
 Opt PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__Type PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__cond ::
 nil).
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__ext_list : list typ := (
  nil).
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__cond (z : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__Type) := 
(  opt_cond PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__cond (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17 z) /\
  opt_cond PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__cond (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17 z) /\
  opt_cond PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__cond (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17 z) /\
  opt_cond PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__cond (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17 z) /\
  opt_cond PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__cond (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17 z) /\
  opt_cond PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__cond (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17 z) /\
  opt_cond PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__cond (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17 z) /\
  opt_cond PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__cond (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17 z) /\
  opt_cond PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__cond (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17 z) /\
  opt_cond PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__cond (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17 z) /\
  opt_cond PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__cond (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17 z) /\
  opt_cond PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__cond (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17 z) /\
  opt_cond PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__cond (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17 z) /\
  True) /\ 
(  True).


Opaque Byte.to_nat Byte.of_nat.
Opaque bind_parse restrict_parse proj_parse return_parse.
Opaque restrict_serialize proj_serialize sigma_serialize append_serialize proj2_serialize.

Opaque read_n_nat read_unit.
Opaque put_n_nat put_unit. 

Opaque opt_bind opt_serialize dft_serialize prepend_serialize list_serial.
Opaque opt_parse list_parse dft_parse fail_parse append_parse
  bind_parse return_parse.

Opaque Z.to_nat Z.of_nat Z.sub Z.add Z.le Z.lt Z.pow Z.opp Z.ltb.
Opaque Nat.mul Nat.shiftr Nat.shiftl Nat.div Nat.modulo Nat.leb Nat.ltb Nat.add
  Nat.sub Nat.land Nat.lor Nat.eqb  Nat.log2 Nat.pow Nat.even PeanoNat.Nat.lnot.
Opaque Compare_dec.le_dec Compare_dec.le_lt_dec ZArith_dec.Z_le_dec lt_eq_lt_dec_new. 
Opaque sumbool_and1 list_and list_and_cons list_cons_S flg_add. 

Opaque list_to_len.
   Opaque length Compare_dec.le_dec Compare_dec.lt_dec PeanoNat.Nat.eq_dec.
   Opaque bool__Format int__Format octet_string_nc__Format bit_string_nc__Format.

   Opaque ByteIdx_to_nat nat_to_ByteIdx add_opt list_bool_format normally_small_len_det_format
  get_byte_len to_parse_skip  open_typ_serialize open_typ_parse open_type_to_len.
  

Opaque seq_cond seq_ext_cond choice_cond.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__Format : T_Format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__nat__Format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__F1 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__F2 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__F1F2 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__F2F1.

Opaque PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__cond PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__Format.

Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__Format : T_Format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__nat__Format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__F1 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__F2 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__F1F2 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__F2F1.

Opaque PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__cond PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__Format.

Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__Format : T_Format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__nat__Format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__F1 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__F2 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__F1F2 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__F2F1.

Opaque PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__cond PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__Format.

Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__Format : T_Format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__nat__Format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__F1 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__F2 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__F1F2 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__F2F1.

Opaque PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__cond PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__Format.

Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__Format : T_Format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__nat__Format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__F1 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__F2 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__F1F2 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__F2F1.

Opaque PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__cond PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__Format.

Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__Format : T_Format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__nat__Format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__F1 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__F2 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__F1F2 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__F2F1.

Opaque PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__cond PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__Format.

Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__Format : T_Format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__nat__Format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__F1 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__F2 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__F1F2 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__F2F1.

Opaque PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__cond PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__Format.

Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__Format : T_Format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__nat__Format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__F1 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__F2 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__F1F2 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__F2F1.

Opaque PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__cond PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__Format.

Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__Format : T_Format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__nat__Format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__F1 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__F2 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__F1F2 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__F2F1.

Opaque PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__cond PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__Format.

Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__Format : T_Format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__nat__Format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__F1 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__F2 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__F1F2 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__F2F1.

Opaque PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__cond PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__Format.

Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__Format : T_Format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__nat__Format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__F1 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__F2 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__F1F2 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__F2F1.

Opaque PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__cond PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__Format.

Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__Format : T_Format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__nat__Format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__F1 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__F2 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__F1F2 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__F2F1.

Opaque PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__cond PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__Format.

Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__Format : T_Format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__nat__Format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__F1 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__F2 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__F1F2 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__F2F1.

Opaque PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__cond PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__Format.


Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__root_Format_Type := Eval cbn in seq_format_prod PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__root_list.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__root_Format_list : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__root_Format_Type :=
  (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17__Format, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17__Format, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17__Format, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17__Format, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17__Format, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17__Format, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17__Format, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17__Format, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17__Format, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17__Format, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17__Format, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17__Format, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17__Format, unit_format))))))))))))).

Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__ext_Format_Type := Eval cbn in get_formats PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__ext_list.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__ext_Format_list : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__ext_Format_Type :=
  unit__Format.

Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__list_type : Set := (seq_type PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__root_list) * (seq_ext_type PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__ext_list).
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__list_cond (z : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__list_type) : Prop :=
        (seq_cond PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__root_list (fst z)) /\ (seq_ext_cond PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__ext_list (snd z)).
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__list_format : T_Format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__list_type PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__list_cond :=
 (* Eval compute in *) seq_ext_format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__root_list PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__root_Format_list PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__ext_list PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__ext_Format_list.

Opaque PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__list_format.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__F1 (z : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__Type) : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__list_type :=
  (((PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR1_r17 z, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxSRSposBandwidthForEachSCS_withinCC_FR2_r17 z, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17 z, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17 z, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17 z, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentNumerologyBetweenSRSposAndInitialBWP_r17 z, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__srsPosWithoutRestrictionOnBWP_r17 z, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResources_r17 z, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfPeriodicAndSemipersistentSRSposResourcesPerSlot_r17 z, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__differentCenterFreqBetweenSRSposAndInitialBWP_r17 z, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__switchingTimeSRS_TX_OtherTX_r17 z, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResources_r17 z, (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__maxNumOfSemiPersistentSRSposResourcesPerSlot_r17 z, tt)))))))))))))), (
tt)).
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__F2 (y : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__list_type) : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__Type :=
  match y with
  | ((j0, (j1, (j2, (j3, (j4, (j5, (j6, (j7, (j8, (j9, (j10, (j11, (j12, _))))))))))))), _)=>
    make__PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__Type j0 j1 j2 j3 j4 j5 j6 j7 j8 j9 j10 j11 j12
  end.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__helper1 : (forall a : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__Type, PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__cond a -> PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__list_cond (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__F1 a)).
                     intros. destruct a. auto. Qed.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__helper2 : (forall a : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__Type, PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__F2 (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__F1 a) = a).
                     intros. destruct a. auto. Qed.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__helper3 : (forall b : PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__list_type, PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__list_cond b -> PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__cond (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__F2 b) /\ PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__F1 (PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__F2 b) = b).
                     intros. destruct b as [y y1]. unfold PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__cond, PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__list_cond in *. simpl.
                     split; unfold seq_type, seq_ext_type in *; simpl in y, y1; repeat destruct_prod; split_and; simpl in *; destruct_all_unit; auto; repeat (split; auto). 

                     Qed.
Definition PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__Format : T_Format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__Type PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__cond :=
 proj2_format PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__cond PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__list_format  PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__F1 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__F2 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__helper1 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__helper2 PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__helper3.

Opaque PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__cond PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17__Format.

