Require Import ASN1Parser.ExtrOCaml.ExtractHelper.

Require Import NR.PC5_RRC_Definitions.
Inductive RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__Type : Set :=
 | RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__true
.
Definition RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__cond := (fun (_ : RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__Type) => True).
Lemma RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__nat__helper.

Definition RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__F1 t :=
  match t with
  | RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__true => 0
  end.
Definition RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__F2 n :=
  match n with
  | 0 => RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__true
  | _ => RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__true
  end.
Lemma RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__F1F2 : forall x : RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__Type, (RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__F1 x <= 0) /\ RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__F2 (RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__F1 x) = x. imp_solve. Qed.
Lemma RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__F2F1 : forall (y : nat) (H : y <= 0), RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__F1 (RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__F2 y) = y. enum_solve H y. Qed.

Record RRCReconfigurationCompleteSidelink_v1720_IEs__nonCriticalExtension__Type : Set := make__RRCReconfigurationCompleteSidelink_v1720_IEs__nonCriticalExtension__Type {}.
Definition RRCReconfigurationCompleteSidelink_v1720_IEs__nonCriticalExtension__cond (z : RRCReconfigurationCompleteSidelink_v1720_IEs__nonCriticalExtension__Type) := True.
Record RRCReconfigurationCompleteSidelink_v1720_IEs__Type : Set :=
  make__RRCReconfigurationCompleteSidelink_v1720_IEs__Type {
    RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720 : option RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__Type ;
    RRCReconfigurationCompleteSidelink_v1720_IEs__nonCriticalExtension : option RRCReconfigurationCompleteSidelink_v1720_IEs__nonCriticalExtension__Type ;
}.
Definition RRCReconfigurationCompleteSidelink_v1720_IEs__list := (
 Opt RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__Type RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__cond ::
 Opt RRCReconfigurationCompleteSidelink_v1720_IEs__nonCriticalExtension__Type RRCReconfigurationCompleteSidelink_v1720_IEs__nonCriticalExtension__cond ::
 nil).
Definition RRCReconfigurationCompleteSidelink_v1720_IEs__cond z := 
  opt_cond RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__cond (RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720 z) /\
  opt_cond RRCReconfigurationCompleteSidelink_v1720_IEs__nonCriticalExtension__cond (RRCReconfigurationCompleteSidelink_v1720_IEs__nonCriticalExtension z) /\
  True.


Opaque Byte.to_nat Byte.of_nat.
Opaque bind_parse restrict_parse proj_parse return_parse.
Opaque restrict_serialize proj_serialize sigma_serialize append_serialize proj2_serialize.

Opaque read_n_nat read_unit.
Opaque put_n_nat put_unit. 

Opaque opt_bind opt_serialize dft_serialize prepend_serialize list_serial.
Opaque opt_parse list_parse dft_parse fail_parse append_parse
  bind_parse return_parse.

Opaque Z.to_nat Z.of_nat Z.sub Z.add Z.le Z.lt Z.pow Z.opp Z.ltb.
Opaque Nat.mul Nat.shiftr Nat.shiftl Nat.div Nat.modulo Nat.leb Nat.ltb Nat.add
  Nat.sub Nat.land Nat.lor Nat.eqb  Nat.log2 Nat.pow Nat.even PeanoNat.Nat.lnot.
Opaque Compare_dec.le_dec Compare_dec.le_lt_dec ZArith_dec.Z_le_dec lt_eq_lt_dec_new. 
Opaque sumbool_and1 list_and list_and_cons list_cons_S flg_add. 

Opaque list_to_len.
   Opaque length Compare_dec.le_dec Compare_dec.lt_dec PeanoNat.Nat.eq_dec.
   Opaque bool__Format int__Format octet_string_nc__Format bit_string_nc__Format.

   Opaque ByteIdx_to_nat nat_to_ByteIdx add_opt list_bool_format normally_small_len_det_format
  get_byte_len to_parse_skip  open_typ_serialize open_typ_parse open_type_to_len.
  

Opaque seq_cond seq_ext_cond choice_cond.
Definition RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__Format : T_Format RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__Type (fun _ => True) :=
(* Eval compute in *) proj3_format RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__nat__Format RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__F1 RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__F2 RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__F1F2 RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__F2F1.

Opaque RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__cond RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__Format.

Definition RRCReconfigurationCompleteSidelink_v1720_IEs__nonCriticalExtension__helper : forall a : RRCReconfigurationCompleteSidelink_v1720_IEs__nonCriticalExtension__Type, True -> True /\ make__RRCReconfigurationCompleteSidelink_v1720_IEs__nonCriticalExtension__Type = a.
  eq_unit_helper_tact. Qed.
Definition RRCReconfigurationCompleteSidelink_v1720_IEs__nonCriticalExtension__Format : T_Format RRCReconfigurationCompleteSidelink_v1720_IEs__nonCriticalExtension__Type RRCReconfigurationCompleteSidelink_v1720_IEs__nonCriticalExtension__cond :=
 (* Eval compute in *) proj_format (fun _ => True) unit_format (fun _ => tt) (fun _ => make__RRCReconfigurationCompleteSidelink_v1720_IEs__nonCriticalExtension__Type)
    RRCReconfigurationCompleteSidelink_v1720_IEs__nonCriticalExtension__helper unit_unique (fun _ => left I).

Opaque RRCReconfigurationCompleteSidelink_v1720_IEs__nonCriticalExtension__cond RRCReconfigurationCompleteSidelink_v1720_IEs__nonCriticalExtension__Format.


Definition RRCReconfigurationCompleteSidelink_v1720_IEs__Format_Type := Eval cbn in seq_format_prod RRCReconfigurationCompleteSidelink_v1720_IEs__list.
Definition RRCReconfigurationCompleteSidelink_v1720_IEs__Format_list : RRCReconfigurationCompleteSidelink_v1720_IEs__Format_Type :=
  (RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720__Format, (RRCReconfigurationCompleteSidelink_v1720_IEs__nonCriticalExtension__Format, unit_format)).
Definition RRCReconfigurationCompleteSidelink_v1720_IEs__list__Format := (*Eval compute in *) seq_format RRCReconfigurationCompleteSidelink_v1720_IEs__list RRCReconfigurationCompleteSidelink_v1720_IEs__Format_list.
Definition RRCReconfigurationCompleteSidelink_v1720_IEs__F1 z :=
  (RRCReconfigurationCompleteSidelink_v1720_IEs__sl_DRX_ConfigReject_v1720 z, (RRCReconfigurationCompleteSidelink_v1720_IEs__nonCriticalExtension z, tt)).
Definition RRCReconfigurationCompleteSidelink_v1720_IEs__F2 (y : seq_type RRCReconfigurationCompleteSidelink_v1720_IEs__list) :=
  match y with
  | (i0, (i1, _))=>
    make__RRCReconfigurationCompleteSidelink_v1720_IEs__Type i0 i1
  end.
Lemma RRCReconfigurationCompleteSidelink_v1720_IEs__F1F2_cond (z : RRCReconfigurationCompleteSidelink_v1720_IEs__Type)
  : RRCReconfigurationCompleteSidelink_v1720_IEs__cond z ->
  (seq_cond RRCReconfigurationCompleteSidelink_v1720_IEs__list (RRCReconfigurationCompleteSidelink_v1720_IEs__F1 z)).
intro H. unfold RRCReconfigurationCompleteSidelink_v1720_IEs__cond in H. simpl. auto. Qed.
Lemma RRCReconfigurationCompleteSidelink_v1720_IEs__F1F2_cond2 (z : RRCReconfigurationCompleteSidelink_v1720_IEs__Type)
 : RRCReconfigurationCompleteSidelink_v1720_IEs__F2 (RRCReconfigurationCompleteSidelink_v1720_IEs__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma RRCReconfigurationCompleteSidelink_v1720_IEs__F2F1_cond (y : seq_type RRCReconfigurationCompleteSidelink_v1720_IEs__list)
  : seq_cond RRCReconfigurationCompleteSidelink_v1720_IEs__list y ->
 (RRCReconfigurationCompleteSidelink_v1720_IEs__cond (RRCReconfigurationCompleteSidelink_v1720_IEs__F2 y)) /\  RRCReconfigurationCompleteSidelink_v1720_IEs__F1 (RRCReconfigurationCompleteSidelink_v1720_IEs__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold RRCReconfigurationCompleteSidelink_v1720_IEs__cond. simpl in *. auto.
 - simpl. unfold RRCReconfigurationCompleteSidelink_v1720_IEs__F1. simpl. destruct_all_unit. auto.   Qed.
Definition RRCReconfigurationCompleteSidelink_v1720_IEs__Format : T_Format RRCReconfigurationCompleteSidelink_v1720_IEs__Type RRCReconfigurationCompleteSidelink_v1720_IEs__cond :=
        proj2_format  RRCReconfigurationCompleteSidelink_v1720_IEs__cond RRCReconfigurationCompleteSidelink_v1720_IEs__list__Format
    RRCReconfigurationCompleteSidelink_v1720_IEs__F1 RRCReconfigurationCompleteSidelink_v1720_IEs__F2 RRCReconfigurationCompleteSidelink_v1720_IEs__F1F2_cond  RRCReconfigurationCompleteSidelink_v1720_IEs__F1F2_cond2 RRCReconfigurationCompleteSidelink_v1720_IEs__F2F1_cond.
Opaque RRCReconfigurationCompleteSidelink_v1720_IEs__cond RRCReconfigurationCompleteSidelink_v1720_IEs__Format.

