Require Import ASN1Parser.ExtrOCaml.ExtractHelper.

Require Import NR.NR_RRC_Definitions.
Require Import NR.OtherConfig_v1700.

Opaque OtherConfig_v1700__cond OtherConfig_v1700__Format.

Require Import NR.SetupRelease.
Require Import NR.SL_L2RelayUE_Config_r17.
Definition RRCReconfiguration_v1700_IEs__sl_L2RelayUE_Config_r17__Type := SetupRelease__Type SL_L2RelayUE_Config_r17__Type.
Definition RRCReconfiguration_v1700_IEs__sl_L2RelayUE_Config_r17__cond := SetupRelease__cond _ SL_L2RelayUE_Config_r17__cond.
Definition RRCReconfiguration_v1700_IEs__sl_L2RelayUE_Config_r17__Format : T_Format RRCReconfiguration_v1700_IEs__sl_L2RelayUE_Config_r17__Type RRCReconfiguration_v1700_IEs__sl_L2RelayUE_Config_r17__cond := SetupRelease__Format _ _ SL_L2RelayUE_Config_r17__Format.
Opaque RRCReconfiguration_v1700_IEs__sl_L2RelayUE_Config_r17__cond RRCReconfiguration_v1700_IEs__sl_L2RelayUE_Config_r17__Format.

Require Import NR.SetupRelease.
Require Import NR.SL_L2RemoteUE_Config_r17.
Definition RRCReconfiguration_v1700_IEs__sl_L2RemoteUE_Config_r17__Type := SetupRelease__Type SL_L2RemoteUE_Config_r17__Type.
Definition RRCReconfiguration_v1700_IEs__sl_L2RemoteUE_Config_r17__cond := SetupRelease__cond _ SL_L2RemoteUE_Config_r17__cond.
Definition RRCReconfiguration_v1700_IEs__sl_L2RemoteUE_Config_r17__Format : T_Format RRCReconfiguration_v1700_IEs__sl_L2RemoteUE_Config_r17__Type RRCReconfiguration_v1700_IEs__sl_L2RemoteUE_Config_r17__cond := SetupRelease__Format _ _ SL_L2RemoteUE_Config_r17__Format.
Opaque RRCReconfiguration_v1700_IEs__sl_L2RemoteUE_Config_r17__cond RRCReconfiguration_v1700_IEs__sl_L2RemoteUE_Config_r17__Format.

Require Import NR.SetupRelease.
Require Import NR.NeedForGapNCSG_ConfigNR_r17.
Definition RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigNR_r17__Type := SetupRelease__Type NeedForGapNCSG_ConfigNR_r17__Type.
Definition RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigNR_r17__cond := SetupRelease__cond _ NeedForGapNCSG_ConfigNR_r17__cond.
Definition RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigNR_r17__Format : T_Format RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigNR_r17__Type RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigNR_r17__cond := SetupRelease__Format _ _ NeedForGapNCSG_ConfigNR_r17__Format.
Opaque RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigNR_r17__cond RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigNR_r17__Format.

Require Import NR.SetupRelease.
Require Import NR.NeedForGapNCSG_ConfigEUTRA_r17.
Definition RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigEUTRA_r17__Type := SetupRelease__Type NeedForGapNCSG_ConfigEUTRA_r17__Type.
Definition RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigEUTRA_r17__cond := SetupRelease__cond _ NeedForGapNCSG_ConfigEUTRA_r17__cond.
Definition RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigEUTRA_r17__Format : T_Format RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigEUTRA_r17__Type RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigEUTRA_r17__cond := SetupRelease__Format _ _ NeedForGapNCSG_ConfigEUTRA_r17__Format.
Opaque RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigEUTRA_r17__cond RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigEUTRA_r17__Format.

Require Import NR.SetupRelease.
Require Import NR.MUSIM_GapConfig_r17.
Definition RRCReconfiguration_v1700_IEs__musim_GapConfig_r17__Type := SetupRelease__Type MUSIM_GapConfig_r17__Type.
Definition RRCReconfiguration_v1700_IEs__musim_GapConfig_r17__cond := SetupRelease__cond _ MUSIM_GapConfig_r17__cond.
Definition RRCReconfiguration_v1700_IEs__musim_GapConfig_r17__Format : T_Format RRCReconfiguration_v1700_IEs__musim_GapConfig_r17__Type RRCReconfiguration_v1700_IEs__musim_GapConfig_r17__cond := SetupRelease__Format _ _ MUSIM_GapConfig_r17__Format.
Opaque RRCReconfiguration_v1700_IEs__musim_GapConfig_r17__cond RRCReconfiguration_v1700_IEs__musim_GapConfig_r17__Format.

Require Import NR.SetupRelease.
Require Import NR.UL_GapFR2_Config_r17.
Definition RRCReconfiguration_v1700_IEs__ul_GapFR2_Config_r17__Type := SetupRelease__Type UL_GapFR2_Config_r17__Type.
Definition RRCReconfiguration_v1700_IEs__ul_GapFR2_Config_r17__cond := SetupRelease__cond _ UL_GapFR2_Config_r17__cond.
Definition RRCReconfiguration_v1700_IEs__ul_GapFR2_Config_r17__Format : T_Format RRCReconfiguration_v1700_IEs__ul_GapFR2_Config_r17__Type RRCReconfiguration_v1700_IEs__ul_GapFR2_Config_r17__cond := SetupRelease__Format _ _ UL_GapFR2_Config_r17__Format.
Opaque RRCReconfiguration_v1700_IEs__ul_GapFR2_Config_r17__cond RRCReconfiguration_v1700_IEs__ul_GapFR2_Config_r17__Format.

Inductive RRCReconfiguration_v1700_IEs__scg_State_r17__Type : Set :=
 | RRCReconfiguration_v1700_IEs__scg_State_r17__deactivated
.
Definition RRCReconfiguration_v1700_IEs__scg_State_r17__cond := (fun (_ : RRCReconfiguration_v1700_IEs__scg_State_r17__Type) => True).
Lemma RRCReconfiguration_v1700_IEs__scg_State_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition RRCReconfiguration_v1700_IEs__scg_State_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 RRCReconfiguration_v1700_IEs__scg_State_r17__nat__helper.

Definition RRCReconfiguration_v1700_IEs__scg_State_r17__F1 t :=
  match t with
  | RRCReconfiguration_v1700_IEs__scg_State_r17__deactivated => 0
  end.
Definition RRCReconfiguration_v1700_IEs__scg_State_r17__F2 n :=
  match n with
  | 0 => RRCReconfiguration_v1700_IEs__scg_State_r17__deactivated
  | _ => RRCReconfiguration_v1700_IEs__scg_State_r17__deactivated
  end.
Lemma RRCReconfiguration_v1700_IEs__scg_State_r17__F1F2 : forall x : RRCReconfiguration_v1700_IEs__scg_State_r17__Type, (RRCReconfiguration_v1700_IEs__scg_State_r17__F1 x <= 0) /\ RRCReconfiguration_v1700_IEs__scg_State_r17__F2 (RRCReconfiguration_v1700_IEs__scg_State_r17__F1 x) = x. imp_solve. Qed.
Lemma RRCReconfiguration_v1700_IEs__scg_State_r17__F2F1 : forall (y : nat) (H : y <= 0), RRCReconfiguration_v1700_IEs__scg_State_r17__F1 (RRCReconfiguration_v1700_IEs__scg_State_r17__F2 y) = y. enum_solve H y. Qed.

Require Import NR.AppLayerMeasConfig_r17.

Opaque AppLayerMeasConfig_r17__cond AppLayerMeasConfig_r17__Format.

Require Import NR.SetupRelease.
Require Import NR.UE_TxTEG_RequestUL_TDOA_Config_r17.
Definition RRCReconfiguration_v1700_IEs__ue_TxTEG_RequestUL_TDOA_Config_r17__Type := SetupRelease__Type UE_TxTEG_RequestUL_TDOA_Config_r17__Type.
Definition RRCReconfiguration_v1700_IEs__ue_TxTEG_RequestUL_TDOA_Config_r17__cond := SetupRelease__cond _ UE_TxTEG_RequestUL_TDOA_Config_r17__cond.
Definition RRCReconfiguration_v1700_IEs__ue_TxTEG_RequestUL_TDOA_Config_r17__Format : T_Format RRCReconfiguration_v1700_IEs__ue_TxTEG_RequestUL_TDOA_Config_r17__Type RRCReconfiguration_v1700_IEs__ue_TxTEG_RequestUL_TDOA_Config_r17__cond := SetupRelease__Format _ _ UE_TxTEG_RequestUL_TDOA_Config_r17__Format.
Opaque RRCReconfiguration_v1700_IEs__ue_TxTEG_RequestUL_TDOA_Config_r17__cond RRCReconfiguration_v1700_IEs__ue_TxTEG_RequestUL_TDOA_Config_r17__Format.

Record RRCReconfiguration_v1700_IEs__nonCriticalExtension__Type : Set := make__RRCReconfiguration_v1700_IEs__nonCriticalExtension__Type {}.
Definition RRCReconfiguration_v1700_IEs__nonCriticalExtension__cond (z : RRCReconfiguration_v1700_IEs__nonCriticalExtension__Type) := True.
Record RRCReconfiguration_v1700_IEs__Type : Set :=
  make__RRCReconfiguration_v1700_IEs__Type {
    RRCReconfiguration_v1700_IEs__otherConfig_v1700 : option OtherConfig_v1700__Type ;
    RRCReconfiguration_v1700_IEs__sl_L2RelayUE_Config_r17 : option RRCReconfiguration_v1700_IEs__sl_L2RelayUE_Config_r17__Type ;
    RRCReconfiguration_v1700_IEs__sl_L2RemoteUE_Config_r17 : option RRCReconfiguration_v1700_IEs__sl_L2RemoteUE_Config_r17__Type ;
    RRCReconfiguration_v1700_IEs__dedicatedPagingDelivery_r17 : option octet_string ;
    RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigNR_r17 : option RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigNR_r17__Type ;
    RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigEUTRA_r17 : option RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigEUTRA_r17__Type ;
    RRCReconfiguration_v1700_IEs__musim_GapConfig_r17 : option RRCReconfiguration_v1700_IEs__musim_GapConfig_r17__Type ;
    RRCReconfiguration_v1700_IEs__ul_GapFR2_Config_r17 : option RRCReconfiguration_v1700_IEs__ul_GapFR2_Config_r17__Type ;
    RRCReconfiguration_v1700_IEs__scg_State_r17 : option RRCReconfiguration_v1700_IEs__scg_State_r17__Type ;
    RRCReconfiguration_v1700_IEs__appLayerMeasConfig_r17 : option AppLayerMeasConfig_r17__Type ;
    RRCReconfiguration_v1700_IEs__ue_TxTEG_RequestUL_TDOA_Config_r17 : option RRCReconfiguration_v1700_IEs__ue_TxTEG_RequestUL_TDOA_Config_r17__Type ;
    RRCReconfiguration_v1700_IEs__nonCriticalExtension : option RRCReconfiguration_v1700_IEs__nonCriticalExtension__Type ;
}.
Definition RRCReconfiguration_v1700_IEs__list := (
 Opt OtherConfig_v1700__Type OtherConfig_v1700__cond ::
 Opt RRCReconfiguration_v1700_IEs__sl_L2RelayUE_Config_r17__Type RRCReconfiguration_v1700_IEs__sl_L2RelayUE_Config_r17__cond ::
 Opt RRCReconfiguration_v1700_IEs__sl_L2RemoteUE_Config_r17__Type RRCReconfiguration_v1700_IEs__sl_L2RemoteUE_Config_r17__cond ::
 Opt octet_string (fun (b : octet_string) => length b < Nat.pow 2 14) ::
 Opt RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigNR_r17__Type RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigNR_r17__cond ::
 Opt RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigEUTRA_r17__Type RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigEUTRA_r17__cond ::
 Opt RRCReconfiguration_v1700_IEs__musim_GapConfig_r17__Type RRCReconfiguration_v1700_IEs__musim_GapConfig_r17__cond ::
 Opt RRCReconfiguration_v1700_IEs__ul_GapFR2_Config_r17__Type RRCReconfiguration_v1700_IEs__ul_GapFR2_Config_r17__cond ::
 Opt RRCReconfiguration_v1700_IEs__scg_State_r17__Type RRCReconfiguration_v1700_IEs__scg_State_r17__cond ::
 Opt AppLayerMeasConfig_r17__Type AppLayerMeasConfig_r17__cond ::
 Opt RRCReconfiguration_v1700_IEs__ue_TxTEG_RequestUL_TDOA_Config_r17__Type RRCReconfiguration_v1700_IEs__ue_TxTEG_RequestUL_TDOA_Config_r17__cond ::
 Opt RRCReconfiguration_v1700_IEs__nonCriticalExtension__Type RRCReconfiguration_v1700_IEs__nonCriticalExtension__cond ::
 nil).
Definition RRCReconfiguration_v1700_IEs__cond z := 
  opt_cond OtherConfig_v1700__cond (RRCReconfiguration_v1700_IEs__otherConfig_v1700 z) /\
  opt_cond RRCReconfiguration_v1700_IEs__sl_L2RelayUE_Config_r17__cond (RRCReconfiguration_v1700_IEs__sl_L2RelayUE_Config_r17 z) /\
  opt_cond RRCReconfiguration_v1700_IEs__sl_L2RemoteUE_Config_r17__cond (RRCReconfiguration_v1700_IEs__sl_L2RemoteUE_Config_r17 z) /\
  opt_cond (fun (b : octet_string) => length b < Nat.pow 2 14) (RRCReconfiguration_v1700_IEs__dedicatedPagingDelivery_r17 z) /\
  opt_cond RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigNR_r17__cond (RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigNR_r17 z) /\
  opt_cond RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigEUTRA_r17__cond (RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigEUTRA_r17 z) /\
  opt_cond RRCReconfiguration_v1700_IEs__musim_GapConfig_r17__cond (RRCReconfiguration_v1700_IEs__musim_GapConfig_r17 z) /\
  opt_cond RRCReconfiguration_v1700_IEs__ul_GapFR2_Config_r17__cond (RRCReconfiguration_v1700_IEs__ul_GapFR2_Config_r17 z) /\
  opt_cond RRCReconfiguration_v1700_IEs__scg_State_r17__cond (RRCReconfiguration_v1700_IEs__scg_State_r17 z) /\
  opt_cond AppLayerMeasConfig_r17__cond (RRCReconfiguration_v1700_IEs__appLayerMeasConfig_r17 z) /\
  opt_cond RRCReconfiguration_v1700_IEs__ue_TxTEG_RequestUL_TDOA_Config_r17__cond (RRCReconfiguration_v1700_IEs__ue_TxTEG_RequestUL_TDOA_Config_r17 z) /\
  opt_cond RRCReconfiguration_v1700_IEs__nonCriticalExtension__cond (RRCReconfiguration_v1700_IEs__nonCriticalExtension z) /\
  True.


Opaque Byte.to_nat Byte.of_nat.
Opaque bind_parse restrict_parse proj_parse return_parse.
Opaque restrict_serialize proj_serialize sigma_serialize append_serialize proj2_serialize.

Opaque read_n_nat read_unit.
Opaque put_n_nat put_unit. 

Opaque opt_bind opt_serialize dft_serialize prepend_serialize list_serial.
Opaque opt_parse list_parse dft_parse fail_parse append_parse
  bind_parse return_parse.

Opaque Z.to_nat Z.of_nat Z.sub Z.add Z.le Z.lt Z.pow Z.opp Z.ltb.
Opaque Nat.mul Nat.shiftr Nat.shiftl Nat.div Nat.modulo Nat.leb Nat.ltb Nat.add
  Nat.sub Nat.land Nat.lor Nat.eqb  Nat.log2 Nat.pow Nat.even PeanoNat.Nat.lnot.
Opaque Compare_dec.le_dec Compare_dec.le_lt_dec ZArith_dec.Z_le_dec lt_eq_lt_dec_new. 
Opaque sumbool_and1 list_and list_and_cons list_cons_S flg_add. 

Opaque list_to_len.
   Opaque length Compare_dec.le_dec Compare_dec.lt_dec PeanoNat.Nat.eq_dec.
   Opaque bool__Format int__Format octet_string_nc__Format bit_string_nc__Format.

   Opaque ByteIdx_to_nat nat_to_ByteIdx add_opt list_bool_format normally_small_len_det_format
  get_byte_len to_parse_skip  open_typ_serialize open_typ_parse open_type_to_len.
  

Opaque seq_cond seq_ext_cond choice_cond.
Opaque RRCReconfiguration_v1700_IEs__sl_L2RelayUE_Config_r17__cond RRCReconfiguration_v1700_IEs__sl_L2RelayUE_Config_r17__Format.

Opaque RRCReconfiguration_v1700_IEs__sl_L2RemoteUE_Config_r17__cond RRCReconfiguration_v1700_IEs__sl_L2RemoteUE_Config_r17__Format.

Opaque RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigNR_r17__cond RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigNR_r17__Format.

Opaque RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigEUTRA_r17__cond RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigEUTRA_r17__Format.

Opaque RRCReconfiguration_v1700_IEs__musim_GapConfig_r17__cond RRCReconfiguration_v1700_IEs__musim_GapConfig_r17__Format.

Opaque RRCReconfiguration_v1700_IEs__ul_GapFR2_Config_r17__cond RRCReconfiguration_v1700_IEs__ul_GapFR2_Config_r17__Format.

Definition RRCReconfiguration_v1700_IEs__scg_State_r17__Format : T_Format RRCReconfiguration_v1700_IEs__scg_State_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format RRCReconfiguration_v1700_IEs__scg_State_r17__nat__Format RRCReconfiguration_v1700_IEs__scg_State_r17__F1 RRCReconfiguration_v1700_IEs__scg_State_r17__F2 RRCReconfiguration_v1700_IEs__scg_State_r17__F1F2 RRCReconfiguration_v1700_IEs__scg_State_r17__F2F1.

Opaque RRCReconfiguration_v1700_IEs__scg_State_r17__cond RRCReconfiguration_v1700_IEs__scg_State_r17__Format.

Opaque RRCReconfiguration_v1700_IEs__ue_TxTEG_RequestUL_TDOA_Config_r17__cond RRCReconfiguration_v1700_IEs__ue_TxTEG_RequestUL_TDOA_Config_r17__Format.

Definition RRCReconfiguration_v1700_IEs__nonCriticalExtension__helper : forall a : RRCReconfiguration_v1700_IEs__nonCriticalExtension__Type, True -> True /\ make__RRCReconfiguration_v1700_IEs__nonCriticalExtension__Type = a.
  eq_unit_helper_tact. Qed.
Definition RRCReconfiguration_v1700_IEs__nonCriticalExtension__Format : T_Format RRCReconfiguration_v1700_IEs__nonCriticalExtension__Type RRCReconfiguration_v1700_IEs__nonCriticalExtension__cond :=
 (* Eval compute in *) proj_format (fun _ => True) unit_format (fun _ => tt) (fun _ => make__RRCReconfiguration_v1700_IEs__nonCriticalExtension__Type)
    RRCReconfiguration_v1700_IEs__nonCriticalExtension__helper unit_unique (fun _ => left I).

Opaque RRCReconfiguration_v1700_IEs__nonCriticalExtension__cond RRCReconfiguration_v1700_IEs__nonCriticalExtension__Format.


Definition RRCReconfiguration_v1700_IEs__Format_Type := Eval cbn in seq_format_prod RRCReconfiguration_v1700_IEs__list.
Definition RRCReconfiguration_v1700_IEs__Format_list : RRCReconfiguration_v1700_IEs__Format_Type :=
  (OtherConfig_v1700__Format, (RRCReconfiguration_v1700_IEs__sl_L2RelayUE_Config_r17__Format, (RRCReconfiguration_v1700_IEs__sl_L2RemoteUE_Config_r17__Format, (octet_string_nc__Format, (RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigNR_r17__Format, (RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigEUTRA_r17__Format, (RRCReconfiguration_v1700_IEs__musim_GapConfig_r17__Format, (RRCReconfiguration_v1700_IEs__ul_GapFR2_Config_r17__Format, (RRCReconfiguration_v1700_IEs__scg_State_r17__Format, (AppLayerMeasConfig_r17__Format, (RRCReconfiguration_v1700_IEs__ue_TxTEG_RequestUL_TDOA_Config_r17__Format, (RRCReconfiguration_v1700_IEs__nonCriticalExtension__Format, unit_format)))))))))))).
Definition RRCReconfiguration_v1700_IEs__list__Format := (*Eval compute in *) seq_format RRCReconfiguration_v1700_IEs__list RRCReconfiguration_v1700_IEs__Format_list.
Definition RRCReconfiguration_v1700_IEs__F1 z :=
  (RRCReconfiguration_v1700_IEs__otherConfig_v1700 z, (RRCReconfiguration_v1700_IEs__sl_L2RelayUE_Config_r17 z, (RRCReconfiguration_v1700_IEs__sl_L2RemoteUE_Config_r17 z, (RRCReconfiguration_v1700_IEs__dedicatedPagingDelivery_r17 z, (RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigNR_r17 z, (RRCReconfiguration_v1700_IEs__needForGapNCSG_ConfigEUTRA_r17 z, (RRCReconfiguration_v1700_IEs__musim_GapConfig_r17 z, (RRCReconfiguration_v1700_IEs__ul_GapFR2_Config_r17 z, (RRCReconfiguration_v1700_IEs__scg_State_r17 z, (RRCReconfiguration_v1700_IEs__appLayerMeasConfig_r17 z, (RRCReconfiguration_v1700_IEs__ue_TxTEG_RequestUL_TDOA_Config_r17 z, (RRCReconfiguration_v1700_IEs__nonCriticalExtension z, tt)))))))))))).
Definition RRCReconfiguration_v1700_IEs__F2 (y : seq_type RRCReconfiguration_v1700_IEs__list) :=
  match y with
  | (i0, (i1, (i2, (i3, (i4, (i5, (i6, (i7, (i8, (i9, (i10, (i11, _))))))))))))=>
    make__RRCReconfiguration_v1700_IEs__Type i0 i1 i2 i3 i4 i5 i6 i7 i8 i9 i10 i11
  end.
Lemma RRCReconfiguration_v1700_IEs__F1F2_cond (z : RRCReconfiguration_v1700_IEs__Type)
  : RRCReconfiguration_v1700_IEs__cond z ->
  (seq_cond RRCReconfiguration_v1700_IEs__list (RRCReconfiguration_v1700_IEs__F1 z)).
intro H. unfold RRCReconfiguration_v1700_IEs__cond in H. simpl. auto. Qed.
Lemma RRCReconfiguration_v1700_IEs__F1F2_cond2 (z : RRCReconfiguration_v1700_IEs__Type)
 : RRCReconfiguration_v1700_IEs__F2 (RRCReconfiguration_v1700_IEs__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma RRCReconfiguration_v1700_IEs__F2F1_cond (y : seq_type RRCReconfiguration_v1700_IEs__list)
  : seq_cond RRCReconfiguration_v1700_IEs__list y ->
 (RRCReconfiguration_v1700_IEs__cond (RRCReconfiguration_v1700_IEs__F2 y)) /\  RRCReconfiguration_v1700_IEs__F1 (RRCReconfiguration_v1700_IEs__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold RRCReconfiguration_v1700_IEs__cond. simpl in *. auto.
 - simpl. unfold RRCReconfiguration_v1700_IEs__F1. simpl. destruct_all_unit. auto.   Qed.
Definition RRCReconfiguration_v1700_IEs__Format : T_Format RRCReconfiguration_v1700_IEs__Type RRCReconfiguration_v1700_IEs__cond :=
        proj2_format  RRCReconfiguration_v1700_IEs__cond RRCReconfiguration_v1700_IEs__list__Format
    RRCReconfiguration_v1700_IEs__F1 RRCReconfiguration_v1700_IEs__F2 RRCReconfiguration_v1700_IEs__F1F2_cond  RRCReconfiguration_v1700_IEs__F1F2_cond2 RRCReconfiguration_v1700_IEs__F2F1_cond.
Opaque RRCReconfiguration_v1700_IEs__cond RRCReconfiguration_v1700_IEs__Format.

