Require Import ASN1Parser.ExtrOCaml.ExtractHelper.

Require Import NR.NR_RRC_Definitions.
Inductive SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__Type : Set :=
 | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s0
 | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s1
 | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s2
 | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s4
 | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s8
 | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s10
 | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s15
 | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s30
 | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s60
 | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s120
 | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s180
 | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s240
 | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s300
 | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s600
 | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s900
 | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s1800
.
Definition SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__cond := (fun (_ : SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__Type) => True).
Lemma SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__nat__helper : to_bit_sz 15 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__nat__Format : T_Format nat (fun z => (z <= 15)) :=
  nat_enum_format 15 SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__nat__helper.

Definition SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__F1 t :=
  match t with
  | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s0 => 0
  | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s1 => 1
  | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s2 => 2
  | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s4 => 3
  | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s8 => 4
  | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s10 => 5
  | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s15 => 6
  | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s30 => 7
  | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s60 => 8
  | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s120 => 9
  | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s180 => 10
  | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s240 => 11
  | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s300 => 12
  | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s600 => 13
  | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s900 => 14
  | SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s1800 => 15
  end.
Definition SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__F2 n :=
  match n with
  | 0 => SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s0
  | 1 => SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s1
  | 2 => SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s2
  | 3 => SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s4
  | 4 => SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s8
  | 5 => SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s10
  | 6 => SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s15
  | 7 => SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s30
  | 8 => SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s60
  | 9 => SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s120
  | 10 => SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s180
  | 11 => SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s240
  | 12 => SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s300
  | 13 => SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s600
  | 14 => SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s900
  | 15 => SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s1800
  | _ => SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__s0
  end.
Lemma SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__F1F2 : forall x : SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__Type, (SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__F1 x <= 15) /\ SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__F2 (SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__F1 x) = x. imp_solve. Qed.
Lemma SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__F2F1 : forall (y : nat) (H : y <= 15), SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__F1 (SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__F2 y) = y. enum_solve H y. Qed.

Record SCG_DeactivationPreferenceConfig_r17__Type : Set :=
  make__SCG_DeactivationPreferenceConfig_r17__Type {
    SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17 : SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__Type ;
}.
Definition SCG_DeactivationPreferenceConfig_r17__list := (
 Nor SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__Type SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__cond ::
 nil).
Definition SCG_DeactivationPreferenceConfig_r17__cond z := 
  SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__cond (SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17 z) /\
  True.


Opaque Byte.to_nat Byte.of_nat.
Opaque bind_parse restrict_parse proj_parse return_parse.
Opaque restrict_serialize proj_serialize sigma_serialize append_serialize proj2_serialize.

Opaque read_n_nat read_unit.
Opaque put_n_nat put_unit. 

Opaque opt_bind opt_serialize dft_serialize prepend_serialize list_serial.
Opaque opt_parse list_parse dft_parse fail_parse append_parse
  bind_parse return_parse.

Opaque Z.to_nat Z.of_nat Z.sub Z.add Z.le Z.lt Z.pow Z.opp Z.ltb.
Opaque Nat.mul Nat.shiftr Nat.shiftl Nat.div Nat.modulo Nat.leb Nat.ltb Nat.add
  Nat.sub Nat.land Nat.lor Nat.eqb  Nat.log2 Nat.pow Nat.even PeanoNat.Nat.lnot.
Opaque Compare_dec.le_dec Compare_dec.le_lt_dec ZArith_dec.Z_le_dec lt_eq_lt_dec_new. 
Opaque sumbool_and1 list_and list_and_cons list_cons_S flg_add. 

Opaque list_to_len.
   Opaque length Compare_dec.le_dec Compare_dec.lt_dec PeanoNat.Nat.eq_dec.
   Opaque bool__Format int__Format octet_string_nc__Format bit_string_nc__Format.

   Opaque ByteIdx_to_nat nat_to_ByteIdx add_opt list_bool_format normally_small_len_det_format
  get_byte_len to_parse_skip  open_typ_serialize open_typ_parse open_type_to_len.
  

Opaque seq_cond seq_ext_cond choice_cond.
Definition SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__Format : T_Format SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__nat__Format SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__F1 SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__F2 SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__F1F2 SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__F2F1.

Opaque SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__cond SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__Format.


Definition SCG_DeactivationPreferenceConfig_r17__Format_Type := Eval cbn in seq_format_prod SCG_DeactivationPreferenceConfig_r17__list.
Definition SCG_DeactivationPreferenceConfig_r17__Format_list : SCG_DeactivationPreferenceConfig_r17__Format_Type :=
  (SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17__Format, unit_format).
Definition SCG_DeactivationPreferenceConfig_r17__list__Format := (*Eval compute in *) seq_format SCG_DeactivationPreferenceConfig_r17__list SCG_DeactivationPreferenceConfig_r17__Format_list.
Definition SCG_DeactivationPreferenceConfig_r17__F1 z :=
  (SCG_DeactivationPreferenceConfig_r17__scg_DeactivationPreferenceProhibitTimer_r17 z, tt).
Definition SCG_DeactivationPreferenceConfig_r17__F2 (y : seq_type SCG_DeactivationPreferenceConfig_r17__list) :=
  match y with
  | (i0, _)=>
    make__SCG_DeactivationPreferenceConfig_r17__Type i0
  end.
Lemma SCG_DeactivationPreferenceConfig_r17__F1F2_cond (z : SCG_DeactivationPreferenceConfig_r17__Type)
  : SCG_DeactivationPreferenceConfig_r17__cond z ->
  (seq_cond SCG_DeactivationPreferenceConfig_r17__list (SCG_DeactivationPreferenceConfig_r17__F1 z)).
intro H. unfold SCG_DeactivationPreferenceConfig_r17__cond in H. simpl. auto. Qed.
Lemma SCG_DeactivationPreferenceConfig_r17__F1F2_cond2 (z : SCG_DeactivationPreferenceConfig_r17__Type)
 : SCG_DeactivationPreferenceConfig_r17__F2 (SCG_DeactivationPreferenceConfig_r17__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma SCG_DeactivationPreferenceConfig_r17__F2F1_cond (y : seq_type SCG_DeactivationPreferenceConfig_r17__list)
  : seq_cond SCG_DeactivationPreferenceConfig_r17__list y ->
 (SCG_DeactivationPreferenceConfig_r17__cond (SCG_DeactivationPreferenceConfig_r17__F2 y)) /\  SCG_DeactivationPreferenceConfig_r17__F1 (SCG_DeactivationPreferenceConfig_r17__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold SCG_DeactivationPreferenceConfig_r17__cond. simpl in *. auto.
 - simpl. unfold SCG_DeactivationPreferenceConfig_r17__F1. simpl. destruct_all_unit. auto.   Qed.
Definition SCG_DeactivationPreferenceConfig_r17__Format : T_Format SCG_DeactivationPreferenceConfig_r17__Type SCG_DeactivationPreferenceConfig_r17__cond :=
        proj2_format  SCG_DeactivationPreferenceConfig_r17__cond SCG_DeactivationPreferenceConfig_r17__list__Format
    SCG_DeactivationPreferenceConfig_r17__F1 SCG_DeactivationPreferenceConfig_r17__F2 SCG_DeactivationPreferenceConfig_r17__F1F2_cond  SCG_DeactivationPreferenceConfig_r17__F1F2_cond2 SCG_DeactivationPreferenceConfig_r17__F2F1_cond.
Opaque SCG_DeactivationPreferenceConfig_r17__cond SCG_DeactivationPreferenceConfig_r17__Format.

