Require Import ASN1Parser.ExtrOCaml.ExtractHelper.

Require Import NR.NR_RRC_Definitions.
Inductive SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__Type : Set :=
 | SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__supported
.
Definition SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__cond := (fun (_ : SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__Type) => True).
Lemma SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__nat__helper.

Definition SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__F1 t :=
  match t with
  | SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__supported => 0
  end.
Definition SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__F2 n :=
  match n with
  | 0 => SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__supported
  | _ => SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__supported
  end.
Lemma SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__F1F2 : forall x : SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__Type, (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__F1 x <= 0) /\ SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__F2 (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__F1 x) = x. imp_solve. Qed.
Lemma SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__F2F1 : forall (y : nat) (H : y <= 0), SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__F1 (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__F2 y) = y. enum_solve H y. Qed.

Inductive SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__Type : Set :=
 | SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__supported
.
Definition SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__cond := (fun (_ : SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__Type) => True).
Lemma SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__nat__helper.

Definition SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__F1 t :=
  match t with
  | SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__supported => 0
  end.
Definition SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__F2 n :=
  match n with
  | 0 => SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__supported
  | _ => SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__supported
  end.
Lemma SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__F1F2 : forall x : SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__Type, (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__F1 x <= 0) /\ SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__F2 (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__F1 x) = x. imp_solve. Qed.
Lemma SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__F2F1 : forall (y : nat) (H : y <= 0), SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__F1 (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__F2 y) = y. enum_solve H y. Qed.

Inductive SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__Type : Set :=
 | SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__supported
.
Definition SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__cond := (fun (_ : SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__Type) => True).
Lemma SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__nat__helper.

Definition SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__F1 t :=
  match t with
  | SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__supported => 0
  end.
Definition SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__F2 n :=
  match n with
  | 0 => SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__supported
  | _ => SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__supported
  end.
Lemma SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__F1F2 : forall x : SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__Type, (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__F1 x <= 0) /\ SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__F2 (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__F1 x) = x. imp_solve. Qed.
Lemma SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__F2F1 : forall (y : nat) (H : y <= 0), SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__F1 (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__F2 y) = y. enum_solve H y. Qed.

Inductive SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__Type : Set :=
 | SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__supported
.
Definition SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__cond := (fun (_ : SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__Type) => True).
Lemma SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__nat__helper.

Definition SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__F1 t :=
  match t with
  | SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__supported => 0
  end.
Definition SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__F2 n :=
  match n with
  | 0 => SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__supported
  | _ => SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__supported
  end.
Lemma SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__F1F2 : forall x : SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__Type, (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__F1 x <= 0) /\ SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__F2 (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__F1 x) = x. imp_solve. Qed.
Lemma SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__F2F1 : forall (y : nat) (H : y <= 0), SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__F1 (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__F2 y) = y. enum_solve H y. Qed.

Inductive SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__Type : Set :=
 | SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__supported
.
Definition SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__cond := (fun (_ : SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__Type) => True).
Lemma SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__nat__helper.

Definition SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__F1 t :=
  match t with
  | SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__supported => 0
  end.
Definition SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__F2 n :=
  match n with
  | 0 => SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__supported
  | _ => SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__supported
  end.
Lemma SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__F1F2 : forall x : SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__Type, (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__F1 x <= 0) /\ SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__F2 (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__F1 x) = x. imp_solve. Qed.
Lemma SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__F2F1 : forall (y : nat) (H : y <= 0), SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__F1 (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__F2 y) = y. enum_solve H y. Qed.

Inductive SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__Type : Set :=
 | SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__supported
.
Definition SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__cond := (fun (_ : SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__Type) => True).
Lemma SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__nat__helper.

Definition SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__F1 t :=
  match t with
  | SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__supported => 0
  end.
Definition SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__F2 n :=
  match n with
  | 0 => SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__supported
  | _ => SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__supported
  end.
Lemma SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__F1F2 : forall x : SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__Type, (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__F1 x <= 0) /\ SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__F2 (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__F1 x) = x. imp_solve. Qed.
Lemma SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__F2F1 : forall (y : nat) (H : y <= 0), SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__F1 (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__F2 y) = y. enum_solve H y. Qed.

Record SpatialRelationsSRS_Pos_r16__Type : Set :=
  make__SpatialRelationsSRS_Pos_r16__Type {
    SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16 : option SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__Type ;
    SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16 : option SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__Type ;
    SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16 : option SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__Type ;
    SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16 : option SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__Type ;
    SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16 : option SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__Type ;
    SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16 : option SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__Type ;
}.
Definition SpatialRelationsSRS_Pos_r16__list := (
 Opt SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__Type SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__cond ::
 Opt SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__Type SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__cond ::
 Opt SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__Type SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__cond ::
 Opt SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__Type SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__cond ::
 Opt SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__Type SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__cond ::
 Opt SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__Type SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__cond ::
 nil).
Definition SpatialRelationsSRS_Pos_r16__cond z := 
  opt_cond SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__cond (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16 z) /\
  opt_cond SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__cond (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16 z) /\
  opt_cond SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__cond (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16 z) /\
  opt_cond SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__cond (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16 z) /\
  opt_cond SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__cond (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16 z) /\
  opt_cond SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__cond (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16 z) /\
  True.


Opaque Byte.to_nat Byte.of_nat.
Opaque bind_parse restrict_parse proj_parse return_parse.
Opaque restrict_serialize proj_serialize sigma_serialize append_serialize proj2_serialize.

Opaque read_n_nat read_unit.
Opaque put_n_nat put_unit. 

Opaque opt_bind opt_serialize dft_serialize prepend_serialize list_serial.
Opaque opt_parse list_parse dft_parse fail_parse append_parse
  bind_parse return_parse.

Opaque Z.to_nat Z.of_nat Z.sub Z.add Z.le Z.lt Z.pow Z.opp Z.ltb.
Opaque Nat.mul Nat.shiftr Nat.shiftl Nat.div Nat.modulo Nat.leb Nat.ltb Nat.add
  Nat.sub Nat.land Nat.lor Nat.eqb  Nat.log2 Nat.pow Nat.even PeanoNat.Nat.lnot.
Opaque Compare_dec.le_dec Compare_dec.le_lt_dec ZArith_dec.Z_le_dec lt_eq_lt_dec_new. 
Opaque sumbool_and1 list_and list_and_cons list_cons_S flg_add. 

Opaque list_to_len.
   Opaque length Compare_dec.le_dec Compare_dec.lt_dec PeanoNat.Nat.eq_dec.
   Opaque bool__Format int__Format octet_string_nc__Format bit_string_nc__Format.

   Opaque ByteIdx_to_nat nat_to_ByteIdx add_opt list_bool_format normally_small_len_det_format
  get_byte_len to_parse_skip  open_typ_serialize open_typ_parse open_type_to_len.
  

Opaque seq_cond seq_ext_cond choice_cond.
Definition SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__Format : T_Format SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__Type (fun _ => True) :=
(* Eval compute in *) proj3_format SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__nat__Format SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__F1 SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__F2 SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__F1F2 SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__F2F1.

Opaque SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__cond SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__Format.

Definition SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__Format : T_Format SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__Type (fun _ => True) :=
(* Eval compute in *) proj3_format SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__nat__Format SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__F1 SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__F2 SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__F1F2 SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__F2F1.

Opaque SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__cond SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__Format.

Definition SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__Format : T_Format SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__Type (fun _ => True) :=
(* Eval compute in *) proj3_format SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__nat__Format SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__F1 SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__F2 SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__F1F2 SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__F2F1.

Opaque SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__cond SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__Format.

Definition SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__Format : T_Format SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__Type (fun _ => True) :=
(* Eval compute in *) proj3_format SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__nat__Format SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__F1 SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__F2 SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__F1F2 SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__F2F1.

Opaque SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__cond SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__Format.

Definition SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__Format : T_Format SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__Type (fun _ => True) :=
(* Eval compute in *) proj3_format SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__nat__Format SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__F1 SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__F2 SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__F1F2 SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__F2F1.

Opaque SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__cond SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__Format.

Definition SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__Format : T_Format SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__Type (fun _ => True) :=
(* Eval compute in *) proj3_format SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__nat__Format SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__F1 SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__F2 SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__F1F2 SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__F2F1.

Opaque SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__cond SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__Format.


Definition SpatialRelationsSRS_Pos_r16__Format_Type := Eval cbn in seq_format_prod SpatialRelationsSRS_Pos_r16__list.
Definition SpatialRelationsSRS_Pos_r16__Format_list : SpatialRelationsSRS_Pos_r16__Format_Type :=
  (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16__Format, (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16__Format, (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16__Format, (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16__Format, (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16__Format, (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16__Format, unit_format)))))).
Definition SpatialRelationsSRS_Pos_r16__list__Format := (*Eval compute in *) seq_format SpatialRelationsSRS_Pos_r16__list SpatialRelationsSRS_Pos_r16__Format_list.
Definition SpatialRelationsSRS_Pos_r16__F1 z :=
  (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Serving_r16 z, (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnCSI_RS_Serving_r16 z, (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Serving_r16 z, (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSRS_r16 z, (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnSSB_Neigh_r16 z, (SpatialRelationsSRS_Pos_r16__spatialRelation_SRS_PosBasedOnPRS_Neigh_r16 z, tt)))))).
Definition SpatialRelationsSRS_Pos_r16__F2 (y : seq_type SpatialRelationsSRS_Pos_r16__list) :=
  match y with
  | (i0, (i1, (i2, (i3, (i4, (i5, _))))))=>
    make__SpatialRelationsSRS_Pos_r16__Type i0 i1 i2 i3 i4 i5
  end.
Lemma SpatialRelationsSRS_Pos_r16__F1F2_cond (z : SpatialRelationsSRS_Pos_r16__Type)
  : SpatialRelationsSRS_Pos_r16__cond z ->
  (seq_cond SpatialRelationsSRS_Pos_r16__list (SpatialRelationsSRS_Pos_r16__F1 z)).
intro H. unfold SpatialRelationsSRS_Pos_r16__cond in H. simpl. auto. Qed.
Lemma SpatialRelationsSRS_Pos_r16__F1F2_cond2 (z : SpatialRelationsSRS_Pos_r16__Type)
 : SpatialRelationsSRS_Pos_r16__F2 (SpatialRelationsSRS_Pos_r16__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma SpatialRelationsSRS_Pos_r16__F2F1_cond (y : seq_type SpatialRelationsSRS_Pos_r16__list)
  : seq_cond SpatialRelationsSRS_Pos_r16__list y ->
 (SpatialRelationsSRS_Pos_r16__cond (SpatialRelationsSRS_Pos_r16__F2 y)) /\  SpatialRelationsSRS_Pos_r16__F1 (SpatialRelationsSRS_Pos_r16__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold SpatialRelationsSRS_Pos_r16__cond. simpl in *. auto.
 - simpl. unfold SpatialRelationsSRS_Pos_r16__F1. simpl. destruct_all_unit. auto.   Qed.
Definition SpatialRelationsSRS_Pos_r16__Format : T_Format SpatialRelationsSRS_Pos_r16__Type SpatialRelationsSRS_Pos_r16__cond :=
        proj2_format  SpatialRelationsSRS_Pos_r16__cond SpatialRelationsSRS_Pos_r16__list__Format
    SpatialRelationsSRS_Pos_r16__F1 SpatialRelationsSRS_Pos_r16__F2 SpatialRelationsSRS_Pos_r16__F1F2_cond  SpatialRelationsSRS_Pos_r16__F1F2_cond2 SpatialRelationsSRS_Pos_r16__F2F1_cond.
Opaque SpatialRelationsSRS_Pos_r16__cond SpatialRelationsSRS_Pos_r16__Format.

