Require Import ASN1Parser.ExtrOCaml.ExtractHelper.

Require Import NR.NR_RRC_Definitions.
Inductive UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__Type : Set :=
 | UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__true
.
Definition UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__cond := (fun (_ : UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__Type) => True).
Lemma UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__nat__helper.

Definition UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__F1 t :=
  match t with
  | UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__true => 0
  end.
Definition UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__F2 n :=
  match n with
  | 0 => UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__true
  | _ => UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__true
  end.
Lemma UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__F1F2 : forall x : UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__Type, (UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__F1 x <= 0) /\ UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__F2 (UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__F1 x) = x. imp_solve. Qed.
Lemma UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__F2F1 : forall (y : nat) (H : y <= 0), UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__F1 (UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__F2 y) = y. enum_solve H y. Qed.

Inductive UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__Type : Set :=
 | UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__true
.
Definition UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__cond := (fun (_ : UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__Type) => True).
Lemma UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__nat__helper.

Definition UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__F1 t :=
  match t with
  | UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__true => 0
  end.
Definition UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__F2 n :=
  match n with
  | 0 => UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__true
  | _ => UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__true
  end.
Lemma UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__F1F2 : forall x : UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__Type, (UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__F1 x <= 0) /\ UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__F2 (UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__F1 x) = x. imp_solve. Qed.
Lemma UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__F2F1 : forall (y : nat) (H : y <= 0), UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__F1 (UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__F2 y) = y. enum_solve H y. Qed.

Inductive UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__Type : Set :=
 | UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__true
.
Definition UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__cond := (fun (_ : UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__Type) => True).
Lemma UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__nat__helper.

Definition UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__F1 t :=
  match t with
  | UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__true => 0
  end.
Definition UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__F2 n :=
  match n with
  | 0 => UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__true
  | _ => UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__true
  end.
Lemma UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__F1F2 : forall x : UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__Type, (UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__F1 x <= 0) /\ UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__F2 (UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__F1 x) = x. imp_solve. Qed.
Lemma UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__F2F1 : forall (y : nat) (H : y <= 0), UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__F1 (UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__F2 y) = y. enum_solve H y. Qed.

Record UE_CapabilityRequestFilterCommon__mrdc_Request__Type : Set :=
  make__UE_CapabilityRequestFilterCommon__mrdc_Request__Type {
    UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC : option UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__Type ;
    UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC : option UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__Type ;
    UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC : option UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__Type ;
}.
Definition UE_CapabilityRequestFilterCommon__mrdc_Request__list := (
 Opt UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__Type UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__cond ::
 Opt UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__Type UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__cond ::
 Opt UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__Type UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__cond ::
 nil).
Definition UE_CapabilityRequestFilterCommon__mrdc_Request__cond z := 
  opt_cond UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__cond (UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC z) /\
  opt_cond UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__cond (UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC z) /\
  opt_cond UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__cond (UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC z) /\
  True.

Inductive UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__Type : Set :=
 | UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__true
.
Definition UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__cond := (fun (_ : UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__Type) => True).
Lemma UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__nat__helper.

Definition UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__F1 t :=
  match t with
  | UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__true => 0
  end.
Definition UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__F2 n :=
  match n with
  | 0 => UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__true
  | _ => UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__true
  end.
Lemma UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__F1F2 : forall x : UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__Type, (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__F1 x <= 0) /\ UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__F2 (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__F1 x) = x. imp_solve. Qed.
Lemma UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__F2F1 : forall (y : nat) (H : y <= 0), UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__F1 (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__F2 y) = y. enum_solve H y. Qed.

Inductive UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__Type : Set :=
 | UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__true
.
Definition UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__cond := (fun (_ : UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__Type) => True).
Lemma UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__nat__helper.

Definition UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__F1 t :=
  match t with
  | UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__true => 0
  end.
Definition UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__F2 n :=
  match n with
  | 0 => UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__true
  | _ => UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__true
  end.
Lemma UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__F1F2 : forall x : UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__Type, (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__F1 x <= 0) /\ UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__F2 (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__F1 x) = x. imp_solve. Qed.
Lemma UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__F2F1 : forall (y : nat) (H : y <= 0), UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__F1 (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__F2 y) = y. enum_solve H y. Qed.

Inductive UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__Type : Set :=
 | UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__true
.
Definition UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__cond := (fun (_ : UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__Type) => True).
Lemma UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__nat__helper.

Definition UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__F1 t :=
  match t with
  | UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__true => 0
  end.
Definition UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__F2 n :=
  match n with
  | 0 => UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__true
  | _ => UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__true
  end.
Lemma UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__F1F2 : forall x : UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__Type, (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__F1 x <= 0) /\ UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__F2 (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__F1 x) = x. imp_solve. Qed.
Lemma UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__F2F1 : forall (y : nat) (H : y <= 0), UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__F1 (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__F2 y) = y. enum_solve H y. Qed.

Inductive UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__Type : Set :=
 | UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__true
.
Definition UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__cond := (fun (_ : UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__Type) => True).
Lemma UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__nat__helper.

Definition UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__F1 t :=
  match t with
  | UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__true => 0
  end.
Definition UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__F2 n :=
  match n with
  | 0 => UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__true
  | _ => UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__true
  end.
Lemma UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__F1F2 : forall x : UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__Type, (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__F1 x <= 0) /\ UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__F2 (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__F1 x) = x. imp_solve. Qed.
Lemma UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__F2F1 : forall (y : nat) (H : y <= 0), UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__F1 (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__F2 y) = y. enum_solve H y. Qed.

Record UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__Type : Set :=
  make__UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__Type {
    UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16 : option UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__Type ;
    UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16 : option UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__Type ;
    UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16 : option UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__Type ;
    UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16 : option UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__Type ;
}.
Definition UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__list := (
 Opt UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__Type UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__cond ::
 Opt UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__Type UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__cond ::
 Opt UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__Type UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__cond ::
 Opt UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__Type UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__cond ::
 nil).
Definition UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__cond z := 
  opt_cond UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__cond (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16 z) /\
  opt_cond UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__cond (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16 z) /\
  opt_cond UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__cond (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16 z) /\
  opt_cond UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__cond (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16 z) /\
  True.

Inductive UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__Type : Set :=
 | UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__true
.
Definition UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__cond := (fun (_ : UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__Type) => True).
Lemma UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__nat__helper.

Definition UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__F1 t :=
  match t with
  | UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__true => 0
  end.
Definition UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__F2 n :=
  match n with
  | 0 => UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__true
  | _ => UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__true
  end.
Lemma UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__F1F2 : forall x : UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__Type, (UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__F1 x <= 0) /\ UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__F2 (UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__F1 x) = x. imp_solve. Qed.
Lemma UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__F2F1 : forall (y : nat) (H : y <= 0), UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__F1 (UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__F2 y) = y. enum_solve H y. Qed.

Record UE_CapabilityRequestFilterCommon__ext0O__Type : Set :=
  make__UE_CapabilityRequestFilterCommon__ext0O__Type {
    UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16 : option UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__Type ;
    UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16 : option UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__Type ;
}.
Definition UE_CapabilityRequestFilterCommon__ext0O__list := (
 Opt UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__Type UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__cond ::
 Opt UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__Type UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__cond ::
 nil).
Definition UE_CapabilityRequestFilterCommon__ext0O__cond z := 
  opt_cond UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__cond (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16 z) /\
  opt_cond UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__cond (UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16 z) /\
  True.

Definition UE_CapabilityRequestFilterCommon__ext0__Type := UE_CapabilityRequestFilterCommon__ext0O__Type.
Definition UE_CapabilityRequestFilterCommon__ext0__cond := UE_CapabilityRequestFilterCommon__ext0O__cond.

Require Import NR.CellGrouping_r16.

Opaque CellGrouping_r16__cond CellGrouping_r16__Format.

Definition UE_CapabilityRequestFilterCommon__ext1O__requestedCellGrouping_r16__Type := list CellGrouping_r16__Type.

Lemma UE_CapabilityRequestFilterCommon__ext1O__requestedCellGrouping_r16__helper1 : (0 <= 1 <= maxCellGroupings_r16)%Z. unfold maxCellGroupings_r16.
 lia. Qed.
Lemma UE_CapabilityRequestFilterCommon__ext1O__requestedCellGrouping_r16__helper2 : to_bit_sz (Z.to_nat (maxCellGroupings_r16 - 1)) <= INT_MAX_LEN.
unfold to_bit_sz, INT_MAX_LEN. 
        assert (H : (0 <= (maxCellGroupings_r16 - 1))%Z). { apply Zorder.Zle_minus_le_0. apply UE_CapabilityRequestFilterCommon__ext1O__requestedCellGrouping_r16__helper1. }
        assert (G := log2_same _ H). rewrite <- G.
        simpl. lia. Qed.
Definition UE_CapabilityRequestFilterCommon__ext1O__requestedCellGrouping_r16__cond (z : UE_CapabilityRequestFilterCommon__ext1O__requestedCellGrouping_r16__Type) :=  (1 <= Z.of_nat (length z) <= maxCellGroupings_r16)%Z /\ (list_and CellGrouping_r16__cond z) .

Record UE_CapabilityRequestFilterCommon__ext1O__Type : Set :=
  make__UE_CapabilityRequestFilterCommon__ext1O__Type {
    UE_CapabilityRequestFilterCommon__ext1O__requestedCellGrouping_r16 : option UE_CapabilityRequestFilterCommon__ext1O__requestedCellGrouping_r16__Type ;
}.
Definition UE_CapabilityRequestFilterCommon__ext1O__list := (
 Opt UE_CapabilityRequestFilterCommon__ext1O__requestedCellGrouping_r16__Type UE_CapabilityRequestFilterCommon__ext1O__requestedCellGrouping_r16__cond ::
 nil).
Definition UE_CapabilityRequestFilterCommon__ext1O__cond z := 
  opt_cond UE_CapabilityRequestFilterCommon__ext1O__requestedCellGrouping_r16__cond (UE_CapabilityRequestFilterCommon__ext1O__requestedCellGrouping_r16 z) /\
  True.

Definition UE_CapabilityRequestFilterCommon__ext1__Type := UE_CapabilityRequestFilterCommon__ext1O__Type.
Definition UE_CapabilityRequestFilterCommon__ext1__cond := UE_CapabilityRequestFilterCommon__ext1O__cond.

Inductive UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__Type : Set :=
 | UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__true
.
Definition UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__cond := (fun (_ : UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__Type) => True).
Lemma UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__nat__helper : to_bit_sz 0 <= INT_MAX_LEN.
  unfold to_bit_sz, INT_MAX_LEN. simpl. lia.
Qed.
Definition UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__nat__Format : T_Format nat (fun z => (z <= 0)) :=
  nat_enum_format 0 UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__nat__helper.

Definition UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__F1 t :=
  match t with
  | UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__true => 0
  end.
Definition UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__F2 n :=
  match n with
  | 0 => UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__true
  | _ => UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__true
  end.
Lemma UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__F1F2 : forall x : UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__Type, (UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__F1 x <= 0) /\ UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__F2 (UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__F1 x) = x. imp_solve. Qed.
Lemma UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__F2F1 : forall (y : nat) (H : y <= 0), UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__F1 (UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__F2 y) = y. enum_solve H y. Qed.

Record UE_CapabilityRequestFilterCommon__ext2O__Type : Set :=
  make__UE_CapabilityRequestFilterCommon__ext2O__Type {
    UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17 : option UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__Type ;
}.
Definition UE_CapabilityRequestFilterCommon__ext2O__list := (
 Opt UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__Type UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__cond ::
 nil).
Definition UE_CapabilityRequestFilterCommon__ext2O__cond z := 
  opt_cond UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__cond (UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17 z) /\
  True.

Definition UE_CapabilityRequestFilterCommon__ext2__Type := UE_CapabilityRequestFilterCommon__ext2O__Type.
Definition UE_CapabilityRequestFilterCommon__ext2__cond := UE_CapabilityRequestFilterCommon__ext2O__cond.

Record UE_CapabilityRequestFilterCommon__Type : Set :=
  make__UE_CapabilityRequestFilterCommon__Type {
    UE_CapabilityRequestFilterCommon__mrdc_Request : option UE_CapabilityRequestFilterCommon__mrdc_Request__Type ;
    UE_CapabilityRequestFilterCommon__ext0 : option UE_CapabilityRequestFilterCommon__ext0__Type ;
    UE_CapabilityRequestFilterCommon__ext1 : option UE_CapabilityRequestFilterCommon__ext1__Type ;
    UE_CapabilityRequestFilterCommon__ext2 : option UE_CapabilityRequestFilterCommon__ext2__Type ;
}.
Definition UE_CapabilityRequestFilterCommon__root_list : list seq_elem := (
 Opt UE_CapabilityRequestFilterCommon__mrdc_Request__Type UE_CapabilityRequestFilterCommon__mrdc_Request__cond ::
 nil).
Definition UE_CapabilityRequestFilterCommon__ext_list : list typ := (
  typ_cons UE_CapabilityRequestFilterCommon__ext0__Type UE_CapabilityRequestFilterCommon__ext0__cond ::
  typ_cons UE_CapabilityRequestFilterCommon__ext1__Type UE_CapabilityRequestFilterCommon__ext1__cond ::
  typ_cons UE_CapabilityRequestFilterCommon__ext2__Type UE_CapabilityRequestFilterCommon__ext2__cond ::
  nil).
Definition UE_CapabilityRequestFilterCommon__cond (z : UE_CapabilityRequestFilterCommon__Type) := 
(  opt_cond UE_CapabilityRequestFilterCommon__mrdc_Request__cond (UE_CapabilityRequestFilterCommon__mrdc_Request z) /\
  True) /\ 
(  opt_cond UE_CapabilityRequestFilterCommon__ext0__cond (UE_CapabilityRequestFilterCommon__ext0 z) /\
  opt_cond UE_CapabilityRequestFilterCommon__ext1__cond (UE_CapabilityRequestFilterCommon__ext1 z) /\
  opt_cond UE_CapabilityRequestFilterCommon__ext2__cond (UE_CapabilityRequestFilterCommon__ext2 z) /\
  True).


Opaque Byte.to_nat Byte.of_nat.
Opaque bind_parse restrict_parse proj_parse return_parse.
Opaque restrict_serialize proj_serialize sigma_serialize append_serialize proj2_serialize.

Opaque read_n_nat read_unit.
Opaque put_n_nat put_unit. 

Opaque opt_bind opt_serialize dft_serialize prepend_serialize list_serial.
Opaque opt_parse list_parse dft_parse fail_parse append_parse
  bind_parse return_parse.

Opaque Z.to_nat Z.of_nat Z.sub Z.add Z.le Z.lt Z.pow Z.opp Z.ltb.
Opaque Nat.mul Nat.shiftr Nat.shiftl Nat.div Nat.modulo Nat.leb Nat.ltb Nat.add
  Nat.sub Nat.land Nat.lor Nat.eqb  Nat.log2 Nat.pow Nat.even PeanoNat.Nat.lnot.
Opaque Compare_dec.le_dec Compare_dec.le_lt_dec ZArith_dec.Z_le_dec lt_eq_lt_dec_new. 
Opaque sumbool_and1 list_and list_and_cons list_cons_S flg_add. 

Opaque list_to_len.
   Opaque length Compare_dec.le_dec Compare_dec.lt_dec PeanoNat.Nat.eq_dec.
   Opaque bool__Format int__Format octet_string_nc__Format bit_string_nc__Format.

   Opaque ByteIdx_to_nat nat_to_ByteIdx add_opt list_bool_format normally_small_len_det_format
  get_byte_len to_parse_skip  open_typ_serialize open_typ_parse open_type_to_len.
  

Opaque seq_cond seq_ext_cond choice_cond.
Definition UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__Format : T_Format UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__Type (fun _ => True) :=
(* Eval compute in *) proj3_format UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__nat__Format UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__F1 UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__F2 UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__F1F2 UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__F2F1.

Opaque UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__cond UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__Format.

Definition UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__Format : T_Format UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__Type (fun _ => True) :=
(* Eval compute in *) proj3_format UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__nat__Format UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__F1 UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__F2 UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__F1F2 UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__F2F1.

Opaque UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__cond UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__Format.

Definition UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__Format : T_Format UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__Type (fun _ => True) :=
(* Eval compute in *) proj3_format UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__nat__Format UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__F1 UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__F2 UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__F1F2 UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__F2F1.

Opaque UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__cond UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__Format.


Definition UE_CapabilityRequestFilterCommon__mrdc_Request__Format_Type := Eval cbn in seq_format_prod UE_CapabilityRequestFilterCommon__mrdc_Request__list.
Definition UE_CapabilityRequestFilterCommon__mrdc_Request__Format_list : UE_CapabilityRequestFilterCommon__mrdc_Request__Format_Type :=
  (UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC__Format, (UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC__Format, (UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC__Format, unit_format))).
Definition UE_CapabilityRequestFilterCommon__mrdc_Request__list__Format := (*Eval compute in *) seq_format UE_CapabilityRequestFilterCommon__mrdc_Request__list UE_CapabilityRequestFilterCommon__mrdc_Request__Format_list.
Definition UE_CapabilityRequestFilterCommon__mrdc_Request__F1 z :=
  (UE_CapabilityRequestFilterCommon__mrdc_Request__omitEN_DC z, (UE_CapabilityRequestFilterCommon__mrdc_Request__includeNR_DC z, (UE_CapabilityRequestFilterCommon__mrdc_Request__includeNE_DC z, tt))).
Definition UE_CapabilityRequestFilterCommon__mrdc_Request__F2 (y : seq_type UE_CapabilityRequestFilterCommon__mrdc_Request__list) :=
  match y with
  | (i0, (i1, (i2, _)))=>
    make__UE_CapabilityRequestFilterCommon__mrdc_Request__Type i0 i1 i2
  end.
Lemma UE_CapabilityRequestFilterCommon__mrdc_Request__F1F2_cond (z : UE_CapabilityRequestFilterCommon__mrdc_Request__Type)
  : UE_CapabilityRequestFilterCommon__mrdc_Request__cond z ->
  (seq_cond UE_CapabilityRequestFilterCommon__mrdc_Request__list (UE_CapabilityRequestFilterCommon__mrdc_Request__F1 z)).
intro H. unfold UE_CapabilityRequestFilterCommon__mrdc_Request__cond in H. simpl. auto. Qed.
Lemma UE_CapabilityRequestFilterCommon__mrdc_Request__F1F2_cond2 (z : UE_CapabilityRequestFilterCommon__mrdc_Request__Type)
 : UE_CapabilityRequestFilterCommon__mrdc_Request__F2 (UE_CapabilityRequestFilterCommon__mrdc_Request__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma UE_CapabilityRequestFilterCommon__mrdc_Request__F2F1_cond (y : seq_type UE_CapabilityRequestFilterCommon__mrdc_Request__list)
  : seq_cond UE_CapabilityRequestFilterCommon__mrdc_Request__list y ->
 (UE_CapabilityRequestFilterCommon__mrdc_Request__cond (UE_CapabilityRequestFilterCommon__mrdc_Request__F2 y)) /\  UE_CapabilityRequestFilterCommon__mrdc_Request__F1 (UE_CapabilityRequestFilterCommon__mrdc_Request__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold UE_CapabilityRequestFilterCommon__mrdc_Request__cond. simpl in *. auto.
 - simpl. unfold UE_CapabilityRequestFilterCommon__mrdc_Request__F1. simpl. destruct_all_unit. auto.   Qed.
Definition UE_CapabilityRequestFilterCommon__mrdc_Request__Format : T_Format UE_CapabilityRequestFilterCommon__mrdc_Request__Type UE_CapabilityRequestFilterCommon__mrdc_Request__cond :=
        proj2_format  UE_CapabilityRequestFilterCommon__mrdc_Request__cond UE_CapabilityRequestFilterCommon__mrdc_Request__list__Format
    UE_CapabilityRequestFilterCommon__mrdc_Request__F1 UE_CapabilityRequestFilterCommon__mrdc_Request__F2 UE_CapabilityRequestFilterCommon__mrdc_Request__F1F2_cond  UE_CapabilityRequestFilterCommon__mrdc_Request__F1F2_cond2 UE_CapabilityRequestFilterCommon__mrdc_Request__F2F1_cond.
Opaque UE_CapabilityRequestFilterCommon__mrdc_Request__cond UE_CapabilityRequestFilterCommon__mrdc_Request__Format.

Definition UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__Format : T_Format UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__Type (fun _ => True) :=
(* Eval compute in *) proj3_format UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__nat__Format UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__F1 UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__F2 UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__F1F2 UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__F2F1.

Opaque UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__cond UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__Format.

Definition UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__Format : T_Format UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__Type (fun _ => True) :=
(* Eval compute in *) proj3_format UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__nat__Format UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__F1 UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__F2 UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__F1F2 UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__F2F1.

Opaque UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__cond UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__Format.

Definition UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__Format : T_Format UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__Type (fun _ => True) :=
(* Eval compute in *) proj3_format UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__nat__Format UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__F1 UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__F2 UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__F1F2 UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__F2F1.

Opaque UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__cond UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__Format.

Definition UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__Format : T_Format UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__Type (fun _ => True) :=
(* Eval compute in *) proj3_format UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__nat__Format UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__F1 UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__F2 UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__F1F2 UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__F2F1.

Opaque UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__cond UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__Format.


Definition UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__Format_Type := Eval cbn in seq_format_prod UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__list.
Definition UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__Format_list : UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__Format_Type :=
  (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16__Format, (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16__Format, (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16__Format, (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16__Format, unit_format)))).
Definition UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__list__Format := (*Eval compute in *) seq_format UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__list UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__Format_list.
Definition UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__F1 z :=
  (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_SinglePanel_r16 z, (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type1_MultiPanel_r16 z, (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_r16 z, (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__type2_PortSelection_r16 z, tt)))).
Definition UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__F2 (y : seq_type UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__list) :=
  match y with
  | (i0, (i1, (i2, (i3, _))))=>
    make__UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__Type i0 i1 i2 i3
  end.
Lemma UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__F1F2_cond (z : UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__Type)
  : UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__cond z ->
  (seq_cond UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__list (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__F1 z)).
intro H. unfold UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__cond in H. simpl. auto. Qed.
Lemma UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__F1F2_cond2 (z : UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__Type)
 : UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__F2 (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__F2F1_cond (y : seq_type UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__list)
  : seq_cond UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__list y ->
 (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__cond (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__F2 y)) /\  UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__F1 (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__cond. simpl in *. auto.
 - simpl. unfold UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__F1. simpl. destruct_all_unit. auto.   Qed.
Definition UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__Format : T_Format UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__Type UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__cond :=
        proj2_format  UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__cond UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__list__Format
    UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__F1 UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__F2 UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__F1F2_cond  UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__F1F2_cond2 UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__F2F1_cond.
Opaque UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__cond UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__Format.

Definition UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__Format : T_Format UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__Type (fun _ => True) :=
(* Eval compute in *) proj3_format UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__nat__Format UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__F1 UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__F2 UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__F1F2 UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__F2F1.

Opaque UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__cond UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__Format.


Definition UE_CapabilityRequestFilterCommon__ext0O__Format_Type := Eval cbn in seq_format_prod UE_CapabilityRequestFilterCommon__ext0O__list.
Definition UE_CapabilityRequestFilterCommon__ext0O__Format_list : UE_CapabilityRequestFilterCommon__ext0O__Format_Type :=
  (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16__Format, (UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16__Format, unit_format)).
Definition UE_CapabilityRequestFilterCommon__ext0O__list__Format := (*Eval compute in *) seq_format UE_CapabilityRequestFilterCommon__ext0O__list UE_CapabilityRequestFilterCommon__ext0O__Format_list.
Definition UE_CapabilityRequestFilterCommon__ext0O__F1 z :=
  (UE_CapabilityRequestFilterCommon__ext0O__codebookTypeRequest_r16 z, (UE_CapabilityRequestFilterCommon__ext0O__uplinkTxSwitchRequest_r16 z, tt)).
Definition UE_CapabilityRequestFilterCommon__ext0O__F2 (y : seq_type UE_CapabilityRequestFilterCommon__ext0O__list) :=
  match y with
  | (i0, (i1, _))=>
    make__UE_CapabilityRequestFilterCommon__ext0O__Type i0 i1
  end.
Lemma UE_CapabilityRequestFilterCommon__ext0O__F1F2_cond (z : UE_CapabilityRequestFilterCommon__ext0O__Type)
  : UE_CapabilityRequestFilterCommon__ext0O__cond z ->
  (seq_cond UE_CapabilityRequestFilterCommon__ext0O__list (UE_CapabilityRequestFilterCommon__ext0O__F1 z)).
intro H. unfold UE_CapabilityRequestFilterCommon__ext0O__cond in H. simpl. auto. Qed.
Lemma UE_CapabilityRequestFilterCommon__ext0O__F1F2_cond2 (z : UE_CapabilityRequestFilterCommon__ext0O__Type)
 : UE_CapabilityRequestFilterCommon__ext0O__F2 (UE_CapabilityRequestFilterCommon__ext0O__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma UE_CapabilityRequestFilterCommon__ext0O__F2F1_cond (y : seq_type UE_CapabilityRequestFilterCommon__ext0O__list)
  : seq_cond UE_CapabilityRequestFilterCommon__ext0O__list y ->
 (UE_CapabilityRequestFilterCommon__ext0O__cond (UE_CapabilityRequestFilterCommon__ext0O__F2 y)) /\  UE_CapabilityRequestFilterCommon__ext0O__F1 (UE_CapabilityRequestFilterCommon__ext0O__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold UE_CapabilityRequestFilterCommon__ext0O__cond. simpl in *. auto.
 - simpl. unfold UE_CapabilityRequestFilterCommon__ext0O__F1. simpl. destruct_all_unit. auto.   Qed.
Definition UE_CapabilityRequestFilterCommon__ext0O__Format : T_Format UE_CapabilityRequestFilterCommon__ext0O__Type UE_CapabilityRequestFilterCommon__ext0O__cond :=
        proj2_format  UE_CapabilityRequestFilterCommon__ext0O__cond UE_CapabilityRequestFilterCommon__ext0O__list__Format
    UE_CapabilityRequestFilterCommon__ext0O__F1 UE_CapabilityRequestFilterCommon__ext0O__F2 UE_CapabilityRequestFilterCommon__ext0O__F1F2_cond  UE_CapabilityRequestFilterCommon__ext0O__F1F2_cond2 UE_CapabilityRequestFilterCommon__ext0O__F2F1_cond.
Opaque UE_CapabilityRequestFilterCommon__ext0O__cond UE_CapabilityRequestFilterCommon__ext0O__Format.

Definition UE_CapabilityRequestFilterCommon__ext0__check_all_none (b : UE_CapabilityRequestFilterCommon__ext0O__Type) : bool :=
match b with 
  | make__UE_CapabilityRequestFilterCommon__ext0O__Type None None  => false 
  | _ => true 
 end.
Definition UE_CapabilityRequestFilterCommon__ext0__Format : T_Format UE_CapabilityRequestFilterCommon__ext0__Type UE_CapabilityRequestFilterCommon__ext0__cond :=
  restrict_add_format UE_CapabilityRequestFilterCommon__ext0__check_all_none UE_CapabilityRequestFilterCommon__ext0O__Format.

Opaque UE_CapabilityRequestFilterCommon__ext0__cond UE_CapabilityRequestFilterCommon__ext0__Format.

Definition UE_CapabilityRequestFilterCommon__ext1O__requestedCellGrouping_r16__Format : T_Format UE_CapabilityRequestFilterCommon__ext1O__requestedCellGrouping_r16__Type UE_CapabilityRequestFilterCommon__ext1O__requestedCellGrouping_r16__cond := seq_of_format CellGrouping_r16__Format 1 maxCellGroupings_r16 UE_CapabilityRequestFilterCommon__ext1O__requestedCellGrouping_r16__helper1 UE_CapabilityRequestFilterCommon__ext1O__requestedCellGrouping_r16__helper2.

Opaque UE_CapabilityRequestFilterCommon__ext1O__requestedCellGrouping_r16__cond UE_CapabilityRequestFilterCommon__ext1O__requestedCellGrouping_r16__Format.


Definition UE_CapabilityRequestFilterCommon__ext1O__Format_Type := Eval cbn in seq_format_prod UE_CapabilityRequestFilterCommon__ext1O__list.
Definition UE_CapabilityRequestFilterCommon__ext1O__Format_list : UE_CapabilityRequestFilterCommon__ext1O__Format_Type :=
  (UE_CapabilityRequestFilterCommon__ext1O__requestedCellGrouping_r16__Format, unit_format).
Definition UE_CapabilityRequestFilterCommon__ext1O__list__Format := (*Eval compute in *) seq_format UE_CapabilityRequestFilterCommon__ext1O__list UE_CapabilityRequestFilterCommon__ext1O__Format_list.
Definition UE_CapabilityRequestFilterCommon__ext1O__F1 z :=
  (UE_CapabilityRequestFilterCommon__ext1O__requestedCellGrouping_r16 z, tt).
Definition UE_CapabilityRequestFilterCommon__ext1O__F2 (y : seq_type UE_CapabilityRequestFilterCommon__ext1O__list) :=
  match y with
  | (i0, _)=>
    make__UE_CapabilityRequestFilterCommon__ext1O__Type i0
  end.
Lemma UE_CapabilityRequestFilterCommon__ext1O__F1F2_cond (z : UE_CapabilityRequestFilterCommon__ext1O__Type)
  : UE_CapabilityRequestFilterCommon__ext1O__cond z ->
  (seq_cond UE_CapabilityRequestFilterCommon__ext1O__list (UE_CapabilityRequestFilterCommon__ext1O__F1 z)).
intro H. unfold UE_CapabilityRequestFilterCommon__ext1O__cond in H. simpl. auto. Qed.
Lemma UE_CapabilityRequestFilterCommon__ext1O__F1F2_cond2 (z : UE_CapabilityRequestFilterCommon__ext1O__Type)
 : UE_CapabilityRequestFilterCommon__ext1O__F2 (UE_CapabilityRequestFilterCommon__ext1O__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma UE_CapabilityRequestFilterCommon__ext1O__F2F1_cond (y : seq_type UE_CapabilityRequestFilterCommon__ext1O__list)
  : seq_cond UE_CapabilityRequestFilterCommon__ext1O__list y ->
 (UE_CapabilityRequestFilterCommon__ext1O__cond (UE_CapabilityRequestFilterCommon__ext1O__F2 y)) /\  UE_CapabilityRequestFilterCommon__ext1O__F1 (UE_CapabilityRequestFilterCommon__ext1O__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold UE_CapabilityRequestFilterCommon__ext1O__cond. simpl in *. auto.
 - simpl. unfold UE_CapabilityRequestFilterCommon__ext1O__F1. simpl. destruct_all_unit. auto.   Qed.
Definition UE_CapabilityRequestFilterCommon__ext1O__Format : T_Format UE_CapabilityRequestFilterCommon__ext1O__Type UE_CapabilityRequestFilterCommon__ext1O__cond :=
        proj2_format  UE_CapabilityRequestFilterCommon__ext1O__cond UE_CapabilityRequestFilterCommon__ext1O__list__Format
    UE_CapabilityRequestFilterCommon__ext1O__F1 UE_CapabilityRequestFilterCommon__ext1O__F2 UE_CapabilityRequestFilterCommon__ext1O__F1F2_cond  UE_CapabilityRequestFilterCommon__ext1O__F1F2_cond2 UE_CapabilityRequestFilterCommon__ext1O__F2F1_cond.
Opaque UE_CapabilityRequestFilterCommon__ext1O__cond UE_CapabilityRequestFilterCommon__ext1O__Format.

Definition UE_CapabilityRequestFilterCommon__ext1__check_all_none (b : UE_CapabilityRequestFilterCommon__ext1O__Type) : bool :=
match b with 
  | make__UE_CapabilityRequestFilterCommon__ext1O__Type None  => false 
  | _ => true 
 end.
Definition UE_CapabilityRequestFilterCommon__ext1__Format : T_Format UE_CapabilityRequestFilterCommon__ext1__Type UE_CapabilityRequestFilterCommon__ext1__cond :=
  restrict_add_format UE_CapabilityRequestFilterCommon__ext1__check_all_none UE_CapabilityRequestFilterCommon__ext1O__Format.

Opaque UE_CapabilityRequestFilterCommon__ext1__cond UE_CapabilityRequestFilterCommon__ext1__Format.

Definition UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__Format : T_Format UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__Type (fun _ => True) :=
(* Eval compute in *) proj3_format UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__nat__Format UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__F1 UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__F2 UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__F1F2 UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__F2F1.

Opaque UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__cond UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__Format.


Definition UE_CapabilityRequestFilterCommon__ext2O__Format_Type := Eval cbn in seq_format_prod UE_CapabilityRequestFilterCommon__ext2O__list.
Definition UE_CapabilityRequestFilterCommon__ext2O__Format_list : UE_CapabilityRequestFilterCommon__ext2O__Format_Type :=
  (UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17__Format, unit_format).
Definition UE_CapabilityRequestFilterCommon__ext2O__list__Format := (*Eval compute in *) seq_format UE_CapabilityRequestFilterCommon__ext2O__list UE_CapabilityRequestFilterCommon__ext2O__Format_list.
Definition UE_CapabilityRequestFilterCommon__ext2O__F1 z :=
  (UE_CapabilityRequestFilterCommon__ext2O__fallbackGroupFiveRequest_r17 z, tt).
Definition UE_CapabilityRequestFilterCommon__ext2O__F2 (y : seq_type UE_CapabilityRequestFilterCommon__ext2O__list) :=
  match y with
  | (i0, _)=>
    make__UE_CapabilityRequestFilterCommon__ext2O__Type i0
  end.
Lemma UE_CapabilityRequestFilterCommon__ext2O__F1F2_cond (z : UE_CapabilityRequestFilterCommon__ext2O__Type)
  : UE_CapabilityRequestFilterCommon__ext2O__cond z ->
  (seq_cond UE_CapabilityRequestFilterCommon__ext2O__list (UE_CapabilityRequestFilterCommon__ext2O__F1 z)).
intro H. unfold UE_CapabilityRequestFilterCommon__ext2O__cond in H. simpl. auto. Qed.
Lemma UE_CapabilityRequestFilterCommon__ext2O__F1F2_cond2 (z : UE_CapabilityRequestFilterCommon__ext2O__Type)
 : UE_CapabilityRequestFilterCommon__ext2O__F2 (UE_CapabilityRequestFilterCommon__ext2O__F1 z) = z.
destruct z. simpl. auto. Qed.
Lemma UE_CapabilityRequestFilterCommon__ext2O__F2F1_cond (y : seq_type UE_CapabilityRequestFilterCommon__ext2O__list)
  : seq_cond UE_CapabilityRequestFilterCommon__ext2O__list y ->
 (UE_CapabilityRequestFilterCommon__ext2O__cond (UE_CapabilityRequestFilterCommon__ext2O__F2 y)) /\  UE_CapabilityRequestFilterCommon__ext2O__F1 (UE_CapabilityRequestFilterCommon__ext2O__F2 y) = y.
  intro H. split; unfold seq_type in y; simpl in y; repeat destruct_prod.
 - unfold UE_CapabilityRequestFilterCommon__ext2O__cond. simpl in *. auto.
 - simpl. unfold UE_CapabilityRequestFilterCommon__ext2O__F1. simpl. destruct_all_unit. auto.   Qed.
Definition UE_CapabilityRequestFilterCommon__ext2O__Format : T_Format UE_CapabilityRequestFilterCommon__ext2O__Type UE_CapabilityRequestFilterCommon__ext2O__cond :=
        proj2_format  UE_CapabilityRequestFilterCommon__ext2O__cond UE_CapabilityRequestFilterCommon__ext2O__list__Format
    UE_CapabilityRequestFilterCommon__ext2O__F1 UE_CapabilityRequestFilterCommon__ext2O__F2 UE_CapabilityRequestFilterCommon__ext2O__F1F2_cond  UE_CapabilityRequestFilterCommon__ext2O__F1F2_cond2 UE_CapabilityRequestFilterCommon__ext2O__F2F1_cond.
Opaque UE_CapabilityRequestFilterCommon__ext2O__cond UE_CapabilityRequestFilterCommon__ext2O__Format.

Definition UE_CapabilityRequestFilterCommon__ext2__check_all_none (b : UE_CapabilityRequestFilterCommon__ext2O__Type) : bool :=
match b with 
  | make__UE_CapabilityRequestFilterCommon__ext2O__Type None  => false 
  | _ => true 
 end.
Definition UE_CapabilityRequestFilterCommon__ext2__Format : T_Format UE_CapabilityRequestFilterCommon__ext2__Type UE_CapabilityRequestFilterCommon__ext2__cond :=
  restrict_add_format UE_CapabilityRequestFilterCommon__ext2__check_all_none UE_CapabilityRequestFilterCommon__ext2O__Format.

Opaque UE_CapabilityRequestFilterCommon__ext2__cond UE_CapabilityRequestFilterCommon__ext2__Format.


Definition UE_CapabilityRequestFilterCommon__root_Format_Type := Eval cbn in seq_format_prod UE_CapabilityRequestFilterCommon__root_list.
Definition UE_CapabilityRequestFilterCommon__root_Format_list : UE_CapabilityRequestFilterCommon__root_Format_Type :=
  (UE_CapabilityRequestFilterCommon__mrdc_Request__Format, unit_format).

Definition UE_CapabilityRequestFilterCommon__ext_Format_Type := Eval cbn in get_formats UE_CapabilityRequestFilterCommon__ext_list.
Definition UE_CapabilityRequestFilterCommon__ext_Format_list : UE_CapabilityRequestFilterCommon__ext_Format_Type :=
  (UE_CapabilityRequestFilterCommon__ext0__Format, (UE_CapabilityRequestFilterCommon__ext1__Format, (UE_CapabilityRequestFilterCommon__ext2__Format, unit__Format))).

Definition UE_CapabilityRequestFilterCommon__list_type : Set := (seq_type UE_CapabilityRequestFilterCommon__root_list) * (seq_ext_type UE_CapabilityRequestFilterCommon__ext_list).
Definition UE_CapabilityRequestFilterCommon__list_cond (z : UE_CapabilityRequestFilterCommon__list_type) : Prop :=
        (seq_cond UE_CapabilityRequestFilterCommon__root_list (fst z)) /\ (seq_ext_cond UE_CapabilityRequestFilterCommon__ext_list (snd z)).
Definition UE_CapabilityRequestFilterCommon__list_format : T_Format UE_CapabilityRequestFilterCommon__list_type UE_CapabilityRequestFilterCommon__list_cond :=
 (* Eval compute in *) seq_ext_format UE_CapabilityRequestFilterCommon__root_list UE_CapabilityRequestFilterCommon__root_Format_list UE_CapabilityRequestFilterCommon__ext_list UE_CapabilityRequestFilterCommon__ext_Format_list.

Opaque UE_CapabilityRequestFilterCommon__list_format.
Definition UE_CapabilityRequestFilterCommon__F1 (z : UE_CapabilityRequestFilterCommon__Type) : UE_CapabilityRequestFilterCommon__list_type :=
  (((UE_CapabilityRequestFilterCommon__mrdc_Request z, tt)), (
(UE_CapabilityRequestFilterCommon__ext0 z, (UE_CapabilityRequestFilterCommon__ext1 z, (UE_CapabilityRequestFilterCommon__ext2 z, tt))))).
Definition UE_CapabilityRequestFilterCommon__F2 (y : UE_CapabilityRequestFilterCommon__list_type) : UE_CapabilityRequestFilterCommon__Type :=
  match y with
  | ((j0, _), (i0, (i1, (i2, _))))=>
    make__UE_CapabilityRequestFilterCommon__Type j0 i0 i1 i2
  end.
Definition UE_CapabilityRequestFilterCommon__helper1 : (forall a : UE_CapabilityRequestFilterCommon__Type, UE_CapabilityRequestFilterCommon__cond a -> UE_CapabilityRequestFilterCommon__list_cond (UE_CapabilityRequestFilterCommon__F1 a)).
                     intros. destruct a. auto. Qed.
Definition UE_CapabilityRequestFilterCommon__helper2 : (forall a : UE_CapabilityRequestFilterCommon__Type, UE_CapabilityRequestFilterCommon__F2 (UE_CapabilityRequestFilterCommon__F1 a) = a).
                     intros. destruct a. auto. Qed.
Definition UE_CapabilityRequestFilterCommon__helper3 : (forall b : UE_CapabilityRequestFilterCommon__list_type, UE_CapabilityRequestFilterCommon__list_cond b -> UE_CapabilityRequestFilterCommon__cond (UE_CapabilityRequestFilterCommon__F2 b) /\ UE_CapabilityRequestFilterCommon__F1 (UE_CapabilityRequestFilterCommon__F2 b) = b).
                     intros. destruct b as [y y1]. unfold UE_CapabilityRequestFilterCommon__cond, UE_CapabilityRequestFilterCommon__list_cond in *. simpl.
                     split; unfold seq_type, seq_ext_type in *; simpl in y, y1; repeat destruct_prod; split_and; simpl in *; destruct_all_unit; auto; repeat (split; auto). 

                     Qed.
Definition UE_CapabilityRequestFilterCommon__Format : T_Format UE_CapabilityRequestFilterCommon__Type UE_CapabilityRequestFilterCommon__cond :=
 proj2_format UE_CapabilityRequestFilterCommon__cond UE_CapabilityRequestFilterCommon__list_format  UE_CapabilityRequestFilterCommon__F1 UE_CapabilityRequestFilterCommon__F2 UE_CapabilityRequestFilterCommon__helper1 UE_CapabilityRequestFilterCommon__helper2 UE_CapabilityRequestFilterCommon__helper3.

Opaque UE_CapabilityRequestFilterCommon__cond UE_CapabilityRequestFilterCommon__Format.

