// This C++ source file was generated by the ASN.1 compiler
// of the TTCN-3 Test Executor version 11.0.0
// for Yilu Dong (yvd5140@e5-cse-362sns2) on Sat May 31 17:31:59 2025

// Copyright (c) 2000-2024 Ericsson Telecom AB

// Do not edit this file unless you know what you are doing.

/* Including header files */

#include "Foo.hh"

namespace Foo {

/* Global variable definitions */

// No XER for S1
const TTCN_JSONdescriptor_t S1_json_ = { FALSE, NULL, FALSE, { JD_UNSET, NULL, NULL }, FALSE, FALSE, FALSE, 0, NULL, FALSE, ESCAPE_AS_SHORT };
const int S1_oer_ext_arr_[0] = {};
const int S1_oer_p_[0] = {};
const TTCN_OERdescriptor_t S1_oer_ = { -1, TRUE, -1, TRUE, 1, 0, S1_oer_ext_arr_, 0, S1_oer_p_};
static const Per_Constraint S1_per_cons_;
const ASN_PERdescriptor_t S1_per_ = { &S1_per_cons_ };
const TTCN_Typedescriptor_t S1_descr_ = { "@Foo.S1", &CHOICE_ber_, &S1_json_, &S1_oer_, &S1_per_, NULL, TTCN_Typedescriptor_t::DONTCARE };
static const ASN_Tag_t S1_b1_tag_[] = { { ASN_TAG_CONT, 0u }};
const ASN_BERdescriptor_t S1_b1_ber_ = { 1u, S1_b1_tag_ };
// No XER for S1_b1
const int S1_b1_oer_ext_arr_[0] = {};
const int S1_b1_oer_p_[0] = {};
const TTCN_OERdescriptor_t S1_b1_oer_ = { -1, TRUE, -1, FALSE, 0, 0, S1_b1_oer_ext_arr_, 0, S1_b1_oer_p_};
const TTCN_Typedescriptor_t S1_b1_descr_ = { "@Foo.S1.b1", &S1_b1_ber_, &BOOLEAN_json_, &S1_b1_oer_, &BOOLEAN_per_, NULL, TTCN_Typedescriptor_t::DONTCARE };
static const ASN_Tag_t S1_b2_tag_[] = { { ASN_TAG_CONT, 1u }};
const ASN_BERdescriptor_t S1_b2_ber_ = { 1u, S1_b2_tag_ };
// No XER for S1_b2
const int S1_b2_oer_ext_arr_[0] = {};
const int S1_b2_oer_p_[0] = {};
const TTCN_OERdescriptor_t S1_b2_oer_ = { -1, TRUE, -1, FALSE, 0, 0, S1_b2_oer_ext_arr_, 0, S1_b2_oer_p_};
const TTCN_Typedescriptor_t S1_b2_descr_ = { "@Foo.S1.b2", &S1_b2_ber_, &BOOLEAN_json_, &S1_b2_oer_, &BOOLEAN_per_, NULL, TTCN_Typedescriptor_t::DONTCARE };
static const ASN_Tag_t S1_b3_tag_[] = { { ASN_TAG_CONT, 2u }};
const ASN_BERdescriptor_t S1_b3_ber_ = { 1u, S1_b3_tag_ };
// No XER for S1_b3
const int S1_b3_oer_ext_arr_[0] = {};
const int S1_b3_oer_p_[0] = {};
const TTCN_OERdescriptor_t S1_b3_oer_ = { -1, TRUE, -1, FALSE, 0, 0, S1_b3_oer_ext_arr_, 0, S1_b3_oer_p_};
const TTCN_Typedescriptor_t S1_b3_descr_ = { "@Foo.S1.b3", &S1_b3_ber_, &BOOLEAN_json_, &S1_b3_oer_, &BOOLEAN_per_, NULL, TTCN_Typedescriptor_t::DONTCARE };

/* Member functions of C++ classes */

void S1::copy_value(const S1& other_value)
{
switch (other_value.union_selection) {
case ALT_b1:
field_b1 = new BOOLEAN(*other_value.field_b1);
break;
case ALT_b2:
field_b2 = new BOOLEAN(*other_value.field_b2);
break;
case ALT_b3:
field_b3 = new BOOLEAN(*other_value.field_b3);
break;
default:
TTCN_error("Assignment of an unbound union value of type @Foo.S1.");
}
union_selection = other_value.union_selection;
}

S1::S1()
{
union_selection = UNBOUND_VALUE;
}

S1::S1(const S1& other_value)
: Base_Type(){
copy_value(other_value);
}

S1::~S1()
{
clean_up();
}

S1& S1::operator=(const S1& other_value)
{
if (this != &other_value) {
clean_up();
copy_value(other_value);
}
return *this;
}

boolean S1::operator==(const S1& other_value) const
{
if (union_selection == UNBOUND_VALUE) TTCN_error("The left operand of comparison is an unbound value of union type @Foo.S1.");
if (other_value.union_selection == UNBOUND_VALUE) TTCN_error("The right operand of comparison is an unbound value of union type @Foo.S1.");
if (union_selection != other_value.union_selection) return FALSE;
switch (union_selection) {
case ALT_b1:
return *field_b1 == *other_value.field_b1;
case ALT_b2:
return *field_b2 == *other_value.field_b2;
case ALT_b3:
return *field_b3 == *other_value.field_b3;
default:
return FALSE;
}
}

BOOLEAN& S1::b1()
{
if (union_selection != ALT_b1) {
clean_up();
field_b1 = new BOOLEAN;
union_selection = ALT_b1;
}
return *field_b1;
}

const BOOLEAN& S1::b1() const
{
if (union_selection != ALT_b1) TTCN_error("Using non-selected field b1 in a value of union type @Foo.S1.");
return *field_b1;
}

BOOLEAN& S1::b2()
{
if (union_selection != ALT_b2) {
clean_up();
field_b2 = new BOOLEAN;
union_selection = ALT_b2;
}
return *field_b2;
}

const BOOLEAN& S1::b2() const
{
if (union_selection != ALT_b2) TTCN_error("Using non-selected field b2 in a value of union type @Foo.S1.");
return *field_b2;
}

BOOLEAN& S1::b3()
{
if (union_selection != ALT_b3) {
clean_up();
field_b3 = new BOOLEAN;
union_selection = ALT_b3;
}
return *field_b3;
}

const BOOLEAN& S1::b3() const
{
if (union_selection != ALT_b3) TTCN_error("Using non-selected field b3 in a value of union type @Foo.S1.");
return *field_b3;
}

boolean S1::ischosen(union_selection_type checked_selection) const
{
if (checked_selection == UNBOUND_VALUE) TTCN_error("Internal error: Performing ischosen() operation on an invalid field of union type @Foo.S1.");
return union_selection == checked_selection;
}

boolean S1::is_bound() const
{
  return union_selection != UNBOUND_VALUE;
}

boolean S1::is_value() const
{
switch (union_selection) {
case UNBOUND_VALUE: return FALSE;
case ALT_b1: return field_b1->is_value();
case ALT_b2: return field_b2->is_value();
case ALT_b3: return field_b3->is_value();
default: TTCN_error("Invalid selection in union is_bound");}
}

void S1::clean_up()
{
switch (union_selection) {
case ALT_b1:
  delete field_b1;
  break;
case ALT_b2:
  delete field_b2;
  break;
case ALT_b3:
  delete field_b3;
  break;
default:
  break;
}
union_selection = UNBOUND_VALUE;
}

CHARSTRING S1::log() const
{
switch (union_selection) {
case ALT_b1:
return CHARSTRING("{ b1 := ") + field_b1->log() + CHARSTRING(" }");
case ALT_b2:
return CHARSTRING("{ b2 := ") + field_b2->log() + CHARSTRING(" }");
case ALT_b3:
return CHARSTRING("{ b3 := ") + field_b3->log() + CHARSTRING(" }");
default:
return UNBOUND_VALUE_LOG;
}
}

void S1::set_implicit_omit()
{
switch (union_selection) {
case ALT_b1:
field_b1->set_implicit_omit(); break;
case ALT_b2:
field_b2->set_implicit_omit(); break;
case ALT_b3:
field_b3->set_implicit_omit(); break;
default: break;
}
}

void S1::encode(const TTCN_Typedescriptor_t& p_td, TTCN_Buffer& p_buf, int p_coding, ...) const
{
  va_list pvar;
  va_start(pvar, p_coding);
  switch(p_coding) {
  case TTCN_EncDec::CT_BER: {
    TTCN_EncDec_ErrorContext ec("While BER-encoding type '%s': ", p_td.name);
    unsigned BER_coding=va_arg(pvar, unsigned);
    BER_encode_chk_coding(BER_coding);
    ASN_BER_TLV_t *tlv=BER_encode_TLV(p_td, BER_coding);
    tlv->put_in_buffer(p_buf);
    ASN_BER_TLV_t::destruct(tlv);
    break;}
  case TTCN_EncDec::CT_JSON: {
    TTCN_EncDec_ErrorContext ec("While JSON-encoding type '%s': ", p_td.name);
    if(!p_td.json)
      TTCN_EncDec_ErrorContext::error_internal
        ("No JSON descriptor available for type '%s'.", p_td.name);
    JSON_Tokenizer tok(va_arg(pvar, int) != 0);
    JSON_encode(p_td, tok, FALSE);
    p_buf.put_s(tok.get_buffer_length(), (const unsigned char*)tok.get_buffer());
    break;}
  case TTCN_EncDec::CT_OER: {
    TTCN_EncDec_ErrorContext ec("While OER-encoding type '%s': ", p_td.name);
    if(!p_td.oer)
      TTCN_EncDec_ErrorContext::error_internal
        ("No OER descriptor available for type '%s'.", p_td.name);
    OER_encode(p_td, p_buf);
    break;}
  case TTCN_EncDec::CT_PER: {
    TTCN_EncDec_ErrorContext ec("While PER-encoding type '%s': ", p_td.name);
    if (!p_td.per) TTCN_EncDec_ErrorContext::error_internal(
      "No PER descriptor available for type '%s'.", p_td.name);
    int opt = va_arg(pvar, int);
    PER_encode(p_td, p_buf, opt);
    break; }
  default:
    TTCN_error("Unknown coding method requested to encode type '%s'", p_td.name);
  }
  va_end(pvar);
}

void S1::decode(const TTCN_Typedescriptor_t& p_td, TTCN_Buffer& p_buf, int p_coding, ...)
{
  va_list pvar;
  va_start(pvar, p_coding);
  switch(p_coding) {
  case TTCN_EncDec::CT_BER: {
    TTCN_EncDec_ErrorContext ec("While BER-decoding type '%s': ", p_td.name);
    unsigned L_form=va_arg(pvar, unsigned);
    ASN_BER_TLV_t tlv;
    BER_decode_str2TLV(p_buf, tlv, L_form);
    BER_decode_TLV(p_td, tlv, L_form);
    if(tlv.isComplete) p_buf.increase_pos(tlv.get_len());
    break;}
  case TTCN_EncDec::CT_JSON: {
    TTCN_EncDec_ErrorContext ec("While JSON-decoding type '%s': ", p_td.name);
    if(!p_td.json)
      TTCN_EncDec_ErrorContext::error_internal
        ("No JSON descriptor available for type '%s'.", p_td.name);
    JSON_Tokenizer tok((const char*)p_buf.get_data(), p_buf.get_len());
    if(JSON_decode(p_td, tok, FALSE, FALSE)<0)
      ec.error(TTCN_EncDec::ET_INCOMPL_MSG,"Can not decode type '%s', because invalid or incomplete message was received", p_td.name);
    p_buf.set_pos(tok.get_buf_pos());
    break;}
  case TTCN_EncDec::CT_OER: {
    TTCN_EncDec_ErrorContext ec("While OER-decoding type '%s': ", p_td.name);
    if(!p_td.oer)
      TTCN_EncDec_ErrorContext::error_internal
        ("No OER descriptor available for type '%s'.", p_td.name);
     OER_struct p_oer;
    OER_decode(p_td, p_buf, p_oer);
    break;}
  case TTCN_EncDec::CT_PER: {
    TTCN_EncDec_ErrorContext ec("While PER-decoding type '%s': ", p_td.name);
    if(!p_td.per)  TTCN_EncDec_ErrorContext::error_internal(
      "No PER descriptor available for type '%s'.", p_td.name);
    int opt = va_arg(pvar, int);
    try {
      PER_decode(p_td, p_buf, opt);
      p_buf.PER_octet_align(FALSE);
    }
    catch (PER_Buffer_Exception) { }
    break; }
  default:
    TTCN_error("Unknown coding method requested to decode type '%s'", p_td.name);
  }
  va_end(pvar);
}

ASN_BER_TLV_t *S1::BER_encode_TLV(const TTCN_Typedescriptor_t& p_td, unsigned p_coding) const
{
  BER_chk_descr(p_td);
  ASN_BER_TLV_t *new_tlv;
  TTCN_EncDec_ErrorContext ec_0("Alternative '");
  TTCN_EncDec_ErrorContext ec_1;
  switch (union_selection) {
  case ALT_b1:
    ec_1.set_msg("b1': ");
    new_tlv = field_b1->BER_encode_TLV(S1_b1_descr_, p_coding);
    break;
  case ALT_b2:
    ec_1.set_msg("b2': ");
    new_tlv = field_b2->BER_encode_TLV(S1_b2_descr_, p_coding);
    break;
  case ALT_b3:
    ec_1.set_msg("b3': ");
    new_tlv = field_b3->BER_encode_TLV(S1_b3_descr_, p_coding);
    break;
  case UNBOUND_VALUE:
    new_tlv = BER_encode_chk_bound(FALSE);
    break;
  default:
    TTCN_EncDec_ErrorContext::error_internal("Unknown selection.");
    new_tlv = NULL;
  }
  return ASN_BER_V2TLV(new_tlv, p_td, p_coding);
}

boolean S1::BER_decode_set_selection(const ASN_BER_TLV_t& p_tlv)
{
  clean_up();
  field_b1 = new BOOLEAN;
  union_selection = ALT_b1;
  if (field_b1->BER_decode_isMyMsg(S1_b1_descr_, p_tlv)) return TRUE;
  delete field_b1;
  field_b2 = new BOOLEAN;
  union_selection = ALT_b2;
  if (field_b2->BER_decode_isMyMsg(S1_b2_descr_, p_tlv)) return TRUE;
  delete field_b2;
  field_b3 = new BOOLEAN;
  union_selection = ALT_b3;
  if (field_b3->BER_decode_isMyMsg(S1_b3_descr_, p_tlv)) return TRUE;
  delete field_b3;
  union_selection = UNBOUND_VALUE;
  return FALSE;
}

boolean S1::BER_decode_isMyMsg(const TTCN_Typedescriptor_t& p_td, const ASN_BER_TLV_t& p_tlv)
{
  if (p_td.ber->n_tags == 0) {
    S1 tmp_type;
    return tmp_type.BER_decode_set_selection(p_tlv);
  } else return Base_Type::BER_decode_isMyMsg(p_td, p_tlv);
}

boolean S1::BER_decode_TLV(const TTCN_Typedescriptor_t& p_td, const ASN_BER_TLV_t& p_tlv, unsigned L_form)
{
  BER_chk_descr(p_td);
  ASN_BER_TLV_t stripped_tlv;
  BER_decode_strip_tags(*p_td.ber, p_tlv, L_form, stripped_tlv);
  TTCN_EncDec_ErrorContext ec_0("While decoding '@Foo.S1' type: ");
  ASN_BER_TLV_t tmp_tlv;
  if (!BER_decode_TLV_CHOICE(*p_td.ber, stripped_tlv, L_form, tmp_tlv) || !BER_decode_CHOICE_selection(BER_decode_set_selection(tmp_tlv), tmp_tlv)) return FALSE;
  TTCN_EncDec_ErrorContext ec_1("Alternative '");
  TTCN_EncDec_ErrorContext ec_2;
  switch (union_selection) {
  case ALT_b1:
    ec_2.set_msg("b1': ");
    field_b1->BER_decode_TLV(S1_b1_descr_, tmp_tlv, L_form);
    break;
  case ALT_b2:
    ec_2.set_msg("b2': ");
    field_b2->BER_decode_TLV(S1_b2_descr_, tmp_tlv, L_form);
    break;
  case ALT_b3:
    ec_2.set_msg("b3': ");
    field_b3->BER_decode_TLV(S1_b3_descr_, tmp_tlv, L_form);
    break;
  default:
    return FALSE;
  }
  return TRUE;
}

int S1::JSON_encode(const TTCN_Typedescriptor_t& p_td, JSON_Tokenizer& p_tok, boolean) const
{
  boolean as_value = p_td.json->as_value;
  int enc_len = as_value ? 0 : p_tok.put_next_token(JSON_TOKEN_OBJECT_START, NULL);
  switch(union_selection) {
  case ALT_b1:
    if (!as_value) {
      enc_len += p_tok.put_next_token(JSON_TOKEN_NAME, "b1");
    }
    enc_len += field_b1->JSON_encode(S1_b1_descr_, p_tok, FALSE);
    break;
  case ALT_b2:
    if (!as_value) {
      enc_len += p_tok.put_next_token(JSON_TOKEN_NAME, "b2");
    }
    enc_len += field_b2->JSON_encode(S1_b2_descr_, p_tok, FALSE);
    break;
  case ALT_b3:
    if (!as_value) {
      enc_len += p_tok.put_next_token(JSON_TOKEN_NAME, "b3");
    }
    enc_len += field_b3->JSON_encode(S1_b3_descr_, p_tok, FALSE);
    break;
  default:
    TTCN_EncDec_ErrorContext::error(TTCN_EncDec::ET_UNBOUND, 
      "Encoding an unbound value of type @Foo.S1.");
    return -1;
  }

  if (!as_value) {
    enc_len += p_tok.put_next_token(JSON_TOKEN_OBJECT_END, NULL);
  }
  return enc_len;
}

int S1::JSON_decode(const TTCN_Typedescriptor_t& p_td, JSON_Tokenizer& p_tok, boolean p_silent, boolean, int p_chosen_field)
{
  if (0 <= p_chosen_field && 3 > p_chosen_field) {
    switch (p_chosen_field) {
    case 0:
      return b1().JSON_decode(S1_b1_descr_, p_tok, TRUE, FALSE);
    case 1:
      return b2().JSON_decode(S1_b2_descr_, p_tok, TRUE, FALSE);
    case 2:
      return b3().JSON_decode(S1_b3_descr_, p_tok, TRUE, FALSE);
    }
  }
  if (p_td.json->default_value.type == JD_STANDARD && 0 == p_tok.get_buffer_length()) {
    *this = *static_cast<const S1*>(p_td.json->default_value.val);
    return 0;
  }
  json_token_t j_token = JSON_TOKEN_NONE;
 if (p_td.json->as_value) {
  size_t buf_pos = p_tok.get_buf_pos();
  p_tok.get_next_token(&j_token, NULL, NULL);
  int ret_val = 0;
  switch(j_token) {
  case JSON_TOKEN_NUMBER: {
    JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_AS_VALUE_ERROR, "number '@Foo.S1'");
    clean_up();
    return JSON_ERROR_FATAL;
  }
  case JSON_TOKEN_STRING: {
    JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_AS_VALUE_ERROR, "string '@Foo.S1'");
    clean_up();
    return JSON_ERROR_FATAL;
  }
  case JSON_TOKEN_LITERAL_TRUE:
  case JSON_TOKEN_LITERAL_FALSE: {
    p_tok.set_buf_pos(buf_pos);
    ret_val = b1().JSON_decode(S1_b1_descr_, p_tok, TRUE, FALSE);
    if (0 <= ret_val) {
      return ret_val;
    }
    p_tok.set_buf_pos(buf_pos);
    ret_val = b2().JSON_decode(S1_b2_descr_, p_tok, TRUE, FALSE);
    if (0 <= ret_val) {
      return ret_val;
    }
    p_tok.set_buf_pos(buf_pos);
    ret_val = b3().JSON_decode(S1_b3_descr_, p_tok, TRUE, FALSE);
    if (0 <= ret_val) {
      return ret_val;
    }
    char* literal_str = mprintf("literal (%s)",
      (JSON_TOKEN_LITERAL_TRUE == j_token) ? "true" : "false");
    try {
      JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_AS_VALUE_ERROR, literal_str);
    }
    catch (const TC_Error&) {
      Free(literal_str);
      throw;
    }
    Free(literal_str);
    clean_up();
    return JSON_ERROR_FATAL;
  }
  case JSON_TOKEN_ARRAY_START: {
    JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_AS_VALUE_ERROR, "array '@Foo.S1'");
    clean_up();
    return JSON_ERROR_FATAL;
  }
  case JSON_TOKEN_OBJECT_START: {
    JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_AS_VALUE_ERROR, "object '@Foo.S1'");
    clean_up();
    return JSON_ERROR_FATAL;
  }
  case JSON_TOKEN_LITERAL_NULL: {
    clean_up();
    return JSON_ERROR_INVALID_TOKEN;
  }
  case JSON_TOKEN_ERROR:
    JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_BAD_TOKEN_ERROR, "");
    return JSON_ERROR_FATAL;
  default:
    return JSON_ERROR_INVALID_TOKEN;
  }
  return ret_val;
 }
 else {
  size_t dec_len = p_tok.get_next_token(&j_token, NULL, NULL);
  if (JSON_TOKEN_ERROR == j_token) {
    JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_BAD_TOKEN_ERROR, "");
    return JSON_ERROR_FATAL;
  }
  else if (JSON_TOKEN_OBJECT_START != j_token) {
    return JSON_ERROR_INVALID_TOKEN;
  }

  char* fld_name = 0;
  size_t name_len = 0;
  dec_len += p_tok.get_next_token(&j_token, &fld_name, &name_len);
  if (JSON_TOKEN_NAME != j_token) {
    JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_NAME_TOKEN_ERROR);
    return JSON_ERROR_FATAL;
  } else {
if (2 == name_len && 0 == strncmp(fld_name, "b1", name_len)) {
      int ret_val = b1().JSON_decode(S1_b1_descr_, p_tok, p_silent, FALSE);
      if (0 > ret_val) {
        if (JSON_ERROR_INVALID_TOKEN == ret_val) {
          JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_FIELD_TOKEN_ERROR, 2, "b1");
        }
        return JSON_ERROR_FATAL;
      } else {
        dec_len += (size_t)ret_val;
      }
    } else if (2 == name_len && 0 == strncmp(fld_name, "b2", name_len)) {
      int ret_val = b2().JSON_decode(S1_b2_descr_, p_tok, p_silent, FALSE);
      if (0 > ret_val) {
        if (JSON_ERROR_INVALID_TOKEN == ret_val) {
          JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_FIELD_TOKEN_ERROR, 2, "b2");
        }
        return JSON_ERROR_FATAL;
      } else {
        dec_len += (size_t)ret_val;
      }
    } else if (2 == name_len && 0 == strncmp(fld_name, "b3", name_len)) {
      int ret_val = b3().JSON_decode(S1_b3_descr_, p_tok, p_silent, FALSE);
      if (0 > ret_val) {
        if (JSON_ERROR_INVALID_TOKEN == ret_val) {
          JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_FIELD_TOKEN_ERROR, 2, "b3");
        }
        return JSON_ERROR_FATAL;
      } else {
        dec_len += (size_t)ret_val;
      }
    } else {
      JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_INVALID_NAME_ERROR, (int)name_len, fld_name);
      return JSON_ERROR_FATAL;
    }
  }

  dec_len += p_tok.get_next_token(&j_token, NULL, NULL);
  if (JSON_TOKEN_OBJECT_END != j_token) {
    JSON_ERROR(TTCN_EncDec::ET_INVAL_MSG, JSON_DEC_STATIC_OBJECT_END_TOKEN_ERROR, "");
    return JSON_ERROR_FATAL;
  }

  return (int)dec_len;
 }
}

int S1::OER_encode(const TTCN_Typedescriptor_t&, TTCN_Buffer& p_buf) const
{
  switch(union_selection) {
  case ALT_b1:
    {TTCN_Buffer buf;
    encode_oer_tag(*S1_b1_descr_.ber, p_buf);
    field_b1->OER_encode(S1_b1_descr_, buf);
    p_buf.put_buf(buf);
    break;
}  case ALT_b2:
    {TTCN_Buffer buf;
    encode_oer_tag(*S1_b2_descr_.ber, p_buf);
    field_b2->OER_encode(S1_b2_descr_, buf);
    encode_oer_length(buf.get_len(), p_buf, FALSE);
    p_buf.put_buf(buf);
    break;
}  case ALT_b3:
    {TTCN_Buffer buf;
    encode_oer_tag(*S1_b3_descr_.ber, p_buf);
    field_b3->OER_encode(S1_b3_descr_, buf);
    encode_oer_length(buf.get_len(), p_buf, FALSE);
    p_buf.put_buf(buf);
    break;
}  default:
    TTCN_EncDec_ErrorContext::error(TTCN_EncDec::ET_UNBOUND, 
      "Encoding an unbound value of type @Foo.S1.");
    return -1;
  }

  return 0;
}
int S1::OER_decode(const TTCN_Typedescriptor_t&, TTCN_Buffer& p_buf, OER_struct& p_oer)
{
  const ASN_Tag_t& descr = decode_oer_tag(p_buf);
  if (S1_b1_descr_.ber->tags[S1_b1_descr_.ber->n_tags-1].tagclass == descr.tagclass &&
      S1_b1_descr_.ber->tags[S1_b1_descr_.ber->n_tags-1].tagnumber == descr.tagnumber) {
    b1().OER_decode(S1_b1_descr_, p_buf, p_oer);
  } else 
  if (S1_b2_descr_.ber->tags[S1_b2_descr_.ber->n_tags-1].tagclass == descr.tagclass &&
      S1_b2_descr_.ber->tags[S1_b2_descr_.ber->n_tags-1].tagnumber == descr.tagnumber) {
      decode_oer_length(p_buf, FALSE);
    b2().OER_decode(S1_b2_descr_, p_buf, p_oer);
  } else 
  if (S1_b3_descr_.ber->tags[S1_b3_descr_.ber->n_tags-1].tagclass == descr.tagclass &&
      S1_b3_descr_.ber->tags[S1_b3_descr_.ber->n_tags-1].tagnumber == descr.tagnumber) {
      decode_oer_length(p_buf, FALSE);
    b3().OER_decode(S1_b3_descr_, p_buf, p_oer);
  } else 
{
    TTCN_error("Cannot find matching tag for type S1");
}
  return 0;
}
void S1::PER_encode(const TTCN_Typedescriptor_t&, TTCN_Buffer& p_buf, int p_options) const
{
if (!is_bound()) {
TTCN_EncDec_ErrorContext::error(TTCN_EncDec::ET_UNBOUND, "Encoding an unbound CHOICE value.");
return;
}
boolean ext_bit = union_selection > 1;
p_buf.PER_put_bit(ext_bit);
if (ext_bit) {
INTEGER sel_code;
TTCN_Buffer ext_add_buf;
switch (union_selection) {
case ALT_b2: {
sel_code = 0;
field_b2->PER_encode(S1_b2_descr_, ext_add_buf, p_options);
break; }
case ALT_b3: {
sel_code = 1;
field_b3->PER_encode(S1_b3_descr_, ext_add_buf, p_options);
break; }
default:
TTCN_EncDec_ErrorContext::error(TTCN_EncDec::ET_UNBOUND, "Internal error: Invalid CHOICE selection, expected an extension addition field.");
return;
}
sel_code.PER_encode_normally_small(p_buf, p_options);
PER_encode_opentype(p_buf, ext_add_buf, p_options);
}
else switch (union_selection) {
case ALT_b1: {
field_b1->PER_encode(S1_b1_descr_, p_buf, p_options);
break; }
default:
TTCN_EncDec_ErrorContext::error(TTCN_EncDec::ET_UNBOUND, "Internal error: Invalid CHOICE selection, expected an extension root field.");
break;
}
}

void S1::PER_decode(const TTCN_Typedescriptor_t&, TTCN_Buffer& p_buf, int p_options)
{
clean_up();
boolean ext_bit = p_buf.PER_get_bit();
if (ext_bit) {
INTEGER sel_code;
sel_code.PER_decode_normally_small(p_buf, p_options);
int sel_int = sel_code;
switch (sel_int) {
case 0: {
TTCN_Buffer ext_add_buf;
PER_decode_opentype(p_buf, ext_add_buf, p_options);
b2().PER_decode(S1_b2_descr_, ext_add_buf, p_options);
break; }
case 1: {
TTCN_Buffer ext_add_buf;
PER_decode_opentype(p_buf, ext_add_buf, p_options);
b3().PER_decode(S1_b3_descr_, ext_add_buf, p_options);
break; }
default:
PER_skip_opentype(p_buf, p_options);
break;
}
} else {
b1().PER_decode(S1_b1_descr_, p_buf, p_options);
}
}


/* Bodies of functions, altsteps and testcases */

void S1_b1_encoder(const BOOLEAN& input_value, OCTETSTRING& output_stream, TTCN_EncDec::coding_t coding_type, unsigned int extra_options)
{
TTCN_Buffer ttcn_buf;
input_value.encode(S1_b1_descr_, ttcn_buf, coding_type, extra_options);
ttcn_buf.get_string(output_stream);
}

INTEGER S1_b1_decoder(OCTETSTRING& input_stream, BOOLEAN& output_value, TTCN_EncDec::coding_t coding_type, unsigned int extra_options)
{
TTCN_EncDec::clear_error();
TTCN_Buffer ttcn_buf(input_stream);
output_value.decode(S1_b1_descr_, ttcn_buf, coding_type, extra_options);
switch (TTCN_EncDec::get_last_error_type()) {
case TTCN_EncDec::ET_NONE:
ttcn_buf.cut();
ttcn_buf.get_string(input_stream);
return 0;
case TTCN_EncDec::ET_INCOMPL_MSG:
case TTCN_EncDec::ET_LEN_ERR:
return 2;
default:
return 1;
}
}

void S1_b2_encoder(const BOOLEAN& input_value, OCTETSTRING& output_stream, TTCN_EncDec::coding_t coding_type, unsigned int extra_options)
{
TTCN_Buffer ttcn_buf;
input_value.encode(S1_b2_descr_, ttcn_buf, coding_type, extra_options);
ttcn_buf.get_string(output_stream);
}

INTEGER S1_b2_decoder(OCTETSTRING& input_stream, BOOLEAN& output_value, TTCN_EncDec::coding_t coding_type, unsigned int extra_options)
{
TTCN_EncDec::clear_error();
TTCN_Buffer ttcn_buf(input_stream);
output_value.decode(S1_b2_descr_, ttcn_buf, coding_type, extra_options);
switch (TTCN_EncDec::get_last_error_type()) {
case TTCN_EncDec::ET_NONE:
ttcn_buf.cut();
ttcn_buf.get_string(input_stream);
return 0;
case TTCN_EncDec::ET_INCOMPL_MSG:
case TTCN_EncDec::ET_LEN_ERR:
return 2;
default:
return 1;
}
}

void S1_b3_encoder(const BOOLEAN& input_value, OCTETSTRING& output_stream, TTCN_EncDec::coding_t coding_type, unsigned int extra_options)
{
TTCN_Buffer ttcn_buf;
input_value.encode(S1_b3_descr_, ttcn_buf, coding_type, extra_options);
ttcn_buf.get_string(output_stream);
}

INTEGER S1_b3_decoder(OCTETSTRING& input_stream, BOOLEAN& output_value, TTCN_EncDec::coding_t coding_type, unsigned int extra_options)
{
TTCN_EncDec::clear_error();
TTCN_Buffer ttcn_buf(input_stream);
output_value.decode(S1_b3_descr_, ttcn_buf, coding_type, extra_options);
switch (TTCN_EncDec::get_last_error_type()) {
case TTCN_EncDec::ET_NONE:
ttcn_buf.cut();
ttcn_buf.get_string(input_stream);
return 0;
case TTCN_EncDec::ET_INCOMPL_MSG:
case TTCN_EncDec::ET_LEN_ERR:
return 2;
default:
return 1;
}
}

void S1_encoder(const S1& input_value, OCTETSTRING& output_stream, TTCN_EncDec::coding_t coding_type, unsigned int extra_options)
{
TTCN_Buffer ttcn_buf;
input_value.encode(S1_descr_, ttcn_buf, coding_type, extra_options);
ttcn_buf.get_string(output_stream);
}

INTEGER S1_decoder(OCTETSTRING& input_stream, S1& output_value, TTCN_EncDec::coding_t coding_type, unsigned int extra_options)
{
TTCN_EncDec::clear_error();
TTCN_Buffer ttcn_buf(input_stream);
output_value.decode(S1_descr_, ttcn_buf, coding_type, extra_options);
switch (TTCN_EncDec::get_last_error_type()) {
case TTCN_EncDec::ET_NONE:
ttcn_buf.cut();
ttcn_buf.get_string(input_stream);
return 0;
case TTCN_EncDec::ET_INCOMPL_MSG:
case TTCN_EncDec::ET_LEN_ERR:
return 2;
default:
return 1;
}
}


/* Bodies of static functions */

void init_module()
{
}


} /* end of namespace */
