/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.9.0, Date: 31-May-2025.
 *
 * Command:  asn1c test.asn1 -c -jer -uper -genMake
 */
#include "Foo.h"

/* S1 */

int asn1Init_S1 (S1* pvalue)
{
   if (0 == pvalue) return RTERR_NULLPTR;
   pvalue->t = 0;
   OSCRTLMEMSET (&pvalue->u, 0, sizeof(pvalue->u));
   return 0;
}

