/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.9.0, Date: 31-May-2025.
 *
 * Command:  asn1c test.asn1 -c -jer -uper -genMake
 */
#include "Foo.h"
#include "rtxsrc/rtxCharStr.h"
#include "rtxsrc/rtxIntDecode.h"

EXTERN int asn1JsonDec_S1 (OSCTXT *pctxt, S1 *pvalue)
{
   int stat = 0;
   OSUTF8CHAR *_choiceId;

   if (stat != 0) return LOG_RTERR (pctxt, stat);

   stat = rtJsonDecMatchChar (pctxt, '{');
   if (stat != 0)  {
      return LOG_RTERR (pctxt, stat);
   }

   stat = rtJsonDecStringValue (pctxt, (OSUTF8CHAR **)&_choiceId);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   stat = rtJsonDecMatchChar (pctxt, ':');
   if (stat != 0)  {
      return LOG_RTERR (pctxt, stat);
   }

   for(;;)  {
      if (0 == rtxUTF8Strcmp (_choiceId, (OSUTF8CHAR *)"b1"))
      {
         stat = rtJsonDecBool (pctxt, &pvalue->u.b1);
         if (stat != 0) return LOG_RTERR (pctxt, stat);

         pvalue->t = 1;

         break;
      }
      if (0 == rtxUTF8Strcmp (_choiceId, (OSUTF8CHAR *)"b2"))
      {
         stat = rtJsonDecBool (pctxt, &pvalue->u.b2);
         if (stat != 0) return LOG_RTERR (pctxt, stat);

         pvalue->t = 2;

         break;
      }
      if (0 == rtxUTF8Strcmp (_choiceId, (OSUTF8CHAR *)"b3"))
      {
         stat = rtJsonDecBool (pctxt, &pvalue->u.b3);
         if (stat != 0) return LOG_RTERR (pctxt, stat);

         pvalue->t = 3;

         break;
      }
      {
         const OSUTF8CHAR *_nvp, *_name;
         OSUTF8CHAR *_value;
         stat = rtJsonDecAnyType (pctxt, &_value);
         if (stat != 0) return LOG_RTERR (pctxt, stat);

         _name = rtxUTF8StrJoin (pctxt, (OSUTF8CHAR *)"\"",  _choiceId, (OSUTF8CHAR *)"\"", 0, 0);
         _nvp = rtxUTF8StrJoin (pctxt, _name, (OSUTF8CHAR *)":", _value, 0, 0);

         pvalue->u.extElem1->data = (OSOCTET *)_nvp;
         pvalue->u.extElem1->numocts = rtxUTF8Len (_nvp) + 1;
         pvalue->t = 4;
      }
      break;
   }
   stat = rtJsonDecMatchChar (pctxt, '}');
   if (stat != 0)  {
      return LOG_RTERR (pctxt, stat);
   }

   if (stat == 0) {
      stat = rtxErrCheckNonFatal (pctxt);
   }

   return stat;
}

EXTERN int asn1PD_S1 (OSCTXT* pctxt, S1* pvalue)
{
   int stat = 0;
   OSUINT32 ui;
   OSBOOL extbit = FALSE;
   ASN1OpenType openType;
   OSSIZE savedSize = 0;
   OSINT16 savedBitOffset = 0;

   RTXCTXTPUSHTYPENAME (pctxt, "S1");

   /* extension bit */

   stat = rtxDecBit(pctxt, &extbit);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   if (!extbit) {
      ui = 0;
      pvalue->t = ui + 1;

      switch (ui) {
         /* b1 */
         case 0:
            RTXCTXTPUSHELEMNAME(pctxt, "b1");
            stat = rtxDecBit(pctxt, &pvalue->u.b1);
            if (stat != 0) return LOG_RTERR (pctxt, stat);

            RTXCTXTPOPELEMNAME(pctxt);
            break;

         default:
            return LOG_RTERR(pctxt, RTERR_INVOPT);
      }
   }
   else {
      stat = pd_SmallNonNegWholeNumber(pctxt, &ui);
      if (stat != 0) return LOG_RTERR (pctxt, stat);
      if (stat != 0) return LOG_RTERR (pctxt, stat);
      pvalue->t = ui + 2;

      if (pvalue->t < 2) return LOG_RTERR (pctxt, RTERR_INVOPT);

      if (ui < 2) {
         stat = pd_Length64 (pctxt, &openType.numocts);
         if (stat < 0) return LOG_RTERR (pctxt, stat);
         else if (stat == RT_OK_FRAG) {
            rtxErrAddStrParm (pctxt, "open type with fragmented length (use -perindef)");
            return LOG_RTERRNEW (pctxt, RTERR_NOTSUPP);
         }

         savedSize = openType.numocts;
         pd_OpenTypeStart (pctxt, &savedSize, &savedBitOffset);
      }

      switch (ui) {
         /* b2 */
         case 0:
            RTXCTXTPUSHELEMNAME(pctxt, "b2");
            stat = rtxDecBit(pctxt, &pvalue->u.b2);
            if (stat != 0) return LOG_RTERR (pctxt, stat);

            RTXCTXTPOPELEMNAME(pctxt);
            break;

         /* b3 */
         case 1:
            RTXCTXTPUSHELEMNAME(pctxt, "b3");
            stat = rtxDecBit(pctxt, &pvalue->u.b3);
            if (stat != 0) return LOG_RTERR (pctxt, stat);

            RTXCTXTPOPELEMNAME(pctxt);
            break;

         default:
            RTXCTXTPUSHELEMNAME (pctxt, "...");

            pvalue->u.extElem1 = rtxMemAllocTypeZ (pctxt, ASN1OpenType);
            if (pvalue->u.extElem1 == NULL) return LOG_RTERR (pctxt, RTERR_NOMEM);
            stat = pd_OpenType (pctxt, &pvalue->u.extElem1->data, &pvalue->u.extElem1->numocts);
            if (stat != 0) return LOG_RTERR (pctxt, stat);

            RTXCTXTPOPELEMNAME (pctxt);

      }

      if (ui < 2) {
         stat = pd_OpenTypeEnd (pctxt, savedSize, savedBitOffset);
         if (stat != 0) return LOG_RTERR (pctxt, stat);
      }
   }

   RTXCTXTPOPTYPENAME (pctxt);

   if (stat == 0) {
      stat = rtxErrCheckNonFatal (pctxt);
   }
   return (stat);
}

