/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "../ESTI_ITS.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_GenerationDeltaTime_H_
#define	_GenerationDeltaTime_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GenerationDeltaTime {
	GenerationDeltaTime_oneMilliSec	= 1
} e_GenerationDeltaTime;

/* GenerationDeltaTime */
typedef long	 GenerationDeltaTime_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_GenerationDeltaTime_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_GenerationDeltaTime;
asn_struct_free_f GenerationDeltaTime_free;
asn_struct_print_f GenerationDeltaTime_print;
asn_constr_check_f GenerationDeltaTime_constraint;
jer_type_encoder_f GenerationDeltaTime_encode_jer;
per_type_decoder_f GenerationDeltaTime_decode_uper;
per_type_encoder_f GenerationDeltaTime_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _GenerationDeltaTime_H_ */
#include <asn_internal.h>
