/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "../ESTI_ITS.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-example -findirect-choice`
 */

#ifndef	_PosPillar_H_
#define	_PosPillar_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PosPillar {
	PosPillar_tenCentimeters	= 1,
	PosPillar_unavailable	= 30
} e_PosPillar;

/* PosPillar */
typedef long	 PosPillar_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PosPillar_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PosPillar;
asn_struct_free_f PosPillar_free;
asn_struct_print_f PosPillar_print;
asn_constr_check_f PosPillar_constraint;
jer_type_encoder_f PosPillar_encode_jer;
per_type_decoder_f PosPillar_decode_uper;
per_type_encoder_f PosPillar_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PosPillar_H_ */
#include <asn_internal.h>
